### ISSUE TITLE
jMonkeyEngine SDK installer fails on MacOSX 10.5

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#10]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=198

> The installer of jMonkeyEngine SDK Alpha-2 fails to run on MacOSX 10.5 because it falsely tries to use Java 1.5 to start the installed.

> Workaround:
> If you have Java 1.6 installed on your computer you can temporarily rename the Java 1.5 folder in /System/Library/Frameworks/JavaVM.framework/Versions/ to some other name like "1.5backup" and run the installer. After installing the folder can be renamed back to "1.5".

**Comment by empirephoenix** [comment]
I believe this problem has died out together with java 1.5 right?

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#13
