### ISSUE TITLE
add getSpatial() methods to GhostControl and RigidBodyControl

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1008]
`com.jme3.bullet.control.GhostControl` and `com.jme3.bullet.control.RigidBodyControl` provide setters for the controlled spatial, but no getter.

Related forum topic:
  https://hub.jmonkeyengine.org/t/how-to-make-projectiles/41301

**Comment by stephengold** [comment]
Thanks for looking into this.

`VehicleControl` is a subclass of `RigidBodyControl`, so adding `getSpatial()` to RBC will address the needs of `VehicleControl`.
`BetterCharacterControl` and `KineticRagdollControl` are subclasses of `AbstractPhysicsControl`, which doesn't have `getSpatial()` yet.

So yes. Please implement `getSpatial()` for `AbstractPhysicsControl` and `CharacterControl` also.

**Comment by quazi-irfan** [comment]
`VehicleControl` is not a subclass of `RigidBodyControl`, but it implements `PhysicsControl`.

I am supposed to add `getSpatial()` to the following classes,
- `GhostControl` extends PhysicsGhostObject implements PhysicsControl, JmeCloneable
- `RigidBodyControl` extends PhysicsRigidBody implements PhysicsControl, JmeCloneable 
- `AbstractPhysicsControl` implements PhysicsControl, JmeCloneable 
- `CharacterControl` extends PhysicsCharacter implements PhysicsControl, JmeCloneable

Note that all 4 classes extends PhysicsControl interface. So doesn't it make more sense to add `getSpatial()` in the super interface?

**Comment by pspeed42** [comment]
I kind of agree that PhysicsControl should have a getSpatial() method... which would force all of those others to implement it somewhere.

As I recall, the point of this is because PhysicsControls will show up in collision events?  If so then, yes, PhysicsControl should definitely have getSpatial().

**Comment by stephengold** [comment]
Sorry I was confused about `VehicleControl`.

The issue I see with adding `getSpatial()` to `PhysicsControl` would be that users might create their own classes that implement `PhysicsControl`, and changing `PhysicsControl` would break their code.

If we do add it to `PhysicsControl` then I request that the commit be in a separate PR.

**Comment by quazi-irfan** [comment]
Should I go ahead and add getSpatial() to the 4 classes?

**Comment by stephengold** [comment]
Yes.

**Comment by quazi-irfan** [comment]
Pull Request #1041 submitted with requested changed.

Are we going to remove getSpatial method from these 4 classes and add it to PhysicsControl interface for 3.3 release?

**Comment by pspeed42** [comment]
PhysicsControl is an interface.  If you add the method there then you will still need it on these classes.

**Comment by quazi-irfan** [comment]
I thought, you would not need it, if getSpatial is marked as default method in the interface.

**Comment by pspeed42** [comment]
Interfaces can't have implementations.  Some class will have to implement the method... anything with "implements PhysicsControl" would have to implement the method.

Are you thinking of a different language maybe?

**Comment by quazi-irfan** [comment]
[Default method](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html) was added in Java 8. You can have a method body in an interface, but you have to mark it default. Its optional for a class to implement the default methods.

**Comment by pspeed42** [comment]
JME is still on Java 7 mostly... else we lose android support, I guess.

**Comment by pspeed42** [comment]
Also, a default interface method wouldn't have access to the spatial field and so would have nothing to return.  So you'd still need the method on the other classes.

**Comment by quazi-irfan** [comment]
Yes, makes sense. Thank you for the explanation.

**Comment by stephengold** [comment]
Fixed in `master` branch at 76049c76f309bceb5eaae43ef78d60e43988ec5a
