### ISSUE TITLE
inconsistent implementations of JmeExporter.save(Savable, File)

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1011]
In `com.jme3.export.binary.BinaryExporter`, the method for saving to a `File` creates the parent directory if it doesn't already exist. However, in `com.jme3.export.xml.XMLExporter`, the corresponding method throws a `java.io.FileNotFoundException` if the parent directory is missing.

Since both classes implement the same interface, it would be convenient if their behaviors were more similar.

**Comment by stephengold** [comment]
Changing the semantics of `BinaryExporter` is a lot more likely to break existing code.

**Comment by pspeed42** [comment]
Yes, sometimes we are slaves to the bad decisions of the past.

**Comment by pspeed42** [comment]
A compromise might be to modify the interface to also have a version that has a boolean createDirectories argument... then the old version can call the new version with true... but folks can do it the safe way if they want to.
