### ISSUE TITLE
Windows issue with Night Light

### ISSUE THREAD

**Issue by tlf30** [jMonkeyEngine/jmonkeyengine#1022]
OK, here is a odd one. I think this might be a LWJGL issue with windows, but I have not tried to test it with anything other than JME3. 
If I have night light turned on in windows 10, and run a JME3 app, when I close the app, windows will some out of night light, but the setting is still enabled. You have to disable and re-enable night light to get it back. I gave tested this on two different computers with several JME3 apps. 

Any thoughts?

**Comment by pspeed42** [comment]
Did you try other lwjgl apps?  Minecraft?  Etc.?

Seems like this is likely not a JME issue.

**Comment by tlf30** [comment]
Just tried minecraft, no issue. Although, I agree that it does not seem like a JME3 issue, but so far I have only been able to recreate it with JME3.

**Comment by stephengold** [comment]
Which version of LWJGL?

**Comment by tlf30** [comment]
I would like to re-clarify that I have not tested with a raw lwjgl app yet.  Their maven setup on their wiki does not work and iirc the ant setup is a nightmare, thus I have not tested it directly yet.

**Comment by empirephoenix** [comment]
Hi, its a windows bug sadly, windows does not properly reset when going out of opengl apps in some states (I have this also with some older other games that do not use jme). Btw usually if you wait 1-5mins the night light will reenable and slowly dim in again.

**Comment by noncom** [comment]
@tlf30 I can recommend using https://justgetflux.com/ which is top-grade configurable blue-light filter. On my Windows 10 it used to drop out after a windowed JME app only rarely and never for more than a couple of secs. But recently it stopped dropping out completely.

**Comment by tlf30** [comment]
I can confirm that this works as a solution. I just wish windows would get its act together with all of these bugs.
