### ISSUE TITLE
FbxLoader not working properly

### ISSUE THREAD

**Issue by tomreineke** [jMonkeyEngine/jmonkeyengine#1025]
1) When I load a fbx model with FbxLoader I'm getting warnings that make me doubt its functionality:
```
WARNING: FBX model isn't using correct forward axis sign. Orientation could be incorrect.
WARNING: FBX model isn't using meters for world units. Scale could be incorrect.
```
I've tried with many models that are working without issues in the Windows 10 3d viewer and the Unreal engine. As an example take the free model https://www.turbosquid.com/3d-models/3ds-used-nokia-cityman/905270

2) In FbxLoader#loadData(InputStream stream) the whole scene is logged in system out with `FbxDump.dumpFile(scene); `
That logging should be removed in my view.

**Comment by Ali-RS** [comment]
Hey @tomreineke  please ask your issues at forum. there you can get more help. https://hub.jmonkeyengine.org/ 

Fbx support is not good at JME. It's not only JME that suffers this, even Blender has problem with Fbx models specially animated models. (You know from my experience dealing with Fbx would cause a headache). (see https://hub.jmonkeyengine.org/t/import-fbx/41456)

I suggest to convert your model to gltf instead then import them to JME.

**Comment by tomreineke** [comment]
Thanks for the great suggestion on using gltf.
