### ISSUE TITLE
Alpha blending wrong when destination has alpha.

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#1028]
I was trying to perform alpha blending where both source and destination had alpha and i was not getting the expected result.

So i've found out that jme uses the same function to blend colors and alphas (when BlendMode = Alpha), i tried to reproduce it on this website https://www.andersriggelsen.dk/glblendfunc.php and i've got the same behaviour i was experiencing.

Since a picture is worth a thousand words, i'm attaching a comparision between the function jme is using (3rd picture) and the function that could fix the issue (4th picture)

![blending](https://user-images.githubusercontent.com/4943530/53680916-02dfaf00-3ce2-11e9-8f72-ba78bf378a00.jpg)

**Comment by stephengold** [comment]
Do you have a request?

**Comment by riccardobl** [comment]
No really, besides maybe a confirmations if this issue is real or if i'm doing something wrong.

**Comment by stephengold** [comment]
Perhaps you want `BlendMode.Additive`:
  https://github.com/jMonkeyEngine/jmonkeyengine/blob/72bed74fa17416d58cc05a2857e78bf1ba4c6d9c/jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java#L783

**Comment by riccardobl** [comment]
No, see the image below, left is Additive right is AlphaAdditive

![additive](https://user-images.githubusercontent.com/4943530/53681706-9a96ca80-3ced-11e9-9bc6-cfd558b262a9.jpg)

**Comment by pspeed42** [comment]
JME hardcodes a specific set of BlendModes (as an enum) which is unfortunate but the way it is.  (JME did this in a lot of cases where I would not have used an enum... Bucket, VertexBuffer.Type, etc.)  The current alpha blending is meant for 3D scenes and so generally you would want to ignore target alpha.

If you need "yet another blendmode" then it could be added... if you can come up with a decent name.

**Comment by pspeed42** [comment]
Or is your contention that JME's BlendMode.Alpha is just wrong in general?
    /**
         * Alpha blending, interpolates to source color from dest color
         * using source alpha.
         * <p>
         * Result = Source Alpha * Source Color +
         *          (1 - Source Alpha) * Dest Color -> (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
         */
    Alpha,

Because looking at the code now, there are many other blending functions and even a BlendMode.Custom that lets you setup specific blending parameters.

GL_ONE, GL_ONE from your picture is JME's AlphaAdditive:
     /**
         * Additive blending that is multiplied with source alpha.
         * For use with glows and particle emitters.
         * <p>
         * Result = (Source Alpha * Source Color) + Dest Color -> (GL_SRC_ALPHA, GL_ONE)
         */
    AlphaAdditive,

**Comment by riccardobl** [comment]
I'm just reporting what i think might be issue, i'm happy in using BlendMode.Custom and that's what i'm using right now.

Additive is GL_ONE GL_ONE for color and alpha, what i was showing is GL_ONE GL_ONE for alpha and GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA for colors.

**Comment by stephengold** [comment]
I don't see an issue here. If action is required, please reopen and explain.

**Comment by riccardobl** [comment]
Ok, maybe i didn't explain myself well enough, so let's recap.

While it's true that jme allows to specify a custom blend mode and thus a workaround is possible and sometimes preferable, what is currently called BlendMode.Alpha doesn't always work as expected (it correctly blends RGB but not A). 
I think this is a problem that should be addressed because only someone who knows the internals of the engine would be able to know about this.

So:

Issue: BlendMode.Alpha is not working as expected when the destination has an alpha channel and the alpha is meaningful for the use case.

Action required: Change BlendMode.Alpha so that it uses a different function to blend the alpha channel,  if this doesn't cause issue with the current use cases.

OR

Add a new blending mode and specify in the comments that this mode doesn't work as expected when the destination has alpha.

**Comment by stephengold** [comment]
L

**Comment by stephengold** [comment]
I'd rather create a new blending mode than change an existing one. I'll label this as an enhancement.

**Comment by riccardobl** [comment]
So, this is how it could look like

In BlendMode a new entry for the mode
```java
 /**
         * Alpha blending, interpolates to source color from dest color
         * using source alpha.
         * The resulting alpha is the sum between the source alpha and the destination alpha.
         * <p>
         * Result.rgb = Source Alpha * Source Color +
         *          (1 - Source Alpha) * Dest Color -> (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
         * Result.a = Source Alpha + Dest Alpha
         * 
         */
        AlphaSumA,

```


In GLRenderer.applyRenderState(RenderState state)

```java
     case AlphaSumA:
                    blendFuncSeparate(
                        RenderState.BlendFunc.Src_Alpha, 
                        RenderState.BlendFunc.One_Minus_Src_Alpha,
                        RenderState.BlendFunc.One,
                        RenderState.BlendFunc.One                    
                    );
                    break;

```

**Comment by stephengold** [comment]
Fine with me. Will there be a pull request?

**Comment by riccardobl** [comment]
Done https://github.com/jMonkeyEngine/jmonkeyengine/pull/1036

**Comment by stephengold** [comment]
Resolved, presumably.
