### ISSUE TITLE
jme3 maven central

### ISSUE THREAD

**Issue by lifeinwild** [jMonkeyEngine/jmonkeyengine#1063]
https://search.maven.org/
jme3 not found in maven central .
Is it difficult to support maven central? I am using maven + maven central.

**Comment by empirephoenix** [comment]
https://wiki.jmonkeyengine.org/jme3/maven.html

**Comment by stephengold** [comment]
The Wiki has been re-organized. I suspect you want https://wiki.jmonkeyengine.org/docs/3.3/getting-started/maven.html

**Comment by stephengold** [comment]
Note: many old releases of JMonkeyEngine were copied to Maven Central in February 2021. Since JCenter was sunsetted, we plan to release to Maven Central going forward. For more information see #1468.
