### ISSUE TITLE
AnimComposer.getAnimClips() and .getAnimClipsNames() should return sets, not collections 

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1070]
Currently in `com.jme3.anim` (new animation system) the `AnimComposer` control defines 2 methods to enumerate all clips contained in the composer. While both methods return collections, the implementation does not allow the same `AnimClip` to be added twice. It would be advantageous to return sets instead, to clarify that duplicates are not allowed.

**Comment by rvandoosselaer** [comment]
I'll tackle this issues this evening.

**Comment by stephengold** [comment]
Removed `getAnimClips()` from the scope of this issue, per discussion at PR #1071.

**Comment by stephengold** [comment]
The issue is open until #1076 gets integrated.
