### ISSUE TITLE
Renderer interface lacks getters for many properties

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1074]
The `com.jme3.renderer.Renderer` interface defines `setAlphaToCoverage()`, `setBackgroundColor()`,  `setClipRect()`, `setDefaultAnisotropicFilter()`, `setDepthRange()`, `setLinearizeSrgbImages()`, `setMainFrameBufferSrgb()`, and `setViewPort()`. However, it does not provide getters for any of these properties.

Runtime access to these properties might aid in debugging render issues.

**Comment by stephengold** [comment]
Further investigation indicates that many of these methods are used dynamically by the `RenderManager`:  `setBackgroundColor()`, `setClipRect()`, `setDepthRange()`, and `setViewPort()`. The corresponding properties are probably of little interest to JME users, so perhaps skip them.

Properties of interest to users include "alphaToCoverage" and "defaultAnisotropicFilter". Not sure yet about "linearizeSrgbImages" and "mainFrameBufferSrgb".

**Comment by quazi-irfan** [comment]
I'll take a look at it tonight.

**Comment by stephengold** [comment]
It looks like "linearizeSrgbImages" and "mainFrameBufferSrgb" are set during initialization of the `JmeContext` and seldom changed thereafter. I infer that their settings might be of interest to users. I'll leave this issue open in case someone wants to implement them in the style of PR #1093.
