### ISSUE TITLE
NullPointerException thrown when gamepad getting disconected on LWJGL3

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1086]
Reference to issue in the forum with a possible fix suggested:
https://hub.jmonkeyengine.org/t/gamepad-disconnect-re-connect/41822

**Comment by Ali-RS** [comment]
Possible fix can be adding this check 

```
if (!glfwJoystickPresent(entry.getKey())) {
    continue;
}
```

after this line:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/7b0471c43a3a9b6cad852293299e1a9c6c90ed35/jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwJoystickInput.java#L128

**Comment by Ali-RS** [comment]
I also noticed logger is initialized wrongly in :
https://github.com/jMonkeyEngine/jmonkeyengine/blob/7b0471c43a3a9b6cad852293299e1a9c6c90ed35/jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwJoystickInput.java#L52

it should be 

`private static final Logger logger = Logger.getLogger(GlfwJoystickInput.class.getName());`

**Comment by jayfella** [comment]
A PR has been submitted. 

https://github.com/jMonkeyEngine/jmonkeyengine/pull/1087
