### ISSUE TITLE
Issue in TestGltfLoading with "zophrac" model

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1089]
Running TestGltfLoading with zophrac model 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/2124e3e86bf898d6c7a7bc90a191cf639e39bacb/jme3-examples/src/main/java/jme3test/model/TestGltfLoading.java#L119

results in an assertion error 

```
java.lang.AssertionError
	at com.jme3.anim.MorphTrack.setKeyframes(MorphTrack.java:125)
	at com.jme3.anim.MorphTrack.<init>(MorphTrack.java:74)
	at com.jme3.scene.plugins.gltf.GltfLoader.readAnimation(GltfLoader.java:842)
	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:134)
	at com.jme3.scene.plugins.gltf.GltfLoader.load(GltfLoader.java:78)
	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at jme3test.model.TestGltfLoading.loadModel(TestGltfLoading.java:239)
	at jme3test.model.TestGltfLoading.simpleInitApp(TestGltfLoading.java:119)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:237)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:475)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:574)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:423)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at jme3test.model.TestGltfLoading.main(TestGltfLoading.java:69)

```

Not sure if this an issue with the model itself or a bug in Gltf loader.
Tested with the master branch.

**Comment by stephengold** [comment]
After creating an account at Sketchfab and downloading the "zophrac" model, I was able to reproduce this issue.

Interestingly, I can load "zophrac" in JME 3.2.3 (using Maud, for instance) so I'd call this issue a regression.

**Comment by Ali-RS** [comment]
>Interestingly, I can load "zophrac" in JME 3.2.3

Yes, it's because JME 3.2.3 does not support morph track.

Assertion error comes from this line: 

https://github.com/jMonkeyEngine/jmonkeyengine/blob/c11fbe4dd8644249ae0e27fd40538bfcfc2fd42c/jme3-core/src/main/java/com/jme3/anim/MorphTrack.java#L125

means that the length of `times` and `weights` arrays are not equal.

**Comment by stephengold** [comment]
Which array is longer?

**Comment by Ali-RS** [comment]
>Which array is longer?

times.length=98
weights.length=5194

**Comment by Ali-RS** [comment]
I opened scene.gltf file in a text editor and serched for these tow numbers and found: 

```
    {
      "bufferView": 6,
      "byteOffset": 1796,
      "componentType": 5126,
      "count": 98,
      "max": [
        5.3333334922790527
      ],
      "min": [
        0
      ],
      "type": "SCALAR"
    },
    {
      "bufferView": 6,
      "byteOffset": 2188,
      "componentType": 5126,
      "count": 5194,
      "max": [
        1
      ],
      "min": [
        0
      ],
      "type": "SCALAR"
    }
```

I do not know what does it mean but if you take a look at others it seems the count matches in pairs. for example : 

```
    {
      "bufferView": 6,
      "byteOffset": 712,
      "componentType": 5126,
      "count": 90,
      "max": [
        5.3333334922790527
      ],
      "min": [
        0
      ],
      "type": "SCALAR"
    },
    {
      "bufferView": 8,
      "byteOffset": 1472,
      "componentType": 5126,
      "count": 90,
      "max": [
        0.084867894649505615,
        0.11089228093624115,
        0.025356562808156013,
        1
      ],
      "min": [
        -0.134776771068573,
        -0.13652418553829193,
        -0.0023585630115121603,
        0.98960131406784058
      ],
      "type": "VEC4"
    },
    {
      "bufferView": 6,
      "byteOffset": 1072,
      "componentType": 5126,
      "count": 91,
      "max": [
        5.3333334922790527
      ],
      "min": [
        0
      ],
      "type": "SCALAR"
    },
    {
      "bufferView": 8,
      "byteOffset": 2912,
      "componentType": 5126,
      "count": 91,
      "max": [
        0.084867894649505615,
        0.11089228093624115,
        0.030399288982152939,
        1
      ],
      "min": [
        -0.13372963666915894,
        -0.13652418553829193,
        -0.0023585630115121603,
        0.99019575119018555
      ],
      "type": "VEC4"
    },
    {
      "bufferView": 6,
      "byteOffset": 1436,
      "componentType": 5126,
      "count": 90,
      "max": [
        5.3333334922790527
      ],
      "min": [
        0
      ],
      "type": "SCALAR"
    },
    {
      "bufferView": 8,
      "byteOffset": 4368,
      "componentType": 5126,
      "count": 90,
      "max": [
        0.4001670777797699,
        0.67250752449035645,
        -0.31195887923240662,
        0.63457202911376953
      ],
      "min": [
        0.31187319755554199,
        0.55527776479721069,
        -0.45616018772125244,
        0.57048559188842773
      ],
      "type": "VEC4"
    }
```

**Comment by stephengold** [comment]
53*98 = 5198, which is probably significant somehow. Without diving deeply into the [glTF 2.0 specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations), my hunch is that our code should print a warning and only use the first 98 attributes.

**Comment by stephengold** [comment]
This issue also breaks `TestAnimMorphSerialization`.

**Comment by stephengold** [comment]
The issue is still present in v3.4.0-beta3.

**Comment by Ali-RS** [comment]
Just tried `TestGltfLoading` with the Zophrac model downloaded today from Sketchfab (https://skfb.ly/ZGGL) and it works fine for me!

**Comment by stephengold** [comment]
I now believe that the assertion in `setKeyframes()` is wrong. The number of weights should equal the number of frames times the number of morph targets. (This becomes clearer if you look at FrameInterpolator.java.)

I hope to revisit this issue after PR #1608 is integrated.

**Comment by Ali-RS** [comment]
Thanks, @stephengold. I will also try it when the PR is merged.

**Comment by stephengold** [comment]
With #1608 integrated, `TestGltfLoading` load the zophrac model just fine.

I recommend a small change to line 115, in order to render the entire model without requiring the user to reposition the camera:
```java
        //loadModel("Models/gltf/zophrac/scene.gltf", new Vector3f(0, 0, 0), 0.01f);
```

**Comment by Ali-RS** [comment]
Thanks for confirming.

>I recommend a small change to line 115, in order to render the entire model without requiring the user to reposition the camera

Submitted the PR: #1610
