### ISSUE TITLE
LWJGL v3.2.2

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1090]
Currently the `jme3-lwjgl3` library in the `master` branch uses LWJGL v3.2.1 .
At some point, we should integrate LWJGL v3.2.2 into jMonkeyEngine. This should include testing on all the major platforms.

**Comment by kone9** [comment]
> Currently the `jme3-lwjgl3` library in the `master` branch uses LWJGL v3.2.1 .
> At some point, we should integrate LWJGL v3.2.2 into jMonkeyEngine. This should include testing on all the major platforms.
Watch this video ... it's in Spanish, so turn off the audio and just watch it.
https://www.youtube.com/watch?v=f0pv8VVcU6Q&t=7s

**Comment by stephengold** [comment]
I watched the video. I don't understand why you wanted me to watch it. I don't understand what it has to do with this issue.

If you need help with jMonkeyEngine, I suggest you ask at the Forum:
    https://hub.jmonkeyengine.org/

**Comment by stephengold** [comment]
And now LWJGL v3.2.3 is available.

**Comment by grizeldi** [comment]
I ttied bumping the lwjgl version as part of my VR experiments some time ago, but the stock blue cube app wouldn't even start due to some glfw error if I remember correctly. Didn't investigate further yet.

**Comment by grizeldi** [comment]
As of 7 days ago lwjgl 3.2.3 is available. I did some local testing and seems that at least the basic blue box runs fine on it.

**Comment by stephengold** [comment]
Resolved in `master` branch at 621a4ab6a9794c9cd359aeb669b7e894e8b44351 .
