### ISSUE TITLE
Using jogl and Offscreen leads to "initial size must be positive (were (0 x 0))"

### ISSUE THREAD

**Issue by GitHub-Ronald** [jMonkeyEngine/jmonkeyengine#1092]
at jogamp.opengl.GLDrawableFactoryImpl.createOffscreenDrawable(GLDrawableFactoryImpl.java:409).

**Comment by stephengold** [comment]
Since jme3-jogl was removed from the Engine on 15 April 2020, this issue is no longer our responsibility.
