### ISSUE TITLE
OpenGL version naming is inconsistent

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#1097]
The version naming in AppSettings is a bit inconsistent, in detail
```
LWJGL_OPENGL3 should be renamed in LWJGL_OPENGL32
LWJGL_OPENGL30 should be added for gl 3.0
LWJGL_OPENGL4 should be renamed in LWJGL_OPENGL40
```
The changes can be applied without breaking backward compatibility by deprecating LWJGL_OPENGL3 and LWJGL_OPENGL4 and fixing the renderers to deal with the new naming, see the commented lines in https://github.com/jMonkeyEngine/jmonkeyengine/pull/1096/commits/e31fc2c96fa8c8e58761eb1c969534a169d3a3ac

**Comment by louhy** [comment]
I can clean that up for you.

**Comment by louhy** [comment]
Hmm, noticed a weird name problem on commit, linked to an old account for some reason so it's saying the wrong author. Will try to fix...

**Comment by louhy** [comment]
Should be good now. 

I'm used to just committing myself or reviewing others changes, so first try with the PR thing on GitHub - let me know if I goofed. :)

**Comment by riccardobl** [comment]
Hey thanks. The changes need to be ported also on the lwjgl3 renderer.
When you are ready, plase submit a pr following these instructions https://help.github.com/en/articles/creating-a-pull-request#creating-the-pull-request

**Comment by louhy** [comment]
Gotcha - already submitted the PR but feel free to reject it etc. 
I think I see what you mean, will take a look at that one tomorrow if you don't mind. 
And no problem - it's time I learn how this OSS collaboration stuff works in practice so I can help out. :)

**Comment by riccardobl** [comment]
Oh i see, you submitted the pr on my fork, it should submitted on this repo instead. :+1:

**Comment by louhy** [comment]
Can do - yeah I was wondering about that since you hadn't merged that yet, I should probably wait until yours is merged, I guess?

**Comment by riccardobl** [comment]
Done, you can reapply the changes to the current master.

**Comment by louhy** [comment]
Should be ready. I did notice there are some internal JME references to the deprecated constants. Should also replace LWJGL_OPENGL3 with LWJGL_OPENGL32 and LWJGL_OPENGL4 with LWJGL_OPENGL40 where they're referenced in subprojects (vr, desktop, etc.) at some point.

**Comment by riccardobl** [comment]
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/pull/1099
