### ISSUE TITLE
Easy way to create meshes and materials

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#11]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=204

**Comment by louhy** [comment]
Since "Google Code" is little more than a zombie these days, here's the (10 years old...) link text in case it ever goes away entirely.

> Posted on Sep 27, 2010 by Helpful Wombat
> It is sometimes neccessary to create meshes and materials at run-time, there should be utility classes that facilitate this kind of use. E.g:
> 
> MeshBuilder mb = new MeshBuilder(); mb.addPosition( ... ) mb.addNormal( ... ) mb.pushTriangle(); // ... Mesh mesh = mb.finish();
> 
> For materials:
> 
> MaterialBuilder mb = new MaterialBuilder(); mb.setDiffuseMap("Textures/color.png"); mb.setNormalMap("Textures/normals.png"); mb.setDiffuseColor(ColorRGBA.DarkGray); Material mat = mb.finish();

But also, is this enhancement still worth implementing? Could use a little discussion to clarify scope and how this should work.

**Comment by pspeed42** [comment]
Should be a third party lib.  There are about 5,034.134 different ways to do something like this.  Each with their own trade offs.  Especially since the little snippets provided add no real value over the "hard" way of just building up the arrays and setting them.

**Comment by louhy** [comment]
Agree. Might as well close this then (I can't). Actually now I see there's quite a few very old "issues" like this one, that are just links (migrated from Google Code I guess), which could be cleaned up to make the issue backlog more manageable.

**Comment by stephengold** [comment]
Sounds good to me.
