### ISSUE TITLE
arm32/64 linux support ??

### ISSUE THREAD

**Issue by Askmewho** [jMonkeyEngine/jmonkeyengine#1101]
Hi! I found than the bullet library than I need its x86 and x86_64 only for linux. The android armhf lib version will not work on GNU/linux projects obviously . Thanks as always.

**Comment by stephengold** [comment]
Thank you for documenting this issue.

**Comment by stephengold** [comment]
The first step, I think would be to define new enum values for Linux-on-ARM platforms (in `com.jme3.system.Platform`) to distinguish from Linux-on-Intel.

**Comment by stephengold** [comment]
Since our current CI providers (AppVeyor and TravisCI) don't yet support Linux-on-ARM, I've started hunting for one that does. We might apply to http://worksonarm.com for instance.

**Comment by Askmewho** [comment]
Thanks @stephengold . I am on million projects at the same time and I didnt try much further. I am not a dev, just an rpi "tester" guy. You were very kind.

**Comment by riccardobl** [comment]
It should be possible to use a crosscompiler.
Eg. from this docker image https://github.com/multiarch/crossbuild

**Comment by stephengold** [comment]
For continuous integration testing, we'll need a Linux-on-ARM run-time environment. Skipping CI testing for Linux-on-ARM (like we do for Android) is not a good option because we rely on CI services for deployment.

**Comment by stephengold** [comment]
PR #1182 defines the relevant `Platform` values. Not much, but it’s a start…

**Comment by riccardobl** [comment]
This should be solved by https://github.com/jMonkeyEngine/jmonkeyengine/pull/1190 .
