### ISSUE TITLE
Error thrown for exported models - gltf exporter(blender 2.8) using "Selected Object" param

### ISSUE THREAD

**Issue by oxplay2** [jMonkeyEngine/jmonkeyengine#1103]
like in topic

Did not seen same issue reported, i think its worth fixing if someone want export single object and import into JME. It might be gltf issue too, but i think its rather JME issue. (probably gltf exporter just dont put additional Nodes above exported object)

> SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
> com.jme3.asset.AssetLoadException: An error occurred loading #####character.gltf
> 	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:150)
> 	at com.jme3.scene.plugins.gltf.GltfLoader.load(GltfLoader.java:78)
> 	at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:259)
> 	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
> 	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
> 	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
> 	at #####.generate(#####.java:125)
> 	at #####.startComponentEnable(#####.java:37)
> 	at #####.simpleUpdate(#####.java:662)
> 	at #####.simpleUpdate(#####.java:107)
> 	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:256)
> 	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
> 	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
> 	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
> 	at com.jme3.scene.plugins.gltf.GltfLoader.readScenes(GltfLoader.java:182)
> 	at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:127)
> 	... 14 more

##### - hidden own code names

**Comment by tlf30** [comment]
@oxplay2 have you tried to do this recently using the master branch of jme3 with the new blender beta? If not, can you please attempt and report back.

Thanks, 
Trevor Flynn

**Comment by jayfella** [comment]
I've just come across this issue and found a solution. There are two scenes:
- OSG_Scene
- Scene

In my instance, **OSG_Scene** had objects in it, but **Scene** did not, and therefore caused the crash reading "null" scenes. The solution is to right-click -> delete the empty scene.

![screenshot](https://i.ibb.co/WsMKtgh/image.png)

**Comment by tlf30** [comment]
This can be closed as it was fixed in #1442
