### ISSUE TITLE
JME serialization does not work with protected/private constructors

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1119]
We should fix JME serialization to work with protected/private constructors. Of course, that probably requires special dispensation in Java 11.

We just have to use reflection to grab the no-arg constructor and make setAccessible(true) or whatever.

Links to the forum page in case: 
https://hub.jmonkeyengine.org/t/jme-serialization-does-not-work-with-protected-private-constructor/41946
https://hub.jmonkeyengine.org/t/solved-need-help-with-triplanar-texturing-on-a-box/41940/24?u=ali_rs

**Comment by Sailsman63** [comment]
What, in general, would a fix here look like?

The serialisation schemes that I've run across generally do require a public, no-arg constructor. Otherwise, your playing monkey-games with Reflection.

Or are you just running into cases where the class was inappropriately built with private constructors?

**Comment by pspeed42** [comment]
The fix would look like playing games with reflection.  Games are already being played with reflection to access private fields, etc..

We require no-arg constructors but often it makes the classes themselves very fragile to have public no-arg constructors.  Any time you see "Provided for serialization, do not call" as a javadoc comment on a public constructor we should feel sad.... there's no reason for it.

**Comment by pspeed42** [comment]
This PR came from another discussion and it's too bad none of the conversation was copied over or a link... because I also don't have the link handy anymore.

**Comment by Ali-RS** [comment]
Description and links to the forum page added in the first post.

**Comment by stephengold** [comment]
Many times I've been bitten by no-arg constructors that I invoked when I wasn't supposed to. Playing monkey games with reflection would be a small price to pay to avoid such errors.

Also: imho, monkey games are very much in the spirit of jMonkeyEngine.

**Comment by stephengold** [comment]
Resolved in 'master' branch at 5eaf653de91210adf6263ebf99a92b09bd1cf28e

It'd be great if someone would sort out which no-arg constructors need protection and update the codebase accordingly. For instance, the no-arg constructor for `Geometry` is used in many places and works fine, but its javadoc says not to use it.
