### ISSUE TITLE
PQTorus Rendering Glitch

### ISSUE THREAD

**Issue by louhy** [jMonkeyEngine/jmonkeyengine#1121]
PQTorus vanishes when you're not looking at it directly. Looks like world bounds aren't updated after the vertex buffer is set: 
https://vimeo.com/341919874

Suggest adding an updateBound() call at the end of updateGeometry() within PQTorus.java: 

```
        ...
        setBuffer(Type.Position, 3, fpb);
        setBuffer(Type.Normal,   3, fnb);
        setBuffer(Type.TexCoord, 2, ftb);
        setBuffer(Type.Index,    3, sib);
        
        updateBound();
    }
```

**Comment by stephengold** [comment]
Good catch!

**Comment by stephengold** [comment]
@louhy Your fix is integrated. Please verify that the glitch is gone from `master` branch.

**Comment by louhy** [comment]
@stephengold Works here!
