### ISSUE TITLE
Can't add components to Nifty

### ISSUE THREAD

**Issue by Monniasza** [jMonkeyEngine/jmonkeyengine#1149]
Brand new Nifty GUI files contain one layer and one screen. However, layers do not show up in layer selection.

To recreate:
1 create empty Nifty GUI
2 open layer selection

**Comment by tonihele** [comment]
This is probably in the wrong place. SDK Nifty-editor bug. You'd better add a screenshot of the problem. You are missing so much details it is hard to understand where and what. I think I found what you are talking about but not sure. Anyway, definitely SDK. The issue should be under https://github.com/jMonkeyEngine/sdk.

If I understood correctly... I might advice you to steer away from the WYSIWYG editor. Better to manually edit the XML. The editor has some shortcomings.

**Comment by Monniasza** [comment]
Recreated (here)[https://github.com/jMonkeyEngine/sdk/issues/205]
