### ISSUE TITLE
jME does not work -- at all -- on modern Java due to a regression

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/jmonkeyengine#1154]
I recently tried to work on some of my jME projects with Java 12, as I do for all of my Java projects, and I found that when jME starts (even with just a SimpleApplication with nothing being rendered beyond jME's default statistic view), the application quickly crashes with a log like this one:

```
<date and time are redacted to protect my time zone> com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.2-stable
 * Branch: HEAD
 * Git Hash: 8291d61
 * Build Date: 2019-07-13
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

An example `java -version` for a Java implementation for which the error takes place:
```openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode)
```

An example `java -version` for a Java implementation for which the error does not take place (jME works as expected):
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
```

OS: Arch Linux
OpenGl Implementation: Nvidia 430.34 on GTX 1070
Linux Kernel version: 5.2.3-arch1-1-ARCH

This issue is new as the project in question did work before (even a few weeks ago, if I recall correctly), but has since stopped working. There have been numerous possibly relevant updates to my system since then, as Arch Linux is a bleeding edge distribution that often gets hundreds of relevant updated packages in a single day. Most notably, both the Linux kernel and Nvidia driver have updated since I last remember the project in question working.

**Comment by pspeed42** [comment]
So, if I get this straight... project was working fine.  JME version was not changed.  System was updated and JME stopped working.

If so then this is not a JME regression.  I recommend discussing trouble shooting questions on the forum where you will get more eyes than the 2 or 3 people that would read this here.

**Comment by john01dav** [comment]
> If so then this is not a JME regression. 
I didn't say that it was a *JME* regression, I said that it is a regression. I have no idea what the regression is in, but after some research on the Internet, it seems to be an LWJGL issue as I found it in the issue trackers of some other LWJGL projects. Unfortunately, I can't debug further as I don't understand LWJGL or JNI well enough to do so, or to write a good bug report to LWJGL. No other (non-LWJGL) programs have an issue on my system's configuration, so it is probably a bug in LWJGL and/or the way that jME uses it. 

I will also put this on the forum.

**Comment by stephengold** [comment]
Based on [this discussion on the forum](https://hub.jmonkeyengine.org/t/solved-jme-does-not-work-at-all-on-modern-java-due-to-a-regression/42112), it appears this issue was more about LWJGL than JMonkeyEngine.

Apparently, the workaround was to switch from LWJGL v2 (jme3-lwjgl library) to LWJGL v3 (jme3-lwjgl3 library).
