### ISSUE TITLE
Blender importer (3.2.4-stable) crashes with NPE

### ISSUE THREAD

**Issue by demoth** [jMonkeyEngine/jmonkeyengine#1167]
Hi guys

The blender loader crashes to load my models (simple cube)

Minimal test
https://pastebin.com/FcisFBx0
with jmonkey engine dependencies 3.2.4-stable

The moment i switch jme3-blender to 3.2.3-stable the code works

Full stack trace
https://pastebin.com/Ag1LRXE6

**Comment by stephengold** [comment]
Would you kindly share the model in question ("fire.blend")?

**Comment by Ali-RS** [comment]
I guess it's due to this commit in JME 3.2.4:  https://github.com/jMonkeyEngine/jmonkeyengine/commit/8f3feb80124b57a4d108040f71c3ad5dfd4cf11f

It seems already fixed in master:  https://github.com/jMonkeyEngine/jmonkeyengine/commit/80aed88f82f6b9415d587be0808522aae93cf12a

**Comment by demoth** [comment]
Thanks for the information! I will stick with the 3.2.3 version until the fix will be released

**Comment by Ali-RS** [comment]
@stephengold  is there going to be a 3.2.5 release?

**Comment by stephengold** [comment]
I'm thinking about it.

**Comment by stephengold** [comment]
I've back-ported the likely fix to the v3.2 branch: 0e2a19c826f47db4e44fab403858fe7de7f77c5e

**Comment by stephengold** [comment]
This issue is fixed in JME 3.3, and the v3.2 branch is now stale, so I'm closing this issue.
