### ISSUE TITLE
Inconsistencies in native libraries path

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#1179]
This is a very minor issue but i'm reporting it anyway in case anyone wants to fix it.
As you see from the following list, the path structure for android and pc/mac natives is inconsistent.  inside the jars android natives are stored in /lib while the others are in /natives. and prebuild natives for jme3-bullet-native are inside a subdirectory "natives" inside /libs while the others aren't

### Jars
**jme3-bullet-native.jar** : jme3-bullet-native.jar/natives
**jme3-bullet-native-android.jar** : jme3-bullet-native-android.jar/lib
**jme3-android-native.jar** : jme3-android-native.jar/lib

### Prebuilt libraries
**jme3-bullet-native** :[ jme3-bullet-native/libs/natives](https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-bullet-native/libs/native)
**jme3-bullet-native-android** : [jme3-bullet-native-android/libs](https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-bullet-native-android/libs)
**jme3-android-native** : [jme3-android-native/libs](https://github.com/jMonkeyEngine/jmonkeyengine/tree/master/jme3-android-native)

**Comment by stephengold** [comment]
Not worth fixing, in my opinion.

**Comment by riccardobl** [comment]
This is defacto fixed by this https://github.com/jMonkeyEngine/jmonkeyengine/pull/1190
