### ISSUE TITLE
com.jme3.scene.shape.Line:updatePoints doesn't behave as expected

### ISSUE THREAD

**Issue by Bekreth** [jMonkeyEngine/jmonkeyengine#1202]
Inside of the `com.jme3.scene.shape.Line` class, the function `updatePoint` does not update the internal `start` and `end` point within the object when it updates the underlying VertexBuffer.  I see that in the `updateGeometry` function (which is protected) these internal fields are updated to keep their values the same as the underlying buffers.  Is this the intended behavior of these functions?

**Comment by pspeed42** [comment]
Probably an oversight.  It's weird to have two methods that do the same thing, though.  A lot of these mesh classes are just half examples, anyway... this particular class could use a lot of cleanup.

**Comment by stephengold** [comment]
Fixed in master branch at 92b161f38eb9992d5dfe5a8928c157ae57c67028.
