### ISSUE TITLE
Engine 3.2.4 fail to start

### ISSUE THREAD

**Issue by akshatGupta2** [jMonkeyEngine/jmonkeyengine#1204]
Hello good people there is a bug in  JMonkeyengine 3.2.4 when i try to start it
. It gives the following warning-

![image](https://user-images.githubusercontent.com/36946364/67142722-92da6500-f281-11e9-9370-589f1fc18a43.png)

And then it closes even on cliking on "Disable modules and continue" button. Can anyone help me.PLEASE.....

**Comment by pspeed42** [comment]
You probably should ask trouble shooting questions on the forum where more people will see it and potentially respond.

**Comment by MeFisto94** [comment]
This would be a case for the sdk repository, but that looks like a corrupted installation.
Please retry with 3.2.4 and maybe 3.3-beta1 and report on the SDK (or the forum) again if they are still here.
