### ISSUE TITLE
Quaternion.lookAt should return "this"

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1210]
Almost every method in the Quaternion class (from<whatever>) return this.
This allows for code like
```java
Quaternion q = new Quaternion().fromAngles(0f, FastMath.PI, 0f);
```

Quaternion.lookAt() doesn't yet, so the code would look like
```java
Quaternion q = new Quaternion();
q.lookAt(v, Vector3f.UNIT_Y)
```

Which especially in a case where you'd just want to pass a lookAt to a method, makes your code look worse. It's also not consistent with the other code (lookAt even uses fromAxes, which returns `this`), but looking at it's position in the file, it has been added later and just overlooked this convention.

Also changing this wouldn't break any user-code.

What do you think?

**Comment by stephengold** [comment]
I'm fine with changing this for JME 3.3

**Comment by pspeed42** [comment]
re: "Also changing this wouldn't break any user-code."

It would actually.  Any classes that were not strictly clean rebuilt would fail to load because the method signature changed.

Ok for 3.3... definitely not ok for 3.2.

**Comment by qs-dragon** [comment]
First time contributing on github, should I wait for a 3.3 branch before creating the pr?

**Comment by pspeed42** [comment]
No.  Master is 3.3 until the branch is cut.
