### ISSUE TITLE
Unable To Check For Updates

### ISSUE THREAD

**Issue by LightspeedLife** [jMonkeyEngine/jmonkeyengine#1225]
I just downloaded the installer and installed on linux today. I updated it through the JMonkey Netbeans help menu, and cannot check for updates again, it just tells me to check my proxy settings and connection. In Options, I have it set to "No Proxy", and the "Test connection" button shows green.

When trying to update plugins, I get "Unable to connect to the jMonkeyEngine SDK Stable because of http://updates.jmonkeyengine.org/stable/3.1/plugins/updates.xml" (broken link).

I'm not sure how I can be of more help, or if anyone else is experiencing this issue.

**Comment by stephengold** [comment]
The jMonkeyEngine project hasn't had a working update server in many years. You should uncheck all 3 of the update centers under Menu bar -> "Tools" -> "Plugins" -> "Settings".

In the future, please direct your support requests to the Forum at https://hub.jmonkeyengine.org/

This issue tracker is for the Engine (libraries), not the SDK (development tools). In the future, please direct SDK issues to the SDK's issue tracker: at https://github.com/jMonkeyEngine/sdk/issues
