### ISSUE TITLE
Joint.setLocalScale() doesn't work like Bone.setLocalScale()

### ISSUE THREAD

**Issue by asxdfd** [jMonkeyEngine/jmonkeyengine#1232]
Hello, here's a problem.
When I use 3.2.0-stable, Bone.setLocalScale() works like what I do in blender. Now I use v3.3.0-beta1, but Joint.setLocalScale() doesn't work like that. I have checked the java doc but there's no instruction.
What's the difference between them?

**Comment by Ali-RS** [comment]
Can you provide a minimal test case for the issue? (One using Bone and one using Joint)

**Comment by pspeed42** [comment]
It also might be helpful to know what "works like what I do in blender" means versus "doesn't work like that".

**Comment by asxdfd** [comment]
> Can you provide a minimal test case? (One for Bone and one for Joint)
> Better to use the default monkey model from jme-testdata package.

Here is the code I'm using now. My code is nearly the same:
for Bone:
```
Node scene = (Node) assetManager.loadModel("rigged_obj.glb");
Node model = (Node) scene.getChild("Armature");
SkeletonControl sc = model.getControl(SkeletonControl.class);
Skeleton ske = sc.getSkeleton();
Bone eyeBallL = ske.getBone("eyeball.l");
eyeBallL.setUserControl(true);
new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 10; i++) {
                    for (int s = 10; s > 0; s--) {
                        eyeBallL.setLocalScale(new Vector3f(1, s * 0.1f, 1));
                        ske.updateWorldVectors();
                        try {
                            Thread.sleep(75);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                    for (int s = 1; s <= 10; s++) {
                        eyeBallL.setLocalScale(new Vector3f(1, s * 0.1f, 1));
                        ske.updateWorldVectors();
                        try {
                            Thread.sleep(75);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }
        }).start();
```

for Joint:
```
Node scene = (Node) assetManager.loadModel("rigged_obj.glb");
Node model = (Node) scene.getChild("Armature");
SkinningControl sc = model.getControl(SkinningControl.class);
Armature ske = sc.getArmature();
Joint eyeBallL = ske.getJoint("eyeball.l");
new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 10; i++) {
                    for (int s = 10; s > 0; s--) {
                        eyeBallL.setLocalScale(new Vector3f(1, s * 0.1f, 1));
                        ske.update();
                        try {
                            Thread.sleep(75);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                    for (int s = 1; s <= 10; s++) {
                        eyeBallL.setLocalScale(new Vector3f(1, s * 0.1f, 1));
                        ske.update();
                        try {
                            Thread.sleep(75);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }
        }).start();
```
The only difference is ske.updateWorldVectors() using 3.2.0-stable and ske.update() using 3.3.0-beta1.

**Comment by asxdfd** [comment]
> It also might be helpful to know what "works like what I do in blender" means versus "doesn't work like that".

When I use Bone.setLocalScale(), I get results that is the same as using blender2.8.0, just scale the Bone. But when using Joint.setLocalScale(), the result is not the same.

**Comment by pspeed42** [comment]
not the same.  Meaning: your computer explodes?  Jello comes out of the speakers?

**Comment by Ali-RS** [comment]
And can you also upload the model "rigged_obj.glb"?

**Comment by asxdfd** [comment]
skeleton structure
![image](https://user-images.githubusercontent.com/42411554/70422952-93d08b80-1aa7-11ea-9e8c-6dfb2e52dc96.png)
result of Joint
![image](https://user-images.githubusercontent.com/42411554/70425728-aa2d1600-1aac-11ea-8f59-a2ce1886b5a8.png)
result of Blender
![image](https://user-images.githubusercontent.com/42411554/70425861-f2e4cf00-1aac-11ea-987a-8de9a22f601a.png)
result of Bone
![image](https://user-images.githubusercontent.com/42411554/70425853-ed878480-1aac-11ea-89cc-4ed3cbe8da05.png)

**Comment by Ali-RS** [comment]
Closing this due to lack of test model.
