### ISSUE TITLE
why i cant input chinese char?

### ISSUE THREAD

**Issue by qq1053831109** [jMonkeyEngine/jmonkeyengine#1237]
why i cant input chinese char?

**Comment by tonihele** [comment]
This is probably about Nifty GUI (based on the fact that you also posted some issues to that project as well). But you don't really specify anything in your question. We are not mind readers. Anyway, please describe what are you using and what would you like to achieve. In more words than these. Do you have some code already? Are you using some IDE or SDK? What what?

Questions are best asked in the forums https://hub.jmonkeyengine.org/. Not here.

**Comment by tonihele** [comment]
https://github.com/nifty-gui/nifty-gui/issues/475, I think that answers the question and this can be closed.
