### ISSUE TITLE
SkeletonDebugger is not work on 3.2.4

### ISSUE THREAD

**Issue by qq1053831109** [jMonkeyEngine/jmonkeyengine#1240]
sd = new SkeletonDebugger("debugger", sc.getSkeleton());
        jaime.attachChild(sd);
        
        // 将SkeletonDebugger的姿态与Jaime的几何体同步。
        Spatial child = jaime.getChild(0);
        sd.setLocalTransform(child.getLocalTransform());
        
        // 创建材质
        Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        mat.setColor("Color", ColorRGBA.Green);
        mat.getAdditionalRenderState().setDepthTest(false);// 禁用深度测试，实现透视效果。
        sd.setMaterial(mat);

dont show anything

**Comment by stephengold** [comment]
Why closed?

**Comment by qq1053831109** [comment]
i find the right code to use SkeletonDebugger!
