### ISSUE TITLE
Integrate Core Profiles for LWJGL2

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1242]
So: Currently specifying any Core Profile apart from OpenGL 3.2 does not work.
Riccardo already has a patch for that, we would really appreciate a Pull Request for that :)

**Comment by riccardobl** [comment]
Isn't it what this commit does?
https://github.com/jMonkeyEngine/jmonkeyengine/commit/a68d8b50e31d9aceaee4a1dfba28e9c2a70b2cfc

**Comment by MeFisto94** [comment]
Yes, I am sorry.
Then the tester on Discord just didn't have any 3.3 release at hand when trying this.
I just recalled that you had a patch but not included.
You also changed something related on lwjgl3, is this also included already?
