### ISSUE TITLE
Terrain could not picked.

### ISSUE THREAD

**Issue by huliqing** [jMonkeyEngine/jmonkeyengine#1261]
I test the problem on jme3.3 alpha5

1.First edit the terrain and then save is as j3o.
2.Use assetManager.loadModel(...terrain.j3o);
3.Use ray to test collide but not success in some terrain patch. 
		  	   
	terrain.collideWith(ray, results);
	
I think maybe is the problem of the code of TerrainQuad.

	private TerrainPicker picker = new BresenhamTerrainPicker(this);

When assetManager load the terrain. It will clone the TerrainQuad.

	if (obj instanceof CloneableSmartAsset) {
		clone = registerAndCloneSmartAsset(key, clone, proc, cache);
	}
	
But the TerrainPicker was not cloned, so the picker will link to anthor old TerrainQuad.
I use the old code can fix my pick problem. But I'm not sure is the right way.

    private int collideWithRay(Ray ray, CollisionResults results) {
        if (picker == null) {
            picker = new BresenhamTerrainPicker(this);
        }
        return picker.getTerrainIntersection(ray, results);
    }

**Comment by MeFisto94** [comment]
So you are using the jMonkeyengine SDK to edit the terrain and to save it?
Could this be a regression from 3ec89ce499662a996d637af005272c8abfc75740? i.e. could you test with 3.3-alpha2?

Your findings sound plausible, though.
I'll think about reverting the picker instantiation into collideWith, it just appeared odd to me without any comment on this behavior (i.e. it is bad as it slows down the first intersection and didn't make much sense as-is).

**Comment by huliqing** [comment]
I'm not use the sdk to test this problem.
I use my own terrain editor use the source code from the old SDK before jme3.3.
The old code no have the problem of pick.&nbsp;


I have upgraded to alpha5 for sometime, but I just found this problem yesterday.
So I'm not sure if the problem is from alpha5&nbsp; or alpha2.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MeFisto94"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月18日(星期六) 凌晨2:37
收件人:&nbsp;"jMonkeyEngine/jmonkeyengine"<jmonkeyengine@noreply.github.com&gt;;
抄送:&nbsp;"胡李青"<31703299@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jMonkeyEngine/jmonkeyengine] Terrain could not picked. (#1261)




So you are using the jMonkeyengine SDK to edit the terrain and to save it?
 Could this be a regression from 3ec89ce? i.e. could you test with 3.3-alpha2?
 
Your findings sound plausible, though.
 I'll think about reverting the picker instantiation into collideWith, it just appeared odd to me without any comment on this behavior (i.e. it is bad as it slows down the first intersection and didn't make much sense as-is).

**Comment by huliqing** [comment]
> So after a quick talk with pspeed, our cloning guy, I got the answer, that:
> `this.picker = new BresenhamTerrainPicker(this);` should probably just added to cloneFields().
> Could you test this locally and confirm that it works? [without your fix]

I have test this code, it can fix the problem of pick.

**Comment by oxplay2** [comment]
im not sure why did not seen issue for my Terrain Editor...

but im glad @huliqing found issue so would no need wonder later whats wrong.

"Use ray to test collide but not success in some terrain patch."

i think i had similar issue, but it was somehow related only for "plain" quads. and it was solved somehow. (while generating plain heightmap i belive)

here is what we use and it work for 3.3-alpha5. (i am able to place objects on every quad of terrain)
```
    public CollisionResult getCursorContact() {
        if (terrain != null) {
            Vector3f origin = cam.getWorldCoordinates(inputManager.getCursorPosition(), 0.0f);
            Vector3f direction = cam.getWorldCoordinates(inputManager.getCursorPosition(), 0.3f);
            direction.subtractLocal(origin).normalizeLocal();
            Ray mouseRay = new Ray(origin, direction);
            CollisionResults results = new CollisionResults();
            terrain.collideWith(mouseRay, results);
            CollisionResult closestCollision = results.getClosestCollision();
            if (closestCollision != null) {
                return closestCollision;
            }
        }
        return null;
    }

```
