### ISSUE TITLE
CapsuleCollisionShape Axis doesn't match the wireframe or collision.

### ISSUE THREAD

**Issue by pixelapp** [jMonkeyEngine/jmonkeyengine#1266]
When declaring a capsule for character control the wireframe and collision of the capsule don't match in terms of the axis.

This is how I declare the capsule CapsuleCollisionShape(1f, 3.5f, 0). This statement is supposed to give me a capsule with the longest side on the X axis. 

In the image below you can see that the feet of the character model are above ground. They should be half way in the floor.

![image](https://user-images.githubusercontent.com/1724088/73040619-3c546800-3e28-11ea-9263-ed1d3103aa74.png)

Solution:

Flip the axis initialization of the class CapsuleCollisionShape(, ,#). Flip the values 0 and 1.
0 is vertical right now. Should be horizontal x axis.
1 is horizontal right now. Should be vertical y axis.
2 axis is ok right now.

**Comment by tlf30** [comment]
Which physics engine are you using? Bullet Native, jBullet, or Minie?

**Comment by pspeed42** [comment]
Questions like this should be asked on the forum.

You specified that you wanted it pointed down the 0 axis so it was: CapsuleCollisionShape(1f, 3.5f, 0)

0 = x-axis... which is what it's pointing along, eh?  I think maybe your definition of "vertical" is wrong.

**Comment by stephengold** [comment]
Hint: cameras and collision objects are subject to rotation, so the shape's X axis may not match the world's X axis and the world's X axis may not match the screen's X axis.
