### ISSUE TITLE
Support ABGR on OpenGL ES

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1280]
Our StatsAppState uses a bitmap texture using a ABGR texture.
Now due to a second bug, #1272 was happening: The renderer assumed desktop to be OpenGL ES and crashed.

What does this mean for Android however? Currently there is no StatsAppState possible and loading of ABGR textures in general is not possible. Why?

See #1256 for the backgrounds: There are driver extensions that allow loading ABGR's directly which make the process fast. If those aren't available, we should load the file into memory, swap the channels and upload it as RGBA.

Now it has to be investigated why this wasn't the case, more detail on that on #1256

**Comment by joliver82** [comment]
As far as I've found, there's only one extension supporting abgr: GL_EXT_texture_type_2_10_10_10_REV but I think you're talking about abgr8, although there's some extensions with bgra formats: GL_EXT_texture_format_BGRA8888 and GL_APPLE_texture_format_BGRA8888. So maybe, a swizzle texture format could be added if running on gles3 as follows: 

formatSwiz(formatToGL, Format.ABGR8, GLExt.GL_RGBA8, GL.GL_RGBA, GL.GL_UNSIGNED_BYTE);

I think this should do the trick and solve the issue for GL ES renderers

**Comment by stephengold** [comment]
Thanks for the investigation @joliver82

**Comment by MeFisto94** [comment]
> Which indeed is added if Caps.Rgba8 is supported.

This was something I just needed to check:
Since we're converting _to_ RGBA8, we need to ensure that it's present, for obvious reasons. 
Now I guess according to the above issue somehow Caps.Rgba8 wasn't set.

We, however, do not use [GL_EXT_abgr](https://people.freedesktop.org/~marcheu/extensions/EXT/abgr.html), right?
According to the code, OpenGL 2.0 natively supports ABGR already, so it doesn't make sense on Desktop but is this extension even available on openGL ES then?
