### ISSUE TITLE
AndroidTouchInput doesn't deal with KeyEvent.ACTION_MULTIPLE

### ISSUE THREAD

**Issue by jarlure** [jMonkeyEngine/jmonkeyengine#1297]
Hey,guys!

I found the bug when I typed "你好"(=“Hello”) by keyboard's input method. Maybe chinese input method is special: If you type an "h",you get a KeyEvent with action=**KeyEvent.ACTION_DOWN**;But when you choose "hi" from input method tips"1.h 2.hi 3.huge 4.hf 5.Hash",you get a KeyEvent with action=**KeyEvent.ACTION_MULTIPLE**.
I know **com.jme3.input.android.AndroidTouchInput** listen to these events and it deals with **KeyEvent.ACTION_DOWN** in method **public boolean onKey(KeyEvent event)**.But it regards **KeyEvent.ACTION_MULTIPLE** as **KeyInputEvent** by mistake,and lost **mCharacters** field.

I beg to fix it,please!
![TIM图片20200217203102](https://user-images.githubusercontent.com/55042881/74654132-9694de80-51c4-11ea-9349-28d1faf3357f.png)

**Comment by jarlure** [comment]
That is,I can get "h" on TouchEvent and get nothing instead of "hi" on KeyEvent beacuse  of mCharacters field missing.

**Comment by stephengold** [comment]
Thanks for the bug report.

**Comment by neph1** [comment]
Can you provide a minimal test app for this? It would make things easier when fixing it.

**Comment by jarlure** [comment]
ok,I'll do that soon.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rickard Edén"<notifications@github.com&gt;; 
发送时间: 2020年4月2日(星期四) 晚上6:51
收件人: "jMonkeyEngine/jmonkeyengine"<jmonkeyengine@noreply.github.com&gt;; 
抄送: "123"<921776645@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jMonkeyEngine/jmonkeyengine] AndroidTouchInput doesn&#39;t deal with KeyEvent.ACTION_MULTIPLE (#1297)





 
Can you provide a minimal test app for this? It would make things easier when fixing it.

**Comment by jarlure** [comment]
Here it is:[https://github.com/jarlure/AndroidTouchInputTest](url)

**Comment by jarlure** [comment]
![debug](https://user-images.githubusercontent.com/55042881/78254074-f30b4d80-7527-11ea-900d-dbf218d94fcd.png)
As shown in illustration

**Comment by neph1** [comment]
I'm not sure how you get the word hints when bringing up JmeContext.showSoftKeyboard(true)
I only get that when I have an EditText selected.

**Comment by jarlure** [comment]
> I'm not sure how you get the word hints when bringing up JmeSystem.showSoftKeyboard(true)
> I only get that when I have an EditText selected.

you should install SogouInput_android_v10.6_sweb.apk ,a very popullar Chinese input app.You can find it by https://github.com/jarlure/AndroidTouchInputTest

**Comment by neph1** [comment]
I can see some benefits to this, but it sounds like a very special use case. Fixing it is rather simple, but it seems difficult to test in a generic way.

**Comment by jarlure** [comment]
![image](https://user-images.githubusercontent.com/55042881/78358731-417f2180-75e6-11ea-901e-d90a22156696.png)
I have tested every Chinese input I know, but no one was responded by jme correctly.They all send KeyEvent.ACTION_MULTIPLE.

**Comment by jarlure** [comment]
> I can see some benefits to this, but it sounds like a very special use case. Fixing it is rather simple, but it seems difficult to test in a generic way.
Fixing bug is better than ignore it. If we do nothing, we will lose lots of Chinese users. Think about an app can't type words, how disappointing! :(

**Comment by jarlure** [comment]
Fixing bug is better than ignore it. If we do nothing, we will lose lots of Chinese users. Think about an app can't type words, how disappointing! :(

**Comment by neph1** [comment]
I have a better understanding of the problem now and have I have fixed it to the best of my abilities. But I'm having issues testing it, and I don't want to install any third party apps to do so. I have installed google's pinyin keyboard but it still shows up as QWERTY in the app. If I can't test it I might just put up a PR and hope someone else can confirm it. Or make a distribution with your test app and you can test it.

**Comment by jarlure** [comment]
Thank you very much for helping us. Android default input can also show this problem, even though it doesn't have powerful hint. You could use Russian or Arabic language for test. They all send KeyEvent.ACTION_MULTIPLE. I guess all languages with non-ASCII  character exist the bug in jme-android.

**Comment by jarlure** [comment]
![input](https://user-images.githubusercontent.com/55042881/78453306-65646500-76c3-11ea-9e61-87f3a6dffd9b.png)
The picture shows that my Android default google input (Russian language) looks like.

**Comment by neph1** [comment]
Thanks for the help. Using russian locale did the trick. PR created.
