### ISSUE TITLE
LWJGL2: Freeze when Context couldn't be initialized

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1319]
"Testcase":
Call `app.start(true)` when the Renderer is set to OpenGL3.0, which will be impossible. Start will block.

Why?
https://github.com/jMonkeyEngine/jmonkeyengine/blob/728a05c4f3b432d2d75bde27bf0e8c731d30e8c2/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java#L173-L175
Init happens in another thread and waitFor(true) will wait for the createdLock to be set.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/728a05c4f3b432d2d75bde27bf0e8c731d30e8c2/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java#L443-L452

https://github.com/jMonkeyEngine/jmonkeyengine/blob/728a05c4f3b432d2d75bde27bf0e8c731d30e8c2/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglAbstractDisplay.java#L117-L132
^ This does not set created in every circumstance, it depends on where the exception happens.

But more importantly:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/728a05c4f3b432d2d75bde27bf0e8c731d30e8c2/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java#L422-L433
Here the createdLock is notified. What if this internalCreate is not called due to an Exception? Right! the lock is waiting infinitely.

Also note that we do set created = true from two different places at two different times.

**Comment by stephengold** [comment]
Fixed in v3.3 branch at 7e3ae5e .
