### ISSUE TITLE
Proper License

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1328]
So, currently our license.txt is some kind of template for the License, which causes Githubs Recognition to fail and list our License as `other`.

I think having the BSD license as `LICENSE` file would probably be the best canonical way, but I wonder what this template file was used for? Netbeans?

**Comment by stephengold** [comment]
I suspect the `LICENSE` file was intended for GitHub. If it were for Netbeans, I think it would be in the sdk project.

**Comment by MeFisto94** [comment]
Well, it's `license.txt` currently and it contains some defines for an IDE to generate comments. That's why I suspected Netbeans. Currently we don't have a real `LICENSE` file, which is what this issue is for.

**Comment by 8Keep** [comment]
It is a template for creating a new "type" of file in Netbeans:
https://platform.netbeans.org/tutorials/nbm-filetemplates.html
So you can use the new file dialog, navigate to your new type of file, and create a new file that has the license at the top already. I don't know if it's used by anyone.

**Comment by tlf30** [comment]
Yeah, that probably was left there my mistake. It should be the actual license.

**Comment by 8Keep** [comment]
i will send a pr for this

**Comment by 8Keep** [comment]
> Yeah, that probably was left there my mistake. It should be the actual license.

It was last edited by Kiril 5 years ago

**Comment by tonihele** [comment]
Fixed via https://github.com/jMonkeyEngine/jmonkeyengine/pull/1371 already.

Just a note that the old Netbeans template could have co-existed too. It can be automatically loaded by Netbeans (at least), it can be referenced in gradle.build like so:

license = file("$rootDir/license.txt")

Then it'll appear to any new code files created in supported IDEs.

**Comment by MeFisto94** [comment]
If IntelliJ supports that too, I'd vote for including that as well

**Comment by ItsMike54** [comment]
Now that this issue is fixed, should this issue be closed?

**Comment by MeFisto94** [comment]
Fixed in #1328 and #1416 I'd say.
