### ISSUE TITLE
AudioBuffer.update accepts any type of ByteBuffer

### ISSUE THREAD

**Issue by plassma** [jMonkeyEngine/jmonkeyengine#1341]
There is no check whether the provided buffer is a nativeBuffer(as required), probalby not easy to implement, but a hint in the javadoc would imho already be a great improvement...

https://hub.jmonkeyengine.org/t/solved-playing-audio-from-audiobuffer-in-audionode-causes-jre-to-die/43091/9

**Comment by stephengold** [comment]
It's easy to check at runtime, using `Buffer.isDirect()`, which was added in Java 1.6

**Comment by stephengold** [comment]
It would also be easy to copy the data to a direct ("native") buffer, if it happens to be in a wrapped ("heap") buffer.

**Comment by plassma** [comment]
I'd suggest throwing an IllegalArgumentException, as I'd not expect the buffer to be copied.
Probably the users can create their buffers as directBuffers, which is more performant...

**Comment by plassma** [comment]
I implemented this simple check, but can't push a new branch to the repo (403), maybe I misunderstood how pullrequests work? I thought create a new branch, and in the pullrequest request a merge from my new branch to the master...

**Comment by MeFisto94** [comment]
You need to fork us first using the UI, which will create a copy of the repository on your account (technically you have two remotes then: upstream, which is us and origin, which is you).

And then you create a new branch on YOUR repository and we merge your branch to our master branch.

The catch is: You don't have permissions to access our repository directly

**Comment by stephengold** [comment]
Fixed in v3.3 branch at c85e2bc .
