### ISSUE TITLE
SDK tabs naming simplification

### ISSUE THREAD

**Issue by slawekmikula** [jMonkeyEngine/jmonkeyengine#135]
Simplify tab naming e.g. 
"AssetPackBrowser Window" to "AssetPack Browser" 
"FilterExplorer Window" to "Filter Explorer"
"SceneExplorer Window" to "Scene Explorer"

It can save a bit of space in multiple tabs in tab-group.

**Comment by Nehon** [comment]
Fixed with commit https://github.com/MeFisto94/jmonkeyengine/commit/e051936f9be015b338992b2b10a51f15d8cf6d36
