### ISSUE TITLE
SDK 3.1-pre-svn JME3 New BasicGame - template with older libraries

### ISSUE THREAD

**Issue by slawekmikula** [jMonkeyEngine/jmonkeyengine#136]
Template BasicGame when creating with current HEAD SDK require older libraries: jme3 and jme3-libraries. Due to fact, that jme3 is split to many partial libraries it has to be updated to core library jme3-core and provide in simple readme in BasicGame method to add more specific libraries.

**Comment by Dokthar** [comment]
This issue was moved to jMonkeyEngine/sdk#31
