### ISSUE TITLE
Tests are being built into the javadoc

### ISSUE THREAD

**Issue by 8Keep** [jMonkeyEngine/jmonkeyengine#1370]
For example, jme3test.bullet.TestIssue1004. I would consider this bad practice, it pollutes the javadoc with classes that no reasonable person would be looking for. Test classes usually don't have any javadoc documentation anyway.

Somewhat related to #1290

**Comment by stephengold** [comment]
I disagree. Code without documentation is crap. In Java, the standard form for documentation is JavaDoc.

**Comment by 8Keep** [comment]
> Code without documentation is crap. In Java, the standard form for documentation is JavaDoc.

I agree, and I don't think my intention clashes with this. When I open the javadoc and click on the com.jme3.scene package, I see:
![Screenshot_20200508_135456](https://user-images.githubusercontent.com/5598822/81434249-df10c800-9133-11ea-883c-d5af00d109cf.png)

I, as a user, do not expect to see automated tests in the javadoc. I don't want to see anything in the "test" sourceset at all, only the "main" sourceset. I don't think I've seen another javadoc that includes the projects automated tests in the javadoc.

What if jMonkeyEngine had many more automated tests, and there were more "TestIssue*" classes than the main classes I want to see documentation of? Navigating that javadoc would be awful. Not to mention, many automated tests don't begin in "Test" (making it hard to discover which classes are part of the automated testing, and which are real core classes), and automated tests aren't built into the jme libs anyway.

**Comment by pspeed42** [comment]
These are not all tests.  Some of them are examples (the majority?).  It's not like we're javadoc'ing unit tests... which I agree is pointless as unit tests are their own documentation.

Automated unit tests should be their own documentation.  They are not even supposed to be included in -source.jar bundles... so they definitely shouldn't be in -javadoc.jar bundles.

**Comment by 8Keep** [comment]
>  It's not like we're javadoc'ing unit tests... which I agree is pointless as unit tests are their own documentation.

I think unit tests are being built into the javadoc. Is TestIssue954 not a unit test?
Important clarification though: These unit tests are not being built into javadoc jars, only dist html (what is being uploaded to javadoc.jmonkeyengine.org)

**Comment by riccardobl** [comment]
I agree with this. Unit tests and examples should be ecluded from the javadoc.

**Comment by stephengold** [comment]
Fixed in "master" branch at e1dc2f6 .

**Comment by stephengold** [comment]
Confirmed fixed in v3.4.0-alpha1
