### ISSUE TITLE
Some suggestions for SimpleApplication

### ISSUE THREAD

**Issue by KongChengPro** [jMonkeyEngine/jmonkeyengine#1379]
First I want to say: Because my mother language is not English, my English is bad, please forgive me.
I think the main event loop `simpleUpdate` is hard to use, so I created the following class.
It can make the main event loop more convenient.
```Java
import com.jme3.app.SimpleApplication;

import java.util.Map;

public abstract class SimpleApplicationPlus extends SimpleApplication {
    protected int frame = 0;
    protected Map<Integer, Command> cmd;
    @Override
    public final void simpleUpdate(float tpf) {
        mainEventLoop(tpf);
    }
    protected void runCommand() {
        frame++;
        for (int perFrame : cmd.keySet()) {
            if (frame%perFrame==0){
                cmd.get(perFrame).run();
            }
        }
    }

    protected void registerCommand(int perFrame, Command command) {
        this.cmd.put(perFrame, command);
    }

    protected abstract void mainEventLoop(float tpf);
}

interface Command {
    void run();
}
```
You can use it like this
```Java
@Override
    public void mainEventLoop(float tpf) {
        // I used lambda instead Anonymous inner class
        registerCommand(1, ()-> {
            box.rotate(0, 2 * tpf, 0);
        });
}
```

**Comment by KongChengPro** [comment]
Oh, I seem to forgot to say something.
the first param of the method `registerCommand` is `perFrame`
It means that if `frame % perFrame == 0`, it will call back the second param

**Comment by pspeed42** [comment]
You should be using app states instead.  Most real games have almost no code at all in simpleInit() and nothing at all in simpleUpdate().  These are really just for quickly creating small demos and test applications.

Also, in general, frame counters are one of the WORST ways to schedule commands since a frame may take 0.00001 seconds or 999999 seconds and you never know.
