### ISSUE TITLE
DistanceLodCalculator serialization bug

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1381]
When serializing, `DistanceLodCalculator` specifies a default of 32 for lodMultiplier. When de-serializing, it specifies a default of 2.7

This means that if the multiplier was 32 before saving the object, it will load with a value of 2.7

**Comment by ItsMike54** [comment]
PR sent for this

**Comment by stephengold** [comment]
Fixed in master branch at 1cc43d9.
