### ISSUE TITLE
OGRE Importer should call saveInitialPose, to be consistent with GLTF

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1395]
See https://hub.jmonkeyengine.org/t/solved-converting-to-j3o/43603 for reference

**Comment by Ali-RS** [comment]
I guess adding `armature.saveInitialPose();` after below line should do the trick. 

https://github.com/jMonkeyEngine/jmonkeyengine/blob/1c638f27639a047b243157e667ed2d84b0c4d0bc/jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/SkeletonLoader.java#L166

**Comment by tlf30** [comment]
Has OGRE been updated to support the new animation system?

**Comment by Ali-RS** [comment]
Yes

**Comment by stephengold** [comment]
I committed the suggested fix to master branch at 14823018e3e04bc67b47c4bff629d1128488d05d

**Comment by stephengold** [comment]
I tested by loading "Models/Oto/Oto.mesh.xml"

**Comment by stephengold** [comment]
For future reference, I created a testcase at https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-examples/src/main/java/jme3test/model/anim/TestIssue1395.java

**Comment by stephengold** [comment]
Confirmed this issue resolved in v3.4.0-beta4.
