### ISSUE TITLE
We need documentation for the new animation system.

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#1402]
I know some people here are using it with the gltf importer, there is still no documentation on the wiki, and the "old" one was deprecated. 
If someone could provide some documentation, it would be greatly appreciated.

**Comment by stephengold** [comment]
Agreed. Thanks for opening the issue here.

**Comment by Ali-RS** [comment]
Nehon has made some on the forum,
https://hub.jmonkeyengine.org/t/monkanim-v2/39877

The heart of the new system is the Tween API from Lemur, saying that you can execute those tweens however you want, could be with "AnimComposer" provided in JME or with something else.

**Comment by tlf30** [comment]
It would be great to have documentation on the new animation system. I actually was about to work on some animation code and did not realize that the wiki did not have the new system under the 3.3 version, so thank you for opening this issue @riccardobl. 
Unfortunately I know very, very little about the new system.

**Comment by Scrappers-glitch** [comment]
> I know some people here are using it with the gltf importer, there is still no documentation on the wiki, and the "old" one was deprecated.
> If someone could provide some documentation, it would be greatly appreciated.

Okay , i am currently studying the new animation system , so which topics would you like to include in the wiki rather than the 'basic implementation' , so i could try to build some testcases & docs specifically for these topics.....

**Comment by tlf30** [comment]
Some detailed examples on tweens, and blending for transitions between animations would be nice. It would be great to have at least one example of using two animations on different parts of the model at once, and how to limit which bones and geometries the animation plays on.

**Comment by stephengold** [comment]
I'd be interested in how to synchronize animations with audio and particles. I don't know what would be the best approach.

**Comment by Scrappers-glitch** [comment]
Okay , thanks for recommendations , I will try my best , I will have a github repo that has a testCase for most of basic animation & tween binding with audio & particle emitters(the hack) into simple scenes , the github repo would have a small wiki that we can revise & add/remove from it before merging to the actual jme wiki.

**Comment by stephengold** [comment]
This issue was originally about documenting the animation system in the wiki.

Improving the javadoc (as PRs #1626 and #1642 do) is also very important, but I think it's a separate issue.

**Comment by Scrappers-glitch** [comment]
> This issue was originally about documenting the animation system in the wiki.

This issue should be moved to the wiki repository.

**Comment by oneMillionWorlds** [comment]
I updated the hello animation documentation page to use the new animation system. Is that what this ticket is requesting?

https://wiki.jmonkeyengine.org/docs/3.4/tutorials/beginner/hello_animation.html

**Comment by richardTingle** [comment]
I updated the hello animation documentation page to use the new animation system. Is that what this ticket is requesting?

https://wiki.jmonkeyengine.org/docs/3.4/tutorials/beginner/hello_animation.html

**Comment by pavly-gerges** [comment]
> Is that what this ticket is requesting? (If so shall we close it?)

As a consequence to what @stephengold has stated, I believe this issue must be converted to the Wiki repository. It essentially requests a complete wiki documentation for the new Animation System. Then, you guys can review it there before closing.

**Comment by stephengold** [comment]
I took a quick look at the wiki page, and it satisfied my expectation.
I think this issue is now resolved, so I'm closing it.

**Comment by yaRnMcDonuts** [comment]
I'm not entirely sure if I should mark this as part of the engine's Future Release v3.8.0 milestone, since this is technically a wiki related issue.

But I added it to the milestone anyways, so that way it can be announced as part of the 3.8 release and will hopefully draw more attention to the updated animation tutorial.
