### ISSUE TITLE
I can't add gizmo from original project to my modified version

### ISSUE THREAD

**Issue by AdanosGotoman** [jMonkeyEngine/jmonkeyengine#1411]
Hello everyone! May I ask you for help? In general, the situation is as follows: based on jme3 my friend from Germany created a program for editing world data for the game Gothic 3. As a separate module, he wrote a utility for viewing game levels and 3D models. Only there is a small problem - he didn't include the gizmo in it. I tried to get inspired by the original engine jme3, but I couldn't manage to add it for object manipulation. Looking at the original SceneEditTool class, I did not understand what was needed SceneComposerToolController and its fields and methods toolController. Can you to look into the class NodeViewerApp? I hope you can tell me how to implement a gizmo for this modification jme3.
https://github.com/georgeto/g3dit/tree/wip-jdk11

**Comment by riccardobl** [comment]
This is the issue tracker of the engine, not the right place to ask for help on your personal project. 
You should open a thread on the forum: https://hub.jmonkeyengine.org
