### ISSUE TITLE
GLTF Converter needs support for AO value in MetallicRoughnessMap

### ISSUE THREAD

**Issue by yaRnMcDonuts** [jMonkeyEngine/jmonkeyengine#1412]
Now that we have added support for packing the AmbientOcclusion value into the Red channel of the MetallicRoughnessMap,
we need to update the GLTF converter so that auto-generated materials utilize this feature.

Currently, whenever the GLTF converter detects the AO packed into the MR map, it will just define the MR map to both material params: "MetallicRoughnessMap" (as expected) and also to "LightMap" (and then it also sets the boolean LightMapAsAoMap to true)

This resulted in an extra texture read from the light map in the PBR shader (which defeats the purpose of packing it into the MR map), which is why PR https://github.com/jMonkeyEngine/jmonkeyengine/pull/1403 was necessary to make it so AO is read directly from the red channel of the MR Map 

Now we need to update the converter to instead set "AoPackedInMrMap" to true whenever the GLTF file detects an AO map packed in the MR Map.

**Comment by stephengold** [comment]
I believe that should be in https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java

**Comment by oxplay2** [comment]
i understand its all about reading AO from red channel of packed MetallicRoughnessMap. (that is correct with khronos spec i assume)

was just curious how GLTF exporter link them, so found link:
![image](https://user-images.githubusercontent.com/45903579/96445803-c2170f80-1210-11eb-9674-4549c064312c.png)
![image](https://user-images.githubusercontent.com/45903579/96445810-ca6f4a80-1210-11eb-9452-c22223adbdc8.png)


it sounds very cool.
