### ISSUE TITLE
bulletjme: Add Bitness/Architecture Suffix

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1422]
For all other native libs we have like `OpenAL64.dll` and `lwjgl32.dll`, not so for bulletjme.
When switching jvms between 32bit and 64bit, you get an UnsatisfiedLinkError due to the DLL requiring a manual deletion.

**Comment by stephengold** [comment]
1. Changing the filenames of Bullet native libraries will break Minie, which relies on the current naming scheme

2. Even with this change, file deletion will still be required when switching between different versions of jme3-bullet-native, or when switching between jme3-bullet-native and Minie

**Comment by Ali-RS** [comment]
Apparently, Minie depends on `bulletjme` natives that are loaded via NativeLibraryLoader on JME side.

**Comment by Ali-RS** [comment]
>Extracting natives from the classpath into the working directory is a risky hack. In the long term, JME should probably use a native-library loader analogous with that of LWJGL v3.

>_Originally posted by @stephengold in https://github.com/jMonkeyEngine/jmonkeyengine/issues/1965#issuecomment-1444233100_
            

I concur with this. We should not extract natives into the working.


LWJGL will try the following paths and the first successful will be used:
- System.getProperty("java.io.tmpdir")
- `<working directory>`
- System.getProperty("user.home")
- Files.createTempDirectory("lwjgl", "")


>JME first looks [working directory](https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L255-L272) if it is writable then chooses that else it looks for [user cache directory](https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L293-L320) inside user.home directory, if found, will extract there, if not found then it will extract to `userHome/.jme3`.

_Originally posted by @Ali-RS in https://github.com/jMonkeyEngine/jmonkeyengine/issues/1965#issuecomment-1444258551_
            
I think we should omit the "check for the working directory" from the above steps, and add another step at the very end to check "java.io.tmpdir" if none of the previous steps succeed.

**Comment by Ali-RS** [comment]
Fixed in #1973 

Added Architecture Suffix to all `bulletjme` natives when extracting. 
**Note: This is not a breaking change, no changes are required on the Minie project.**

https://github.com/jMonkeyEngine/jmonkeyengine/blob/308cdf12fb1042d07866ab726b4835c492bd8d59/jme3-desktop/src/main/java/com/jme3/system/NativeLibraries.java#L74-L86
