### ISSUE TITLE
No  terminate()  method in BaseAppState

### ISSUE THREAD

**Issue by fredokun** [jMonkeyEngine/jmonkeyengine#1428]
The documentation for  `com.jme3.app.state.BaseAppState` is misleading

https://github.com/jMonkeyEngine/jmonkeyengine/blob/507cc2213f16449af8938d4eaa1987138e9d4dec/jme3-core/src/main/java/com/jme3/app/state/BaseAppState.java#L50

From what I see, `initialize()` is (purposely) final  and there is no such method `terminate()`.
Perhaps it was decided that `onEnable()/onDisable()` is enough for lifecycle management ?

**Comment by Ali-RS** [comment]
A typo I guess. That should be the `cleanup()` method.

**Comment by Ali-RS** [comment]
Fixed in #1429
