### ISSUE TITLE
Remove Sailing Navigation Code from jme3-desktop

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#1430]
It's about https://github.com/jMonkeyEngine/jmonkeyengine/tree/f652591/jme3-desktop/src/main/java/jme3tools/navigation
In this folder we have a few utilities and others related to sailing and something like a StringUtil (which however has severe issues such as an infinite loop).

A) This doesn't belong into jme3-desktop specifically
B) I can't see a reason to have this directly on the engine.

It's history predates the switch from SVN, so we can't say much about the history, maybe @normen remembers?
Eitherway this would probably best be kept on `jME-Contributions` if at all.

**Comment by normen** [comment]
Yep, that was a contribution coming in pretty early in the development of jme3, was the result of a cool project simulating freighter navigation afaicr. A lot of code that might have been usable so we kept it. There was no "contribution repo" or anything back then. I guess it was never really used by anyone.

Am 21.11.2020 16:10 schrieb MeFisto94:

**Comment by stephengold** [comment]
I've created https://github.com/jMonkeyEngine-Contributions/jme3tools.navigation and submitted PR #1450.

@benjamij Do you have any comments on this issue?

**Comment by stephengold** [comment]
The removal happened in "master" branch at e7cb2d8ce97972d9c73179f0f94e8bc735b43039 .
