### ISSUE TITLE
Remove 10000.monkeyz from jme3-core

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1431]
We don't need this file, which is included as an asset in all jme3-core JARs.
It consists entirely of an ASCII graphic of the JME logo:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/resources/10000.monkeyz

**Comment by riccardobl** [comment]
this is not used anywhere right?
I guess it was used as some sort of branding for terminal apps(?)

**Comment by stephengold** [comment]
Right. I've always assumed it was a joke.

**Comment by MeFisto94** [comment]
The history is somewhere on the hub, I think. It was related to the 10kth commit(?) or something as celebration.

**Comment by stephengold** [comment]
I found it:

https://hub.jmonkeyengine.org/t/jmonkeyengine-reaches-10000-commits-revisions/24355

**Comment by stephengold** [comment]
Resolved in "master" branch at ce9a651 .
