### ISSUE TITLE
setFrameRate on lwjgl3 leads to too slow frame rate

### ISSUE THREAD

**Issue by richardTingle** [jMonkeyEngine/jmonkeyengine#1455]
**Issue**
When running JME with jme3-lwjgl3 the AppSettings#setFrameRate method call does not work correctly, causing far lower frame rates that requested. My application, when unlimited runs at around 60 fps, but when limited runs as follows:

| Requested | Actual |
|--|--|
| 60 |  30|
| 120 |  37|
| 240 |  45|
| 2400 |  55|
| No limit |  60|

This only occurs with jme3-lwjgl3, jme3-lwjgl works fine

**Investigation so far**
I've had a look in the debugger at what's going on in LwjglWindow#runLoop and on line 564 I see it trying to figure out how long to sleep for:

`final double sleep = frameSleepTime - (timer.getTimePerFrame() / 1000.0)`

However, timer.getTimePerFrame() appears to always return zero, leading to it always sleeping for the full 1/frameRate. Meaning if the application is under any sort of load that brings it close (or worse below) to the requested frame rate it slows the application way below the requested rate.

This appears to be because `Timer#update` is never called (a different times update method is called, but not the one in `LwjglWindow`

**Environment**

I'm running `3.3.2-stable` but I've also checked out and run against the V3.3 branch and it behaves the same (master looks like it would have the same problem but crashes for me)

**Comment by richardTingle** [comment]
There are some other problems in runLoop, `timer.getTimePerFrame()` is in seconds so it should be multiplied by 1000, not divided. But the bigger problem is that even if corrected it still runs at the wrong frame rate, as on frame 1 it detects and corrects the problem, then on frame 2 there is (as far as it sees) no problem, so it doesn't sleep. Meaning every other frame runs too fast.

 jme3-lwjgl's version of this seems much more complicated (necessarily so) calling Sync.sync which runs a longer average thereby avoiding the problem

**Comment by riccardobl** [comment]
This is fixed by this unmerged patch:

https://github.com/jMonkeyEngine/jmonkeyengine/pull/1406/commits/2f62afc3996b37171b636e71c4f7a70cf3a5fcf9

from pr https://github.com/jMonkeyEngine/jmonkeyengine/pull/1406

**Comment by richardTingle** [comment]
Awesome! I'll stop investigating in that case. 

Should this issue be closed or should it stay open till the PR is merged?

**Comment by stephengold** [comment]
I'm fine leaving this open. It might help someone solve a similar issue. And it's not like we're going to clear out the backlog anytime soon...

**Comment by stephengold** [comment]
richtea reported this issue fixed in 3.4.0-beta1:

https://hub.jmonkeyengine.org/t/engine-v3-4-0-beta-testing/44507/5
