### ISSUE TITLE
Material name for objLoader

### ISSUE THREAD

**Issue by YHKing101** [jMonkeyEngine/jmonkeyengine#1472]
**com\jme3\scene\plugins\OBJLoader.java** in this file

**protected Geometry createGeometry(ArrayList<Face> faceList, String matName)** in this function

Link the resolved MTL material to the model
But the name of the Geometry is generated statically from the code

code：
**Geometry geom = new Geometry(objName + "-geom-" + (geomIndex++), mesh);**

and not setName to  material
so I think if can set material Name by MTLLoader ‘s matName
In this way, the name of the material is consistent with the name of the MTL file
If a model wants to perform a special operation on one of the materials, it can obtain the material in code. At present, I don't know how to obtain a special material in the code
Of course, this is just a place that I think may be optimized. It may be unreasonable. Please check it

    implementation 'org.jmonkeyengine:jme3-core:3.3.2-stable'
    implementation 'org.jmonkeyengine:jme3-plugins:3.3.2-stable'
    implementation 'org.jmonkeyengine:jme3-android:3.3.2-stable'
    implementation 'org.jmonkeyengine:jme3-android-native:3.3.2-stable'
    implementation 'org.jmonkeyengine:jme3-effects:3.3.2-stable'

**Comment by pspeed42** [comment]
My reading of the code is that matName can be null... it's also used to look up the material in the .mtl file.

The MTLLoader, does set the name:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/plugins/java/com/jme3/scene/plugins/MTLLoader.java#L155

So I think your suggestion is only covering the case of default materials for when there is no MTL file but somehow there IS a material name.  I guess it does no harm but it seems like a relatively rare case?  (I don't know as I never ever use OBJ files.)

**Comment by tlf30** [comment]
I interpreted that he was requesting to set the geometry to the name of the material. I don't see a reason to do this though. Especially considering that a material can be used on more than one geometry. Perhaps I am reading his question wrong.

**Comment by YHKing101** [comment]
material.setName(matName);   
I think that，good job~~~

Because the MTL file defines the material name, I think when parsing a material from MTL, the resolved material name should be set to the material object
After adding your line of code, the mesh object is bound to a specific material, so that you can operate on a specific material during the loop traversal
These are my views, ha ha ha

**Comment by YHKing101** [comment]
> 
> 
> I interpreted that he was requesting to set the geometry to the name of the material. I don't see a reason to do this though. Especially considering that a material can be used on more than one geometry. Perhaps I am reading his question wrong.

My problem only appears in the obj model with material. I see that the code is a geometry corresponding to a material. I don't know if my understanding of the code is correct

**Comment by pspeed42** [comment]
Geometry != material.  Material != Geometry.

**Comment by YHKing101** [comment]
> 
> 
> Geometry != material. Material != Geometry.

I think my previous expression is not very clear, which makes you confused.
I also know that geometry and material are two conceptual things
I am puzzled that the names of multiple materials created by mtlloader are empty, so I think we can use the name defined by newmtl in the MTL file, so that an obj model can find the material according to this name and set properties for the material

**Comment by pspeed42** [comment]
As shown in the code I linked, if the material is in the mtl file then it is already named.  If the object refers to this named material then that is the material used.  At least according to the code.

re: "I am puzzled that the names of multiple materials created by mtlloader are empty"  This is not true.  There is no case where a material "created by the MTLLoader" will be empty.

If you are seeing materials with no name then they were not created by the MTLLoader.  They were default materials because the MTL didn't have them.

I would suggest that if you want to trouble-shoot what's wrong with your models that the forum is a better place for that.

**Comment by YHKing101** [comment]
> 
> 
> As shown in the code I linked, if the material is in the mtl file then it is already named. If the object refers to this named material then that is the material used. At least according to the code.
> 
> re: "I am puzzled that the names of multiple materials created by mtlloader are empty" This is not true. There is no case where a material "created by the MTLLoader" will be empty.
> 
> If you are seeing materials with no name then they were not created by the MTLLoader. They were default materials because the MTL didn't have them.
> 
> I would suggest that if you want to trouble-shoot what's wrong with your models that the forum is a better place for that.



I mention QA because the name obtained in 3.3.2-stable (the latest version available at present) is empty. Your additional code can solve my problem ~ ~ ~ thank you very much
