### ISSUE TITLE
assertion fails for createIndexBuffer(0, 0)

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1477]
Here's the relevant portion of the stack trace:
```text
Mar 12, 2021 8:39:43 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.AssertionError: out of range: -1
	at com.jme3.scene.mesh.IndexByteBuffer.<init>(IndexByteBuffer.java:71)
	at com.jme3.scene.mesh.IndexBuffer.createIndexBuffer(IndexBuffer.java:81)
```

Discovered in JME v3.4.0-alpha1

**Comment by stephengold** [comment]
Note: this worked in v3.3.2-stable, so it's a regression.

**Comment by Ali-RS** [comment]
Should `createIndexBuffer(0, 0)` be allowed or it should throw an `IllegalArgumentException`?

**Comment by stephengold** [comment]
The use case is an empty index buffer to represent an empty mesh---one with no vertices.

**Comment by Ali-RS** [comment]
Submitted a fix: https://github.com/jMonkeyEngine/jmonkeyengine/pull/1479

**Comment by stephengold** [comment]
Thanks for the fix!

**Comment by stephengold** [comment]
I verified that the fix works in my application.
