### ISSUE TITLE
Add Getter/Setter methods for attribute fieldOfView in the class Camera.java

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/jmonkeyengine#1491]
As discussed in the forum, would it be possible to add the getter and setter methods for the attribute fieldOfView in the Camera.java class to make it easier to read and write in the next release ?

https://hub.jmonkeyengine.org/t/getter-setter-methods-for-attribute-fieldofview-in-the-class-camera-java-in-jme-3-4/44426

**Comment by stephengold** [comment]
Yes, it's possible. Are you going to write the code and submit a pull request? Or would you prefer someone else did that?

**Comment by capdevon** [comment]
I'm not very familiar with github yet. It would be better if someone else did it, who knows the project well
