### ISSUE TITLE
jme-lwjgl3 - bug for starting app

### ISSUE THREAD

**Issue by supertick** [jMonkeyEngine/jmonkeyengine#1514]
What is expected :  When starting a SimpleApplication JMonkeyEngine would spawn a thread for internal processing with an option to "waitFor" block until started.

What is observered: The calling thread is endlessly blocked by calling the run() method directly - with a note ...
// NOTE: this is required for Mac OS X!
https://github.com/jMonkeyEngine/jmonkeyengine/blob/v3.2.3-stable/jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java#L420-L423

PR submitted - https://github.com/jMonkeyEngine/jmonkeyengine/pull/1513

**Comment by tonihele** [comment]
Hmm, is this the correct issue... But check out what LibGX tries to do with their LWJGL 3 MacOS starting problem:
https://github.com/libgdx/libgdx/pull/6673

**Comment by Ali-RS** [comment]
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/pull/1690
