### ISSUE TITLE
TestLeakingGL not clearing memory of unused objects

### ISSUE THREAD

**Issue by Markil3** [jMonkeyEngine/jmonkeyengine#1525]
https://hub.jmonkeyengine.org/t/white-screen-on-context-restart-lwjgl-garbage-collection-issue/43866/28?u=markil3
While I was working on fixing context restarts, I found out that, despite what it says, TestLeakingGL does not seem to remove its unused geometries from memory like it says it does. As I continue to let it run, it rapidly eats up more memory, quickly reaching 2 GB and beyond. Further testing reveals that this is a very old bug that hasn't worked properly since before version 3.1.
I'm running this on an Ubuntu 20.04 GNOME environment, with an NIVIDA Quadro M4000, using the proprietary 460 driver.

**Comment by Markil3** [comment]
Oddly enough, when I switch to the Nouveau driver, the example seems to maintain 60 FPS a lot of the time, even as it exceeds 6 GB of memory. Granted, there are lag spikes, but
Of course, that driver seems to drop the FPS on a lot of my other applications, and doesn't play nicely with Wine games _at all_, so I can't really recommend that driver.

**Comment by Ali-RS** [comment]
Can you try with setting this flag to `true`

https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObjectManager.java#L61

**Comment by Markil3** [comment]
The UNSAFE flag doesn't seem to have an effect. I tried on jme3-lwjgl, jme3-lwjgl3, and I later set the renderer to OpenGL 4.5. The memory still steadily climbed in all cases.

**Comment by Ali-RS** [comment]
Can you please add this code while setting the UNSAFE flag to true

`System.gc();`

after this line

https://github.com/jMonkeyEngine/jmonkeyengine/blob/ceb356462aeedf7769dced52e1d5572b01deca31/jme3-examples/src/main/java/jme3test/stress/TestLeakingGL.java#L80

**Comment by Markil3** [comment]
It seems to slow down the climb a little bit. However, it climbs all the same, and calling the garbage collector all the time drastically impacts performance (although I might be running on JDK 8).

**Comment by Markil3** [comment]
I have noticed that, even though UNSAFE is true, deleteBufs and realObj are always false and null, respectfully. This warrants investigation.
https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObjectManager.java#L161

**Comment by Ali-RS** [comment]
`deleteBufs and realObj are always false `

Yes, and that's what confuses me. 
What the hell NativeObjectManager is doing then!?

**Comment by Markil3** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObjectManager.java#L177
The user deletion queue never seems to have anything in it. I'll see if I can find where it gets populated.

**Comment by Ali-RS** [comment]
@Markil3 can you try setting the log level to FINE and see if it logs anything?

https://github.com/jMonkeyEngine/jmonkeyengine/blob/ceb356462aeedf7769dced52e1d5572b01deca31/jme3-examples/src/main/java/jme3test/stress/TestLeakingGL.java#L75

**Comment by Markil3** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObject.java#L234
The user queue gets populated here. However, I can't seem to find any relevent code that actually calls this. Just the camera, and that's it.
![Screenshot from 2021-04-15 11-42-13](https://user-images.githubusercontent.com/75867393/114914838-0c540480-9de0-11eb-86f8-5885133cf97e.png)

**Comment by Ali-RS** [comment]
I think that's for deleting manually by the user, I might be wrong so.

There is also 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObject.java#L193

which seems to be the one used by NativeObjectManager

**Comment by Ali-RS** [comment]
/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObjectManager.java#L183-L192

**Comment by Ali-RS** [comment]
Sorry, I hit the close button by mistake while editing my post.

**Comment by Markil3** [comment]
I know that everyone loves logging libraries, but I can never seem to get them to work properly on my end.

Anyway, here's the log:
https://gist.github.com/Markil3/7244cadcaa4dc23939b690462f5057c4
To keep the log size down, I ran it for three frames before stopping the app with SimpleApplication#stop(). From what I can see, nothing actually gets deleted for the first tick. It isn't until the end of the second it (tick1) that anything is removed (and the stuff removed is vastly outnumbers by the stuff created, at least until I shut it down).

**Comment by Markil3** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObject.java#L193
This method is ultimately called from NativeObjectManager as part of its cleanup (the deleteUnused method I posted earlier) or when shutting down.

**Comment by Markil3** [comment]
**I think that's for deleting manually by the user, but I might be wrong.**
That seems accurate. In that case, the only time deleteNativeObject() gets called at all besides shutdown is in the same method when it is polling the refQueue. Now, that certainly gets populated (how it gets populated is a little obtuse, but it definitely seems to have stuff in it after calling registerObject(NativeObject). Now, unless I'm missing something, once an object is added to the queue, it doesn't leave the queue until it is polled by the deleteUnused() method called at the end of every frame. Here, it goes through every item in the queue (well, up to whatever MAX_REMOVES_PER_FRAME is set to, at least). If I set MAX_REMOVES_PER_FRAME high enough, I consistently get 1800 removals per tick. This changes depending on how many spheres I generate (if I generate 100 per tick, I usually get 200 objects removed per tick, although I did get 400 on one tick for some reason). For every object, NativeObjectManager tells the object to remove itself from its rendering object (how exactly this happens depends on the object, but usually the object will call a method on GLRenderer.
Now, from my tests, every object that gets registered is removed. There is never any more registered objects compared to deleted objects. From this, I see two possibilities:

1. There is an error in the implementation of at least one of the NativeObjects, so it isn't getting removed properly. There are 12 total implementors of NativeObject. One of them is in the android library. Five more are related to audio, so I doubt any of them are causing problems. The search would thus likely put us in the remaining 6, which can be found in the .scene, .shader, and .texture packages of the jMonkey core.
2. Whatever is hogging memory is unrelated to the native objects. If so, we are back to square 1.

**Comment by pspeed42** [comment]
re:  (how it gets populated is a little obtuse, but it definitely seems to have stuff in it after calling registerObject(NativeObject))
...if this is standard WeakReference (or any of the XxxReference stuff) then the queue population is automatically done by the garbage collector when the object is weakly reachable (etc.).  When and how this happens is well documented in the JDK javadoc.

If you run the JME SDK, I think there is already a memory profiler that you can use to see what's taking all of the memory and trace back up to see where it comes from.  By the same you are really overflowing, it should be easy enough to see.

**Comment by Ali-RS** [comment]
Taking a closer look I could get a bit grasp on code.

As mentioned the `refQueue` in NativeObjectManager will be filled by the garbage collector.

but as you mentioned earlier, the boolean `deleteBufs` is set to false (the last argument)

https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObjectManager.java#L190

so it will never destroy the buffer in:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/92a94790a2628e336c248ee7dd622219839c1242/jme3-core/src/main/java/com/jme3/util/NativeObjectManager.java#L161-L165

even if you set the UNSAFE to true.

Note in this case the NativeObject is a VertexBuffer.

I think the reson boolean `deleteBufs` is set to false is because in JME when you clone a model (or load via AssetManager) it will share the mesh data (VertexBuffer) on all the clones so if it destroys the buffer when one clone gets removed then it will crash all other clones that are still in scene, but I might be wrong anyway.

**Comment by Markil3** [comment]
Also keep in mind that realObj has never been anything but null in my testing, so that even if we set deleteBufs to true, the code still wouldn't trigger.

**Comment by pspeed42** [comment]
Something to consider is that I create TONS of meshes on the fly in almost every one of my tech demos (far terrain, block worlds, etc.) and memory leakage has never been an issue.  I don't even manually delete stuff anymore like I used to do in old Mythruna.

,,,which points to some potential flaw in the test setup.

**Comment by Markil3** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/ceb356462aeedf7769dced52e1d5572b01deca31/jme3-examples/src/main/java/jme3test/stress/TestLeakingGL.java#L83
This seems to be problematic. If I just stop cloning them and just directly use the original all the time, then that seems to fix it. It now just hovers between 220 and 240 MB.
Apparently, jmonkey does not like to create an exponential number of mesh objects and just doesn't properly garbage collect them for some reason. Using the same one each time, though, seems to work just fine.
Of course, skipping the creation of meshes may bypass the point of the test, so I don't know.
@pspeed42, do you mean meshes as jmonkey defines them (the vertices shapes, what other engines calls "geometry"), or the combination of shape and material in general?

**Comment by Markil3** [comment]
So apparently, if I use the same mesh for all of my spheres, the NativeObjectManager registers two objects that it removes as soon as I'm done using it (in this test, that happens when I close the application). If I just create a bunch of meshes and do nothing with them, they are not garbage collected, nor do they even register in NativeObjectManager at all.
```
rootNode.detachAllChildren();
for (int y = -15; y < 15; y++){
    for (int x = -15; x < 15; x++){
        original.deepClone();
    }
}
```
I'm suspecting that something with these meshes are getting stored somewhere and not dereferenced.

**Comment by pspeed42** [comment]
Yes, I mean I literally create new Mesh(), fill it with data, stick it in a geometry... then maybe a few seconds later, abandon it and create a new one.  Thousands and thousands and thousands of times.  Memory is stable.

**Comment by pspeed42** [comment]
Does the test ever throw OutOfMemory errors or does it always eventually recover and keep RAM below some value?

...if it never throws an error then maybe it's just GC settings at issue.

**Comment by Markil3** [comment]
I tried it when I limited the heap to 1G, and it eventually stopped and hovered around 700 MB. I'm running it at the default settings now (maximum of about 8 GB), and, according to JProfiler, garbage collection seems to happen every 40 seconds or so and idling the rest of the time. The committed memory after about 6 minutes seems to be hovering around 2.75 GB of RAM
Of course, the FPS is down to 17 frames per second, so there seems to be something going on there.
If I apply @Ali-RS's earlier suggestion and run garbage collection every second, JProfiler reports a steady memory consumption (at the cost of 12 frames per second).
I'm getting the distinct feeling that I just wasted everyone's time.

**Comment by Markil3** [comment]
Alright, I ended up going back to the test that sent me down this rabbit hole: the context restart. I ran it through a stress test where I restarted the context several times a second. In both the original restart code and my new one, the memory climbed a little, but it eventually stopped and hovered.
At this point, I'm not sure I can really find an issue anymore. TestLeakingGL has a pretty low framerate, but it is testing the memory, not the CPU performance. Unless we want to differ on that point, I think I'll just close this issue and go on ahead with the context restart stuff I was working on earlier.
Really sorry for dragging you all down this time for what turned out to be a non-issue, everyone.

**Comment by Ali-RS** [comment]
Just tried this my self

>Does the test ever throw OutOfMemory errors
Yes, it does in my case.

>If I apply @Ali-RS's earlier suggestion and run garbage collection every second, JProfiler reports a steady memory consumption (at the cost of 12 frames per second).

when used with `deepClone();` or `clone()`?

>...every time you see hires geometry pop-in around the player, that's a new Mesh(). Happens thousands of times in this video... and you can see memory stays pretty stable. (Upper right corner.) It's even back down to 18% by the end.

Hmm, but that shows the heap memory, not the direct memory. Afaik mesh data all are stored on out of heap.
