### ISSUE TITLE
Add more constructors to the AnimEvent class

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/jmonkeyengine#1529]
As discussed on the forum, would it be possible to add 4 more constructors to make creating an AnimEvent easier and more compact? https://hub.jmonkeyengine.org/t/question-about-new-animation-system-part-3-engine-v-3-4-0-beta1/44546/4
```
        public AnimEvent(Spatial model, String actionName, String layerName, LoopMode loopMode) {
            this.composer = model.getControl(AnimComposer.class);
            this.actionName = actionName;
            this.layerName = layerName;
            this.loopMode = loopMode;

            Action eventAction = composer.action(actionName);
            initialDuration = (float) eventAction.getLength();
        }

        public AnimEvent(Spatial model, String actionName, String layerName) {
            this(model, actionName, layerName, LoopMode.DontLoop);
        }

        public AnimEvent(Spatial model, String actionName) {
            this(model, actionName, AnimComposer.DEFAULT_LAYER, LoopMode.DontLoop);
        }

        public AnimEvent(Spatial model, String actionName, LoopMode loopMode) {
            this(model, actionName, AnimComposer.DEFAULT_LAYER, loopMode);
        }
```

**Comment by Ali-RS** [comment]
`this.composer = model.getControl(AnimComposer.class);`

As already mentioned in the forum this may return "null" if anim root (which has the AnimComposer) is a child of the model node. I think this will be always null for Gltf models as Gltf loader always wrap it inside a node. So might better to pass the AnimComposer directly in the constructor.

Also better to use `this()` in the upper constructors to delegate it to the last one instead of copy-pasting the code in all constructors.

**Comment by capdevon** [comment]
Even the AnimComposer you pass to the constructor could be null, any parameters you pass to any method / constructor could be null.  Even the AnimationEvent class did not check if the AnimControl was null, it was up to common sense of the programmer. If you think this is useful you can throw an exception in case `model.getControl (AnimComposer.class)` returns null by specifying it in the constructor description. End users would have more options to choose from.

For the second point I completely  agree with you.

**Comment by pspeed42** [comment]
```
cinematic.addCinematicEvent(0, new AnimationEvent(player.getChild("Armature"), "Rain_Dance", LoopMode.Loop));
```
If you are already going to make the user specify the exact right child then we not just specify the control, too... it's not much more code:
```
cinematic.addCinematicEvent(0, new AnimationEvent(player.getChild("Armature").getControl(AnimComposer.class), "Rain_Dance", LoopMode.Loop));
```
...and as I understand it, it's very hard to get AnimComposer to do anything BUT loop.  Common complaint that it loops even when you don't want it to.

The problem with beefy constructors is that they become suited to only a narrow set of cases and we end up with 50 constructors all with the exact parameters someone needed for 1-2 specific use cases.

...versus some application-specific factory methods that already knew that their models all had "Armature" and could just roll it in.
MyAnimEvents.create(player, "Rain_Dance");

**Comment by capdevon** [comment]
I agree, but in this case, with the extra builders the transition from the old to the new animation system would be easier and would encourage users to update their codes effortlessly and without having to learn too much new information. It's a good way to sponsor new features without straying too far from previous ones. 

In this way the differences would be minimal.

old anim system:
```
cinematic.activateCamera(0, cineCam.getName());
cinematic.addCinematicEvent(0, new SoundEvent("Sound/Environment/Nature.ogg", LoopMode.Loop));
cinematic.addCinematicEvent(0, new SoundEvent("Sound/Effects/kick.wav"));
cinematic.addCinematicEvent(0, new AnimationEvent(player.getChild("Armature"), "Rain_Dance", LoopMode.Loop));
```
new anim system:
```
cinematic.activateCamera(0, cineCam.getName());
cinematic.addCinematicEvent(0, new SoundEvent("Sound/Environment/Nature.ogg", LoopMode.Loop));
cinematic.addCinematicEvent(0, new SoundEvent("Sound/Effects/kick.wav"));
cinematic.addCinematicEvent(0, new AnimEvent(player.getChild("Armature"), "Rain_Dance", LoopMode.Loop)); // with new constructor
```

Mine is just a suggestion. The solution that you have proposed solves all the scenarios. I accept any final decision, the exchange of ideas is always useful to improve the engine :)

**Comment by capdevon** [comment]
After discussions with the community, I believe this change is no longer necessary and can be closed. Thank you all.
