### ISSUE TITLE
MorphControl doesn't override cloneFields(), jmeClone(), read(), nor write()

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1548]
As was pointed out at the Forum, the `MorphControl` class supposedly implements `JmeCloneable` and `Savable`, yet none of the relevant methods are overridden.

https://hub.jmonkeyengine.org/t/issue-with-multiple-models-and-morph-animations/44598

Obviously this makes it impossible to load a `MorphControl` from assets.

Also, the OP reported that after cloning a model with a `MorphControl`, the clone and the original morphed in synchrony.

In my own tests, cloning a model with a `MorphControl` resulted in a crash:
```text
RendererException: Cannot recompile shader source
```

**Comment by stephengold** [comment]
You're quite right.

**Comment by Ali-RS** [comment]
After testing on a bunch of different models I confirmed that works fine to move 

https://github.com/jMonkeyEngine/jmonkeyengine/blob/226176b379e723495613e0f59b6ea21e9eb03d7b/jme3-core/src/main/java/com/jme3/anim/MorphControl.java#L79-L82

into setSpatial() method.

```
    @Override
    public void setSpatial(Spatial spatial) {
        super.setSpatial(spatial);

        // gathering geometries in the sub graph.
        // This must be done in the update phase as the gathering might add a matparam override
        targets.clear();
        if (spatial != null) {
            spatial.depthFirstTraversal(targetLocator);
        }
    }
```

**Comment by Ali-RS** [comment]
And this line

https://github.com/jMonkeyEngine/jmonkeyengine/blob/226176b379e723495613e0f59b6ea21e9eb03d7b/jme3-core/src/main/java/com/jme3/anim/MorphControl.java#L90

should be changed like

`for (Geometry geom : targets.getArray())`

**Comment by stephengold** [comment]
A 2nd PR sounds to me like a good plan.

**Comment by stephengold** [comment]
Okay, @Ali-RS. It's your turn now!

**Comment by Ali-RS** [comment]
I'm on it :)
