### ISSUE TITLE
Material parameter of type IntArray is empty after resetting it

### ISSUE THREAD

**Issue by theMinka** [jMonkeyEngine/jmonkeyengine#1564]
I found a bug related to Material parameters of the type VarType.IntArray.

If you set the parameter for the first time, everything works fine.
However, if you change the parameter later on, it won't be set within the Shader.
The parameter get erased and is empty.

I noticed the bug inside the class Uniform.
When resetting the parameter, the buffer gets resized but not populated with the right array data.
I can provide a pull request to fix the problem.

**Comment by stephengold** [comment]
Thanks for reporting this issue. I would welcome a pull request. If you provide one, please include a test case.
