### ISSUE TITLE
android 9-11 bug

### ISSUE THREAD

**Issue by blueming333** [jMonkeyEngine/jmonkeyengine#1578]
skybox can not use on android9-11
like this:
Spatial sky = SkyFactory.createSky(assetManager, "Textures/Sky/St Peters/StPeters.jpg", SkyFactory.EnvMapType.SphereMap);
 rootNode.attachChild(sky);
its is nothing to render

**Comment by blueming333** [comment]
Device name is "google Pixel 3 XL"

**Comment by stephengold** [comment]
This issue tracker is for tracking known issues with the software. Few people monitor it.

To get help with troubleshooting, I recommend joining the [jMonkeyEngine Hub](https://hub.jmonkeyengine.org/) and creating a new Troubleshooting topic there.

When you do that, please mention which version of jMonkeyEngine you are using. Use `System.out.println(JmeVersion.FULL_NAME);` to find that information.

**Comment by blueming333** [comment]
thanks
already creating topic on https://hub.jmonkeyengine.org/t/android-skybox-bug/44751

**Comment by cjjwzj** [comment]
` Texture west = assetManager.loadTexture("Textures/SkyBox/SYPY_RT.jpg");
        Texture east = assetManager.loadTexture("Textures/SkyBox/SYPY_LF.jpg");
        Texture north = assetManager.loadTexture("Textures/SkyBox/SYPY_FR.jpg");
        Texture south = assetManager.loadTexture("Textures/SkyBox/SYPY_BK.jpg");
        Texture up = assetManager.loadTexture("Textures/SkyBox/SYPY_UP.jpg");
        Texture down = assetManager.loadTexture("Textures/SkyBox/SYPY_DN.jpg");
        Geometry sky = (Geometry) SkyFactory.createSky(assetManager, west, east, north, south, up, down);
        sky.setLocalScale(0.5f);
        sky.getMaterial().getAdditionalRenderState().setDepthFunc(RenderState.TestFunction.LessOrEqual);

        rootNode.attachChild(sky);`


The webpage won't open, let's put some solutions here.

**Comment by stephengold** [comment]
@cjjwzj:
1. Why are you posting to a closed issue?
2. Which webpage won't open?
