### ISSUE TITLE
Missing item in the BinaryExporter documentation

### ISSUE THREAD

**Issue by fabrice-ducos** [jMonkeyEngine/jmonkeyengine#1597]
The [documentation](https://javadoc.jmonkeyengine.org/v3.3.0-beta1/com/jme3/export/binary/BinaryExporter.html) of the format descriptor refers to a 19th item.

However the format descriptor only contains 18 items.

**Comment by stephengold** [comment]
Thanks for informing us of the issue. I see what you mean.

Someone needs to read the code carefully to determine what it actually does.
