### ISSUE TITLE
framework problem loading FBX file

### ISSUE THREAD

**Issue by hujiana** [jMonkeyEngine/jmonkeyengine#1601]
model = assetManager.loadModel("Models/Ashed/redcar.fbx");

     1.使用assetManager 加载fbx的时候会一直阻塞在该代码处。 
     2. fbx可以SDK 工具中转为j3o文件吗，在SDK工具中转换时提示Could not find blender executable!
Failed to create model, running blender caused an error。

**Comment by stephengold** [comment]
An importer for FBX files is included in the "jme-plugins" library. Make sure that library is included in your application.

If you encounter difficulties with the SDK version 3.3, perhaps SDK version 3.2.4 will work better.

For troubleshooting assistance, please joint the JMonkeyEngine Forum (also called the Hub): https://hub.jmonkeyengine.org/
