### ISSUE TITLE
VirtualIndexBuffer generates odd number of indices for LineLoop

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1603]
Difficulties with mesh synthesis led to the discovery that, for a LineLoop mesh, the `VirtualIndexBuffer` always calculates an odd number of indices for a `Mesh` with mode=`LineLoop`.

In current "master" branch:
```java
            case LineLoop:
                numIndices = (numVerts - 1) * 2 + 1;
                return;
```

For line meshes, the number of indices should always be even, never odd. To correct this, I suggest:
```java
            case LineLoop:
                numIndices = numVerts * 2;
                return;
```

However, this change would need to be carefully tested.

**Comment by pspeed42** [comment]
LineLoop is like LineStrip except that the last two points are connected.  Each vertex otherwise connects to the previous one.  

https://www.khronos.org/opengl/wiki/Primitive

So for four points you will have four lines.  

I don't know what VirtualIndexBuffer is actually used for but to me for a LineLoop the number of indexes would generally be the same as the number of vertexes.  To me neither math seems correct which is why I think I don't know what this class is for.

**Comment by stephengold** [comment]
`VirtualIndexBuffer` simplifies the processing of meshes by allowing developers to treat a `TriangleFan`- or `TriangleStrip`-mode mesh as a plain old `Triangles`-mode mesh and a `LineLoop`-mode or `LineStrip`-mode mesh as a plain old `Lines`-mode mesh.  It does this by generating extra indices that aren't in the actual `IndexBuffer`.

A `LineLoop`-mode mesh with 10 indices is going to have 10 lines, but when accessed via a `VirtualIndexBuffer` it looks like a `Lines`-mode mesh. Still 10 lines, but now it needs 20 indices.

**Comment by stephengold** [comment]
As I suspected, there's also a bug in the generated indices (for `LineLoop`-mode meshes).

Another reason this issue lay undiscovered for so long is that the Engine only uses `VirtualIndexBuffer` in one place: `BIHTree`. For obvious reasons, `BIHTree` is only sees meshes composed of triangles, never ones composed of lines!

The ironic thing is that someone contributed a thorough set of JUnit tests for `VirtualIndexBuffer`. However those tests are themselves incorrect for `LineLoop` mode! Resolution of this issue will include expanded JUnit tests (to increase coverage) and corrections to existing tests (to match the intended semantics of `LineLoop` mode).
