### ISSUE TITLE
Is LwjglDisplay.java safe to delete?

### ISSUE THREAD

**Issue by quazi-irfan** [jMonkeyEngine/jmonkeyengine#1609]
`class LwjglDisplay` in `com.jme3.system.lwjgl` is not used anywhere. Is it ok to send a pull request with this file removed?

Here is the content of `LwjglDisplay.java`,
```
package com.jme3.system.lwjgl;

/**
 * @author Daniel Johansson
 */
public class LwjglDisplay extends LwjglWindow {

    public LwjglDisplay() {
        super(Type.Display);
    }
}

```

**Comment by stephengold** [comment]
Good question.

**Comment by stephengold** [comment]
It don't know exactly what the class does, but it's accessed via reflection from "JmeDesktopSystem.java", so I don't think we can simply delete it.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/7c5fe46cf92653b47184e442e9896c5587e116e4/jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java#L202

**Comment by quazi-irfan** [comment]
Thanks for looking into it.
