### ISSUE TITLE
Add support for BC7 texture compression

### ISSUE THREAD

**Issue by Pesegato** [jMonkeyEngine/jmonkeyengine#1619]
BC7 hardware compression is part of DirectX11

On the zip file there is a PNG and its BC7 equivalent.

[16.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/7337119/16.zip)

**Comment by stephengold** [comment]
I'm still unclear on the motivation. If you have the texture as a PNG, why not use that?

**Comment by stephengold** [comment]
Who wants to review the PR?
