### ISSUE TITLE
Add support for texture flipping of BC4 and BC5 signed formats

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#1623]
Add support for texture flipping of BC4 and BC5 signed formats. This is maybe just a trivial task of setting the block size right.

You can use DDS as the texture container and the code handling the flipping is in https://github.com/jMonkeyEngine/jmonkeyengine/blob/ceb356462aeedf7769dced52e1d5572b01deca31/jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java

**Comment by stephengold** [comment]
Thanks for filing the issue.
