### ISSUE TITLE
Un-deprecate AndroidBufferImageLoader

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1634]
Hi

`AndroidBufferImageLoader` which internally uses the Android Bitmap class to load images, supports loading a variety of texture formats (such as WebP images) that are not supported by the `AndroidNativeImageLoader`.

I am not sure why it is deprecated, should we un-deprecate it for v3.5?

**Comment by stephengold** [comment]
It was deprecated by @shadowislord back in 2015 with the following commit message: "Android Images: deprecate classes that won't be used in 3.1" Perhaps Kirill remembers what was going to prevent it from being used...

Here's the full commit, in case that helps:  bbbcd8eba

**Comment by stephengold** [comment]
Unsurprisingly, no response from Kirill. Very few monkeys keep an eye on GitHub these days.
@Ali-RS Perhaps you should also raise this question at the Forum/Hub.
@normen do remember anything about why `AndroidBufferImageLoader` was deprecated in 2015?

**Comment by Ali-RS** [comment]
A forum topic is created: https://hub.jmonkeyengine.org/t/any-clue-why-androidbufferimageloader-is-deprecated/45075

**Comment by normen** [comment]
I think it was because the native version was so much faster but I'm not sure.

**Comment by stephengold** [comment]
Whether or not we un-deprecate `AndroidBufferImageLoader`, we should probably document which formats each loader supports and also the performance differential, if known.

**Comment by Scrappers-glitch** [comment]
Well, that was the reason why : 

https://github.com/jMonkeyEngine/jmonkeyengine/blob/2542ceb565ce6e4cf561cf6c61b4d2028d8f52b8/jme3-android/src/main/java/com/jme3/texture/plugins/AndroidNativeImageLoader.java#L12

And if we want to un-deprecate this class, we may need to use `bitmap.setPremultiplied(false)` in order to prevent the alpha channels premultiplications before loading, but that may result in a runtime exception, we need to test this : 

https://developer.android.com/reference/android/graphics/Bitmap#setPremultiplied(boolean)

**Comment by stephengold** [comment]
@Ali-RS do you concur?

**Comment by Ali-RS** [comment]
>@Ali-RS do you concur?

Yes

Here is the list of supported formats: (most notably WebP and HEIF)

https://developer.android.com/guide/topics/media/media-formats#image-formats

Regarding performance, it is recommended to reuse the same bitmap for loading multiple textures instead of recycling and creating a new one. It is possible to use `inBitmap` field.

https://developer.android.com/reference/android/graphics/BitmapFactory.Options#inBitmap

More info:

https://www.youtube.com/watch?v=_ioFW3cyRV0

https://www.geeksforgeeks.org/how-to-use-bitmap-pools-in-android/

https://developer.android.com/topic/performance/graphics/manage-memory

However there is ristrictions to it:

> Manage Memory on Android 3.0 and Higher
Android 3.0 (API level 11) introduces the BitmapFactory.Options.inBitmap field. If this option is set, decode methods that take the Options object will attempt to reuse an existing bitmap when loading content. This means that the bitmap's memory is reused, resulting in improved performance, and removing both memory allocation and de-allocation. However, there are certain restrictions with how inBitmap can be used. In particular, before Android 4.4 (API level 19), only equal sized bitmaps are supported. For details, please see the inBitmap documentation. 

So min API level must be 19 to be able to reuse Bitmap to load images with different size. Also Bitmap size must be greater or equal to image size to be able to load it, so it needs to be initialized with a max size.

I think for now we can skip the optimization step until we have encountred with the performance issue :)

Regarding `bitmap.setPremultiplied(false)` I will try it soon.

**Comment by Ali-RS** [comment]
Tried with `options.inPremultiplied = false;`. 
Visually I see no difference though.

Premultiplied: false
![premultiply-false](https://user-images.githubusercontent.com/5787647/141078578-6899f82a-6d7a-48bc-9e38-73d3b1d01f40.png)

Premultiplied: true
![premultiplied-true](https://user-images.githubusercontent.com/5787647/141078621-cc457052-a9b0-4090-845c-4178bfc9dae2.png)

**Comment by Ali-RS** [comment]
If you agree I can submit a PR wihich
 - set `options.inPremultiplied = false;` (requires [API Level 19](https://developer.android.com/reference/android/graphics/BitmapFactory.Options#inPremultiplied) )
 - update AndroidBufferImageLoader doc with supported format and add a TODO for posible future optimization with Bitmap reuse
 - un-deprecate AndroidBufferImageLoader

**Comment by stephengold** [comment]
I have no objection to the proposed PR. However, I'm ignorant about Android, so I'll rely on you and Scrappers-glitch to decide the best course.

**Comment by Scrappers-glitch** [comment]
> Tried with `options.inPremultiplied = false;`. Visually I see no difference though.
> 
> Premultiplied: false ![premultiply-false](https://user-images.githubusercontent.com/5787647/141078578-6899f82a-6d7a-48bc-9e38-73d3b1d01f40.png)
> 
> Premultiplied: true (default) ![premultiplied-true](https://user-images.githubusercontent.com/5787647/141078621-cc457052-a9b0-4090-845c-4178bfc9dae2.png)

Have you noticed any speed downside ?

**Comment by Ali-RS** [comment]
No. But to be specific I need to use a nano timer to measure the load time.

**Comment by Scrappers-glitch** [comment]
> Do you mean image load time? No, I did not notice. But for a precise answer, I need to use a nano timer to measure the load time.

Alright, you can do a PR to add the changes and undeprecate this class, I will help in testing and reviewing if needed.

One more question, are you going to need to add another code to help the system determine which loader to use ? Based on the file extensions ?

**Comment by Ali-RS** [comment]
>One more question, are you going to need to add another code to help the system determine which loader to use ? Based on the file extensions ?

>EDIT : alright i have looked at the code, you would likely hook a LOADER line into Android.cfg to be included in the General.cfg.

I register the loader inside simpleInitApp `assetManager.registerLoader(AndroidBufferImageLoader.class, "webp");`

In the PR should I add a config for webp inside Android.cfg or better to let users register it via AssetManager themselve if they need it?

**Comment by Scrappers-glitch** [comment]
> > One more question, are you going to need to add another code to help the system determine which loader to use ? Based on the file extensions ?
> 
> > EDIT : alright i have looked at the code, you would likely hook a LOADER line into Android.cfg to be included in the General.cfg.
> 
> I register the loader inside simpleInitApp `assetManager.registerLoader(AndroidBufferImageLoader.class, "webp");`
> 
> Should I add a config for WebP inside `Android.cfg` in the PR or better to let users register it via AssetManager themselves if they need it?

I am not sure currently, let me search for this and reply back.

**Comment by Ali-RS** [comment]
Submitted PR #1660

**Comment by stephengold** [comment]
I don't see much harm in registering a loader that's rarely used.

**Comment by Ali-RS** [comment]
@stephengold thanks for your comment. Added an entry for WebP & HEIF images in Android.cfg.

**Comment by Ali-RS** [comment]
>Tried with options.inPremultiplied = false;.
Visually I see no difference though.

Heh, I guess this is because the alpha value in my texture is either 1 or 0 so visually it will have no effect. I think difference would apprear if texture is semitranslucent (alpha is any thing between [0, 1])
