### ISSUE TITLE
Wrong iOS packages docs

### ISSUE THREAD

**Issue by Scrappers-glitch** [jMonkeyEngine/jmonkeyengine#1648]
Both classes `IosTouchHandler`, `TouchEventPool` have wrong class documentations, they should describe how they really deal with iOS native under the hood, and repetitive `android` keywords should be replaced by `iOS`.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/f0dd68b746ecd57ca315de2a564d082ac26fd8e4/jme3-ios/src/main/java/com/jme3/input/ios/IosTouchHandler.java#L48

https://github.com/jMonkeyEngine/jmonkeyengine/blob/f0dd68b746ecd57ca315de2a564d082ac26fd8e4/jme3-ios/src/main/java/com/jme3/input/ios/TouchEventPool.java#L39

**Comment by stephengold** [comment]
Good catch!

**Comment by Scrappers-glitch** [comment]
I think we may need to add an iOS label.
