### ISSUE TITLE
Serializer has an unused line

### ISSUE THREAD

**Issue by wlfbck** [jMonkeyEngine/jmonkeyengine#166]
The variable created in line 205
`SerializerRegistration reg = new SerializerRegistration(serializer, cls, classId);`
 of com.jme3.network.serializing.Serializer is never used and the instantiation itself also doesn't do anything.

As a sidenote, the whole Serializer is a bit intransparent because of the chained `return otherMethod(args);` and i think in turn there is some more stuff that is never used.

**Comment by empirephoenix** [comment]
Seems to be fixed in master by now
