### ISSUE TITLE
JME 3.5.0-alpha1 incompatible with Java 7

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1661]
The distributed file "jme3-core-3.5.0-alpha1.module" at MavenCentral contains the following:
```json
"attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
```

Since it specifies JVM version 8, newer build tools won't allow it to be used in projects that specify compatibility with Java 7.

This issue arose from 2 changes to "common.gradle":
+ Jdk 11 compatibility (ad2ba95e993d3ad16f95c189e25c1b2c54763826) which bumped `sourceCompatibility` from '1.7' to '1.8' and
+ Gradle 6.9 (PR #1588) which caused Gradle to publish a .module file to MavenCentral

Returning to 1.7 compatibility will require some changes to our source code, to avoid using Java 8 features such as lambdas.

**Comment by Ali-RS** [comment]
Why should we return to java 1.7 compatibility?

Note even LWJGL 3 requires Java 8 or later to build and run.

**Comment by stephengold** [comment]
The .module file breaks existing Gradle projects that worked with JME 3.4.0, such as Heart.

**Comment by Ali-RS** [comment]
Can we prevent .module file from getting published to maven?

**Comment by tlf30** [comment]
I would say that it is time to drop support for java 7. At this point I would say it is also time to start looking at dropping 8 and moving to 11 as the main lts supported version since 17 is the main lts now. Most projects are only supporting the moat recent two LTS versions. If we continue to support java 7 we will never be able to use the new features in java.

**Comment by stephengold** [comment]
Both ideas (moving to 8 and moving to 11) are worth considering.

I remember hearing we needed Java 7 compatibility to run on Android devices, but that was many years ago. Back in May of 2020, Adi Barda still had a requirement for Java 8 compatibility, but maybe that's passed now.

I don't feel comfortable dropping support for 7 without first raising the idea at the Hub/Forum.

**Comment by stephengold** [comment]
I see you took care of that for me. Thanks!

https://hub.jmonkeyengine.org/t/jme3-minimum-java-version/45111

**Comment by Ali-RS** [comment]
>I remember hearing we needed Java 7 compatibility to run on Android devices

Not anymore. We can use new language features (excluding sealed class) up to Java 17 (including lambda, records, text block, instanceof pattern matching, switch expressions) on old Android versions as well (Android 4.4+) using Android desugaring. I have already tried it.

Note that my above statement is only regarding Java Language features.

New Java API features such as Java 11 HttpClient and Java 17 Foreign Function & Memory API is not supported by Android yet.
