### ISSUE TITLE
Logging statement should be guarded

### ISSUE THREAD

**Issue by vxel** [jMonkeyEngine/jmonkeyengine#1672]
In the Node class, two logging statements are not guarded and show a performance impact due to the `this.toString()`.

Line 434 :
`logger.log(Level.FINE, "{0}: Child removed.", this.toString());`

Line 464 : 
`logger.log(Level.FINE, "{0}: All children removed.", this.toString());`

Those statements should be guarded with : 
`if (logger.isLoggable(Level.FINE)) { ... }`

As shown in the profile summary below, this logging is responsible for almost 100% of the CPU used by the method :
![image](https://user-images.githubusercontent.com/28866693/143059036-0845698f-6f02-4f0e-b63f-36d91000d1d9.png)

**Comment by pspeed42** [comment]
:facepalm: The code goes through the trouble of calling the format version but then calls toString() anyway.

Because:
```
logger.log(Level.FINE, "{0}: Child removed.", this);
```
...would have been fine, too.

**Comment by tonihele** [comment]
Oh dear :D Good catch @vxel, planning to make a PR for this? I think it still can make 3.5 release, although that is not for me to decide.

**Comment by vxel** [comment]
Yeah I can prepare a PR for this. The fix is trivial ;-)
