### ISSUE TITLE
Expand Quad to support changing the orientation 

### ISSUE THREAD

**Issue by bob0bob** [jMonkeyEngine/jmonkeyengine#1700]
This would be nice to new people special that don’t have lower level idea, being able to change orientation for its placement.

Right now Quads are center at lower left corner. Enhancement would be able to change this, lowerLeft, LowerCenter, LowerRight, Center, UpperLeft, UpperCenter, UpperRight.

**Comment by pspeed42** [comment]
One of the super nice things about the existing Quad class is that it is the simplest example of creating a mesh.  I often refer to it and refer folks to it for learning basic mesh creation because it is simple and straight-forward.  Also super nice for cutting-pasting from.

To whomever implements this change, please keep this in mind... and consider making a new class if things get too complicated.

After all, this proposed change is only saving the user from having to make their own:
```
   mesh.setBuffer(Type.Position, 3, new float[]{0,      0,      0,
                                                width,  0,      0,
                                                width,  height, 0,
                                                0,      height, 0
                                                });
```
call on the mesh with slightly different values.

**Comment by bob0bob** [comment]
@pspeed42   Is that not the whole point of an engine.  Most people go to engine so they don't have to write the basic code to develop a game.  Work on making the game,  so having feature (even if not used often) allows more people to be successful with JME.

Quad changing orientation, can allow for "EASY" rotation.    Try rotating a QUAD in JME,  IT IS A "PAIN" and caps doesn't do the HELL justice for what you have to do to get JME Engine to rotate a quad on center.   Who wants to rotate from lower left corner.

Not all 3D games are entirely based on 3d Models.   I know JME aim is 3d Game Engine, but the idea of having a billboard class make it sure that Quads are often used.

Things that make it easier for new people to start running with JME is better.
I have my own engine and tried out JME in hopes to stop writting LOWER level code and focus on my Game, but I quickly found out JME is not that.  It is most there, but it limits many OpenGL functions or doesn't have some standard engine functions.   There are still many things a newbie has to write on their own.

Having to change the location is very simple and can be done with just a couple of line of code to make those changes.

**Comment by stephengold** [comment]
@bob0bob, if the goal is to provide a centered rectangle, it would be simpler to move `CenterQuad` from jme3-vr to jme3-core.

Also, please consider whether #1701 might meet the same needs as this PR.

**Comment by bob0bob** [comment]
Just going to close this issue.   To much agrueing over the feature.  It is not about just centering, it is about adjusting the orientation to different areas.  But everyone is stuck on centering or not understanding.

Thanks for you time,  I'm just going to alter the JME3.4 and having my own with features that are missing from the engine,  just like scissors is a basic OpenGL feature but everyone just wanted to argue over this idea instead of looking for solution.  It was just about how "I don't see why" to "use a shader" (more complicated than required).   It is a simple addition to JME, but no one wants to see it.

There seems to be real huge issues with the communicate of JME and "WHAT ITS FUTURE IS".   More people complain then come up with solutions.   

I experience through the forum also,  about 50% of the time, I get help and the other 50% is about arguing about concepts.

**Comment by stephengold** [comment]
I'm sorry you had unpleasant experiences.

**Comment by bob0bob** [comment]
Me too.
