### ISSUE TITLE
NullPointerException with JoyStick and no buttons

### ISSUE THREAD

**Issue by heliflieger** [jMonkeyEngine/jmonkeyengine#1739]
A GameController without buttons generates a NullPointerException in GlfwJoystickInput.java:112

java.lang.NullPointerException
	at com.jme3.input.lwjgl.GlfwJoystickInput.loadJoysticks(GlfwJoystickInput.java:112)

The reason is, that there are no buttons for this device available.

![image](https://user-images.githubusercontent.com/11368027/148990448-0153f358-9a13-4af8-8e0d-d7b880d5dec6.png)

**Comment by stephengold** [comment]
Solved in "master" branch at 72a21b1 and in "v3.5" branch at efe5ba67.
