### ISSUE TITLE
PhysicsRigidBody setDamping methods (jME3-bullet.jar)

### ISSUE THREAD

**Issue by luis-moral** [jMonkeyEngine/jmonkeyengine#175]
If you call setLinearDamping() and then setAngularDamping() the linear damping is not applied.

Looking at the sources they are calling different native methods:

public void setLinearDamping(float linearDamping) {
        setDamping(objectId, linearDamping, getAngularDamping());
    }

public void setAngularDamping(float angularDamping) {
        setAngularDamping(objectId, angularDamping);
    }

Calling setAngularDamping() and after setLinearDamping() or just setDamping() works ok.

**Comment by stephengold** [comment]
I'm having difficulty reproducing the issue in current `master` branch. The following test code succeeds with `jme3-bullet`:
```
    public void simpleInitApp() {
        CollisionShape capsule = new SphereCollisionShape(1f);
        PhysicsRigidBody body = new PhysicsRigidBody(capsule, 1f);
        body.setLinearDamping(0.03f);
        body.setAngularDamping(0.04f);
        assert body.getLinearDamping() == 0.03f;
        assert body.getAngularDamping() == 0.04f;
        stop();
    }
```

The issue may have been fixed in Bullet end.

Anyway, I'm closing the issue.
