### ISSUE TITLE
Framebuffer is not sized correctly when COCOA_RETINA_FRAMEBUFFER=false

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#1751]
The result is cropped like the image below:
![image](https://user-images.githubusercontent.com/4943530/149824829-5f6bbad4-ad89-4b07-9057-207de772571b.png)

I tried to debug this behavior, and it seems that the default framebuffer is created of the same size as if COCOA_RETINA_FRAMEBUFFER was enabled, but it is not fitted to the window...this seems like a glfw bug.

I think we should revert a1ae3fd47a8a7911a69eb96810e4c06645826a55 for now

**Comment by stephengold** [comment]
> I think we should revert a1ae3fd for now

I believe that would break applications running on Windows systems that support scaling. See issue #1745 and the Hub/Forum discussion at https://hub.jmonkeyengine.org/t/jme-lwjgl3-issue-with-mouse-coords/45252/3

**Comment by riccardobl** [comment]
This should be made to not break windows apps since it is a mac specific setting (as per glfw docs and also retina are mac's displays). If there is some scaling that is dependent on isUseRetinaFrameBuffer() being true on non Mac system, then it should be changed to depend on something else, eg. the value of glfwGetWindowContentScale(). I'll look into this other issue, because the old code seems fine to me...

**Comment by stephengold** [comment]
I agree that `GLFW_COCOA_RETINA_FRAMEBUFFER` is documented as affecting only macOS systems. However, that setting apparently requires that mouse locations to be scaled using `glfwGetWindowContentScale()`---hence the need for PR #1607.

On Windows systems with display scaling, `glfwGetWindowContentScale()` returns values other than 1. If mouse locations are scaled on Windows systems, they will be incorrect---see issue #1745.

> If there is some scaling that is dependent on isUseRetinaFrameBuffer() being true on non Mac system, then it should be changed to depend on something else, eg. the value of glfwGetWindowContentScale().

`AppSettings.isUseRetinaFrameBuffer()` should only be enabled on Mac systems.

**Comment by riccardobl** [comment]
Possible fix: https://github.com/jMonkeyEngine/jmonkeyengine/issues/1745#issuecomment-1014930250
