### ISSUE TITLE
SphereCollisionShape setScale() warning (jME3-bullet.jar)

### ISSUE THREAD

**Issue by luis-moral** [jMonkeyEngine/jmonkeyengine#176]
The constructor calls createShape() and this one calls setScale() which shows an annoying warning each time a SphereCollisionShape is instanced.

I would suggest to remove the call to setScale() in the createShape() method.

**Comment by stephengold** [comment]
I believe this issue was resolved in 'master' branch by the following commit:

https://github.com/jMonkeyEngine/jmonkeyengine/commit/e776967c2361ccc3c35c64f61c4130df8bab6588
