### ISSUE TITLE
X Error of failed request: BadWindow (invalid Window parameter) with LWJGL3

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1778]
### Platform

Linux Mint x64  with Mesa (v20) graphics driver

### JDK

AdoptOpenJDK 16

### Bug description

When I open a swing window (e.g. JME error dialog) along with the GLFW window, the moment I close the swing window it crashes the app with the below error. I am using LWJGL 3.

### Stacktrace or crash log output

```shell
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x4e0005b
  Serial number of failed request:  1332
  Current serial number in output stream:  1332
```

**Comment by stephengold** [comment]
Is this a regression, or did JME 3.4.1-stable have the same issue?

**Comment by Ali-RS** [comment]
Nope, I believe not a regression. I can reproduce it with older versions too.

**Comment by SylvainBertrand** [comment]
Hi! I'm also struggling with the transition to LWJGL3 for an application of our own that uses JME and AWT/Swing.
I've been trying to figure out various code examples that cause an application to crash when running on Linux (testing on Ubuntu 20.04).
Here's one example that seems similar to what you're experiencing @Ali-RS :
```
package example;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

import org.lwjgl.glfw.GLFW;

public class CodeSnippet
{
   public static void main(String[] args)
   {
      new JFrame();

      GLFW.glfwInit();

      new JFileChooser().showOpenDialog(null);
   }
}
```
When closing the dialog to open a file, the whole app terminates immediately with the following error message:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x4a00020
  Serial number of failed request:  1515
  Current serial number in output stream:  1515
```
In this example, it seems enough to move the GLFW initialization to be the first thing to run to prevent the error from popping.

I'm still digging for solutions, as migrating away from Swing/AWT or JME is not viable solution for me.

**Comment by Ali-RS** [comment]
>In this example, it seems enough to move the GLFW initialization to be the first thing to run to prevent the error from popping.

@SylvainBertrand thanks for the hint!

If I disable the JME Settings dialog (so GLFW will be initialized first) then opening/closing a Swing window seems to be working fine.

**Comment by Ali-RS** [comment]
The error does not occur with the latest snapshot build of LWJGL3.

**Comment by Ali-RS** [comment]
Fixed by https://github.com/jMonkeyEngine/jmonkeyengine/commit/76ebd1443ccc18249e9f082d528cd39baf59da84
