### ISSUE TITLE
Crash of example application runner using Linux

### ISSUE THREAD

**Issue by mbcraft** [jMonkeyEngine/jmonkeyengine#1789]
uname -a

Linux frey 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

java -version

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

java -jar jMonkeyEngine3.jar

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jme3.util.ReflectionAllocator (file:/home/marco/Scaricati/jMonkeyEngine/lib/jme3-core.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jme3.util.ReflectionAllocator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
mar 27, 2022 1:44:13 PM com.jme3.system.JmeDesktopSystem initialize
INFORMAZIONI: Running on jMonkeyEngine 3.5.1-stable
 * Branch: HEAD
 * Git Hash: 28bf1c9
 * Build Date: 2022-03-20
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

------------------------ it seems that trying to run any example make the application crash.

**Comment by Ali-RS** [comment]
Hi

If you are using the lwjgl2 backend (jme3-lwjgl), please try to switch to lwjgl3 ((jme3-lwjgl3) and see if it works.

**Comment by stephengold** [comment]
Support questions like this are better addressed at the Hub (JMonkeyEngine's Discourse forum):  https://hub.jmonkeyengine.org/

The "Inconsistency detected" error indicates that OpenJDK was compiled with a version of the C runtime library that's incompatible with one of the native libraries in your application. jme3-lwjgl is a likely candidate, but there are several other possibilities. It's more of an issue with OpenJDK than with JMonkeyEngine.

On my own Linux system, I worked around this issue by installing [Temurin](https://adoptium.net/) and setting the JAVA_HOME environment variable in my .bashrc to point to the install directory `export JAVA_HOME=/usr/lib/jvm/Temurin/jdk-11.0.14.1+1`

**Comment by mbcraft** [comment]
Thanks for the replies. My linux configuration is quite old and maybe it's a problem of my hardware. I tryed on a new laptop in windows and it worked, even if some examples have missing assets and won't start, but the majority of it is working. Thanks for the suggestions.

**Comment by Scrappers-glitch** [comment]
> Support questions like this are better addressed at the Hub (JMonkeyEngine's Discourse forum): https://hub.jmonkeyengine.org/
> 
> The "Inconsistency detected" error indicates that OpenJDK was compiled with a version of the C runtime library that's incompatible with one of the native libraries in your application. jme3-lwjgl is a likely candidate, but there are several other possibilities. It's more of an issue with OpenJDK than with JMonkeyEngine.
> 
> On my own Linux system, I worked around this issue by installing [Temurin](https://adoptium.net/) and setting the JAVA_HOME environment variable in my .bashrc to point to the install directory `export JAVA_HOME=/usr/lib/jvm/Temurin/jdk-11.0.14.1+1`

I also have this issue when using openJDK-11, worked it by using oracle jdk-1.8.

**Comment by Scrappers-glitch** [comment]
> Thanks for the replies. My linux configuration is quite old and maybe it's a problem of my hardware. I tryed on a new laptop in windows and it worked, even if some examples have missing assets and won't start, but the majority of it is working. Thanks for the suggestions.

Download jdk from oracle website, extract, then to run, locate its java executable file : 
```
/home/Downloads/jdk-1.8.0/bin/java -jar MyGame.jar
```
and it will work !
