### ISSUE TITLE
Wrong callback to `JmeSurfaceView#destroy()`

### ISSUE THREAD

**Issue by Scrappers-glitch** [jMonkeyEngine/jmonkeyengine#1799]
As i recall, `app.destroy()` is called back by the system listener which is governed by application listeners, in this case there is a duplicate call to `destroy()` : 
1) https://github.com/jMonkeyEngine/jmonkeyengine/blob/3d979df4bc9f3044b414e13d442880c5054e6aca/jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java#L363

2) https://github.com/jMonkeyEngine/jmonkeyengine/blob/3d979df4bc9f3044b414e13d442880c5054e6aca/jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java#L507

There should only be `app.stop()` which will naturally dispatch the context.destroy().

The proposed fix should move the `legacyApplication.stop(!isGLThreadPaused());` to the `ON_DESTROY` instead of the direct call to destroy() and should call `legacyApplication.destroy()` inside the `destroy()`.

**Comment by stephengold** [comment]
@Scrappers-glitch Will you provide us with a PR?

**Comment by Scrappers-glitch** [comment]
Yeah sure, i will do a PR at the end of this week.

**Comment by Scrappers-glitch** [comment]
Hello, 
i am testing now on android.
The problem that i have described on the community hub is due to explicitly setting glSurfaceView to null when destroying the app...and unfortunately `setRequestOrientation(...)` invokes onDestroy() prematurely, so when trying to add it to the screen, the  result is `IllegealStateException : Cannot add a null object`, the final fix is removal of explicit nulling..
