### ISSUE TITLE
JmeSurfaceView: Follow package naming conventions

### ISSUE THREAD

**Issue by Scrappers-glitch** [jMonkeyEngine/jmonkeyengine#1803]
I have looked up the android core packages, i found the major package `android.view` where android views live and `android.app` where android application components live, but special featured android views are located within special packages like `android.webkit.WebView` and `android.opengl.GlSurfaceView`, so i think the best packaging option out there for JmeSurfaceView is `com.jme3.view.surfaceview.JmeSurfaceView` and i will create a package-info for it, if you are okay with these changes or have an objection let me know.

`com.jme3.view ` can hold other android views as features for jme.

Due to issue #1800 , i accustomed to put `JmeSurfaceView` directly inside `com.jme3.app` which is wrong !
`com.jme3.app` is the package for jMonkeyEngine application components including app launchers and vital states.

**Comment by Scrappers-glitch** [comment]
This is more like a `Documentation` issue from my opinion.

**Comment by stephengold** [comment]
> This is more like a Documentation issue from my opinion.

I disagree because it's a breaking change.

**Comment by Scrappers-glitch** [comment]
> so i think the best packaging option out there for JmeSurfaceView is `com.jme3.view.surfaceview.JmeSurfaceView` and i will create a package-info for it, if you are okay with these changes or have an objection let me know.

I will try to take a response from the community.

**Comment by Scrappers-glitch** [comment]
Here we go : 
https://hub.jmonkeyengine.org/t/relocate-jmesurfaceview-to-com-jme3-view-surfaceview-package/45510

**Comment by Scrappers-glitch** [comment]
I need to know what is next to get this merged, please let me know.

**Comment by Scrappers-glitch** [comment]
This issue was to be linked to PR #1819, i will close it as completed.
