### ISSUE TITLE
Typo in method name 'TrackData.checkTimesConsistantcy'

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/jmonkeyengine#1816]
Should be 'Consistency'.

I haven't had a chance to verify the source code, but if it's only used in the `TrackData` class, the method visibility could change to `private`

https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/TrackData.java#L173

**Comment by stephengold** [comment]
It's not used anywhere else in the Engine. However, it's the sort of utility method that an application might want to use, so we should probably create a new method and deprecate the old one.

I'll take care of it.
