### ISSUE TITLE
In the process of loading OBJ model encounters an error.

### ISSUE THREAD

**Issue by EmptyDreams** [jMonkeyEngine/jmonkeyengine#1835]
When I try to load an OBJ model, the console outputs the following statement:

```bash
7月 14, 2022 2:50:47 下午 com.jme3.scene.plugins.OBJLoader readLine
警告: Unknown statement in OBJ! o
```

At the same time, the material of the model is displayed incorrectly. The normal effect and program effect are shown below (the left is normal) :

![效果图](https://user-images.githubusercontent.com/44894906/178920866-0906b68a-0045-4d54-b5e9-b1f92da1cd2f.jpg)

My code:

```kotlin
import com.jme3.app.SimpleApplication
import com.jme3.light.DirectionalLight
import com.jme3.material.Material
import com.jme3.math.Vector3f

fun main() {
    val task = Main()
    task.start()
}

class Main : SimpleApplication() {

    private val teapot by lazy { assetManager.loadModel("Models/a.obj") }

    override fun simpleInitApp() {
        val matDefault = Material(assetManager, "Common/MatDefs/Misc/ShowNormals.j3md")
        teapot.setMaterial(matDefault)
        rootNode.attachChild(teapot)

        val sun = DirectionalLight()
        sun.direction = Vector3f(-0.1f, -0.7f, -1.0f)
        rootNode.addLight(sun)
    }

}
```

**Comment by pspeed42** [comment]
You will get better results asking trouble-shooting questions on the forum.  https://hub.jmonkeyengine.org/

Regarding the material, you set the material to the "show normals" debug material and that's what your view is showing.  The computer is doing what you told it to do.
