### ISSUE TITLE
Allow access to VehicleWheel Rotation and Location

### ISSUE THREAD

**Issue by empirephoenix** [jMonkeyEngine/jmonkeyengine#185]
Inside the VehicleWheel class from bullet, there is a worldRotation and a worldLocation field.

These are used to apply the transformation to the Spatial of the wheel.
When using the Physicengine directly, eg via a ES, there however is no need for a spatial. It would be nice to add the following two getters to VehicleWheel

	public void getWheelWorldRotation(final Quaternion store) {
		store.set(this.wheelWorldRotation);
	}

	public void getWheelWorldLocation(final Vector3f store) {
		store.set(this.wheelWorldLocation);
	}

These are as save as possible, since they cannot modify the values of the Wheel, and would allow the useage of the phyicsvehicle outside of a pure jme scenegraph context.

**Comment by shadowislord** [comment]
Fixed in 409f5ab766162d98821287b0dbe6c5b3aa5c554c
