### ISSUE TITLE
Interested in a Blender like cam control?

### ISSUE THREAD

**Issue by RaiNova** [jMonkeyEngine/jmonkeyengine#1854]
I've written a cam control 

![image](https://user-images.githubusercontent.com/2886662/193451700-216f5932-0ff7-4f40-83f7-81edb542fa45.png)

in Kotlin, without unit tests, and not integrated into the JMonkey class hierarchy.

Is anybody interested in integrating it into the JMonkey library? Then I would provide the Kotlin class.

**Comment by Ali-RS** [comment]
Hi @RaiNova, Nice work.

We recommend extensions be published on the JME store (https://store.jmonkeyengine.org/) + a forum post about the extension on the JME forum (https://hub.jmonkeyengine.org/). You can then host the source code (Java or Kotlin) on your GitHub page.

Thanks
