### ISSUE TITLE
Link not working in `Controlling Game Logic > Application States`

### ISSUE THREAD

**Issue by Ledmington** [jMonkeyEngine/jmonkeyengine#1856]
In [this section](https://wiki.jmonkeyengine.org/docs/3.4/core/app/state/application_states.html#code-samples) the link to `BulletAppState` does not work.
It pointed to the package `jme3-bullet` which I think now is called `jme3-jbullet`, so the new link should be [this](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-jbullet/src/main/java/com/jme3/bullet/BulletAppState.java).

**Comment by stephengold** [comment]
Thanks for getting in touch with us about the dead link.

Please note that the dead link is part of the JMonkeyEngine Wiki, which has its own issue tracker: https://github.com/jMonkeyEngine/wiki/issues

JMonkeyEngine v3.3 included 2 physics engines: "jme-bullet" and "jme3-jbullet". The latter was removed from v3.4, but the Wiki page you cited was never updated to reflect the change.

**Comment by Ledmington** [comment]
I'm sorry, I never noticed the wiki repository, I'm closing this issue and recreating it on that repository.
