### ISSUE TITLE
Broken "License" link in README file

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/jmonkeyengine#1857]
Broken "License" link in README file
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/LICENSE

It should be:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/LICENSE.md

**Comment by stephengold** [comment]
This is a direct result of PR #1855.

**Comment by kaaquist** [comment]
Can I fix this here as part of the hacktoberfest?
