### ISSUE TITLE
jme3-lwjgl3 Produces Gaps Between Boxes When Using Lighting Material

### ISSUE THREAD

**Issue by tilltheis** [jMonkeyEngine/jmonkeyengine#1859]
Hi,

On the latest stable JME3 release, using LWJGL3 (`org.jmonkeyengine:jme3-lwjgl3:3.5.2-stable`), when I place several boxes next to each other, using the `Common/MatDefs/Light/Lighting.j3md` material, there's always a little dark gap between the boxes. It's invisible when the camera is really close to it but becomes bigger the farther it is away. When I use LWJGL2 (`org.jmonkeyengine:jme3-lwjgl:3.5.2-stable`) there is no such problem.

LWJGL3 produces gaps (unexpected behavior):
![lwjgl3](https://user-images.githubusercontent.com/296131/197402540-e56b389d-f8b0-4bda-8691-cafc629cfb22.png)

LWJGL2 does not produce gaps (expected behavior):
![lwjgl2](https://user-images.githubusercontent.com/296131/197402538-787a432e-d383-434a-b604-46933f74c5c6.png)

Here is the test setup to reproduce the issue:
```java
for (int x = 0; x < 10; x++) {
    for (int y = 0; y < 10; y++) {
        Box box = new Box(16, 0.1f, 16);
        Geometry geometry = new Geometry("", box);
        Material material = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
        material.setBoolean("UseMaterialColors", true);
        material.setColor("Diffuse", ColorRGBA.Red);
        geometry.setMaterial(material);
        geometry.setLocalTranslation(32 * x, 0, 32 * y);
        rootNode.attachChild(geometry);
    }
}
rootNode.addLight(
        new DirectionalLight(
                new Vector3f(-0.1f, -1f, -0.1f).normalizeLocal(), new ColorRGBA(2f, 2f, 2f, 1f)));
```

And here is the full example project: https://github.com/tilltheis/Jme3GapTest
It has 1 commit linking against LWJGL2 and another commit linking against LWJGL3.

Hint:
There is no issue if I use a box height of zero. Therefore I assume the problem is related to the shadow calculation.
```java
Box box = new Box(16, 0, 16);
```

Please tell me if you need any more input.

**Comment by stephengold** [comment]
Thank you for reporting this issue and providing a test project. If you're looking for help with troubleshooting, please join the [JMonkeyEngine Forum/Hub](https://hub.jmonkeyengine.org/)

**Comment by riccardobl** [comment]
> Therefore I assume the problem is related to the shadow calculation.
Does your scene have shadows? 

Can you try to enable antialiasing?

**Comment by tilltheis** [comment]
@riccardobl Enabling anti-aliasing doesn't change anything.

**Comment by riccardobl** [comment]
Ok, i've tried your test scene and I can't reproduce this on ubuntu with an rtx 2060s. 
Which os are you running it on? Windows 11? GPU and drivers?
Do you have high dpi/scaling settings in your machine?

And, if you can, please try to set
```
material.setColor("Ambient", ColorRGBA.Red);
```
for each cube and replace the directional light with
```
rootNode.addLight(new AmbientLight(ColorRGBA.White));
```
if after this the "gaps" are still there, we can probably rule out possible lighting issues.

My suspicion is that this has something to do with framebuffer scaling done by the backend or the windows manager that introduces some sort of aliasing, since from our side the lwjgl2 and lwjgl3 implementations are pretty much the same.

**Comment by Ali-RS** [comment]
I also could not reproduce it on my Linux machine.

**Comment by tilltheis** [comment]
@riccardobl 

My hardware and software setup is this:

OS: Windows 10 Pro 64bits (10.0, build 19043)
GPU: Radeon RX Vega, driver: "AMD Software: Adrenalin Edition" 22.5.1
CPU: AMD Ryzen 7 2700X

I haven't configured high DPI scaling of any sort.

---

Setting the ambient material color and only using an ambient light indeed fixes the problem for me:
```java
Material material = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
material.setBoolean("UseMaterialColors", true);
material.setColor("Diffuse", ColorRGBA.Red);
material.setColor("Ambient", ColorRGBA.Red);

rootNode.addLight(new AmbientLight(ColorRGBA.White));
```

Using a very light ambient light color and a directional light of any value also fixes the problem:
```java
Material material = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
material.setBoolean("UseMaterialColors", true);
material.setColor("Diffuse", ColorRGBA.Red);
material.setColor("Ambient", ColorRGBA.Red);

Vector3f lightDirection = new Vector3f(-0.1f, -1f, -0.1f).normalizeLocal();
rootNode.addLight(new AmbientLight(ColorRGBA.fromRGBA255(255, 255, 255, 255)));
rootNode.addLight(new DirectionalLight(lightDirection, ColorRGBA.fromRGBA255(255, 255, 255, 255)));
```

However, when I equally turn down both light values, at some point the gaps appear again, eg like this:
```java
Material material = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
material.setBoolean("UseMaterialColors", true);
material.setColor("Diffuse", ColorRGBA.Red);
material.setColor("Ambient", ColorRGBA.Red);

Vector3f lightDirection = new Vector3f(-0.1f, -1f, -0.1f).normalizeLocal();
rootNode.addLight(new AmbientLight(ColorRGBA.fromRGBA255(150, 150, 150, 255)));
rootNode.addLight(new DirectionalLight(lightDirection, ColorRGBA.fromRGBA255(150, 150, 150, 255)));
```

**Comment by tilltheis** [comment]
It seems to have been a driver issue!

Thank you for asking me for my driver version. When I looked up my installed version (AMD Software: Adrenalin Edition 22.5.1) I saw that an upgrade was available and installed it (AMD Software: Adrenalin Edition 22.10.2). Now the problem is gone for me.

I'm very sorry to have wasted your time on this issue. But maybe other's will find it useful when they run into similar problems. The learning, at least for me, is that AMD products are not the most reliable ones since this isn't the first HW/SW problem I've had with AMD.

**Comment by riccardobl** [comment]
> I'm very sorry to have wasted your time on this issue.

Don't worry, reporting this issue was the right thing to do, and thank you for following up with the solution.
Sometimes these kinds of bugs happen, and they might be related to performance or quality trade-offs enabled in the driver settings rather than the driver itself. 

If it happens again, please don't hesitate to reopen the issue.
