### ISSUE TITLE
Performance: LightFilter gets applied even if not needed

### ISSUE THREAD

**Issue by zzuegg** [jMonkeyEngine/jmonkeyengine#1867]
Hi, during my investigation on my deferred performance i found that the LightFilter gets applied on each RenderManager.renderGeometry()

I looked up on how Jme internally works around this issue when no lights are needed and it seems it does not. 

It surely impacts the performance of the AbstractShadowRenderer. At least on objects outside of the view frustum but inside of the shadow frustum the light filtering is not needed. 

A quick fix would be to implement:
``
tmp = RenderManager.getLightFilter();
RenderManager.setLightFilter(null);
//Do your stuff
RenderManager.setLightFilter(tmp);
``

what do you think? applying the easy fix or implement a fix at global scale?

**Comment by Ali-RS** [comment]
Probably you should ask on the forum as there will be a few more eyes to see it there.

But without knowing much about this, from what I understand when the light filter is removed then RenderManager will use all the lights in the `geom.getWorldLightList()` for rendering geometry. Is this what you want in your case? Wouldn't it be bad for performance?

I do not have enough knowledge in this area, but if it should be up to the caller to decide if it needs light filtering or not then what about introducing a new method?

`RenderManager.renderGeometry(Geometry geom, boolean requiresLightFiltering)`

otherwise, your quick fix sounds ok to me.

>implement a fix at global scale?

Do you have a better way in mind?

**Comment by zzuegg** [comment]
> But without knowing much about this, from what I understand when the light filter is removed then RenderManager will use all the lights in the geom.getWorldLightList() for rendering geometry. Is this what you want in your case? Wouldn't it be bad for performance?

The performance penalty comes from doing frustum checks for each light. I will have to dig deeper into the LightMode techniques to see if there is more to gain. 
Not only my case would benefit from this fix. Any rendering technique that renders geometries from the scenegraph with lights attached suffers from this penalty. At very least the shadow renderers suffer from this. 

> but if it should be up to the caller to decide if it needs light filtering or not then what about introducing a new method?

In an optimal solution it would be up to the material.technique to decide if it needs light at all. But the technique gets selected after the lights are filtered so there is no way to get that info without major refactoring.

If this option is out of reach the next best solution would be that the caller gets an option to apply the the filters. a boolean would be nicer, but by setting LightFilter to null we kind of have that option. 

Another, maybe better solution would be to create an NullLightFilter that is settable when not wanting filtration.

**Comment by Ali-RS** [comment]
>Another, maybe better solution would be to create an NullLightFilter that is settable when not wanting filtration.

Would NullLightFilter return an empty LightList, right?

**Comment by zzuegg** [comment]
> Will NullLightFilter return an empty LightList or world LightList?

It will not add any lights to the filteredLightList but return immediately

**Comment by zzuegg** [comment]
Yeah sure. I will make the changes one all agree on the design solutions.

**Comment by Ali-RS** [comment]
>`NullFilter.use(renderManager); NullFilter.revert(renderManager)`

Hmm, it seems backward to me as it is the RenderManager that uses the filter not vice versa.

What about `RenderManager.renderGeometry(Geometry geom, LightFilter filter)` so it will use the specified filter instead of the default one.

**Comment by Ali-RS** [comment]
Yeah, that makes sense.

@pspeed42 may we hear about your opinion as well?

**Comment by pspeed42** [comment]
I don't really understand the problem enough to comment.  I do wonder what NullFilter.revert() is doing, though.

**Comment by Ali-RS** [comment]
>I do wonder what NullFilter.revert() is doing, though.

I guess it removes itself from RenderManager and sets back the default light filter.

**Comment by Ali-RS** [comment]
>It surely impacts the performance of the AbstractShadowRenderer.

By the way, I looked at AbstractShadowRenderer, SpotLightShadowRenderer, PointLightShadowRenderer, and DirectionalLightShadowRenderer but I couldn't find where they are using `RenderManager.renderGeometry` except in the below method which seems to be for debugging use only

https://github.com/jMonkeyEngine/jmonkeyengine/blob/ac8c1012d2ded0812d91a393f935c9f0f7d0c192/jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java#L456-L473

Can you please point out which code you refer to?

**Comment by zzuegg** [comment]
`viewPort.getQueue().renderShadowQueue(shadowMapOccluders, renderManager, shadowCam, true);`

It ultimately uses renderGeometry()

> I don't really understand the problem enough to comment. I do wonder what NullFilter.revert() is doing, though.

The base problem is that every time a geometry gets rendered all lights from Geometry.getWorldLights() are filtered against the camera frustum. Like in the shadow map rendering pass this is unnecessary since no lights are used during actual rendering.

**Comment by zzuegg** [comment]
I tested it locally. NullFilter would work as we expected. 

https://gist.github.com/zzuegg/246f7cb47daf4f8d8c5a3a64a83544f8

This would be the implementation. Without comments up to now but

**Comment by Ali-RS** [comment]
Having NullLightFilter statically bookkeeping old light filter and RenderManager still seems a bit weird to me though,  I would rather not use that static bookkeeping stuff and methods inside the NullLightFilter and instead do something like:

Define null filter as a class field somewhere at the top in the using class
```
private static final LightFilter NULL_FILTER = new NullLightFilter();

```

then use it like this:

```
LightFilter previous = renderManager.getLightFilter();
remderManager.setLightFilter(NULL_FILTER);
// do your stuff
remderManager.setLightFilter(previous);

```

It requires adding just one more line of code.

P.S:
one might say why not use `remderManager.setLightFilter(null);` then, well this way render manager would still pass the geometry world light list to the material but using NullLightFilter it will just pass an empty list.

This is just my opinion anyway. 

Hope to hear other's opinion as well :)

**Comment by pspeed42** [comment]
This is why I was curious what revert() was doing... because I couldn't see how it would work without sharing state with the entire JVM.  ...a big no-no.

**Comment by zzuegg** [comment]
Allright.
I agree on the global static issue but i would still prefer applyTo(RenderManager) and revert(). But it is your call. I implement it the way you like
(Thats why i am a really bad api designer)

**Comment by Ali-RS** [comment]
@zzuegg, any update?

**Comment by zzuegg** [comment]
I have implemented the changes but had not yet time to test them fully for side effects.
