### ISSUE TITLE
Vertex colors not loaded in Gltf models

### ISSUE THREAD

**Issue by Abstrusle** [jMonkeyEngine/jmonkeyengine#1871]
Models coloured through vertex colours are not properly rendered in the application; various attempts in altering the formats and materials have resulted in null results. If a material isn't specified, the model is wholly white. Using the lighting material, even with "UseVertexColor" it's wholly black without details.

The following code is without utilizing any material, but it may be altered to set the 'Lighting.j3md' material. "UseVertexColor" does not appear to function as intended.
```
Light directionalLight = new DirectionalLight(new Vector3f(-10, -5, -10));
Light ambientLight = new AmbientLight();
Material material = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
material.setBoolean("UseVertexColor", true);
Spatial playerModel = assetManager.loadModel("models/TestGirl.glb");
playerModel.setLocalScale(0.5f);
playerModel.setLocalTranslation(new Vector3f(-4,-7.1f,0));

rootNode.attachChild(playerModel);
rootNode.addLight(directionalLight);
rootNode.addLight(ambientLight);
```

The model file is available here, for testing:
[TestModel.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/10102604/TestModel.zip)

**Comment by Ali-RS** [comment]
Tried it with Unsahded, Lighting and PBRLighting materials but could not get vertex colors to work. I can confirm mesh has a color buffer on it. `VertexBuffer[fmt=Float, type=Color, usage=Dynamic, elements=7268]`

**Comment by pspeed42** [comment]
GLTF issues aside, I can assure you 100% that vertex colors work in the engine, definitely for Unshaded.j3md because I use that one all the time (unless it was broken very recently).  So to whomever is looking at this, it would be worth checking what's in the color buffer.

**Comment by Abstrusle** [comment]
> 

What's a colour buffer.

**Comment by Ali-RS** [comment]
I figured this change in gltf blender addon broked GltfLoader.

https://github.com/KhronosGroup/glTF-Blender-IO/pull/1169

If I revert that change I can successfully load vertex colors in JME.

**Comment by pspeed42** [comment]
Lovely. Is there something in the GLTF that indicates the bad version versus the good version?  Or are we stuck having to do some odd detection to find these cases?  

Either way, nice of them to break this for everyone.  (Or maybe JME is reading these values in a dumb way.  50/50 chance.)

**Comment by Ali-RS** [comment]
Well, I guess it is detectable based on buffer type.

In the old way, the buffer attribute was a float buffer

```
        {
            "bufferView" : 3,
            "componentType" : 5126,
            "count" : 24,
            "type" : "VEC4"
        },

```


https://github.com/jMonkeyEngine/jmonkeyengine/blob/a2d639ca73a7344f1aa4b8b97e74a49af2da3887/jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfUtils.java#L98-L99

after the change, it is now exported as unsigned short buffer

```
        {
            "bufferView" : 3,
            "componentType" : 5123,
            "count" : 24,
            "normalized" : true,
            "type" : "VEC4"
        },

```
https://github.com/jMonkeyEngine/jmonkeyengine/blob/a2d639ca73a7344f1aa4b8b97e74a49af2da3887/jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfUtils.java#L94-L95

there is already a check in GltfLoader to unpack short back to a float buffer but it seems something goes wrong down the road.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/a2d639ca73a7344f1aa4b8b97e74a49af2da3887/jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java#L1293-L1298

**Comment by tonihele** [comment]
I got this fixed, I'll submit a PR shortly.

**Comment by tonihele** [comment]
Thank you @Abstrusle for taking the time to report this. GLTF pipeline is very important and as such I'd say this bug is high priority level.
