### ISSUE TITLE
JME fails at displaying glTF compliance test model from KhronosGroup

### ISSUE THREAD

**Issue by manuelrmo** [jMonkeyEngine/jmonkeyengine#1874]
The following glTF test model shows up black in JME, while other glTF viewers will succeed to display it (like Windows' 3D Viewer):
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest

The reason seems to be related to the following setting within the glTF model:
"metallicFactor": 0

![Capture](https://user-images.githubusercontent.com/118840772/204993468-03aa496c-29bd-4486-9938-455747f9a401.PNG)

**Comment by Ali-RS** [comment]
So will it display correctly if you change `metallicFactor`?

Also is there a light probe added to the scene?

**Comment by manuelrmo** [comment]
> So will it display correctly if you change `metallicFactor`?

Somehow yes. See the screenshot below with `metallicFactor` changed to `0.5` for one of the meshes. Need to turn on PBR Environment in the viewer. 

> Also is there a light probe added to the scene?

I guess no need, see the previous answer.

> Does it use the `KHR_texture_transform` extension you submitted in your other PR?

Yes, but the extension is irrelevant: an image should display with and without the extension.

> Does it only happen with models that use `KHR_texture_transform` extension?

No, since the issue has nothing to do with the extension. 

![Capture](https://user-images.githubusercontent.com/118840772/205014008-faa6a14f-4d28-4c28-b6f3-6841e19a46f9.PNG)

**Comment by manuelrmo** [comment]
The screenshot below is what comes out in the latest stable SDK, after converting the `.gltf` file to `.j3o` and applying the `Unshaded` material definition to all geometries.

![Capture3](https://user-images.githubusercontent.com/118840772/205058844-ae7c3ced-bae0-4b58-93be-6afba70a729b.PNG)

**Comment by neph1** [comment]
I've been investigating this for the SDK: https://github.com/jMonkeyEngine/sdk/issues/418
Can you verify that metallic factor is black when it's 0? Because jme's pbr material defaults to 1 (for some reason). Ie, change back to 0 after 0.5 and see if it's still black.

**Comment by manuelrmo** [comment]
> change back to 0 after 0.5 and see if it's still black.

Yes, it's still black. 

Above, I directly edited the `.gltf` file to change `metallicFactor` to `0.5`.
You can do a similar thing on the SDK: convert `.gltf` to `.j3o,` `create j3m file` for a geometry, then change the value of the `Metallic` parameter. So changing `Metallic` from `0` to `0.5` then back to `0` makes the geometry black again.

**Comment by neph1** [comment]
> So changing `Metallic` from `0` to `0.5` then back to `0` makes the geometry black again.

I can't reproduce that. A material with Metallic 0 looks fine in both Material Editor and SceneComposer, while a material with Metallic 1 will be black, unless there is a light present.

**Comment by manuelrmo** [comment]
> I can't reproduce that.

Did you use the TextureTransformTest model? This issue happens with this model and my comments refer only to this model, you can download it at this link:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest

**Comment by manuelrmo** [comment]
I found the cause of the issue: it's not related to `metallicFactor` but to the non-use of "normals" in the glTF model.

So I searched for another test model not using normals, and I found the fox model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox

This model, as the previous one, has no attribute "NORMAL" for the mesh:

                    "attributes": {
                        "POSITION": 0,
                        "TEXCOORD_0": 1,
                        "JOINTS_0": 2,
                        "WEIGHTS_0": 3
                    },

When opening the model in JME, the fox shows up dark, see the screenshot:

![fox1](https://user-images.githubusercontent.com/118840772/205581762-78d076c7-abf6-44a1-a7d4-c468a8cc8f8b.PNG)

However, the same model with normals shows up properly in JME. For example, Blender will add in the normals after importing/exporting the glTF model. When opening the exported glTF model in JME, the issue has dissapeared, see the screenshot:

![fox2](https://user-images.githubusercontent.com/118840772/205581882-06810db9-92f9-49dd-a074-bef4a1bb4470.PNG)

For both screenshots above, `metallicFactor` is 0.

**Comment by Ali-RS** [comment]
Are those models probably using the `KHR_materials_unlit` extension?

**Comment by manuelrmo** [comment]
> Are those models probably using the KHR_materials_unlit extension?

No

**Comment by Ali-RS** [comment]
@pspeed42 what do you think?

**Comment by pspeed42** [comment]
About what?  If we're supposed to calculate normals then I guess we need to calculate normals.  Potentially not straight forward if vertexes need to be duplicated, etc..
