### ISSUE TITLE
updateBound() is missing in native GImpactCollisionShape

### ISSUE THREAD

**Issue by jimbok8** [jMonkeyEngine/jmonkeyengine#188]
updateBound() has been commented out in in native GImpactCollisionShape

fragment for  jme3-bullet version:
    //        ((GImpactMeshShape)objectId).updateBound();
    //        objectId.setLocalScaling(Converter.convert(getScale()));
    //        objectId.setMargin(margin);
    meshId = NativeMeshUtil.createTriangleIndexVertexArray(triangleIndexBase, vertexBase, numTriangles, numVertices, vertexStride, triangleIndexStride);

fragment for  jme3-jbullet version:
    cShape = new GImpactMeshShape(tiv);
    cShape.setLocalScaling(Converter.convert(worldScale));
    ((GImpactMeshShape)cShape).updateBound();

I suspect this came about during creation of '''NativeMeshUtil.createTriangleIndexVertexArray()''' routine.

**Comment by shadowislord** [comment]
If you would like, you can make a pull request with the fix .. The person who is maintaining the physics support is not currently available.
