### ISSUE TITLE
NoSuchMethodError in BufferUtils.createFloatBuffer() with JDK 8

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#1896]
```console
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.FloatBuffer.clear()Ljava/nio/FloatBuffer;
	at com.jme3.util.BufferUtils.createFloatBuffer(BufferUtils.java:871)
	at mygame.Main.main(Main.java:7)
```

+ I can't reproduce this issue in jme3-examples, only in a separate project.
+ I can't reproduce this issue with JDK 11 or 17, only with  JDK 8 .
+ I can't reproduce this issue with JME 3.5.2, only with JME 3.6.0-alpha1 .

Will  JME 3.6 support Java 1.8?

Here's the test app:
```java
package mygame;

import com.jme3.util.BufferUtils;

public class Main {
    public static void main(String[] arguments) {
        BufferUtils.createFloatBuffer(3);
    }
}
```

**Comment by Ali-RS** [comment]
Going to check it.

>Will JME 3.6 support Java 1.8?

It should.

**Comment by Ali-RS** [comment]
I can reproduce this. 

I checked `BufferUtils.class` bytecode version is 52 (compiled with java 8) so I have no clue why it still throws NoSuchMethodError.

Does anyone have any clue?

**Comment by Ali-RS** [comment]
I submitted a fix in https://github.com/jMonkeyEngine/jmonkeyengine/pull/1897

**Comment by Ali-RS** [comment]
Apparently, this happens also with alpha2!
