### ISSUE TITLE
main.yml: OSSRH artifacts are build with different java version

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1923]
I noticed DeployRelease job that publishes Maven Publication to OSSRH repository has no `setup-java` action to install the intended java version on the OS and probably the latest ubuntu comes with java 11 by default or could be that running the `./gradlew publishMavenPublicationToOSSRHRepository` installs java 11 by default(?) so artifacts are built with java 11.

https://github.com/jMonkeyEngine/jmonkeyengine/blob/458e9ec210c131f92f4d8e5f93f01f1dc93b0a5b/.github/workflows/main.yml#L293-L341

The JME 3.6.0-alpha3 artifacts published on the [Maven Central Repo](https://repo1.maven.org/maven2/org/jmonkeyengine/jme3-core/3.6.0-alpha3/) have **_Created-By: 11 (Eclipse Adoptium)_** in their MANIFEST.MF.

**Comment by Ali-RS** [comment]
Submitted a fix in #1924

**Comment by Scrappers-glitch** [comment]
The deploy task doesn't call `./gradlew build`, it downloads the pre-built artifacts and publishes them.

**Comment by Scrappers-glitch** [comment]
Btw, this issue has a wrong flag.

**Comment by Ali-RS** [comment]
>The deploy task doesn't call ./gradlew build, it downloads the pre-built artifacts and publishes them.

I do not know where `publishMavenPublicationToOSSRHRepository` task come from but by looking at the logs on GitHub action seems it also calls `compileJava` task:
https://github.com/jMonkeyEngine/jmonkeyengine/actions/runs/3922595564/jobs/6705722231#step:6:135

**Comment by Ali-RS** [comment]
Also, here it says that it will rebuild the artifacts

https://github.com/jMonkeyEngine/jmonkeyengine/blob/458e9ec210c131f92f4d8e5f93f01f1dc93b0a5b/.github/workflows/main.yml#L326
