### ISSUE TITLE
setLineWidth calls ignored in 3.6.0-beta1

### ISSUE THREAD

**Issue by richardTingle** [jMonkeyEngine/jmonkeyengine#1946]
Calls to material.getAdditionalRenderState().setLineWidth seem to be being ignored in 3.6.0-beta1

With the following sample program

```
public class LineWidthTest extends SimpleApplication{

    public static void main(String[] args){
        LineWidthTest app = new LineWidthTest();
        AppSettings settings = new AppSettings(true);
        app.setShowSettings(false);
        app.setSettings(settings);
        app.start();
    }

    @Override
    public void simpleInitApp() {
        Line line = new Line(new Vector3f(0,0,0), new Vector3f(0,3,0));
        Geometry lineGeometry = new Geometry("line", line);
        Material lineMat = new Material(getAssetManager(),"Common/MatDefs/Misc/Unshaded.j3md");
        lineMat.setColor("Color", ColorRGBA.White);
        lineMat.getAdditionalRenderState().setLineWidth(10);
        lineGeometry.setMaterial(lineMat);
        rootNode.attachChild(lineGeometry);
    }
}

```
On jme 3.6.0-beta1 it appears as follows (thin line):

![image](https://user-images.githubusercontent.com/6330028/218164142-1d7b5309-fc27-46ae-a57a-0652a31cbefb.png)

But on 3.5.0-stable it appeas like this (with the requested thicker line):

![image](https://user-images.githubusercontent.com/6330028/218164149-4f50f40d-0799-4737-b9c7-9c4cccc7c794.png)

**Comment by stephengold** [comment]
In OpenGL there are limits on line widths. What's the value of `renderer.getMaxLineWidth()` in your test environment?

**Comment by richardTingle** [comment]
> In OpenGL there are limits on line widths. What's the value of `renderer.getMaxLineWidth()` in your test environment?

I took it all the way down to 2. Everything looks the same as 1. (Although this question might have been superseded by Ali's comment that this is a known issue.)

**Comment by richardTingle** [comment]
> In OpenGL there are limits on line widths. What's the value of `renderer.getMaxLineWidth()` in your test environment?

1.0 when running in 3.6.0-beta1. 10.0 when running in 3.5.0-stable

**Comment by richardTingle** [comment]
> That is a known issue with the OpenGL core profile which is used by default in JME 3.6 #1752
> 
> If you switch back to the compatibility profile, LineWidth will work.

That PR seems to change from OpenGL 2 to OpenGL 3 which seems like a good thing. Are linewidths just not going to be a thing anymore going forward?

**Comment by pspeed42** [comment]
My weak understanding is that line widths are no longer a thing after OpenGL2.  I have not looked online to confirm this but my memory is that support was even spotty in OGL2.  Like, nvidia = always yes, ATI/AMD = sometimes yes, intel = always no.

Back in pre-OGL2 days, you had to have a high end card that supported "CAD graphics" to get line widths and things.

**Comment by richardTingle** [comment]
Fair enough. I wonder if we should mark that method as deprecated in that case?

(And I'll have to think of an alternative for 3d pick lines that remain visible at both short and long distances)

**Comment by stephengold** [comment]
> > In OpenGL there are limits on line widths. What's the value of `renderer.getMaxLineWidth()` in your test environment?
> 
> 1.0 when running in 3.6.0-beta1. 10.0 when running in 3.5.0-stable

You might be able to draw 10-pixel lines in 3.6.0-beta1 if you set `settings.setRenderer(AppSettings.LWJGL_OPENGL2)`
But you'd still have a portability issue.

**Comment by Ali-RS** [comment]
>I wonder if we should mark that method as deprecated in that case?

I would rather not deprecate it because it is still usable with OpenGL "compatibility profile" but I will update the Javadoc on `setLineWidth` and mention this problem with "core profile".

**Comment by richardTingle** [comment]
Thanks @Ali-RS!
