### ISSUE TITLE
It seems jmf library coming with j-ogg-all is not required?

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1958]
I noticed if I exclude the jmf library coming with [j-ogg-all](https://github.com/stephengold/j-ogg-all), I can still play ogg sound in JME. Looks like jmf is not required for decoding ogg files(?) if so, we may safely exclude it in `jme3-jogg`. (the jmf jar size is 1.8 MB!)

From a quick glance at [ogg](https://github.com/stephengold/j-ogg-all/tree/master/src/main/java/de/jarnbjo/ogg) package, I could not find any class using `jmf` package.

@stephengold can you please confirm if jmf library is required for decoding ogg files in JME?

**Comment by stephengold** [comment]
> if jmf library is required for decoding ogg files in JME?

I don't see an easy way to check whether JMF is required. The runtime checks you did are encouraging but they didn't cover all code paths. "jmf-2.1.1e.jar" contains 993 class files in over 100 packages with a wide variety of names, so grepping for names would be a huge undertaking.

I'm sure jme3-jogg utilizes only a fraction of j-ogg-all's capabilities. If the goal is to minimize application size, one might copy code from j-ogg-all to jme3-jogg on an as-required basis and see where the process leads. That would be intellectually satisfying, but my experience with shrinking JME apps has convinced me that that big wins are in reducing texture sizes, not deleting unused code.

**Comment by Scrappers-glitch** [comment]
Jmf has a lot of functions rather than just code used by j-ogg-all, so i think the only way to reduce the size of the jmf library is by maintaining the jmf library and re-distributing it into multiple modules and so the jogg-all can selectively implement the needed code only....

**Comment by Ali-RS** [comment]
>If the goal is to minimize application size, one might copy code from j-ogg-all to jme3-jogg on an as-required basis and see where the process leads.

The goal is to remove unrequired libraries. It is a good idea to copy only the required classes to jme3-jogg but until someone does that I would rather go with the simplest path by excluding the unrequired library.

```
   api ('com.github.stephengold:j-ogg-all:1.0.2') {
        exclude module: "jmf"
    }
```

**Comment by stephengold** [comment]
> one might copy code from j-ogg-all to jme3-jogg on an as-required basis and see where the process leads.

I performed this experiment and found that jme3-jogg needs only 3 packages from j-ogg-all in order to compile:
 + de.jarnbjo.ogg
 + de.jarnbjo.util.io and
 + de.jarnbjo.vorbis

Those 3 packages all compile without JMF. So unless there are hidden runtime dependencies (via reflection), we can safely exclude JMF as proposed above.
