### ISSUE TITLE
NativeLibraryLoader wrong libraries path

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1965]
- All the native libraries registered by default for lwjgl 2 and 3 in NativeLibraryLoader have the wrong path! (it still works for lwjgl2 and JInput because of this [fallback](https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L570) because lwjgl2 and JInput natives are located in the root of the jar)

https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L123-L200

- NativeLibraryLoader is never used by jme3-lwjgl3. LWJGL 3 uses its own [SharedLibraryLoader](https://github.com/LWJGL/lwjgl3/blob/b44ba7af8030200bee34d7dfb77edf5617589328/modules/lwjgl/core/src/main/java/org/lwjgl/system/SharedLibraryLoader.java#L35) so we should remove lwjgl3 libraries from there as it is misleading. Also trying to load lwjgl3 libraries via NativeLibraryLoader won't work anyway and will produce an UnsatisfiedLinkError as it wouldn't find the libraries because of a wrong path. 

```
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.UnsatisfiedLinkError: The required native library 'lwjgl' was not found in the classpath via 'native/linux/liblwjgl.so'. Error message: no lwjgl in java.library.path
	at com.jme3.system.NativeLibraryLoader.loadNativeLibrary(NativeLibraryLoader.java:590)
	at jme3test.helloworld.HelloAudio.simpleInitApp(HelloAudio.java:27)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:601)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:704)
	at java.lang.Thread.run(Thread.java:750)
```

- It does not register the ARM natives for macOS and Linux.

Thoughts?

**Comment by stephengold** [comment]
I'm fine with jme3-lwjgl not supporting ARM architectures.

`NativeLibraryLoader` should be cleaned up so it doesn't register non-existent and/or unnecessary libraries.

**Comment by Scrappers-glitch** [comment]
Do you want to clean-up this or just fix-to-work ?

**Comment by Ali-RS** [comment]
I was thinking of cleaning all the lwjgl3-related stuff and fixing the wrong path for lwjgl2-related stuff.

Do you have another opinion?

**Comment by Ali-RS** [comment]
I do not know about BulletJme though!

**Comment by Ali-RS** [comment]
Also found these usages in jme3-vr

https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java#L122-L132

**Comment by stephengold** [comment]
> Does Minie use `NativeLibraryLoader` for loading natives?

Yes, though seldom explicitly. Most Minie apps simply assume JME will automatically load the natives during initialization.

> Is the `bulletjme` natives' path correct?

Yes.

**Comment by Scrappers-glitch** [comment]
> Do you have another opinion?

I don't know much about the internal design of how jme deals with native libraries apart from just extracting them from the jar file, but i think it's better to keep all the native libraries, as far as we can, inside one directory in the jar file, for example: 
- lib/linux/x86-64/libxxxx.so
- lib/linux/x86/libxxx.so

Or:
- native/linux/x86-64/libxxx.so
- native/linux/x86/libxxx.so

And, if we are forced to have multiple directories for natives, then we should build a new abstract NativeLibraryLoader and extend the utility to create for example, `BulletLibraryLoader` and `LwjglLibraryLoader` that would just change the native directory path.

**Comment by Ali-RS** [comment]
>but i think it's better to keep all the native libraries, as far as we can, inside one directory in the jar file, for example:

Each library puts them in a different path for example jinput and lwjgl2 put them in jar root while lwjgl3 puts them in `<os>.<arch>.org.lwjgl.<libraryname>` for example `linux.x64.org.lwjgl.opengl.liblwjgl_opengl.so`.

**Comment by Scrappers-glitch** [comment]
> And, if we are forced to have multiple directories for natives, then we should build a new abstract NativeLibraryLoader and extend the utility to create for example, `BulletLibraryLoader` and `LwjglLibraryLoader` that would just change the native directory path.

It was best to consider this while designing the code, but idk if we now have time to refactor, or just want to go with the fix-to-work solution, if i ever got enough time, i will redesign this, however, if you would like, you can open another issue at any time to redesign and assign me....

**Comment by Ali-RS** [comment]
I mean JME NativeLibraryLoader already can manage this. We register a native library by specifying a name for that library and a platform and the native library path in the jar and then we can load it with `NativeLibraryLoader.loadNativeLibrary(libraryName); `

https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibrary.java#L39

I do not see why we may want to redesign or change it.

**Comment by Ali-RS** [comment]
But we can improve it by fixing these hardcoded hacks:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L577

https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L666

**Comment by Ali-RS** [comment]
See https://github.com/jMonkeyEngine/jmonkeyengine/issues/1968

**Comment by Scrappers-glitch** [comment]
> I can not see why we need to redesign it.

I don't prefer large functions with too many blocks, there are a lot of hidden bugs in them, plus yeah the hardcorded directories and names may fail in some other places (according to the condition, the names may change or written wrongly, so you will have to go over each dependency and refactor it), I haven't glanced the NativeLibraryLoader in details yet, give me sometime to glance it and I will reply back on what should be done on my opinion on the newly created issue, but it indeed looking at it from here, it needs a lot of work.

**Comment by stephengold** [comment]
Regarding the "bulletjme" native libraries (originally for "jme3-bullet" but now used only by Minie), there was a previous proposal to change their names: #1422

**Comment by stephengold** [comment]
> Should we change the names of bulletjme natives?

I'd rather not rename physics natives because that would require changes on the Minie side and probably cause some temporary breakage of application builds.

> I think no change will be required on Minie.

Minie added those files to the JAR to begin with! So if the names change, I think Minie must be built differently.

At that point, old versions of Minie won't work with new versions of jme3-desktop and new versions of Minie won't work with old versions of jme3-desktop. That's a lot of pain for (what looks to me like) slight benefit.

Extracting natives from the classpath into the working directory is a risky hack. In the long term, JME should probably use a native-library loader analogous with that of LWJGL v3.

**Comment by Ali-RS** [comment]
>Minie added those files to the JAR to begin with! So if the names change, I think Minie must be built differently.

Specifying `extractAsName` should not require any changes to Minie, I am sure of it. It will still look for `libbulletjme` inside the jar but will extract it as `libbulletjme32` or `libbulletjme64`.

>Extracting natives from the classpath into the working directory is a risky hack. In the long term, JME should probably use a native-library loader analogous with that of LWJGL v3.

It first looks working directory if it is writable it picks it else it looks for [cache directory](https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L294-L311) in user.home directory if found it, will extract there, if not found then it will extract to `userHome/.jme3`.

LWJGL v3 extracts its natives inside the `temp` directory.

**Comment by stephengold** [comment]
> It will still look for libbulletjme inside the jar but will extract it as libbulletjme32 or libbulletjme64.

Ah! I didn't understand that. That should be okay then.

> LWJGL v3 extracts its natives inside the temp directory.

What bothers me is JME only extracts to a file if the file doesn't already exist. Ideally, natives should be extracted each time the application is run. Otherwise you might reuse natives from a different platform or version, or (paranoia follows) you might use natives maliciously planted on your filesystem.

**Comment by Ali-RS** [comment]
>What bothers me is JME only extracts to a file if the file doesn't already exist.

Or the file lastModified date is different.
https://github.com/jMonkeyEngine/jmonkeyengine/blob/375015f14c5f3cbda18302b3aa990e5f023e9da1/jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java#L628-L641

**Comment by stephengold** [comment]
> Should I apply this?

I think so. The only downside I see is performance.

> About the different "versions", they will have different lastModified dates so the new one should overwrite the old one.

Sometimes one actually wants the older version.

**Comment by Ali-RS** [comment]
>Ideally, natives should be extracted each time the application is run.

Will handle this in a separate PR.
