### ISSUE TITLE
AppSettings.setSamples() wrong javadoc

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#1977]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/44a50de4d7797dc3dd8d46cd1f51308e9a05d627/jme3-core/src/main/java/com/jme3/system/AppSettings.java#L883-L887

https://github.com/jMonkeyEngine/jmonkeyengine/blob/44a50de4d7797dc3dd8d46cd1f51308e9a05d627/jme3-core/src/main/java/com/jme3/system/AppSettings.java#L278

**Comment by Scrappers-glitch** [comment]
Do we need to change the actual default value in code or the javadoc?

**Comment by stephengold** [comment]
> Do we need to change the actual default value in code or the javadoc?

I don't think it matters. If I recall correctly, both values (0 and 1) have the same effect. But in case I'm mistaken, changing the javadoc would be safest.

**Comment by andygibson** [comment]
PR: https://github.com/jMonkeyEngine/jmonkeyengine/pull/2044

**Comment by Ali-RS** [comment]
Thank you @andygibson!
