### ISSUE TITLE
com.jme3.post.ssao.SSAOFilter does not exist

### ISSUE THREAD

**Issue by erikmartinessanches** [jMonkeyEngine/jmonkeyengine#1984]
The docs says this class exist, but it's not present in the gradle-downloaded jME library. This code was working some months ago on an x64 intel macbook (though I did not use gradle) and now I'm on an M1, if it matters.

macOS v13.2, jME v 3.5.2-stable, semuru-18 (IBM JDK version 18.0.2).
![SCR-20230309-s66](https://user-images.githubusercontent.com/4912935/224132346-55a37d0d-4cff-4673-a9f4-3189d11b4c1c.png)

**Comment by Ali-RS** [comment]
That class is in `jme3-effects` module, you need to add `jme3-effects` to the gradle dependencies.
