### ISSUE TITLE
NativeLibraryLoader.java throws inconsistent exceptions when failing to open Jar files

### ISSUE THREAD

**Issue by drhaozhong** [jMonkeyEngine/jmonkeyengine#1999]
If this class fails to open a jar file, computeNativesHash throws UnsupportedOperationException:

`try{
 ... conn = url.openConnection();
} catch (IOException ex) {
            throw new UnsupportedOperationException(ex);
        } finally {
            if (conn != null) {
                try {
                    conn.getInputStream().close();
                    conn.getOutputStream().close();
                } catch (IOException ex) { }
            }
        }`

However, loadNativeLibrary throws UncheckedIOException

`try {
            conn = url.openConnection();
            in = conn.getInputStream();
        } catch (IOException ex) {
            // Maybe put more detail here? Not sure..
            throw new UncheckedIOException("Failed to open file: '" + url + 
                                           "'. Error: " + ex, ex);
        }`

This is confusing. Can this problem be fixed?

**Comment by stephengold** [comment]
Thank you for reporting this issue.
