### ISSUE TITLE
Instanced objects are culled when using WaterFilter

### ISSUE THREAD

**Issue by foxcc2021** [jMonkeyEngine/jmonkeyengine#2007]
It seems there is a bug in culling checks of instanced objects.

![20230510202939](https://github.com/jMonkeyEngine/jmonkeyengine/assets/93635496/ffeda85e-90c8-4d36-bcbf-bc657fca3b42)
The tree model should not be culled.

![20230510203009](https://github.com/jMonkeyEngine/jmonkeyengine/assets/93635496/143f7e2f-4a75-467f-bd45-673dc5261e85)
The correct scene expected．

After some debugging, I found that, it seems the instanceCullingFunction used the wrong camera to cull checks in the InstancedGeometry。
Because the WaterFilter has a reflectionCam, the default camera will be replaced when waterFilter rendering.
![20230510202701](https://github.com/jMonkeyEngine/jmonkeyengine/assets/93635496/f99bffdb-23e1-4bec-bfeb-9615320d7e29)

![20230510210756](https://github.com/jMonkeyEngine/jmonkeyengine/assets/93635496/8641fb3b-c566-4eb0-be0f-005773c6270e)
I've solved my problem using this way,pass the render camera from the instanced node to the instanced geometry for culling checks.
Hope this can helps.

JME version:3.6.0-stable
System: win10

**Comment by Ali-RS** [comment]
I can not reproduce this issue, can you provide a simple test case demonstrating the issue?

**Comment by Ali-RS** [comment]
I can not reproduce this issue, can you provide a simple test case demonstrating the issue?

**Comment by foxcc2021** [comment]
I made a video to show the issue.

https://youtu.be/fbHqHQu6js8

The simple test case is:
`
public class TestWaterAndInstanced extends SimpleApplication {
    
    public static void main(String[] args) {
        TestWaterAndInstanced test = new TestWaterAndInstanced();
        test.start();
    }
    
    private Box mesh;
    private Material mat;
    private InstancedNode instanceNode;
    
    @Override
    public void simpleInitApp() {
        flyCam.setMoveSpeed(10);
        
        DirectionalLight light = new DirectionalLight();
        light.setDirection(new Vector3f(-1, -1, -1));
        rootNode.addLight(light);
        
        mat = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
        mat.setBoolean("UseInstancing", true);
        
        mesh = new Box(0.5f, 0.5f, 0.5f);
        
        FilterPostProcessor fpp = new FilterPostProcessor(assetManager);
        WaterFilter waterFilter = new WaterFilter();
        waterFilter.setReflectionScene(rootNode);
        fpp.addFilter(waterFilter);
        viewPort.addProcessor(fpp);
        
        instanceNode = new InstancedNode("TestInstancedNode");
        rootNode.attachChild(instanceNode);
        
        for (int i = 0; i < 1000; i++) {
            Geometry obj = new Geometry("TestBox" + i, mesh);
            obj.setLocalTranslation(0, 10, 0);
            obj.setLocalScale(1, 1, 1);
            obj.setMaterial(mat);
            obj.setLocalTranslation(i, i, 0);
            instanceNode.attachChild(obj);
        }
        instanceNode.instance();
    }
}
`

**Comment by foxcc2021** [comment]
> public boolean checkCulling(Camera cam) { 
>      this.cam = cam; 
>      return super.checkCulling(cam); 
>  }

I think maybe the problem is with checkCulling method, cam will be replaced by reflectionCam of WaterFilter.
InstancedNode renders the instance object in its render method, but the cam has been replaced.
But I just found out, that there is something wrong with my solution, causing the whole InstancedNode to disappear.

**Comment by Ali-RS** [comment]
Thanks for the test and video, I am going to try it soon.

By the way, you can also disable instance culling by setting `InstancedGeometry.setInstanceCullingFunction(null);` (note that this is a static method) which should resolve the issue.

**Comment by foxcc2021** [comment]
Thank you!
Culling check of the instancing object is very useful for large scenes.
Hope it can be fixed.

**Comment by Ali-RS** [comment]
I can reproduce the issue with your test case. Passing the camera from InstancedNodeControl as you suggested seems to resolve the issue.

**Comment by foxcc2021** [comment]
> Would you like to submit a PR?

I'm sorry, I don't know how to make the PR.
