### ISSUE TITLE
`BaseAction.setMaskPropagationEnabled()` misnomer?

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#2014]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/ca0b54e9f69e388e4705ae9792f917abc2d0e494/jme3-core/src/main/java/com/jme3/anim/tween/action/BaseAction.java#L66-L80

I believe I used the wrong name in the above methods. Which word better suits there, "Propagation" or "Dispatching" or "Forward" or...? 

I know it is late to rename it, but if you think it is named wrongly please let me know if I need to deprecate it and introduce a new method.

**Comment by Scrappers-glitch** [comment]
IDK, I have never had problems with animation masks (maybe because I haven't leveraged its full potential), if a parent passes something to a child then this is a form of inheritance, so I guess `Mask Inheritance` might be appropriate, also `heritage` is a good shrunk version of inheritance.

**Comment by stephengold** [comment]
I think "propagation" is fine. "Inheritance" would also work, but that word already has an important meaning in the context of object-oriented programming languages.

**Comment by Scrappers-glitch** [comment]
> but that word already has an important meaning in the context of object-oriented programming languages.

By the way, the CullHint uses the Inherit keyword, so it is quite usable within the proper context.

**Comment by Ali-RS** [comment]
Thanks, based on feedbacks, I am willing to keep the current name.
