### ISSUE TITLE
Guard setters against negative values

### ISSUE THREAD

**Issue by Scrappers-glitch** [jMonkeyEngine/jmonkeyengine#2027]
Those public setters aren't supposed to be negative values and need to be guarded to avoid un-expected results.

1) [`BlendableAction#setTransitionLength(double)`](https://github.com/JMonkey-Archive/jmonkeyengine/blob/bbd041c1020b1e80154a5c78f9ae45513bcc977e/jme3-core/src/main/java/com/jme3/anim/tween/action/BlendableAction.java#L107-L110)
2) [`AbstractTween#setLength(double)`](https://github.com/JMonkey-Archive/jmonkeyengine/blob/bbd041c1020b1e80154a5c78f9ae45513bcc977e/jme3-core/src/main/java/com/jme3/anim/tween/AbstractTween.java#L59-L61)

I don't think duration factors can be negative.

**Comment by SaichandChowdary** [comment]
PR - https://github.com/jMonkeyEngine/jmonkeyengine/pull/2037
