### ISSUE TITLE
DefineList needs refactored to support >64 defines

### ISSUE THREAD

**Issue by yaRnMcDonuts** [jMonkeyEngine/jmonkeyengine#2032]
I've opened this issue following up the discussion from this thread:

https://hub.jmonkeyengine.org/t/optimize-terrain-shaders-for-tri-planar-mode-per-layer-remove-fog-defines-to-make-room/46816/9

The DefineList class currently sets an arbitrary limit of 64 defines per technique.

As suggested by @pspeed42 the best way to fix this is to refactor the DefineList class is to allow the Array to expand rather than pre-allocating it with a limited size of 64. And he also mentioned some other things that could be cleaned up or done better in that class, so we can continue discussing the specifics of what needs refactored here. 

I'm not a core dev nor an official contributor so I admittedly do not feel comfortable making an attempt at refactoring this area of the engine without first having more guidance or a clear outline to follow ahead of time. So if anyone wants to give me some guidance and specifications then I can work on refactoring DefineList, or if anyone more experienced wants to steal the thunder and submit your own PR for this issue then you are more than welcome to do so.

**Comment by pspeed42** [comment]
I make take a stab at starting some unit tests this week if I get a minute.

**Comment by stephengold** [comment]
Resolved in "master" branch at 58365c4b8a3929954718ac3e292ca77675dd5540 by PR #2116.
