### ISSUE TITLE
Artifact when taking screenshot of odd-height ViewPort (using AWTPanelsContext)

### ISSUE THREAD

**Issue by jdeyton** [jMonkeyEngine/jmonkeyengine#204]
Hello all,

I was trying to implement the ability to capture screenshots of ViewPorts from within a project that uses the AWTPanelsContext to render said ViewPorts.

I discovered that when taking screenshots of AWT Frames with odd heights, the very middle of the generated PNG files have a horizontal streak across them (see attached image). With even heights, the screenshots are fine.

It looks like the bug may have to do with the loop condition on line 88 in com.jme3.util.Screenshots.java.
~~~~
for (int y = 0; y < height / 2; y++){
~~~~
Changing the loop condition to something like `y < Math.ceil(height * 0.5)` fixed the problem for me.

Cheers,
Jordan

![testimage](https://cloud.githubusercontent.com/assets/5607944/5444884/1302f210-847d-11e4-9ebe-0cba85a9c8a7.png)

**Comment by shadowislord** [comment]
Fixed in 66d4763a04fd5a63d4b4b45e062546cd035944f6, but the ScreenshotAppState no longer uses this method anyway.

**Comment by jdeyton** [comment]
Thanks! Keep up the good work, guys/gals!
