### ISSUE TITLE
ArmatureMask.createMask() duplicate code

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#2045]
From a quick glance, the for-loop in the below method looks redundant to me and should be removed because `affectedJoints` is already set by the `mask.addBones(armature, joints);`

https://github.com/jMonkeyEngine/jmonkeyengine/blob/5155f56616497a4087ffc43af53f968c565dd065/jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java#L89-L96

refrence for `addBones()` method:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/5155f56616497a4087ffc43af53f968c565dd065/jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java#L104-L109

**Comment by codex128** [comment]
#2046

**Comment by Scrappers-glitch** [comment]
I totally agree and also notice the vulnerability (for NullPointerExceptions) of using `armature.getJoint(joint)` over `ArmatureMask#findJoint(...)`, it's better by all means to replace it, it's a literal code defect not only duplication.

**Comment by andygibson** [comment]
`ArmatureMask#findJoint(...)` throws an IllegalArgumentException if the joint name is not found- is that the desired behaviour for when a joint is not found?
The alternative would be to use `getJoint` in `addBones` and check if its not `null`.

**Comment by pspeed42** [comment]
Personally, I expect findXXX style methods to return null if something is not found and getXXX style methods to throw an exception (in the case that there are both).

"find" = "a query"  "get" = "give me that thing I truly expect to be there"

**Comment by andygibson** [comment]
I agree 100% on exceptions with find/get - but that ship has probably sailed for now. I'd be happy to implement that way, but they are public API methods, and not sure whether the rest of the API respects this find/get principle.

Aside from that, the question remains of whether to throw an exception if we pass a JointName that doesn't exist - is it exception worthy? I don't have a great grasp of context for this method, so I can't say one way or another, but happy to implement either.

Cheers

**Comment by Ali-RS** [comment]
My two cents

>ArmatureMask#findJoint(...) throws an IllegalArgumentException if the joint name is not found- is that the desired behaviour for when a joint is not found?

Yes

https://github.com/jMonkeyEngine/jmonkeyengine/blob/5155f56616497a4087ffc43af53f968c565dd065/jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java#L111-L117

`findJoint()` is a private method, so I think we can safely rename it if the current name is not suitable.
