### ISSUE TITLE
Flat shading terrain quad

### ISSUE THREAD

**Issue by hunterboerner** [jMonkeyEngine/jmonkeyengine#205]
Is there a way to render a TerrainQuad without the smooth shading. I am trying to create a low-poly game and it needs to be flat shaded. I'm generating the terrain from perlin noise so the SDK can't help me.

Thanks

**Comment by Relic724** [comment]
haha, lol. love the cartman!

That would be the classic Left Hand vs. Right Hand coordinate system question. the search terms for that question could also be called Clockwise vs CounterClockwise Culling.  

Default for JME3 is Clockwise Culling(eg it displays all triangles that are counterclockwise), *if I remember correctly*.  That said, it can be set either way that you like by something similar to:
myGeometry.getMaterial().getAdditionalRenderState().setFaceCullMode(RenderState.FaceCullMode.Front);  //or .Back for CounterClockwise Culling or .FrontAndBack if you want to look back and see the back side of what you just went through.... lol.

so your vertices order for default behavior would properly be...
(1,4,5),(1,5,2),(2,5,6),(2,6,3),(4,7,8)....etc. (always counter-clockwise) to display. if the order becomes clockwise, then it becomes culled.

Game On,
Charles Anderson

**Comment by hunterboerner** [comment]
Ok, so it looks like the TerrainQuad ends up telling the terrainpatch to calculate new normals in this method:

```

    /**
     * recalculate all of the normal vectors in this terrain patch
     */
    protected void updateNormals() {
        FloatBuffer newNormalBuffer = geomap.writeNormalArray(null, getWorldScale());
        getMesh().getBuffer(Type.Normal).updateData(newNormalBuffer);
        FloatBuffer newTangentBuffer = null;
        FloatBuffer newBinormalBuffer = null;
        FloatBuffer[] tb = geomap.writeTangentArray(newNormalBuffer, newTangentBuffer, newBinormalBuffer, (FloatBuffer)getMesh().getBuffer(Type.TexCoord).getData(), getWorldScale());
        newTangentBuffer = tb[0];
        newBinormalBuffer = tb[1];
        getMesh().getBuffer(Type.Tangent).updateData(newTangentBuffer);
        getMesh().getBuffer(Type.Binormal).updateData(newBinormalBuffer);
    }
```

What do I need to change to get the right normals needed for flat shading (or am I looking in the wrong place?)?

**Comment by Relic724** [comment]
That code looks to be where they make an allowance for the dynamic vertex adjustment you were wanting for your project.  

What you are looking for are (JME3)Material assignments. It's the shader code that can use/ignore these normals for the look you are wanting.

**Comment by hunterboerner** [comment]
So do I need to mess with the normals or just modify the lighting shaders?

**Comment by Relic724** [comment]
Just modify the lighting shaders.

**Comment by jmaasing** [comment]
Much higher chance of getting an answer if you post these types of questions on the forum rather than using the issue tracker:
http://hub.jmonkeyengine.org/forum/

**Comment by Relic724** [comment]
Indeed, this is a Forum type topic.

**Comment by hunterboerner** [comment]
I can't because the forum won't send me a confirmation email :{

**Comment by Relic724** [comment]
Ok, tell ya what.  just close this as an issue on this site, and you can email me directly at gmail (the suffix being a com and the prefix is relic724) and I'm just typing it out like this to obfuscate against the obvious mail bots that troll the web.  I'm not the forum, but I don't mind assisting folks.  The forum does seem to be a bit wonky since the Server Reset, and I'm throwing my hat into the ring to help fix it.

**Comment by erlend-sh** [comment]
@hunterboerner still having problems? I've found your user on our forum. If you'd like I can manually approve you with a temporary password.

**Comment by hunterboerner** [comment]
That would be helpful. I know Charles said he could help me if I emailed
him but two minds are greater than one.

**Comment by Relic724** [comment]
@erlend-sh oh, and I'm tossing my hat into the ring for assisting with the forum after the server reset incident. you can email me at gmail, my username is the same just all lower case. It's a com, just in case.

I thought it(the forum) would be cleared up by now, but it seems to be taking a bit. I'll help out if you I can be of assistance to speed the recovery. I know the whole php/mySQL/javascript/css pipeline from previous web projects.
