### ISSUE TITLE
jME in Swing Canvas has B and R components switched

### ISSUE THREAD

**Issue by OndrejSpanel** [jMonkeyEngine/jmonkeyengine#206]
I use JME in a Swing canvas for rendering. With recent jME builds the color components B and R are switched. I guess there is some mismatch in BGR / RGB colors - jME and Swing do not agree in current version. Some older communication indicates there was something special done to prevent this:

http://hub.jmonkeyengine.org/forum/topic/jmeswing-color-problems/

> Sorry, it looks right if it is instead:
> 
> BufferedImage.TYPE_INT_BGR
...
> we have a valid image from OpenGL, just not getting it to Swing with colors in the format Swing wants. What you’re proposing would do it (it sounds like) but we can use GL12.BGRA

The problem shows since commit

> Revision: d3258429ec1e648c75d7c926bad1d60becc55b0d
> Date: 6.12.2014 4:36:55
> Message:
> Use unified renderer architecture for LWJGL by default (other backends pending)

Previous commits are fine.

I might be able to create a small self contained example demonstrating the problem, but given my Swing application is in Scala and quite large, it may need some effort (and time).

My jME - Swing integration is done as described in http://hub.jmonkeyengine.org/wiki/doku.php/jme3:advanced:swing_canvas

**Comment by normen** [comment]
Thanks for the info. Note that for production use you should resort to the 3.0 stable build, the master branch is NOT to be used for anything but testing and WILL break constantly.

**Comment by OndrejSpanel** [comment]
Thanks, yes, I am aware of this and I am not using it for production, I just wanted the developers to be aware of the issue, as I am not sure how frequent is the testing with Swing - I guess not much, as this does not look like a typical usage. I just reported it here so that it does not stay in the 3.1 release

**Comment by normen** [comment]
The SDK uses swing so yes, it is a common use.
