### ISSUE TITLE
Strange jogg issue. Leaking context?

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#2063]
I don't have yet an idea about the cause of this issue nor a test case that is reliable, however, i've found that if this ogg file is loaded in HelloAudio instead of Gun.wav, the app hangs forever.
I've also found what seems to be some sort of context leaking in jogg when building the engine with teavm, as it seems the samplerate (22k) of Gun.ogg is propagated to the ocean wave sound somehow, but this might be unrelated.

The file is attached.
[Gun.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/12361978/Gun.zip)

**Comment by stephengold** [comment]
Probably solved in the "master" branch by f33d4a8172e596e1088b55a92094212d99dc928e
