### ISSUE TITLE
LWJGL 2 threading problem with failed init

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#2077]
Take a look what happens in:
https://hub.jmonkeyengine.org/t/help-with-jme-v3-6-1-stable-sdk3-assetbrowser-alpha/47140

Obviously the initialization fails and there is very little that we can do about that. But if we can handle that error more gracefully, it would be great. I'm talking about the failed synchronization that happens here:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglAbstractDisplay.java#L135

Need to create an error from similar source seen on the hub post. And see if adding sync block is enough or does that result in dead lock etc.

**Comment by stephengold** [comment]
Between v3.5.2 and v3.6.0, JME switched from the ancient LWJGL v2.9.3 to our own in-house LWJGL v2.9.5
The good news is that there weren't many changes between 2.9.3 and 2.9.5.
I'm curious whether this issue can be reproduced using JME v3.6.0 with LWJGL forced to v2.9.3

**Comment by tonihele** [comment]
> Between v3.5.2 and v3.6.0, JME switched from the ancient LWJGL v2.9.3 to our own in-house LWJGL v2.9.5 The good news is that there weren't many changes between 2.9.3 and 2.9.5. I'm curious whether this issue can be reproduced using JME v3.6.0 with LWJGL forced to v2.9.3

I don't think this matters. The problem described in the forum is just because the graphics adapter does not support OpenGL extensions needed for the init. So everything is normal in that regard. Basically the forum poster just downgraded the default OpenGL renderer version (which was changed in jME 3.6) and that fixed it.

So this ticket is only about the code line mentioned. The code line can never work. And as such it should be fixed. 

The rationale is that when this unexpected event happens, it is even more confusing when another (trivial coding error) exception is added to the stack.

**Comment by tonihele** [comment]
I can take a stab at this at some point. If it is really as trivial as I assume, the fix is just 2 lines of code.
