### ISSUE TITLE
jme3-plugins imports EmissiveStrengthTest incorrectly

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#2085]
I noticed a defect in GltfLoader while developing the MonkeyWrench library.

The test data is [EmissiveStrengthTest from Khronos's glTF sample models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/EmissiveStrengthTest). The model includes 5 colored cubes, each with a different emissive strength.

Here's how it looks in CompareLoaders when "EmissiveStrengthTest/glTF/EmissiveStrengthTest.gltf" is loaded using jme3-plugins:
![EmissiveStrength-231008](https://github.com/jMonkeyEngine/jmonkeyengine/assets/2287609/9b57d56b-8f2a-4a9e-89cc-3d6ee099dca3)

Please compare the screenshot embedded above with the image from the Khronos repo: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/EmissiveStrengthTest/screenshot/screenshot_large_plain.jpg

The cubes are supposed to be rendered in different hues.

Preliminary investigation revealed that GltfLoader created a distinct PBR material for each cube, but all the materials have identical parameters, including "EmissiveIntensity" of 2. In order to render properly, some of the cubes should have different values for the "EmissiveIntensity" material parameter, including 4, 8, and 16.

**Comment by stephengold** [comment]
Forgot to mention:  `GltfLoader` produces diagnostic messages on this asset:
```console
Oct 08, 2023 4:52:17 PM com.jme3.scene.plugins.gltf.CustomContentManager readExtension
WARNING: Could not find loader for extension KHR_materials_emissive_strength
Oct 08, 2023 4:52:17 PM com.jme3.scene.plugins.gltf.CustomContentManager readExtension
WARNING: Could not find loader for extension KHR_materials_emissive_strength
Oct 08, 2023 4:52:17 PM com.jme3.scene.plugins.gltf.CustomContentManager readExtension
WARNING: Could not find loader for extension KHR_materials_emissive_strength
Oct 08, 2023 4:52:17 PM com.jme3.scene.plugins.gltf.CustomContentManager readExtension
WARNING: Could not find loader for extension KHR_materials_emissive_strength
```

**Comment by stephengold** [comment]
I verified the fix in `CompareLoaders` using a snapshot build of JME (Git hash 88813e2).
It looks great!
Thank you @codex128 for the fix.

**Comment by stephengold** [comment]
I took another, closer look at EmissiveStrengthTest at Git hash cf74247, with PR #2088 applied.

It now seems to me that the leftmost cube (the one with the "Emit1" material) isn't as intensely blue as it appears in [the "Plain Rendering" screenshot](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/EmissiveStrengthTest/screenshot/screenshot_large_plain.jpg).

Analyzing the imported model, I see the "EmissiveIntensity" is set to `2` in the "Emit1" material. I believe that ought to be `1`. Looking at the code, however, I don't see why.

@codex128 could you take another look at the EmissiveStrengthTest?

**Comment by codex128** [comment]
Oh, sorry, saw this just now!

Sure, I'll take another peek at it, although I don't remember much of the details.

**Comment by codex128** [comment]
[PBRLighting](https://github.com/jMonkeyEngine/jmonkeyengine/blob/b5754e8f3dc83f1eeb41e7a987d42ba816e656f8/jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md#L19-L20) uses a default of 2 on EmissiveIntensity. The [gltf test model](https://github.com/KhronosGroup/glTF-Sample-Models/blob/1f5e8c3b01f6c49d9f3abaf778cca559d2f95f7b/2.0/EmissiveStrengthTest/glTF/EmissiveStrengthTest.gltf#L123) does not specify an emissive strength value for material "Emit1" (which I'm guessing is the problematic material), because it expects the gltf default value of 1, except we're providing 2 as the default.

Since the default of value 2 seems to be working as expected elsewhere, changing the default to 1 would likely break a lot of things. Someone who understands the emission calculations in the shader should look into this.

**Comment by stephengold** [comment]
@codex128:
The KHR_materials_emissive_strength extension to glTF defines the default value to be 1.0:

https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_emissive_strength/README.md#parameters

Since our PBRLighting.j3md material uses a different default, jme3-plugins ought to set the strength to 1.0 if the model doesn't specify the strength. Last I checked, it wasn't doing this.

**Comment by codex128** [comment]
Oh, yeah, sorry :stuck_out_tongue:
I've submitted #2163 that should fix this.

![](https://github.com/codex128/ImageUpload/blob/master/emissive-test-result.png?raw=true)
