### ISSUE TITLE
NoClassDefFoundError when launching the generated jar test launcher

### ISSUE THREAD

**Issue by zzuegg** [jMonkeyEngine/jmonkeyengine#2096]
All works fine if i start the test chooser trough gradle run. 
When starting the jar created by gradle dist it results in an error:
`Uncaught exception thrown in Thread[#56,jME3 Main,6,main]
NoClassDefFoundError: com/jme3/plugins/json/JsonElement`

same error when launching with java -jar

**Comment by stephengold** [comment]
I suspect this is due to a missing dependency in "jme3-examples/build.gradle", probably "jme3-plugins-json" .

**Comment by zzuegg** [comment]
Would it then, not have the same error when launch with the gradle run? 
I have checked, and jme3-plugins-json is not added to the lib folder, i am suspecting the cause in the task dist at the artifact resolving/copying. But i am not good at this
