### ISSUE TITLE
SDK 3.0 - IDE null pointer exception attempting to open .j3m file

### ISSUE THREAD

**Issue by wcomohundro** [jMonkeyEngine/jmonkeyengine#210]
I have recently installed SDK 3.0 (Windows 7, 64 bit) and am fully up-to-date (as far as I can tell).  When attempting to double click on any .j3m file to open it in the IDE, a null-pointer exception is thrown from     com.jme3.gde.materials.EditableMaterialFile.initMatDef#189

I don't know if this is related, but if I try to open any .xml file, the IDE just beeps and does nothing.

**Comment by normen** [comment]
I guess you don't keep your j3m files in the assets folder.

**Comment by wcomohundro** [comment]
I am just learning jMonkey and poke into odd corners a lot.  In this particular case, I was trying to open files from within jME3-testdata.jar

I can open other types of files from within a jar.  Are .j3m and .xml files different/special ?

**Comment by normen** [comment]
Please use the forum at hub.jmonkeyengine.org for generic beginner questions.

**Comment by wcomohundro** [comment]
If I had not seen the null-pointer exception, I would not have reported this as a bug.
I would not expect a simple double-click anywhere in the IDE to throw an internal exception.

Thanks for the quick response.

**Comment by normen** [comment]
It probably shouldn't but it wouldn't open anything either.
