### ISSUE TITLE
LodGenerator: null in returning VertexBuffer.

### ISSUE THREAD

**Issue by MelVimL** [jMonkeyEngine/jmonkeyengine#2114]
During prepeartions for Issue #751 I found a Bug.
The result array can have "null" elements in it. The LodGenerator counts the successfully computed lods(`bakedLods`), failed Lods are stored as **null** in `lods.` 
In the end the lods coppied to the result:

`System.arraycopy(lods, 0, bakedLods, 0, numBakedLods);
return bakedLods;`

The Bug happens when lods in between failed so an null get copied.

![grafik](https://github.com/jMonkeyEngine/jmonkeyengine/assets/51533828/0feb551a-5a87-450f-9eb8-bb61ce796740)

How to reproduce:

```
   float[] REDUCTION_VALUES = { 0.5f, 0.55f, 0.6f, 0.65f, 0.7f, 0.75f, 0.80f };
   @Test
   public void testSphereReductionCollapsCost() {
        LodGenerator lod = new LodGenerator(sphere()); // sphere() -> new Sphere(12, 12, 1, false, false);
        VertexBuffer[] buffer = lod.computeLods(LodGenerator.TriangleReductionMethod.COLLAPSE_COST, REDUCTION_VALUES);
        
        int[] expected = { ... };
        int[] actual = getBufferSizes(buffer);  // Generates a List of buffer sizes.
        assertArrayEquals(expected, actual );

```

**Comment by riccardobl** [comment]
Are you working on submitting a patch for this?
If i understand the issue correctly, we just need to replace System.arraycopy with a manual copy that filters out nulls. Is that right?

**Comment by MelVimL** [comment]
Yes but I work currently on a refactoring of the LodGenerator. 
It looks like this bug get fixed by it but I am not sure how long it will take me to finish it. 

But if its easier I can create a pull request with the fix amd tests now I would do it.

**Comment by riccardobl** [comment]
Thank you for the patch @MelVimL
