### ISSUE TITLE
Missing accessor restricts extending AbstractShadowRenderer

### ISSUE THREAD

**Issue by jayfella** [jMonkeyEngine/jmonkeyengine#212]
the following line: https://github.com/jMonkeyEngine/jmonkeyengine/blob/6e287d0ef2d619c62524ae5245721d490b168cd7/jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java#L467

is missing the "protected" accessor  and therefore does not allow extending the class as shown here: http://puu.sh/ffqO9/b4eff5593b.png

**Comment by Nehon** [comment]
fixed 
see https://github.com/jMonkeyEngine/jmonkeyengine/commit/dca050b96b4e93b79dcc261f52c3436c11152a35
