### ISSUE TITLE
CrossHatchFilter: read/write methods are missing

### ISSUE THREAD

**Issue by capdevon** [jMonkeyEngine/jmonkeyengine#2169]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-effects/src/main/java/com/jme3/post/filters/CrossHatchFilter.java

The filter does not implement the `Savable.read()` and `Savable.write()` methods, so you cannot save and load configuration properties.

I do not have the source code locally. Anyone who can submit a PR is welcome.

**Comment by stephengold** [comment]
Good catch!

**Comment by stephengold** [comment]
Oops! Instead of creating a pull request, I accidentally committed the fix directly to "master".
If this causes any issues, let me know, and I'll try to solve them.

Fixed in "master" branch at Git hash d4e8df52f3d695ff953664db92a876d17df40511.
