### ISSUE TITLE
Not compatible with gradle 2.3

### ISSUE THREAD

**Issue by empirephoenix** [jMonkeyEngine/jmonkeyengine#221]
The current JME build is not compatible with gradle 2.3 this is not a real serious problem due to gradlew.

Making the compability is also not a very easy task, as the complete spec for native librarys changed the definition.
https://gradle.org/docs/2.3/release-notes#major-changes-to-incubating-'native-component'-and-'jvm-component'-plugins
If we ever in the future switch to a newer gradle version, this needs to be adressed, untill then its fine.
- Where:
  Build file '/home/empire/workspace/jmetess/jme3-bullet-native/build.gradle' line: 14
- What went wrong:
  A problem occurred evaluating project ':jme3-bullet-native'.
  
  > Could not find method libraries() for arguments [build_6jpyhlbugnd9xy7jl7svlcn3m$_run_closure2@730bea0] on project ':jme3-bullet-native'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.383 secs
empire-z86 [gradle tasks] ~/workspace/jmetess  
empire-z86% gradle -version

---
## Gradle 2.3

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_31 (Oracle Corporation 25.31-b07)
OS:           Linux 3.18.6-1-ARCH amd64

**Comment by shadowislord** [comment]
Already fixed in 3.1/3.2
