### ISSUE TITLE
How to convert gltf format containing animation to j3o format?

### ISSUE THREAD

**Issue by xxlwanmm** [jMonkeyEngine/jmonkeyengine#2216]
When I use JME SDK, I want to convert the gltf format file containing animation into j3o format, but an error occurs during the conversion : "JME only supports linear interpolation for animations". 
Can anyone help me? How to convert gltf format containing animation to j3o format?

**Comment by stephengold** [comment]
This is a bug tracker. You'll be more likely to get a timely solution to your issue if you join [the JMonkeyEngine discord hub/forum](https://hub.jmonkeyengine.org/) and post your question there.
