### ISSUE TITLE
Camera pointing in wrong direction on/after initialization

### ISSUE THREAD

**Issue by codex128** [jMonkeyEngine/jmonkeyengine#2242]
I've noticed a small regression with 3.7alpha. The default application camera can no longer be configured to face a certain direction during initialization. It always reverts to pointing a different direction afterward.

**Comment by stephengold** [comment]
I'm unsure what you're talking about. Could you be more specific about "certain direction" and "during initialization"? Could you provide a small test app that demonstrates the issue?

**Comment by codex128** [comment]
Sorry, my bad, I am unable to reproduce the issue anymore. :sweat:
