### ISSUE TITLE
Occasionally spatial#collideWith will claim a collision is at infinite distance

### ISSUE THREAD

**Issue by richardTingle** [jMonkeyEngine/jmonkeyengine#2284]
Occasionally spatial#collideWith will return a collision result with the distance at infinity. I suspect this occurs because in [BIHNode](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/collision/bih/BIHNode.java#L400) the "hits" check is done in local coordinate space then done a second time in world space and numerical precision leads to the two having different answers.

My proposal is to include a second world-space isFinite test before committing the collision

Discussed at https://hub.jmonkeyengine.org/t/picking-sometimes-returns-infinite-distances/47715/2

**Comment by stephengold** [comment]
Not yet integrated into v3.7 branch, so not included in v3.7.0-stable.
