### ISSUE TITLE
BatchNode can throw IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jcfandino** [jMonkeyEngine/jmonkeyengine#2296]
There are temporary arrays that are reused to work with vertex buffers.
Some conditions cause the index to be used for storing more vertices that they can hold and this throws the exception.

A proposed solution is to validates the arrays' size before accessing them, recreating the arrays if they are too small.

I commented this in more detail in the hub: https://hub.jmonkeyengine.org/t/batchnode-and-indexoutofboundsexception/47766

**Comment by stephengold** [comment]
@jcfandino Thank you for documenting the issue (and submitting a fix).
