### ISSUE TITLE
jme-angle submodule causes git failures at GitHub Actions

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#2320]
I recently noticed that most of the GitHub Actions CI jobs are generating warnings during the "Post clone the repo" step:
```console
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
fatal: No url found for submodule path 'jme-angle/src/native/angle' in .gitmodules
Warning: The process '/usr/bin/git' failed with exit code 128
```

Since it's just a warning, it doesn't cause CI builds to fail.

I was curious what the "jme-angle" submodule is for. It was introduced by PR #1782, but I don't understand why. @riccardobl can you explain please?

**Comment by riccardobl** [comment]
You are right, it was part of an attempt to port jme to google angle, but it is not used, it was pushed by mistake. Should be removed

**Comment by stephengold** [comment]
I'll take care of it.
