### ISSUE TITLE
TestPostFiltersCompositing is not working properly

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#246]
Seems that setting the a background color in the gui node with a 0 alpha value doesn't result in a 0 value alpha in the texture when using a FPP in the guiNode.
Maybe something die to the FPP texture format used.

**Comment by shadowislord** [comment]
When using an HDR format, alpha is not available in any of the framebuffer textures. Normally alpha should not be required, and it does not really make any sense in the context of a post-processing system.

**Comment by Nehon** [comment]
Well it was making sense for this test case.... I agree it's not the most common case though.

**Comment by Nehon** [comment]
duplicate of https://github.com/jMonkeyEngine/jmonkeyengine/issues/492
