### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by hurzl** [jMonkeyEngine/jmonkeyengine#249]
You say it's pure java, so why the different OS downloads and where are the tags the downloads are built from?

**Comment by Nehon** [comment]
Please posts your questions on the forum http://hub.jmonkeyengine.org/

We package the engine with a SDK based on Netbeans and it comes with an installer. hence the different OS downloads.

The downloads are build from the 3.0 branch (latest is 3.0.10)

**Comment by hurzl** [comment]
The forum is hardly readable because it has almost the same colour for back- and foreground.

Branch 3.0 doesn't have a build.gradle. I get an error herer
``` ..../engine/src/networking/com/jme3/network/kernel/udp/UdpEndpoint.java:130: error: exception IOException is never thrown in body of corresponding try statement
    [javac]         } catch( IOException e ) {
    [javac]           ^
```
When I run gradle build on master I get changed files like project.xml, project.properties. Shouldn't these probably be taken out from git?
What do I have to run after I have built with gradle?

**Comment by gouessej** [comment]
@hurzl Which version of OpenJDK do you use?

**Comment by gouessej** [comment]
This bug is fixed on master: https://github.com/jMonkeyEngine/jmonkeyengine/commit/f31911f039743cc8121cf02899dbc37456e58a1d

**Comment by hurzl** [comment]
1.8

**Comment by Nehon** [comment]
"The forum is hardly readable because it has almost the same colour for back- and foreground."
Well the forum doesn't send me a mail each time someone posts.
This is an issue tracker, not a chat.

You'd get more people to answer these questions on the forum forum anyway.
If you have trouble to read it, tweak you monitor contrast.

**Comment by hurzl** [comment]
These are issues. And if you don't want to get emails you can set this in github.

**Comment by pspeed42** [comment]
Please fix your browser and post support questions on the forum.

**Comment by hurzl** [comment]
What's to fix in my browser?

**Comment by pspeed42** [comment]
Well, you are so far the only one who has been unable to read the forum... so I suspect your browser or your system is misconfigured in some way.  In case it's a browser problem, here is how the colors look to everyone else:  http://i.imgur.com/KTiE0zW.png

**Comment by hurzl** [comment]
Yes, that's what I mean by unreadable.

**Comment by pspeed42** [comment]
Well, if that's still a problem then it might be settings on your monitor or perhaps there is an issue with your eyes or something.  As that is perfectly readable to me and I'm generally the first to complain about such things.

Try adjusting the contrast on your monitor to normal human levels.

**Comment by hurzl** [comment]
I wonder why usually text is black on white or white on black to get the best contrast possible. There might be a reason for that. Maybe black ink was invented for readability.
My monitor is at a human level. Setting it so that I can read 171 on 56 is totally inhuman.

**Comment by pspeed42** [comment]
Paper doesn't shine in our eyes.  Too much contrast makes things less readable, not more.

You are the first human to have complained so far.  There must be half the web you have problems reading.

**Comment by jayfella** [comment]
Please - I'm getting email bombed and it has absolutely nothing to do with the engine itself. If you have any questions, please use the forum. This is not the place to do so, and I ask politely that we please continue the discussion there.

**Comment by empirephoenix** [comment]
So no more notifications. #pissed
