### ISSUE TITLE
TangentBinormalGenerator fails with simple Box

### ISSUE THREAD

**Issue by wcomohundro** [jMonkeyEngine/jmonkeyengine#252]
Applying TangetBinormalGenerator.generate( someSimpleBox ) produces Warning messages "Normal and tangent are parallel for vertex ..." for 8 different vertices.  This results in a cube with 2 faces that just disappear if no Ambient light is provided.  Include the ambient light in the test case below to see that the faces are there and have a texture, but the red PointLight for the 2 faces is gone.

        Box aBox = new Box(1,1,1);
        Geometry aGeometry = new Geometry( "Box", aBox );
        TangentBinormalGenerator.generate( aBox );
        
        Material aMaterial = new Material(assetManager, "Common/MatDefs/Light/Lighting.j3md");
        aMaterial.setTexture( "DiffuseMap", 
                assetManager.loadTexture("Textures/Terrain/BrickWall/BrickWall.jpg") );
        aMaterial.setTexture( "NormalMap", 
                assetManager.loadTexture( "Textures/Terrain/BrickWall/BrickWall_normal.jpg") );
        aMaterial.setBoolean( "UseMaterialColors", false );    
        aMaterial.setColor( "Diffuse",ColorRGBA.White );
        aMaterial.setColor( "Specular",ColorRGBA.White );
        aMaterial.setFloat( "Shininess", 64f );
        aGeometry.setMaterial( aMaterial );
        
        // Rotate 45 degrees to see multiple faces
        aGeometry.rotate( FastMath.QUARTER_PI, FastMath.QUARTER_PI, 0.0f );
        rootNode.attachChild( aGeometry );
         
        /** Must add a light to make the lit object visible! */
        PointLight aLight = new PointLight();
        aLight.setPosition( new Vector3f(0,3,3) );
        aLight.setColor( ColorRGBA.Red );
        rootNode.addLight( aLight );
        
        if ( false ) {
        	AmbientLight bLight = new AmbientLight();
        	bLight.setColor( ColorRGBA.Gray );
        	rootNode.addLight( bLight ); 
        }

I am doing a lot of experimenting with CSG which means my meshes are produced programmatically so I have to rely on the generator if I want Normal based lighting to work.  I do not understand the generator code well enough to fix it, but a hack that forces a non-zero tangent to be produced in the warning condition at least keeps my cube faces visible.

**Comment by empirephoenix** [comment]
Hm yeah i guess it is a problem.

If there are flat shaded objects the normals are of course parallel. Combined with the fact that the Box itself has already  tangent buffer kinda hints to this case not being handled correctly.

Expected result would be to get the exact same buffer that was there originally i think.

**Comment by Nehon** [comment]
Actually, that was a big bug in the tangent generator.
Thanks for this issue because it allowed me to find it.

Here is what the cube looks like now with your test case 
http://i.imgur.com/zNnLbnL.png

Here is what the weird guy looks like
http://i.imgur.com/ZUVaqBo.png
Normals are right and there is no seam.

Here is the fix : 
https://github.com/jMonkeyEngine/jmonkeyengine/commit/95d5fdf9c5b45f1bbd4d52e8e2a17f21ad03faa5
As you can see it was a very dumb issue. When computing tangent Normal and binormal with the tempVars the result was not cloned. Meaning we kept the tempVars reference, taht were modified later on....
Nasty.
