### ISSUE TITLE
BlenderLoader TextureKeys

### ISSUE THREAD

**Issue by empirephoenix** [jMonkeyEngine/jmonkeyengine#253]
Remove commit:
https://github.com/jMonkeyEngine/jmonkeyengine/commit/9f32bcf7bb116afcfcc8bcacd3bdfbdc18fb2bf0
when resolved.

The current blenderloader produces null TextureKeys, resulting in embedded Textures and unexpected behaviour. This hackfix supresses this, but should be removed as soon as possible.

The base problem is, that in the loaded features of the blenderloader the original Texturekey is not stored, but only the image, so in the shortpath version using the already loaded files, they key in the texture is not properly restored.

**Comment by shadowislord** [comment]
Why not just use Texture.setKey()? All other loaders already do this.

**Comment by empirephoenix** [comment]
Because there is no TextureKey at the point anymore, and I did not want to introduce larger changes to his code :)

**Comment by stephengold** [comment]
Since jme3-blender was removed from the Engine on 19 April 2020, this issue is now moot.
