### ISSUE TITLE
Typo in RigidBodyControl Javadoc

### ISSUE THREAD

**Issue by Turakar** [jMonkeyEngine/jmonkeyengine#258]
Hello, I've just found a small fault: You have a typo in the Javadoc of the RigidBodyControl.setApplyPhysicsLocal(boolean) method. There's "traslation" instead of "tra*n*slation".

http://javadoc.jmonkeyengine.org/com/jme3/bullet/control/RigidBodyControl.html#setApplyPhysicsLocal%28boolean%29

**Comment by erlend-sh** [comment]
Make a quick pull request for it and we'll merge it :)
