### ISSUE TITLE
Create on-site demos

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#26]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=327

**Comment by empirephoenix** [comment]
Since both proposed ways, applets and webstart are kinda dead, this is dead as well.

The next closest thing, aka youtube videos are there.

**Comment by gouessej** [comment]
Why not using the native packager of JMonkeyEngine, PackR or JNDT to make a simple installer to run a few demos instead of using applets and webstart which have effectively become unusable?

**Comment by shadowislord** [comment]
The jME distribution package includes a TestChooser application.
I just noticed the alpha1 release is missing the distribution package, which is strange, because the build server was supposed to upload is automatically...

**Comment by erlend-sh** [comment]
I like @gouessej's idea of making a standalone TestChooser demo application though, as an alternative to the bundled app.
