### ISSUE TITLE
Contributor guidelines incorrectly state that eGit (Eclipse Git) does not support HTTPS

### ISSUE THREAD

**Issue by Sleaker** [jMonkeyEngine/jmonkeyengine#265]
Eclipse eGit definitely supports HTTPS and has supported HTTPS ever since it was built.  I have never had problems using github, or git repositories with HTTPS and eGit.  The contributor documentation should be changed to remove this inaccuracy.  If someone is having problems with HTTPS and eGit then it is an issue with their setups.  If there are instructions actually necessary for Eclipse beyond what is there I can help provide them.

**Comment by Nehon** [comment]
Fixed the contributor doc
