### ISSUE TITLE
NetBeans SDK Crashes When Loading Specific Image Terrain

### ISSUE THREAD

**Issue by john01dav** [jMonkeyEngine/jmonkeyengine#270]
**NOTE:**
Hello JME3! I wasn't really sure what project to place this in since there is no project for the IDE/SDK, but I think this project best fits. Please feel free to let me know where it should go if not here and I can repost it. 

**What did you intend to do, what was the expected outcome?**
I intended to import a heightmap (the one attached) into JME3. I expected it to work.

**What outcome do you experience instead?**
It failed for an unknown reason. However, it does appear to work in other projects in the SDK.

**What steps will reproduce the problem?**
I imported the attached heightmap into JME3 via the Image Terrain option in the Scene Design view. Once I had entered all of the values into the wizard and told it to begin the process, it appears to begin but then the SDK suddenly closes with the error at the end of this issue post.

**Software Configuration:**
Product Version: jMonkeyEngine SDK 3.0
Updates: Updates available
Java: 1.7.0_51; Java HotSpot(TM) 64-Bit Server VM 24.51-b03
Runtime: Java(TM) SE Runtime Environment 1.7.0_51-b13
System: Linux version 3.19.5-200.fc21.x86_64 running on amd64; UTF-8; en_US (jmonkeyplatform)
User directory: /home/<removed>/.jmonkeyplatform/3.0
Cache directory: /home/<removed>/.jmonkeyplatform/3.0/var/cache

**Hardware Configuration:**
CPU: Amd FX-8350, default clock speed (4GHZ)
GPU: Nvidia MSI GTX 770
Motherboard: Gigabyte 990FXA-UD3
Ram: 8GB (total, not allocated, I don't know how much JME3 has)

**Console Output:**
```
OGL: Throttling update loop.
EDT: addNotify
OGL: Enter showing state.
OGL: Visible. Create strategy.
OGL: Ceased throttling update loop.
EDT: componentResized 926, 612
############ Wizard panel listener added: org.openide.util.WeakListenerImpl$Change[org.openide.WizardDescriptor$Listener]

(java:12924): Gdk-ERROR **: The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 34340 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
````

**Heightmap:**
![islandtest](https://cloud.githubusercontent.com/assets/3982497/7486177/d006f872-f366-11e4-8ee7-a50770014c23.png)

**Comment by grizeldi** [comment]
@john01dav does this still hapen in the latest version?

**Comment by MeFisto94** [comment]
I'm moving this to the SDK Repo :)
