### ISSUE TITLE
SimpleBatchNode does not recalculate the BoundingVolume

### ISSUE THREAD

**Issue by zzuegg** [jMonkeyEngine/jmonkeyengine#275]
Bug occurs only if you never modify a sub item that was batched. 

All ok, if updateGeometricState gets called manually, or when a control is added to one of the sub items.

Here is a small testcase:

https://gist.github.com/zzuegg/43b2697d14913e679975

**Comment by zzuegg** [comment]
Same issue with regular BatchNode.java

**Comment by Nehon** [comment]
OK this one is fixed. Thanks for the test case
