### ISSUE TITLE
SDK Menu at wrong position (Ubuntu Gnome)

### ISSUE THREAD

**Issue by jonnius** [jMonkeyEngine/jmonkeyengine#278]
I just installed the jMonkeyEngine SDK 3.0. Apart from that it looks really ugly (like in the 90s) in contrast to screenshots I have seen, the Menu is quasi not usable. When I click on an item (e.g. "file"), the menu is shown at a wrong position, as you can see in the picture below. 
![jmonkeyengine sdk](https://cloud.githubusercontent.com/assets/4456588/7803756/0ee0f2ce-032e-11e5-8d1a-3ba1b5f827cb.png)
It is beeing showed at exact the same position as on the first start of jMonkeyEngine SDK when it has not been maximized. But regardless of how I resize the window or restart the program, the menu will always be shown at that position.

**Comment by Nehon** [comment]
What Operating System are you on?

**Comment by iamcreasy** [comment]
info: jMP menus look fine on Ubuntu 14.04 with Unity.

**Comment by jonnius** [comment]
I am on Ubuntu Gnome 15.04 with Gnome 3.14.

**Comment by kles4enko** [comment]
@jonnius Hello!
I used the same OS. The root cause in OpenJDK. Please, replace it, install OracleJDK  - everything will be ok!
FYI: Java PPA
https://launchpad.net/~webupd8team/+archive/ubuntu/java

**Comment by normen** [comment]
The SDK comes with a bundled Oracle JDK, the system JDK is not used (unless you changed the config file or run your own build). Did you look at this? http://wiki.jmonkeyengine.org/doku.php/sdk:troubleshooting

**Comment by jonnius** [comment]
I solveld the problem. According to http://wiki.jmonkeyengine.org/doku.php/sdk:troubleshooting the setting jdkhome="jdk" should have been a comment by default, but it was not. I set an # to make it a comment and now it is working fine.

**Comment by normen** [comment]
What you did by doing that is make the SDK use the system-installed JDK.

**Comment by jonnius** [comment]
So the problem is not solved. But a workaround is to use system-installed JDK, in my case it is OpenJDK 8.

**Comment by normen** [comment]
The problem is the system LAF.

**Comment by jonnius** [comment]
No it is not. Changing the LAF did not solve the problem.
