### ISSUE TITLE
Parallax doesn't work with PBRLighting

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#280]
The parallax in PBRLighting is broken.
See http://hub.jmonkeyengine.org/t/parallax-and-pbr-in-jme-3-1/32500 and https://github.com/jMonkeyEngine/jmonkeyengine/pull/279

**Comment by Nehon** [comment]
Thanks ;)

**Comment by Nehon** [comment]
done in https://github.com/jMonkeyEngine/jmonkeyengine/commit/719a683c2c037f8f342acaa2ab15603e7c790c91
