### ISSUE TITLE
Broken Spec/Gloss pipeline in PBRLighting

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#281]
I think there is a missing .r  (||b||g)  in PBRLighting.frag at row 170
`Roughness = 1.0 - texture2D(m_GlossMap, newTexCoord)>>>>>here<<<<<;`

**Comment by Nehon** [comment]
true!
will fix it thanks

**Comment by Nehon** [comment]
Finally got to this.
Thank you.
