### ISSUE TITLE
Alpha problem in PBRLighting

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#283]
Since BaseColor's default value is (0,0,0,0) the gl_FragColor.a by default is equal to 0 and everything works fine, but if the BaseColor's alpha is setted to 1 the fragments where the resulting alpha is 1 look overbright.
See images below.

With gl_FragColor.a = 1
![sddafdaadf26](https://cloud.githubusercontent.com/assets/4943530/7879175/574f7496-05ee-11e5-854b-e7af93c84aed.png)

With gl_FragColor.a = 0
![sddafdaadf27](https://cloud.githubusercontent.com/assets/4943530/7879177/585bab5c-05ee-11e5-9a75-a30fb001d937.png)

(The geometries shown in those screens are in the Opaque bucket and their texture has alpha = 1)

**Comment by Nehon** [comment]
Hello, I can't reproduce this issue on my side.
I have someone else reporting this kind of issue (at least with this over brightness).
What is your hardware?

**Comment by riccardobl** [comment]
amd r9 270x with catalyst drivers on linux.
I just noticed they released a new version of them, i will update to it and see if something changes .

**Comment by riccardobl** [comment]
Sorry for the delay.
I am still investigating, but I think I've found the problem: the scene (made w/ blender) was actually over bright but when the pbr's resulting alpha is 0, the additional light is somehow removed (?).
Tell me if that makes sense to you, because I don't know how lights are managed in the engine.
