### ISSUE TITLE
Remove Caching .blend's (In BlenderModelImporter)

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#285]
Hey Guys,
This is just a little enhancement:
During my workflow I had to restart the sdk a thousand times, because each time I made a change to my blend file, I could not reimport it because the AssetLoader used the cached file.

What do you think? Should we (if possible?) remove caching for all blend files in general or only in BlenderModelImporter?

If someone would use a blender loader in his app, he would use the spatial multiple times, but not load it again. That would be a code-design fault then, anyway.

**Comment by normen** [comment]
Theres mechanisms in place to clear the asset cache already.

**Comment by normen** [comment]
How do you import your file anyway? Best way would be to simply keep your .blend file in the assets folder directly (as described in the manual). When you then right-click it and select "convert to j3o" the cache is definitely cleared each time. For the model import tool its true that the cache isn't cleared atm though, gonna fix that.

**Comment by normen** [comment]
Fixed in #ceb45ff

**Comment by MeFisto94** [comment]
I imported them using the ModelImporter-Plugin as I can preview If everything went fine and such.
Thank you for that fix :)

PS: hurry up with making 3.1 stable ;)
