### ISSUE TITLE
There are no locators currently registered

### ISSUE THREAD

**Issue by Aidamina** [jMonkeyEngine/jmonkeyengine#286]
I have a small application that uses the android system to render a scene. When I run it standalone. (Register the activity that extends AndroidHarness as Main) everything works as expected. When I launch that same activity with an intent from another activity within the same application I get a "AssetNotFoundException". As well as a warning "There are no locators currently registered". 

Ive been trying to track down the issue myself. I am thinking it has something todo with the loading of the Android.Cfg file. But I cant for the live of me understand why it works in the first use case, and doesnt in the second.

Anybody have similar experiences with this?

Im working of the trunk btw

**Comment by normen** [comment]
Please use the forum at hub.jmonkeyengine.org for general troubleshooting requests
