### ISSUE TITLE
Add a way to globally set anisotropic filtering value

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#296]
Right now the anisotropic filtering has to be set on each texture.
It's very impractical as you usually want to set it globally.

There should be a way to set the filtering globally in the app settings and then apply this setting each time a texture is loaded.
User should be able to override this setting for a given texture.

**Comment by shadowislord** [comment]
I have this implemented locally. Going to commit it soon ...

**Comment by empirephoenix** [comment]
Adding the ability for a post loading listener to the assetmanager would allow this pretty nice. Also it would allow other but similar stuff. Eg. in games low detail mode, remove all parallax parameters.

**Comment by Nehon** [comment]
That was the recommended way to do it but somehow it doesn't work when you have embeded textures in a j3m file. You receive the events for the material file not for the sub sequent assets loaded with it. Maybe we could just fix that issue.

In anycase, I find it very inconvenient for this particular case of anisotropic filtering. This should really be a global setting.

**Comment by shadowislord** [comment]
This is already fixed
