### ISSUE TITLE
Add new constructors for lights

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#297]
Add the following convenience constructors:
`AmbientLight(ColorRGBA color)`
`DirectionalLight(ColorRGBA color, Vector3f direction)`
`PointLight(ColorRGBA color, Vector3f position)`
`SpotLight(ColorRGBA color, Vector3f position, Vector3f direction, float innerAngle, float outerAngle)`

**Comment by Dokthar** [comment]
Btw adding a cloneForSpatial(Spatial spatial) into the LightControl would be very appreciate into the scene editor.

**Comment by Nehon** [comment]
Please, this is harldy related to the issue.
Create an other issue, and describe it thouroughly.
Thanks

**Comment by pspeed42** [comment]
Not to mention that LightControl already has cloneForSpatial()... so.... yeah, if you do mention this on a forum or a different issue then include exactly what you are talking about at the same time.

**Comment by zzuegg** [comment]
any news on this, there are two PR open for this issue: 306 and 302

**Comment by DannyJo** [comment]
Pull Request #306 resolves this issue.
