### ISSUE TITLE
Split renderer into multiple modules

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#3]
The Renderer class and implementations are becoming more bloated. Since
jME3 does not have RenderStates to encapsulate specific functionality, it
is required to split the renderer into several "modules" which would handle
a specific functionality.

Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=53

**Comment by shadowislord** [comment]
Going to close this since universal renderer architecture makes this much easier to manage.
