### ISSUE TITLE
Site is not working

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#300]
"It's not just you! http://jmonkeyengine.org looks down from here."

A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

**Comment by shadowislord** [comment]
Notifying @kwando @erlend-sh

**Comment by jayfella** [comment]
Just to let you guys know, I put the information on how to contact the server guys on the google docs sheet if I am unavailable.

**Comment by shadowislord** [comment]
Thanks for the fix @kwando
