### ISSUE TITLE
When will 3.1 be available on maven?

### ISSUE THREAD

**Issue by axhm3a** [jMonkeyEngine/jmonkeyengine#307]
Hey Folks,

when will 3.1 Branch be available via maven?

Background: 

`Currently i use gradle / jetbrains ide for multi platform builds. And since i changed from static jar linking to gradle/maven everything has become great and shiny.`

kind regards,

Daniel

**Comment by zzuegg** [comment]
you can easily ise jitpack for private projects in the time until there is a official stable/snapshot release

**Comment by axhm3a** [comment]
Thank you zzuegg!

this solves my issue for now.
