### ISSUE TITLE
LwjglOffscreenBuffer without Pbuffers

### ISSUE THREAD

**Issue by OndrejSpanel** [jMonkeyEngine/jmonkeyengine#310]
`LwjglOffscreenBuffer` currently uses Pbuffers. Unfortunately Pbuffers are not supported by nVidia nSight frame debugger. Would it be possible to implement  `LwjglOffscreenBuffer` using FBO instead?

Would there be some drawbacks / limitations of using FBO?

**Comment by shadowislord** [comment]
LWJGL 2.x does not support creating offscreen contexts without Pbuffers. On the other hand, LWJGL 3.x does support this, so the LWJGL 3.x implementation of OffscreenBuffer would probably use a hidden window opengl context instead of a pbuffer.

**Comment by OndrejSpanel** [comment]
To clarify: I am not requesting anyone to implement this, I intend to try it on my own, I would just be glad if someone more knowledgeable could review my design, so that I do not run into some obstacle I do not currently see.

I have briefly looked at the `OffscreenBuffer` implementation and it seems to me it is implemented on the side of jME, not LWJGL - in the class called `LwjglOffscreenBuffer`. This class is currently using `Pbuffer` object provided by LWGL, but I do not see it using anything more high-level. I would like to create an alternative FBO implementation, but perhaps I am not seeing something which will prevent me to do so? Why is a hidden window needed for FBO? Is it because we need to create a separate context for FBO? Why - I thought compared to `Pbuffer, which requires a separate context, FBO can be used in the normal OpenGL context.

The only  complication I see is the `AwtPanel#drawFrameInThread` accessing the data from another thread, but I think this is solvable by other means than creating a separate context - `glReadPixels` can read data from the rendering thread and byte data can be transferred between threads with some basic synchronization, it is not necessary to share the frame buffer itself.

An advanced alternative could to be use a texture to share data, in which case it would be perhaps possible to avoid glReadPixels completely and to directly render from the texture into the `AWTPanel` - but this is something I am not quite sure about, and perhaps this it is not possible at all.

**Comment by zzuegg** [comment]
Hi, just a quick info input,
-In GLFW a hidden window is required to create a context in the first place
-FBO's are not sharable between contexts since, even the name suggests otherwise, they are not objects

Not sure what you usecase is, but if you only want to render to a FBO for nSight, you probably can create your own, render to that and debug it trough nSight. (Note, i never used nSight, only ApiTrace)

**Comment by shadowislord** [comment]
You need to have an OpenGL context to use OpenGL. An FBO is not an OpenGL context. 
In LWJGL 2.x, three ways were provided for creating an OpenGL context: display, canvas, and pbuffer. In LWJGL 3.x which uses GLFW, there's only one way: creating a window, but that window can be hidden, thus achieving an offscreen OpenGL context.

**Comment by shadowislord** [comment]
This depends on issue #314

**Comment by shadowislord** [comment]
Seems like this is already fixed since we support LWJGL 3.0 with offscreen buffers
