### ISSUE TITLE
jglfont-core.jar is missing in nifty-bundle

### ISSUE THREAD

**Issue by Mordag** [jMonkeyEngine/jmonkeyengine#311]
I am not sure whether this issue has been reported yet, but in the current version (3.0.10) the lib "jglfont-core.jar" is missing in the nifty-bundle. The lib is inside the jmonkeyplattform/libs, but somehow is missing it's connection to the IDE (if you try to add the .jar via "add library" directly from jmonkey). Additional to that, the javadoc is missing.

**Comment by tonihele** [comment]
Ah this is why the batched Nifty doesn't work...
http://hub.jmonkeyengine.org/t/tonegod-vs-niftygui/33317/16?u=tonihele

**Comment by shadowislord** [comment]
Does the issue still occur in 3.1? I thought we defaulted to using the batched renderer in 3.1

**Comment by Mordag** [comment]
I haven't checked this yet, but I thought this still could be an issue in 3.1.
