### ISSUE TITLE
Welcome Screen Says JmonkeyEngine 3.0

### ISSUE THREAD

**Issue by 8Keep** [jMonkeyEngine/jmonkeyengine#318]
![2015-08-21 10_16_57-jmonkeyengine sdk 3 1-alpha1](https://cloud.githubusercontent.com/assets/5598822/9410362/dfdaf4a2-47ed-11e5-8caf-28c77112f676.png)

It says the latest version is 3.0. The output window says the corrent version.

**Comment by shadowislord** [comment]
Hey @jayfella I assigned you to this issue since its happening because the wiki page needs to be updated, but unfortunately we are locked out of the wiki.

**Comment by DannyJo** [comment]
Is it this page?

http://wiki.jmonkeyengine.org/doku.php/sdk:welcome:3_0

**Comment by normen** [comment]
Thats the page, yes. There’ll have to be a new one for the 3.1 SDK and the URL and local content of the „Welcome Plugin“ will have to be adapted. The purpose of that wiki page is basically that we can change it to say „Hey 3.0 user, 3.1 is out, go get it!“. If that wiki page you linked changes the 3.0 SDK will force the welcome window to open when the SDK is started.

**Comment by shadowislord** [comment]
I created a new (mostly) identical page for 3.1. Now only the URL needs to be changed in the SDK plugin.
http://wiki.jmonkeyengine.org/doku.php/sdk:welcome:3_1

**Comment by grizeldi** [comment]
This has been fixed in PR #427.

**Comment by Nehon** [comment]
Yep Thanks
