### ISSUE TITLE
Unable to login into the wiki

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#319]
Currently trying to login into the wiki doesn't work with any user account, it says: "Sorry, username or password was wrong."
Any help would be appreciated.

**Comment by erlend-sh** [comment]
(bleh, forgot that GitHub Issues doesn't accept multiple assignees)

Since @jayfella seems completely occupied for the time being, I think we rely on @kwando to do some detective work on this one :mag:

**Comment by kwando** [comment]
It worked before on our new server?

**Comment by erlend-sh** [comment]
Yep, for quite some time. Jay made a Discourse-DokuWiki login integration which was working fine for a while, but it has now stopped working. My guess is an API change in Discourse is the culprit.

Perhaps the time is ripe to move our docs to Jekyll...

**Comment by erlend-sh** [comment]
Our own API server was down. Turned it back on and wiki logins are working again.

Nice detective work @kwando! :+1:
