### ISSUE TITLE
jmonkey 3.1 native physics bug

### ISSUE THREAD

**Issue by sniper-shot** [jMonkeyEngine/jmonkeyengine#321]
Hi,sorry for my english
When setting the project to use native physics,adding RigidBodyController to a spatial in the scene editor,the loading that spatial and attaching it yo root node,when calling applyForce,applyImpulse,applyTorque or applyTorqueImpulse makes the spatial disapeare,
Replacing the read() and write() functions of bullet PhysicsRigidBody with the read() and write() functions of jbullet PhysicsRigidBody (with some tweaking) solves the problem.
Last,really thanks for this incridible engine

**Comment by normen** [comment]
Please make a more detailed report in the forum at hub.jmonkeyengine.org, preferably with a test case.

**Comment by shadowislord** [comment]
Can you please provide a small test case which reproduces the problem?

**Comment by Dokthar** [comment]
just FYI, the forum thread is :  http://hub.jmonkeyengine.org/t/jmonkey-3-1-native-bullet-bug/33595

**Comment by empirephoenix** [comment]
Short questions, did you test if the rotation/position returned from native code for those affected bodys contains NAN (not a number) floats?

**Comment by stephengold** [comment]
Since native physics was removed from the Engine on 26 February 2021, this issue is now moot.
