### ISSUE TITLE
Blender Loader crashes for files created with Blender 2.75

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#322]
JMonkey's Blender file loader (com.jme3.scene.plugins.blender.BlenderLoader) crashes when trying to load/import files that where saved with Blender 2.75a. The exact same file loads just fine when saved with Blender 2.74. I suspect a change to Blender's file format. Unfortunately the Loader code is too complex for me to understand/fix myself.

Unfortunately I can't provide a minimal test case, as small Blender files tend to work perfectly. And the affected object/meshes that crash the Loader seem to change randomly when saving the file after doing minor changes to it.

Here is a stacktrace:

```
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 92
    at java.util.ArrayList.subListRangeCheck(ArrayList.java:1004)
    at java.util.ArrayList.subList(ArrayList.java:996)
    at com.jme3.scene.plugins.blender.meshes.Face.loadAll(Face.java:487)
    at com.jme3.scene.plugins.blender.meshes.TemporalMesh.<init>(TemporalMesh.java:126)
    at com.jme3.scene.plugins.blender.meshes.TemporalMesh.<init>(TemporalMesh.java:98)
    at com.jme3.scene.plugins.blender.meshes.MeshHelper.toTemporalMesh(MeshHelper.java:119)
    at com.jme3.scene.plugins.blender.objects.ObjectHelper.toObject(ObjectHelper.java:171)
    at com.jme3.scene.plugins.blender.BlenderLoader.load(BlenderLoader.java:104)
    ... 6 more
```

Affected revision: 5570

**Comment by shadowislord** [comment]
@jmekaelthas : do you have any idea why this happens?

**Comment by jmekaelthas** [comment]
@shadowislord  I will take a look at it tomorrow or today in the evening and let you know.

**Comment by jmekaelthas** [comment]
I will need a file where the crash occurs. I tried the simple file loaded from 2.75a and it was fine. I also used more complex model and it was fine as well.

**Comment by slyh80** [comment]
I just created a minimal test case with only 3 meshes. It crashes reproducably when loading it into JMonkey. How can I send you the file?

**Comment by erlend-sh** [comment]
Just upload it on whichever service you prefer, e.g. Google Drive, Dropbox, a personal server etc.

**Comment by slyh80** [comment]
Sure. Here you go:
https://www.dropbox.com/s/1gn0fjchq38m2x4/building-crash-test.blend?dl=0

**Comment by slyh80** [comment]
Maybe this bug also affected earlier versions of blender. I have a relatively complex scene with UV-mapped textures. 3 out of the 50 models have their textures maps slightly scrambled after loaded in JMonkey. In Blender everything look fine; the OGRE loader imported everything fine, too.
As soon as this bug is fixed I'll check again and maybe open a separate issue if this problem consist.

**Comment by jmekaelthas** [comment]
The file has strill the 2.73 version defined in it. I deleted one object, saved it and then reverted the deletion and saved again. This caused the version in the file to be updated to 2.75 and the error disappeared.
I thought it might be a minor issue and I will quick fix it. But this bug will need further investigation. Try the workaround I mentioned and le t me know if it works.

Unfortunately I am not able to work on it at the moment. I am getting married tomorrow and my time rapidly shrinks ;) That is the reason I was quite absent for the last month and a half. 
But I will keep the file and I'll take care of it when I get back home in two weeks ;)

**Comment by slyh80** [comment]
Unfortunately this won't work for me. I created the file by appending(!) some meshes from an existing file to a newly created 2.75 blender file. I then removed one mesh after another until the file finally loaded without an exception in JMonkey. Then I undid the last deletion, saved again and verified that JMonkey now fails to load the file again, which it did. So I basically applied your work-around while creating the file already. ;)

Have a nice wedding and and even nicer honeymoon! :gift:

**Comment by slyh80** [comment]
Please also see the discussion regarding the same topic in the jMonkey forums: http://hub.jmonkeyengine.org/t/we-need-help-maintaining-the-sdk/33724/4

Some users can simply re-save the broken test case and will then have a file that works with jMonkey. After trying out the current test build of Blender 2.76 (from 2015-09-02) I also could save and load my test case and my original more complex scene without errors in jMonkey. So maybe this issue was a Blender bug after all.

I still see incorrectly UV mapped models in jMonkey when directly loading Blender files, though. The same models work correctly when exporting and importing through OGRE. This may indicate an issue either in the Blender loader or Blender itself.  I'll probably create a minimal test case and add a new issue for this.

**Comment by grizeldi** [comment]
We're now at blender 2.79. Why is this still open?

**Comment by MeFisto94** [comment]
Given that re-saving the file in a more recent blender version seems to have solved this issue, I'm going to close this.
