### ISSUE TITLE
Blender loader handles lights incorrectly

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#324]
JMonkey's Blender loader seems to add all lights (and their LightNodes) to the scene's root node instead of their correct position in the scene graph.

Background:
It is possible in Blender to add lights somewhere down in the scene's hierarchy. For example like this:

```
MyScene
   |-- House
        |-- Porch
            |-- SpotLight
            |-- PorchDoor
```

When loading this simple scene using JMonkey's Blender loader, it will add the SpotLight and its LightNode to "MyScene" instead of "Porch". So the scene graph will look something like this in JMonkey:

```
MyScene
   |-- House
        |-- Porch
            |-- PorchDoor
   |-- LightNode (referencing the SpotLight)
   |-- SpotLight
```

The problem is, that the SpotLight will now affect all of the objects in the scene, and not only the Porch as the artist probably wanted it to.
The LightNode which is created for each light in the scene is also attached to the incorrect parent (i.e. the scene's root node).

(Note: The SpotLight is not actually a Node in JMonkey, but is stored inside the lights list of the "parent" node.)

I added a fix/patch below that will create a scene graph like this:

```
MyScene
   |-- House
        |-- Porch
            |-- PorchDoor
            |-- LightNode (referencing the SpotLight)
            |-- SpotLight
```

You may ask yourself why the LightNode now is added to the same parent as the SpotLight. The reason for this is founded in how JMonkey handles lights.

My motivations are as follows:
- When the artist added the light as a child of "Porch", she wanted only the children of "Porch" to receive lighting from the Spotlight. Thus the light has to be added to "Porch". If it was a child of "LightNode" it would only affect the LightNode itself and its children. (So nothing in our example.)
- But: The artist/programmer still expects the LightNode, which was created for the light, to be at the same position as it was in Blender. So if the Porch moved, the light moves with it.
  Makes sense, right?

Disclaimer: I'm by far no expert on lighting in JMonkey and also have no real knowledge of the source code of the Blender loader. So please thoroughly review may changes in the patch below. And please also make sure that the changes make sense according to my explanation above.

I also want to note that Blender completely ignores the position of the light in the scene graph during rendering. When rendering our example scene in Blender, our Spotlight would affect all of the scene and not just the Porch. (I don't know how Blender's game engine would handle the light.) But this is OK for a renderer that supports radiosity etc. I guess.

Here is the patch:

```
Index: BlenderLoader.java
===================================================================
--- BlenderLoader.java  (revision 5566)
+++ BlenderLoader.java  (working copy)
@@ -242,10 +251,8 @@
                 Structure objectStructure = pObject.fetchData().get(0);

                 Object object = objectHelper.toObject(objectStructure, blenderContext);
-                if (object instanceof LightNode) {
-                    result.addLight(((LightNode) object).getLight());// FIXME: check if this is needed !!!
-                    result.attachChild((LightNode) object);
-                } else if (object instanceof Node) {
+
+                if (object instanceof Node) {
                     if (LOGGER.isLoggable(Level.FINE)) {
                         LOGGER.log(Level.FINE, "{0}: {1}--> {2}", new Object[] { ((Node) object).getName(), ((Node) object).getLocalTranslation().toString(), ((Node) object).getParent() == null ? "null" : ((Node) object).getParent().getName() });
                     }
@@ -253,6 +260,11 @@
                         result.attachChild((Spatial) object);
                     }
                 }
+
+                if (object instanceof LightNode) {
+                    LightNode lightNode = ((LightNode)object);
+                    lightNode.getParent().addLight(lightNode.getLight());
+                }
             }
         }
         return result;
```

**Comment by normen** [comment]
Lights in jME affect only the children of the node they're attached to. This is different in blender where it affects the whole scene no matter where in the graph it is. This is why lights are generally attached to the root node, so they light the whole scene. You generally can't expect the loader to keep your scene hierarchy completely intact. E.g. in blender one object can have multiple materials, in jME that would be multiple objects (geometries).

**Comment by slyh80** [comment]
Why can't I expect the loader to keep my hierarchy intact? Technically it's possible AND makes sense. I want the lights to affect the children of the node the light is in.

Example:
I have a building with 6 floors. On each floor there are 3 point lights. You're saying that it makes sense that all 18 lights affect all objects in all of the scene? That does not make much sense to me. What makes sense to me -- especially performance-wise -- is to split the scene hierarchically into 6 separate floors that each has 3 lights. At least that's what I would do if I created the scene in code.

Or is there another way to have 18 lights in one scene in JMonkey?

**Comment by normen** [comment]
I gave an example for "why". Your point is a decision between WYSIWYG (in blender the lights affect the whole scene) and jME features. If we had done it the other way around we might have a bug report of somebody who complains that the light he added doesn't affect the scene. I just explained why its done the way it is.

**Comment by slyh80** [comment]
Well, you did it the other way around with the OGRE importer not too long ago.

And, still, if I wanted to build a 6-floor building with 3 point lights on each floor, how would I do this in jME?

**Comment by normen** [comment]
You'd put the light for each floor in a node with the floor.

**Comment by slyh80** [comment]
And how would I do this if the blender loader puts all lights in the root node, although I thoroughly added them to the correct floor in Blender?

The problem is, of course, that Blender handles lights differently than jME does. Blender treats all lights globally, which makes some sense for its renderer, I guess.

But as long as jME has no proper scene editor as, say, the Unreal engine has, I'm stuck with Blender to create my scenes. And that includes creating a relatively complex hierarchy in Blender, although it does not make sense for the Blender renderer at all.

It's perfectly fine for me to use Blender to create my scences. Don't get me wrong on this. But the loader should allow me to import my scenes as close as possibly to how I layed them out in Blender. Because that's why I use Blender and the Blender loader in the first place.

**Comment by normen** [comment]
So how would you turn off a light on the floor?

**Comment by slyh80** [comment]
((LightNode)rootNode.getChild("myCoolLight")).getLight().setEnabled(false)

If there was a method setEnabled(boolean) in the Light class, of course, which for some reason is not.

Why are you asking the question? Turning off a light is not harder whether it's attached to the root node or some other node.

**Comment by normen** [comment]
Because you have to detach it to turn it off. This makes it hard to turn it on again because how do you know where it was? The solution: Place nodes instead of lights and attach them in code to these special nodes.

**Comment by slyh80** [comment]
Now you lost me. Are we really talking about the same problem?

**Comment by normen** [comment]
Yes, your problem of placing lights in your scene the way you want them.

**Comment by slyh80** [comment]
So what you are saying is to add the lights to some other special node ("Node" node?!) to be able to disable lights. But lights only affect the children of this node, right? So they would do nothing. :) This is why you lost me.

As I said, I'm no expert in lighting in jME, so maybe I'm missing something.

**Comment by normen** [comment]
You have a node. The node has a location and a rotation. You can attach the light to any node you want to all the way down to the root node and you can place it at the location its supposed to be (the light placeholder node you placed in blender).

**Comment by slyh80** [comment]
Ooooh, you mean to place a Node/Empty **in Blender**, and later **in code** move the light to the location of this placeholder node. While the light is attached to the root node. Right? And then, if you wanted to disable the light, you could simply remove it from the root node's light list. Did you mean this?

That is of course possible. Not exactly what I would to do in my usecase, though. I also don't see an advantage over removing the light directly from its containing node and storing it somewhere.
It also would not fix my initial problem, which basically is the fact that a light attached to the root node affects all geometry, and kills the rendering performance to basically 0 fps if there are enough lights in the scene.

Actually moving the lights to their placeholders (or their parent) later in code so they won't do this anymore is not very elegant.

To allow turning lights off it would be quite easy to add a setEnabled()-method to the Light class. The graph's light lists would need updating no matter how you do it. You'd have to add a parent to the light, though.

Or without the setEnabled()-method you could simply add a ```Map<LightNode, Node>``` to your code, where the Node is its old containing Node (aka Parent). The Light could easily be found through it's LightNode object (as created by the Blender loader) by name or some other measure.

But we digress. Everything written thus far has nearly nothing to do with my initial bug report, which I wrote because the Blender importer misplaces the lights and their LightNodes by adding them to the scene root node instead of their desired place in the hierarchy.
I understand why you would want to add all lights to the root node for some use cases. But I don't understand why you would want do the same thing with the LightNodes. It breaks the parent-child relationship! (Going back to my original example: Due to this problem if you moved the House, the Porch SpotLight would not move with it.) It makes absolutely no sense!
I still don't think it makes to much sense for the lights, either.

(The Ogre importer puts the lights at the correct position in the graph, BTW.)

**Comment by normen** [comment]
Yeah, the LightNode should be placed in the hierarchy.

The Ogre importer imports the scene 1:1 as its stored in the ogre file which in turn depends on how the exporter created it. Some exporters don't include node hierarchy at all, some do. The blender loader has to make some decisions about how to import the file as it doesn't get a "curated" model but reads the blender file directly - and as you also indicated blender and a game engine renderer are two completely different things.

Generally I'd suggest not to use model formats / editors for light placement though unless you want to bake light maps (which you probably should given you didn't seem to want to turn off your lights anyway). Light in 3d editors and in game engines are quite different things - you're probably generally better off creating lights on the engine side (e.g. with the SDK scene composer - which is basically exactly made for doing the things that are engine dependent and not modeling - or in code). Same with particle effects etc.

**Comment by slyh80** [comment]
I already use lightmaps for the overall look and only use some realtime lights to improve realism when characters move near certain lights. I really want to position them in blender, because I don't want to use multiple tools to compose my scene. This worked pretty well so for. As long as I don't switch to the blender importer from the OGRE importer. ;-)

Your argument about different exporters and importers is not valid, though. Blender has a hierarchy model. The Blender loader simply converts Blender's hierarchy to jME objects with the exact same hierarchy -- except for the lights.
And, by the way, the OGRE **exporter** uses the same hierarchy as Blender. The OGRE **importer** basically does the same as the Blender importer. And it could easily add all lights to the root node as does the Blender importer.
JMonkey and Blender are mostly compatible.

I understand that it's a bit of a problem to use the lights from Blender directly. Currently I add custom properties (```remove=true```) to certain nodes in blender, which are then later removed during conversion from blender to j3o files in my build process.
So right now I already can tell Blender to ignore certain lights (by making them invisible to the renderer) during lightmap baking, and tell my simple conversion tool to ignore certain objects, including most lights. This way I can use blender for all modelling needs. For particle effects or simplified collision models et al I will or already do use placeholders, of course.

**Comment by normen** [comment]
Theres various ogre exporters for blender and various 3d modelers.

I agree that the ogre importer should probably attach lights to the root node as well though instead of mindlessly importing the graph as it is.

**Comment by davidB** [comment]
(@slyh80 This discussion should be in the forum so community could share point of view).

I'm not the author of the blender importer, but I'm work on an other blender exporter. And I did the same choice when I import data into the jme, light are attached to the rootNode and a LightNode is attached in the scene hierarchie.
```
MyScene
   |-- House
        |-- Porch
            |-- PorchDoor
            |-- LightNode (referencing the SpotLight)
   |-- SpotLight
```

because in blender the light is global, and the same behavior in jME is to attach it to root, if I move a mode like NPC, player,... under the light I "expect it" to be enlighten. With your proposal mobile model need to be moved in the scenegraph to be under the right light zone.

Now a solution, used by some of us : we post-process loaded data in game : 
* to add effect
* to modify display regarding current gamedata
* to replace placeholder model
* to add/complete physics
* to optimize 
* fix light : you can use this phase to visit the model and move light to the parent of LightNode. Today I used the exact opposite I move light from root of the loaded model to the rootNode of the scene, because NPC/avatar arent child of the "floor" model.

**Comment by slyh80** [comment]
I'm still not really convinced that adding the lights to the root node is the right way to go. But anyway.

The fix for the incorrectly placed LightNodes is as follows. With this patch the lights themselves are added to the root node again:

```
Index: BlenderLoader.java
===================================================================
--- BlenderLoader.java	(revision 5566)
+++ BlenderLoader.java	(working copy)
@@ -242,10 +251,8 @@
                 Structure objectStructure = pObject.fetchData().get(0);
 
                 Object object = objectHelper.toObject(objectStructure, blenderContext);
-                if (object instanceof LightNode) {
-                    result.addLight(((LightNode) object).getLight());// FIXME: check if this is needed !!!
-                    result.attachChild((LightNode) object);
-                } else if (object instanceof Node) {
+
+                if (object instanceof Node) {
                     if (LOGGER.isLoggable(Level.FINE)) {
                         LOGGER.log(Level.FINE, "{0}: {1}--> {2}", new Object[] { ((Node) object).getName(), ((Node) object).getLocalTranslation().toString(), ((Node) object).getParent() == null ? "null" : ((Node) object).getParent().getName() });
                     }
@@ -253,6 +260,11 @@
                         result.attachChild((Spatial) object);
                     }
                 }
+
+                if (object instanceof LightNode) {
+                    LightNode lightNode = ((LightNode)object);
+                    result.addLight(lightNode.getLight());
+                }
             }
         }
         return result;
```
