### ISSUE TITLE
Blender loader does not flip coordinates of UV map

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#325]
In Blender the UV coordinates start in the **lower**-left corner (0|0) and go to the upper-right corner (1|1).
In OpenGL (and thus JMonkey) the UV coordinates start in the **upper**-left corner (0|0) and goes to the **lower**-right corner (1|1).

The Blender loader imports Blender's UV coordinates unaltered and does not flip the v-component of the UV coordinates. Thus, a model that contains UV coordinates and a texture is rendered incorrectly in JMonkey.

Possible fix:
The Blender loader should correct Blender's UV coordinates by flipping the v-component so they work correctly in OpenGL/JMonkey.

It would probably be sufficient to call `flipUV(false, true);` in the constructor of class `com.jme3.scene.plugins.blender.meshes.Face`. But I'm no expert regarding the Blender loader.

**Comment by stephengold** [comment]
Since jme3-blender was removed from the Engine on 19 April 2020, this issue is now moot.
