### ISSUE TITLE
Material "ColoredTextured.j3md" does not contain important Technique definitions

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#328]
While using the SSAOFilter in combination with material "ColoredTextured.j3md" I noticed that geometry using said material was not rendered during the SSAO filter pre-processing step. This is due to the fact that SSAOFilter uses forced technique "PreNormalPass", which unfortunately is not defined in "ColoredTextured.j3md". In fact, it doesn't define any of the many techniques all or most of the other materials provided by JMonkey do.

(I'm using material "ColoredTextured.j3md" to texture my model with a baked texture, that contains all diffuse, light and shadow information and should not be affected by any light. ColoredTextured is the fastest solution to achieve this.)

**Comment by pspeed42** [comment]
Hmm... I thought ColoredTextured was actually removed.  Pretty sure it's deprecated and replaced by Unshaded.j3md, though.

**Comment by slyh80** [comment]
If it really is deprecated it should be marked as such or removed completely.
(Unshaded works like a charm, too.)

**Comment by shadowislord** [comment]
Deprecated in https://github.com/jMonkeyEngine/jmonkeyengine/commit/616dadc4981d739c121285df8426fc3863f622cc
