### ISSUE TITLE
Blender loader doesn't use active UVMap if more than one UVMap is present

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#335]
Blender allows to define multiple UVMaps for a geometry/mesh. Only one of them can be active at a time and will be used during rendering.

jME's Blender loader does not load the _active_ UVMap from the .blend file, but seems to always pick the last one in the list, no matter if it is active or not.

Expected behavior:
The loader should only load and use the active UVMap.

Workaround:
Delete all but one of the UVMaps in Blender.

**Comment by stephengold** [comment]
Since jme3-blender was removed from the Engine on 19 April 2020, this issue is now moot.
