### ISSUE TITLE
Method createChannel() of AnimControl throws NullPointerException in SDK JMonkeyEngine 3.1 Alpha  

### ISSUE THREAD

**Issue by gilzamir** [jMonkeyEngine/jmonkeyengine#337]
Hi,

i get NullPointerException when execute the follow code in JMonkeyEngine 3.1:

```java
package mygame;

import com.jme3.animation.AnimChannel;
import com.jme3.animation.AnimControl;
import com.jme3.app.SimpleApplication;
import com.jme3.light.DirectionalLight;
import com.jme3.material.Material;
import com.jme3.math.ColorRGBA;
import com.jme3.math.Vector3f;
import com.jme3.renderer.RenderManager;
import com.jme3.scene.Geometry;
import com.jme3.scene.Node;
import com.jme3.scene.shape.Box;
import com.jme3.system.AppSettings;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 * test
 * @author normenhansen
 */
public class LoadModel extends SimpleApplication {

    private static AppSettings settings;


    private static final String ANI_IDLE = "ArmatureAction.001";
    private static final String ANI_WALK = "ArmatureAction";
    
    public static void main(String[] args) {
        settings = new AppSettings(true);
        settings.setTitle("Does it!");
        //settings.setSettingsDialogImage("Interface/splashscreen.jpg");
      
        LoadModel app = new LoadModel();
        app.setSettings(settings);
        app.start();
    }
    
    private AnimControl control;
    private AnimChannel channel;
    
    @Override
    public void simpleInitApp() {
        Node car = (Node)assetManager.loadModel("Textures/MyModel/arm.mesh.j3o");
        car.setLocalTranslation(new Vector3f(0.0f, -1f, 0.0f));
        rootNode.attachChild(car);
        control = car.getControl(AnimControl.class);
        
        channel = control.createChannel();
        
        channel.setAnim(ANI_IDLE);

        for (String anim : control.getAnimationNames()) {
            System.out.println(anim);
        }
        
        
        
        DirectionalLight sun = new DirectionalLight();
        sun.setDirection(new Vector3f(-1.0f, -1.0f, -1.5f));
        sun.setColor(ColorRGBA.White);
        
        Box b = new Box(1, 1, 1);
        
        Geometry geom = new Geometry("Box", b);
       
        geom.setLocalScale(100, 1f, 100);
        geom.setLocalTranslation(0, -6, -10);
        
        Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        mat.setColor("Color", ColorRGBA.White);
        geom.setMaterial(mat);

        rootNode.attachChild(geom);
        rootNode.addLight(sun);
    }

    public void enableFullScreenMode() {
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        DisplayMode mode[] = device.getDisplayModes();
        settings.setResolution(mode[0].getWidth(), mode[0].getHeight());
        settings.setFrequency(mode[0].getRefreshRate());
        settings.setDepthBits(mode[0].getBitDepth());
        settings.setFullscreen(device.isFullScreenSupported());
    }
    
    @Override
    public void simpleUpdate(float tpf) {
        //TODO: add update code
    }

    @Override
    public void simpleRender(RenderManager rm) {
        //TODO: add render code
    }
}
```
The error in log is that: 

run:
set 11, 2015 9:17:01 AM com.jme3.system.JmeDesktopSystem initialize
INFORMAÇÕES: Running on jMonkeyEngine 3.1-alpha1
 * Branch: master
 * Git Hash: c5c893f
 * Build Date: 2015-08-17
set 11, 2015 9:17:01 AM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFORMAÇÕES: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
set 11, 2015 9:17:01 AM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFORMAÇÕES: OpenGL Renderer Information
 * Vendor: Intel Inc.
 * Renderer: Intel HD Graphics 4000 OpenGL Engine
 * OpenGL Version: 2.1 INTEL-10.6.33
 * GLSL Version: 1.20
 * Profile: Compatibility
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: Audio Device: Built-in Output
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: Audio Vendor: Apple Computer Inc.
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: Audio Renderer: Software
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: Audio Version: 1.1
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: ALC extensions: ALC_EXT_CAPTURE ALC_ENUMERATION_EXT ALC_EXT_MAC_OSX ALC_EXT_ASA ALC_EXT_ASA_DISTORTION ALC_EXT_ASA_ROGER_BEEP
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: AL extensions: AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE AL_EXT_float32 AL_EXT_STATIC_BUFFER AL_EXT_SOURCE_NOTIFICATIONS AL_EXT_SOURCE_SPATIALIZATION
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFORMAÇÕES: AudioRenderer supports 64 channels
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
ADVERTÊNCIA: Pausing audio device not supported.
set 11, 2015 9:17:02 AM com.jme3.audio.openal.ALAudioRenderer initOpenAL
ADVERTÊNCIA: OpenAL EFX not available! Audio effects won't work.
set 11, 2015 9:17:02 AM com.jme3.app.Application handleError
GRAVE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
	at mygame.LoadModel.simpleInitApp(LoadModel.java:51)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:227)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.initInThread(LwjglAbstractDisplay.java:131)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:212)
	at java.lang.Thread.run(Thread.java:745)

IMPORTANT INFORMATION: the same code in JMonkeyEngine SDK 3.0 runs without errors.

**Comment by davidB** [comment]
Can you edit your ticket and use the right syntax for the block of code see https://guides.github.com/features/mastering-markdown/  (you can use the previex tab to check)

**Comment by gilzamir** [comment]
Right! Thanks. I will go to edit now!

**Comment by DannyJo** [comment]
Sounds like ```car.getControl(AnimControl.class)``` returns null for some reason. Might be an issue with the model ```Textures/MyModel/arm.mesh.j3o```. It will be hard to replicate without seeing the model file.

**Comment by gilzamir** [comment]
I checked if car.getControl(AnimControl.class) and see that one do not returns null.  When i see stacktrace, i checked that error is in line 131 ("listener.initialize();")  of the class LwjglAbstractDisplay. The file model is here: https://www.dropbox.com/s/4zttonntxotgg9o/arm.mesh.j3o?dl=0.

**Comment by shadowislord** [comment]
Based on the stack trace you posted, the error appears in your code:
```
Uncaught exception thrown in Thread[jME3 Main,5,main] java.lang.NullPointerException 
at mygame.LoadModel.simpleInitApp(LoadModel.java:51)
```
Line number 51 is:
```
channel = control.createChannel();
```
Therefore control is `null`. It is `null` because the root node of `arm.mesh.j3o` does not have an `AnimControl`.

**Comment by gilzamir** [comment]
I am sending the image to the hiearquia arm.mesh.j3o file. It seems to me that there is a AnimControl in root node of arm.mesh.j3o.
![captura de tela 2015-09-11 as 14 25 21](https://cloud.githubusercontent.com/assets/3324420/9821583/a23cbab8-5891-11e5-9967-ddc94fd43702.png)

**Comment by gilzamir** [comment]
The problem is a model  in my project folder. Thanks!

**Comment by doitwrong** [comment]
what was the problem of the model and how you fix it, i m having the same issues in blender model runs but when i convert it j3o only shows model

**Comment by pspeed42** [comment]
You should ask trouble shooting questions on the forum instead of tagging onto another 'bug' report that should also have been a trouble shooting question on the forum... since the exception was clearly thrown by user code.
