### ISSUE TITLE
Substring gets negative value all the time.

### ISSUE THREAD

**Issue by ben0bi** [jMonkeyEngine/jmonkeyengine#338]
I want to use substr for getting all the characters in a string to make a text parser.

substr(0,1) works
substr(1,1) works too,

but everything above 1 comes in as negative number plus 1.
e.g. substr(20,1) gives back an error stating that -19 is out of index.

I cannot even use src.substring(src.length()-1,1) --> The first one comes ever in as negative number.

This is with the normal substr function, I don't get it. 
I have Linux Ubuntu and OpenJDK (IcedTea 2.5.6)

I don't know if this is jMonkey-related or OpenJDK related so I post it here.

**Comment by ben0bi** [comment]
(Now I use charAt but it is still an issue)

**Comment by davidB** [comment]
It's not related to jMonkeyEngine, it's pure java. They are several way to parse String. I suggest you to find a tuto about java and parse string (reading char by char is often the wrong way).

links:
* http://docs.oracle.com/javase/7/docs/api/java/io/StringReader.html
* https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#charAt%28int%29

**Comment by pspeed42** [comment]
Yeah, with all due respect, this is a "user doesn't know javadoc" error because the substring() javadoc clearly states beginIndex and endIndex... not start and length.  If your first thought at sings of trouble isn't "let me look at the javadoc" then you will fail often.

**Comment by pspeed42** [comment]
Or, wait... maybe we are the dumb ones.  What the heck is substr()?

**Comment by ben0bi** [comment]
Sorry my fault. I took second parameter as length, not as endIndex.

But why does it make the first parameter to negative? Does it count from endIndex backwards to beginIndex? Funny...

**Comment by pspeed42** [comment]
beginIndex 20 endIndex 1 means you are trying to capture the string backwards 19 characters, ie: -19 characters from the beginIndex.
