### ISSUE TITLE
IllegalStateException when playing sound (JME 3.1 Alpha 1)

### ISSUE THREAD

**Issue by satscape** [jMonkeyEngine/jmonkeyengine#341]
The following code works fine in 3.0 stable, but not in 3.1 Alpha 1
```java
audioStep.playInstance();   // same for .play() method
```
Where audioStep is an AudioNode loaded up with a mono ogg file. Used for player's footsteps. Other sound files throw the below exception too, so it doesn't seem to be the audio file itself.

```java
Exception in thread "jME3 Audio Decoder" java.lang.IllegalStateException: Cannot use setTime on a stream that is not seekable. You must load the file with the streamCache option set to true
	at com.jme3.audio.AudioStream.setTime(AudioStream.java:217)
	at com.jme3.audio.openal.ALAudioRenderer.fillStreamingSource(ALAudioRenderer.java:724)
	at com.jme3.audio.openal.ALAudioRenderer.updateInDecoderThread(ALAudioRenderer.java:949)
	at com.jme3.audio.openal.ALAudioRenderer.run(ALAudioRenderer.java:245)
at com.jme3.audio.openal.ALAudioRenderer.checkDead(ALAudioRenderer.java:230)
	at com.jme3.audio.openal.ALAudioRenderer.playSourceInstance(ALAudioRenderer.java:1009)
	at com.jme3.audio.AudioNode.playInstance(AudioNode.java:210)
```
It throws this repeatedly and eventually locks up JME.

More info....
```java
Running on jMonkeyEngine 3.1-alpha1
 * Branch: master
 * Git Hash: c5c893f
 * Build Date: 2015-08-17
LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 610/PCIe/SSE2
 * OpenGL Version: 4.5.0 NVIDIA 346.82
 * GLSL Version: 4.50 NVIDIA
 * Profile: Compatibility
Audio Device: OpenAL Soft
Audio Vendor: OpenAL Community
Audio Renderer: OpenAL Soft
Audio Version: 1.1 ALSOFT 1.15.1
ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
AudioRenderer supports 64 channels
Audio effect extension version: 1.0
Audio max auxilary sends: 4
Returning hash code of content
Checking page id 256,898,459 vs stored id 256,898,459
```

Running 64-bit Linux Mint.

**Comment by normen** [comment]
The error message is pretty clear. Do you call setTime() on a stream that is not seekable and doesn't have the streamCache option set to true?

**Comment by satscape** [comment]
streamCache option is false, I don't call setTime()....just .play() or .playInstance()
Should streamCache be true? I just wanted to play a sound effect, I didn't realise how complex it is.
How do I know if a sound file "seekable"...it's an ogg file containing a single one-shot sound effect.

I'm quite happy to stick with SDK 3.0, it does everything I want and more which includes playing sound effects.

**Comment by shadowislord** [comment]
@satscape 
Can you show the code on how you load the sound? 
Normally you have to specify that you want streaming for it to load in stream mode.

**Comment by satscape** [comment]
@shadowislord 
I made helper method to attach sounds to a node:
```java
public static AudioNode setAudioSource(Node attachToNode, String name, boolean isOneShot) {
        AudioNode node = new AudioNode(assetManager, "Sounds/"+name+".ogg", !isOneShot);
        node.setPositional(true);
        node.setLooping(!isOneShot);
        node.setVolume(1);
        node.setReverbEnabled(false);
        node.setRefDistance(100); 
        node.setMaxDistance(10000000);
        attachToNode.attachChild(node);
        return node;
    }
```

Then when I want to use it:
```java
AudioNode audioStep;
// blah....
audioStep=AudioHelper.setAudioSource(theNode,"step",true);
```
The true is for "one shot", so streaming=false. I think I read in the wiki that one off short sounds should not be streamed and long/music sort of sounds should be streamed, has this changed?

**Comment by shadowislord** [comment]
Actually, the expectation is that you set both parameters to false... For most sounds which are less than 10 seconds, you should be using the buffered mode instead of streamed mode.

This is explained (maybe not too well..) here:
http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:audio#audio_terminology

**Comment by satscape** [comment]
@shadowislord Thanks, I'll experiment and see what works. In my original code above, I was using the other overload with 3 parameters and setting it to false, so maybe the 4 parameter overload with  ..false,false) will work.

**Comment by shadowislord** [comment]
I created a new issue report to clarify the differences between the various parameters in AudioNode.
https://github.com/jMonkeyEngine/jmonkeyengine/issues/342
Since your problem is solved I'll close this one.
