### ISSUE TITLE
Check values of math constants to ensure they were not accidently changed

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#343]
Constants like `Vector3f.ZERO` and others in the math package should be checked each frame (via assertion, or debug option) to ensure they remain what they are supposed to be. This prevents accidental changes by user code.

**Comment by kwando** [comment]
What about a ```SanityCheckAppState``` for this?

**Comment by DannyJo** [comment]
How about creating an immutable version of the Vectors.

**Comment by kwando** [comment]
Instance variables in VectorXf is declared public which makes that impossible, without breaking lots of code. =/

**Comment by DannyJo** [comment]
Oh yes, forgot about that. Back to checking each frame then.

**Comment by normen** [comment]
Actually I prepared an Annotation checker for this that can be used in Java6+ during compilation, the code isn't complete but the skeleton is here: https://code.google.com/p/jmonkeyengine/source/browse/#svn%2Fbranches%2Fjme-checker

Thats also why theres the Annotation code in jme3-core

**Comment by stephengold** [comment]
Resolved in "master" branch at 45b1908 (26 November 2019)
