### ISSUE TITLE
FastMath nearestPowerOfTwo() speedup

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#348]
FastMath nearestPowerOfTwo() speedup by playing with bits. I'm sorry, I didn't discuss this in the forum prior. But I found this: http://stackoverflow.com/questions/5242533/fast-way-to-find-exponent-of-nearest-superior-power-of-2. It shows a bit performance increase indeed, nothing ground breaking :).

There is also this, that (i < 1 ? 0) is because FastMath nearestPowerOfTwo() says that nearest is then 0. And the bit version says 1. Which I think is correct. Then it would be something like (int) (i < 1 ? 1 : Math.pow(2, 32 - Integer.numberOfLeadingZeros(i - 1))); to still leave the calculation out on negative numbers.

And I tried this (I realize this is not really a valid way to create benchmarks, but):

    public static void main(String[] args) {
        int val;
        long start = System.currentTimeMillis();
    
    //        for (int i = -10000000; i < 10000000; i++) {
    //            int x = FastMath.nearestPowerOfTwo(i);
    //            int y = (int) (i < 1 ? 0 : Math.pow(2, 32 - Integer.numberOfLeadingZeros(i - 1)));
    //            if (x != y) {
    //                throw new RuntimeException("Fug");
    //            }
    //        }

        for (int i = 0; i < 100000000; i++) {
            val = FastMath.nearestPowerOfTwo(i);
        }
        System.out.println("Fastmath took: " + (System.currentTimeMillis() - start));

        start = System.currentTimeMillis();
        for (int i = 0; i < 100000000; i++) {
            val = (int) (i < 1 ? 0 : Math.pow(2, 32 - Integer.numberOfLeadingZeros(i - 1)));
        }
        System.out.println("Took: " + (System.currentTimeMillis() - start));

        start = System.currentTimeMillis();
        for (int i = 0; i < 100000000; i++) {
            val = FastMath.nearestPowerOfTwo(i);
        }
        System.out.println("Fastmath took: " + (System.currentTimeMillis() - start));

        start = System.currentTimeMillis();
        for (int i = 0; i < 100000000; i++) {
            val = (int) (i < 1 ? 0 : Math.pow(2, 32 - Integer.numberOfLeadingZeros(i - 1)));
        }
        System.out.println("Took: " + (System.currentTimeMillis() - start));

    }

**Comment by shadowislord** [comment]
Actually there's an even faster algorithm that doesn't require Math.pow(), I implemented it here: https://github.com/jMonkeyEngine/jmonkeyengine/commit/d269839efb1470b3f44c5d201baf49e117783118

Thanks.
