### ISSUE TITLE
Reduce uniform changes by comparing them before frame

### ISSUE THREAD

**Issue by empirephoenix** [jMonkeyEngine/jmonkeyengine#351]
See:
https://github.com/jMonkeyEngine/jmonkeyengine/pull/292

Reuse smaller objects where the comparison cost is low, especially the matrices, wich stay stable for a whole frame.

**Comment by shadowislord** [comment]
I already have this implemented locally - works great. Reduces uniforms set per frame by about x2. Combined with vertex array object support, this reduces number of GL calls made per object significantly (for a nice FPS boost).

**Comment by AlrikG** [comment]
What is the difference to my implementation?
