### ISSUE TITLE
native bullet does not work on Android 5 (?)

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#353]
Due to the new Java runtime (ART) in Android 5, there are stricter checks on JNI calls. It seems to cause native crashes on native bullet.
Need to test native bullet on Android 5 to see how well it works.

**Comment by joliver82** [comment]
I was having a look at all Android labeled issues just in case I could help with something and from my point of view this could be closed because native bullet is properly working in android nowadays. In fact I'm using it in my project
