### ISSUE TITLE
Centered text is rendered blurry by class 'BitmapText'

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#355]
When using BitmapText to render a string while its alignment is set to "Center" some of the lines appear blurry, while others don't.

What it should look like:
https://www.dropbox.com/s/fj1xldsco0pd5yj/centered-text-nice.png

What it actually looks like:
https://www.dropbox.com/s/j3d8l43y99wdvif/centered-text-ugly.png

The reason for this is that class 'Letters', which does the actual alignment calculation, for centered lines calculates a gapX position that is not always an integer number, i.e. that is not pixel-perfect, resulting in the blurry text. IMHO the x coordinates of the rendered text should always be set to a whole number.

This could simply be achieved by casting the result of the calculation in line 217 of class 'com.jme3.font.Letters' to (int).

**Comment by pspeed42** [comment]
Bitmap text can be used in a lot of contexts where casting to an int would
be horrible.  Better to do your own centering, I guess.

**Comment by slyh80** [comment]
Did you take a look at the code I mentioned?

What could happen in the worst case if a line was moved a maximum of 0.5 "pixels" to the left or right?

**Comment by pspeed42** [comment]
You are making the incorrect assumption that units are always pixels.

**Comment by slyh80** [comment]
Well, that's because in this case they actually are pixels, not just abstract units. So the suggested fix would in fact just snap the beginning of a centered line to a "fullsize" pixel.
We are talking about bitmap fonts here, after all.

There is one exception:
If you manually set the size of the font to something small (<2) by calling BitmapFont.setSize(), some of the centered lines will be off by some (screen) pixels. This is because a scale factor is applied to all positions and sizes, and so the pixels become in fact units.
But even for size values well below 1 the result looked far from catastrophic. (Some of the lines were off by about 1 character.)

I still see no reason to not round the indent value to an integer when centering text. If the size of the font is not changed, everything looks nice and crisp. Currently half of all lines look blurry and crappy.

If in fact a user chooses to set the size to a very low value -- for whatever reason, and instead of simply scaling the Node -- the centering is off by some (screen) pixels, which is hardly noticable, if at all.

To have the best of both worlds, you could even take the scale into account before rounding:

```
                if (alignment == Align.Center) {
                    gapX = (width-lineWidth)/2;
                    if (getScale() > 0.3f) {
                    	gapX = Math.round(gapX);
                    }
                } else if (alignment == Align.Right) {
```

**Comment by pspeed42** [comment]
Or, since the box used to center is 100% arbitrary and 100% set by you...
you could just always set an even-sized text box?

The "for whatever reason" is when using text in a 3D scene... or when
animating the text... or any of a dozen other reasons that snapping to
units would look pretty bad or put the text in completely strange places.
When 1 unit is a meter in the 3D world, snapping looks pretty bad..

Scale is not the only thing that sets the font size... and > 0.3 seems
pretty arbitrary.  To be a correct solution, you'd have to let the user
specify their alignment units and then also take _WORLD_ scale into account
for centering.  Or... just set an even sized text box to begin with, I
guess.

**Comment by pspeed42** [comment]
Note: these kinds of discussions should not happen in github.  They should
happen on the forum.

**Comment by slyh80** [comment]
100 - 77 = 23
23 / 2 = 11,5

(100 = box width; 77 = line width)
So, no, an even-sized text box wouldn't help a bit.

**Comment by pspeed42** [comment]
<insert what I'd reply if this was on the forum>

**Comment by slyh80** [comment]
Never mind.
