### ISSUE TITLE
Font creator doesn't create more than 256 characters

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#356]
Font creator doesn't create more than 256 characters. The Font Creator lets the user select the char range and even shows them on the preview, but the end result contains just one page with 256 characters max.
![fontcreator](https://cloud.githubusercontent.com/assets/8344766/10146705/f10ad55e-6632-11e5-8dc3-bdf29b212483.png)

Easy fix would be just to produce one page with the given character range (max displayable char...). If I understood correctly, JME does read these, no matter what the max range is. Also the preview image could be inside a scrollable container. As it tends to eat up and hide all the controls when it is big enough.

Here some discussion from the forums (also pin pointed some of the code points which might be related):
http://hub.jmonkeyengine.org/t/font-creator-for-jmp/16273/30

**Comment by tonihele** [comment]
I might be able to do this. At least I have now JME forked and running. Is it ok, if I:
 - Create all chars on same page (I'm not sure does JME even support the pages)
 - Put the font preview inside some scrollpanel to get rid of the eating the screen effect
 - Change the tooltip on "char range" not to say about padding
 - Use StringBuilder in com.jme3.gde.angelfont.FontCreator.java

This is really @normen 's work of art. Any thoughts?

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#6
