### ISSUE TITLE
DefaultLightFilter does not support BoundingSphere

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#362]
If the user is using bounding spheres in their scene graph, the following error will appear:
`UnsupportedOperationException: Only AABB supported for now`

jME3 lights need to implement an intersectSphere method in order to support light v. sphere intersection.

**Comment by Dokthar** [comment]
(yeah you see two commit here because i did a mess with the first one, tried to resolve conflict ... ouch )
