### ISSUE TITLE
BitmapFont positions text incorrectly when VAlign is set to "Center" or "Bottom"

### ISSUE THREAD

**Issue by slyh80** [jMonkeyEngine/jmonkeyengine#363]
If the user sets the vertical align of a `BitmapFont` to either `VAlign.Center` or `VAlign.Bottom` it positions the text incorrectly. I'll only discuss `VAlign.Bottom` here.

For `VAglin.Bottom` the text is positioned _below_ the defined text box and renders downwards from there. Instead it should position the text at the bottom border of text box and render upwards.

Screenshot:
https://www.dropbox.com/s/2idcx1oxg4jrwl9/valign-bottom-incorrect.png?dl=0

The right text should be inside the blue box; the last line "touching" the bottom border.

The bug is probably caused by in incorrect calculation of `totalHeight` in method `Letters.validateSize()`.

Code to reproduce:

```
BitmapText label = font.createLabel("This is a test text that has a bottom valign.");
Rectangle textbox = new Rectangle(380, 240, 110, 100);
label.setBox(textbox);
label.setVerticalAlignment(VAlign.Bottom);

Geometry backgroundBox = new Geometry("", new Quad(textbox.width, -textbox.height, true));
backgroundBox.setMaterial(mat);
backgroundBox.setLocalTranslation(textbox.x, textbox.y, 0);
getGuiNode().attachChild(backgroundBox);

getGuiNode().attachChild(label);
```

**Comment by stephengold** [comment]
I was able to reproduce this issue in current `master` branch.

**Comment by stephengold** [comment]
Thank you for pursuing this issue!

**Comment by stephengold** [comment]
Re-target to v3.3.0, due to risk of breaking existing applications.
