### ISSUE TITLE
Vector3f.equals() fails for (-0, 0, 0)

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#365]
It's pretty simple to reproduce:

    System.out.println(Vector3f.ZERO.equals(new Vector3f(0f, -0f, 0f)));
This will print out "false" because Float.compare() seems to see -0 and 0 as a different thing.
Unfortunately this is quite confusing for the user and built in code which checks for Vector3f.ZERO.

Don't ask me how I got to Vectors with -0 (it appeared arithmetically and wierdly java allows that)

**Comment by shadowislord** [comment]
Here's the explanation behind using Float.compare instead of ==:
http://hub.jmonkeyengine.org/t/vector3f-equals-bug/32074/3

**Comment by MeFisto94** [comment]
Okay, but why don't we add something like if (a == -0f) or (b == -0f) { return (a == b); }?
I mean, I get the case with Float.NaN but since -0 and 0 are mathematically equal (and no one will use a special (-0, -0, -0) Vector to state something different like (0, 0, 0)) we could work around this?

Atleast for the -0 case it's quite confusing to have that reaction

**Comment by shadowislord** [comment]
If the `equals()` method is modified according to this, it would violate the contract for `hashCode()`, because then there will be two vectors that have different hash code but will be equal according to `equals()`.

If you like, you can implement something an `approximateEquals()` which will use a more relaxed comparison involving epsilons and such.

**Comment by MeFisto94** [comment]
I see, the hashCode is the Problem. That explains the reason :)
One could simply check if the length of the Vector is zero.
Thanks for clarification

**Comment by pspeed42** [comment]
Also, approximateEquals() is essentially already implemented.

Use: v1.distanceSquared(v2) < EPSILON for whatever 'close' you want to define as approximate.
