### ISSUE TITLE
Can we get a new minor release?

### ISSUE THREAD

**Issue by Ohmnivore** [jMonkeyEngine/jmonkeyengine#369]
I'm having this issue on both of my computers: http://hub.jmonkeyengine.org/t/invalidenum-1208-wont-go-away/33755/22

It stops me from using jMonkeyEngine 3.1, and it makes me very sad. If I understand correctly, the fix is already in the source code (https://github.com/jMonkeyEngine/jmonkeyengine/commit/78d2d6e944116fa61b24b4aee89cdf13459d2795), we just need to release a new version and problem solved. I'd do that if I could compile the source but I'm having some trouble with that.

**Comment by DannyJo** [comment]
The 3.1 snapshot jars are available in the Maven repo, just go there and download them or better yet, just point your Gradle or Maven dependency management to them.

They are versioned as `3.1.0-SNAPSHOT`

http://updates.jmonkeyengine.org/maven/

**Comment by normen** [comment]
Please don't nag, especially not via the github issues feature.
