### ISSUE TITLE
Add warning to material when more than 16 textures are used

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#37]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=383

**Comment by shadowislord** [comment]
If more than 16 textures are used then an `ArrayIndexOutOfBoundException` is thrown in `GLRenderer.bindTextureAndUnit`

**Comment by stephengold** [comment]
Forum topic: https://hub.jmonkeyengine.org/t/12-textures-splatting-in-new-terrainlighting-j3md/17561
