### ISSUE TITLE
Can't paint terrain, buttons appear to me missing.

### ISSUE THREAD

**Issue by coopsmoss** [jMonkeyEngine/jmonkeyengine#370]
I'm using the 3.1 alpha on Ubuntu

In the Terrain Editor Window I believe the paint button is missing and so I am unable to paint.
Two is only one spray can button, it appears to be the paint icon but when you mouse over it says "erase a texture from the terrain"

![screenshot from 2015-10-25 14 58 38](https://cloud.githubusercontent.com/assets/10568885/10718149/e674fcae-7b28-11e5-849a-08017c96d7b5.png)

**Comment by Dokthar** [comment]
The button you have is the paint tool. The tool tip is wrong and already been corrected ( #336 )

**Comment by grizeldi** [comment]
So why is this still open?
