### ISSUE TITLE
Sometimes after deserializing a J3O, animations are broken

### ISSUE THREAD

**Issue by pateman** [jMonkeyEngine/jmonkeyengine#371]
Related to this topic: http://hub.jmonkeyengine.org/t/solved-ogrexml-model-animation-broken-after-exporting-to-j3o/34200

A solution is also present there.

**Comment by marshhxx** [comment]
Hi @pateman 
I'm experiencing a similar issue on Android. 
I exported a 3ds Max model to OgreXml. The animated model works perfectly but the first time takes about 20s to render. 
I then imported my OgreXml model to jMonkeyPlatform and convert it to j3o binary. The model takes 1s to render but animations are broken.
Did you solve it adding rootBone.reset(); in the Skeleton.read() method?
Did you then import the new jars to your project?

Thanks for your help!

**Comment by pateman** [comment]
@marshhxx, yes, that's basically what solved the problem for me. I didn't really import a modified JAR. I just downloaded the source file from the repo, put it under the same package in my project's source, modified it, and rebuilt the project.

**Comment by marshhxx** [comment]
@pateman Thanks for the help! I try it and worked :+1:  
I found a simpler solution that worked where you don't need to change the library. Have a look at this link http://hub.jmonkeyengine.org/t/android-graphic-glitches/33403/25

Basically what you need to do is apply "setHardwareSkinningPreferred" to your Spatial.
SkeletonControl skeletonControl = player.getControl(SkeletonControl.class);
skeletonControl.setHardwareSkinningPreferred(true);

Hope it helps!

**Comment by Nehon** [comment]
To anyone willing to take this one
Solution is to add rootBone.reset() be fore this line -> https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/animation/Skeleton.java#L307

**Comment by Ali-RS** [comment]
Will take this.

**Comment by pdid17** [comment]
This issue should be closed with the merging of the PR.

**Comment by stephengold** [comment]
The PR has been merged.
