### ISSUE TITLE
TestPBRLighting crashes with an invalid enum error when assertions are enabled.

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#374]
Enable assertion, launch TestPBRLighting, you got it.
invalid enum on a glCheckError.
Works fine otherwise, but still...

**Comment by shadowislord** [comment]
Closing due to lack of information / stack trace / etc.

**Comment by Nehon** [comment]
Dude... that's just a remainder for me to fix it... You don't need information...

**Comment by shadowislord** [comment]
Still no information about the issue. I am guessing this is a duplicate of #558 which is also an "invalid enum" error.
