### ISSUE TITLE
Changing number of samples then calling app.restart() causes text to vanish

### ISSUE THREAD

**Issue by Retzinsky** [jMonkeyEngine/jmonkeyengine#380]
If you do:

settings.setSamples(x);
this.restart();

text and other geometry attached to the guiNode either vanishes or is rendered incorrectly. 'x' is some valid number of samples not equal to the current sampling amount. If that amount of sampling is set at application start, it works fine.

**Comment by pspeed42** [comment]
I think you should post about this to the forum with more of the code so that the community can trouble-shoot it.  It might be a bug in our code or your code.  Hard to tell and github is not a trouble-shooting forum.

**Comment by DannyJo** [comment]
Was there ever a forum post for this or a simple isolated test case to be able to reproduce?

**Comment by Retzinsky** [comment]
http://hub.jmonkeyengine.org/t/issues-with-changing-anti-aliasing-samples-after-application-start/34380/3

**Comment by Nehon** [comment]
The other issue has a test case
