### ISSUE TITLE
SDK 3.0 - Editor controls not working as expected

### ISSUE THREAD

**Issue by Shadow1Raven** [jMonkeyEngine/jmonkeyengine#387]
Hello,

I've been experiencing several problems with the editor(s) of the jME SDK version 3.0. This includes, that I can't navigate using the arrow keys or insert a new line using enter. Thus, marking text using the keyboard is not possible. Marking text using the mouse also doesn't show any signs of markered text (e.g. a blue background and white foreground). Assuming the XML editor is different from the java editor, I must admit to experience these bugs in every editor window. 
I am running the JME SDK (64-bit) on Windows 7. The SDK runs in Java 1.7.0_51, 64 bit.

**Comment by iamcreasy** [comment]
The [jME forum](http://hub.jmonkeyengine.org/)is a better place to ask this question.

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#4
