### ISSUE TITLE
NullPointerException when using BufferUtils.destroyDirectBuffer

### ISSUE THREAD

**Issue by Eviradnus** [jMonkeyEngine/jmonkeyengine#395]
I sometimes get this NPE:

    Caused by: java.lang.NullPointerException: null
	at com.jme3.util.BufferUtils.destroyDirectBuffer(BufferUtils.java:1296) ~[jME3-core.jar:na]

The actual code line 1296:

    Object cleaner = cleanerMethod.invoke(toBeDestroyed);

The ```BufferUtils.cleanerMethod``` static field is not yet initialized when executing the statement l.1296 - hence the NPE.

Indeed, the ```loadCleanerMethods()``` method seems to be incorrect. It goes like this:

        // If its already true, exit, if not, set it to true.
        if (BufferUtils.loadedMethods.getAndSet(true)) {
            return;
        }
        // This could potentially be called many times if used from multiple
        // threads
        synchronized (BufferUtils.loadedMethods) { /* initialization of static fields */ }

Unfortunately, the guard clause ```BufferUtils.loadedMethods.getAndSet(true)``` is not enough to prevent a concurrent thread to get to the ```return``` statement before the ```synchronized``` init block has been processed...

**Comment by gouessej** [comment]
Please move the test into the synchronized block and tell us if it solves your problem.

**Comment by empirephoenix** [comment]
Actually wouldn't a static initializer block be the correct sync less solution for this?

If I see correctly loadCleanerMethods only would need to be converted to be a static block

**Comment by Eviradnus** [comment]
@gouessej Doing so should solve my NPE problem indeed (though I cannot easily test this actually, since it's a random concurrency issue), but the whole ```loadCleanerMethods()``` method would become a ```synchronized``` bottleneck... which is not a good idea.

Rather, I reckon using something like a [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking) would enable the early ```return``` short-cut, while avoiding a globally ```synchronized``` block.

**Comment by Eviradnus** [comment]
Or, as @empirephoenix said, and if initializing these fields without needing them is not an issue, then a simple static init block may do the job. :)

**Comment by gouessej** [comment]
Double-checked locking shouldn't be necessary here.

I like empirephoenix's solution but we must ensure that this source code doesn't prevent the loading of the class if it fails somehow.

**Comment by empirephoenix** [comment]
try catch in static blocks is allowed, dump it all in a try catch and go for it :)

**Comment by Eviradnus** [comment]
Well, it seems to me the use of this ```AtomicBoolean loadedMethods``` is a failed attempt at double-checked locking... but I may be wrong.

Whatever, do as you please: I'll stick to my try/catch/ignore workaround for now, since it's only about freeing memory (and it happens at most once or twice at startup)... Not that critical.

**Comment by empirephoenix** [comment]
Yes i guess you are right, not having the fields volatile is a breach of contract anyway.
