### ISSUE TITLE
Old mesh names when applying new blend file

### ISSUE THREAD

**Issue by Triangle345** [jMonkeyEngine/jmonkeyengine#410]
After changing mesh names in blender on an already converted blend file (j3o), jmonkey asks whether or not to apply the blend changes.  After clicking yes, inspection of the j3o scene shows that the old mesh names remain in the scene graph along with the new ones.  It seems that these old names should be removed.  A current work around is to simply reconvert the blend file and create a new j3o in which case the old names are completely gone from from this newly created j3o.

**Comment by normen** [comment]
Well the SDK has no other hint at which mesh is which but the name so if you change that the old meshes are kept. A workaround might be an option to delete all meshes that weren't found (by name) in the current j3o - which in turn might delete meshes that you added to the j3o file later (not in blender).

**Comment by Triangle345** [comment]
Why not just wipe and reload everything when a change is detected.  The only downside I could think of is a possible wait time for a new j3o to be generated? All though as you mentioned, it might permanently remove non blender made meshes.  Is there a way to "mark" something as blender or other tool made so that if a change is detected for that object, it automatically wipes it and reloads? 
Sorry for my ignorance as I have not looked at the source for the importer yet.

**Comment by normen** [comment]
Then you could just say "no" and convert it again. The point of this is keeping changes you made in the SDK (Materials, Particle Effects etc. etc.) and only importing changes you made to meshes.

https://youtu.be/6-YWxD3JByE?t=2000

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#3
