### ISSUE TITLE
small bug in LightProbeFactory

### ISSUE THREAD

**Issue by jmkinzer** [jMonkeyEngine/jmonkeyengine#424]
In the PBRisComing branch, looking over the code for LightProbeFactory.java. At line 156:
        if(probe.getIrradianceMap() == null) {
            probe.getIrradianceMap().getImage().dispose();
            probe.getPrefilteredEnvMap().getImage().dispose();
        }
It should be instead:
if(probe.getIrradianceMap() != null)

**Comment by Nehon** [comment]
doh, right.
Thanks will change this.

**Comment by Nehon** [comment]
fixed with https://github.com/jMonkeyEngine/jmonkeyengine/commit/a670877df172a06e6a96d52a417671084d748c0c
