### ISSUE TITLE
Shader Nodes can't open Lighting.j3md

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#429]
Opening the Lighting.j3md in ShaderNodes leads to a ```NullPointerException```.
The Exception itself isn't interesting, but we should find out what goes wrong so that the ```ShaderGenerationInfo == null```

See https://github.com/MeFisto94/jmonkeyengine/commit/4b177caa071200b2eb5340e8c5fc20367dbe6537 for where the NPE happens.

**Comment by Nehon** [comment]
Sorry wrong manipulation

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#2
