### ISSUE TITLE
LWJGL 3 context cannot be created on Mac OS X

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#433]
Mac OS X requires window management code to run on the main thread. Unfortunately, jME3 creates a separate thread to initialize the window. 
This will be a breaking change which is only included for applications opting to use LWJGL 3.

**Comment by zzuegg** [comment]
As an addon info, on osx, the main thread has to be thread 0.
It requires the vm argument -XstartOnFirstThread

**Comment by shadowislord** [comment]
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/commit/e541a5a147e0dc8acefee694fce4d7f8a616a5be
