### ISSUE TITLE
Rotating models in SceneComposer in SDK not done correctly 

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine/jmonkeyengine#437]
Rotating a model in scene composer is not done correctly and Parent node box not rotating along with mesh box and cause problem in transforming model in scene.
see detailed description here : 
http://hub.jmonkeyengine.org/t/bug-report-problem-with-rotating-models-in-scenecomposer-in-sdk/35224

**Comment by grizeldi** [comment]
I'll try to figure out where the problem lie.

**Comment by Dokthar** [comment]
@grizeldi don't go crazy on this, you'll have to look into scenecomposer's tools (some stuff i worked on  ;) ).

**Comment by grizeldi** [comment]
@Dokthar I know. Checked out the classes yesterday, added some debug printlns, but I still didn't find the void that is called when you rotate something...

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#1
