### ISSUE TITLE
Skybox breaks Ray Collision

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#449]
Hey,
So the history:
Back in alpha1 there was an optimation which caused Collisions between a Sphere and a Bounding Box to throw an Exception (iirc). As several threads popped up, @pspeed42 found out that this optimation actually breaks more than it helps.
I don't know if this is connected, maybe Paul remembers, but I wanted to point that out.

Now we have the Issue that once you have a skybox in the SceneGraph under the Node you collide with, you get no results at all.

See [here](http://hub.jmonkeyengine.org/t/solved-why-does-my-mouse-picking-not-collide-with-anything/35241) and there are also more posts like that (which is why I had that idea).

I didn't include a test case but it should be easily reproducable.

**Comment by shadowislord** [comment]
A skybox is located infinitely far away, so all collisions would be located at infinity, and thus invalid. Closing this issue as it is expected behavior
