### ISSUE TITLE
Cannot save the scene.

### ISSUE THREAD

**Issue by EngjellRraklli** [jMonkeyEngine/jmonkeyengine#465]
After making changes to a new scene, it can't be saved. If closing and click yes in the confirmation popup, the scene can't be opened anymore.S.D.K problem with the latest alpha version.

**Comment by Nehon** [comment]
Could you please report this issue in the sdk dedicated project?
https://github.com/jMonkeyEngine/sdk/issues

Thanks

**Comment by EngjellRraklli** [comment]
Yep, sorry, just noticed there were 2 different projects. Thanks.
