### ISSUE TITLE
Positional audio breaks when parent node getWorld* methods are called.

### ISSUE THREAD

**Issue by ZoltanTheHun** [jMonkeyEngine/jmonkeyengine#470]
If positional audio is attached to a node and on the audio node or on one parents, any of the getWorld* methods are invoked, or the getPosition() of the audio node, the transformation flags are reset and the audio position won't get updated.

Topic of discussion:
https://hub.jmonkeyengine.org/t/positional-audio-wiki-update-please/35536/15

**Comment by shadowislord** [comment]
Fixed in https://github.com/jMonkeyEngine/jmonkeyengine/commit/9d094b222af01a896e5ddf716af588fba0e819dd
