### ISSUE TITLE
Can not open the website?

### ISSUE THREAD

**Issue by PartaCana** [jMonkeyEngine/jmonkeyengine#478]
I am very new to github, so I apologize if this question seems stupid. I clicked on the link that leads to jmonekeyengine.org, not it won't open. My internet connection is fine, there are no problems there. So ,I guess there is a minimum internet speed required for me to open it?

**Comment by Dokthar** [comment]
It's not just you : http://downforeveryoneorjustme.com/jmonkeyengine.org/
you can go on the forum, https://hub.jmonkeyengine.org
