### ISSUE TITLE
Bullet native needs recompilation.

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#483]
Linux x64 build of libbulletjme.so is not up to date with the source and need to be recompiled, I don't know if it's the same with other releases.
Some issues caused by this outdated version are:
1. GImpactCollisionShapes do not work
2. getAngularFactor  returns always 0 
3. angular factor set to 0 by default.

**Comment by shadowislord** [comment]
Should be fixed for Windows / Linux. Will update the OSX natives tomorrow.
