### ISSUE TITLE
3.1.0 beta 1

### ISSUE THREAD

**Issue by ZakharD** [jMonkeyEngine/jmonkeyengine#493]
When you run any test of physics:

Uncaught exception thrown in Thread[jME3 Main,6,main]
NoClassDefFoundError: com/bulletphysics/collision/dispatch/CollisionConfiguration

**Comment by Ali-RS** [comment]
this post may help you.
https://hub.jmonkeyengine.org/t/solved-problem-with-switching-to-jbullet-in-jme-3-1-alpha-5-sdk/35698

If you add [stack-alloc.jar](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/lib/stack-alloc.jar) and [jbullet.jar ](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/lib/jbullet.jar)it works like it used to.

**Comment by Nehon** [comment]
Please use the forum for trouble shooting
hub.jmonkeyengine.org
