### ISSUE TITLE
Serialization of Hardware-Skinned j3o's broken

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#499]
Hey Guys,
So the issue is essentially this: With the switch to HW Skinning the Serialization of animated Models changed in two ways:
a) We try to serialize "NumOfBones" and "BoneMatrices" as MatParams. This is wrong since they are regenrated every frame and trigger our "does not support shared materials" warning (since the matrices simply aren't equal)

b) We couldn't serialize Arrays of Matrixf and others so the BoneMatrices were actually null

To fix this issue I proposed the "MatParams" Fix along with the Transiency Attribute for Materials. The Problem here is that since this Information is stored in Material it's decoupled from SkeletonControl.
See [here](https://github.com/MeFisto94/jmonkeyengine/tree/MatParams). It still misses the j3md part, some testing and a more clever array serialization, though.

"Also I noticed that you’re assuming that all matparam arrays are savable arrays in the code, you should probably make sure that they are specifically a Savable[]"

The reason I didn't create a PR is because instead of hacking this in an deleting it in 3.2 again, it might be better to simply backport the 3.2 MPO SkeletonControl to 3.1 and make use of it.

No matter what, we have to do something since it's currently preventing any sdk from loading/saving any animated model

**Comment by pspeed42** [comment]
Seems to me that maybe the real problem is this: "This is wrong since they are regenrated every frame and trigger our "does not support shared materials" warning (since the matrices simply aren't equal)"

...once we can save/load Matrix4f maybe we just need to detect that a different way?

Presumably the material wasn't shared when the skeleton control was serialized... but the skeleton control was serialized as part of the spatial that holds the material.  If we serialize/deserialze the material, is JME's serialization smart enough to fix up the reference?  If so then the skeleton control would have the right material and could null out these references itself.

Just random ideas of different skeleton specific solutions.

**Comment by MeFisto94** [comment]
it didn't seem to fix them since it's not only about the materials which are part of the SkeletonControl (there is a list of "targetMaterials") but they can be materials from some random influenced Geometry.

I tried it by first making those Matrices serializable without changing the transiency but yeah, then you get those "don't use shared materials" warnings.

I don't know if we can implement another check for shared materials but then we still waste space and time since those matrices won't ever be read (apart from said check).
Maybe we could bypass the check and/or null those values upon the first update() call? I'll try that locally asap but we still waste some space.

I didn't see how big such a matrix is but given that you can have plenty of them when dealing with multiple geometries and such, it's a bit of data but on the other hand it's not worth an ugly hack probably

**Comment by pspeed42** [comment]
"don't use shared materials" warnings.
...if it's a warning then let them warn.  I thought it was an error... if so change it to a warning: done.

**Comment by MeFisto94** [comment]
I have to check what it is exactly, I guess an error but still a false positive spammed once per frame and animated geometry is not only confusing but stressing the logger^^

**Comment by pspeed42** [comment]
No... warn once and reset the buffer.  If the warning was real then the animation goes funky for them and they get a warning every frame... if not then everything moves along fine.

**Comment by MeFisto94** [comment]
https://github.com/MeFisto94/jmonkeyengine/tree/HwSkinningFixV01 This is with simply skipping the first conversion, I like this more since it has no false positive and does crash the application instead of only warning the user.

https://github.com/MeFisto94/jmonkeyengine/tree/HwSkinningFixV02 this however is the desired version, let's see what the others think about it.

**Comment by pspeed42** [comment]
I think the second one is probably better.  The first one feels kind of hacky and will potentially hide the error from the user until some odd later time.  Yes, users might see false positive warnings in the issue's care but I understand that this fix is only temporary anyway.

I'll defer to others' opinion at this point.

**Comment by Nehon** [comment]
I also prefer the warning and spam version.
