### ISSUE TITLE
FrameBuffer class can't have multiple render targets without bound textures.

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#502]
The FrameBuffer class has a setColorBuffer(Image.Format) method that creates a RenderBuffer without a texture bound.

That's useful when you want to get the rendered buffer copied to the CPU in a byteBuffer unsing the renderer.readFrameBuffer() method.

However, FrameBuffer lack the capability to add multiple render target without a texture bound to the renderBuffer. (only addColorTexture(TextureXXX) is available). 

We should add a addColorBuffer(Image.Format) method.

ps : I'm aware of the setTargetIndex() method, but it actually doesn't solve the issue as it doesn't change the renderBuffer slot, but the index of the renderBuffer in the renderBuffer list (which btw makes me doubt about its usefulness....)

**Comment by shamanDevel** [comment]
I stumbled over this problem while working on some very small test projects. My workaround was to always use a texture, but yes, this method is really missing.
I hope, this pull request solves it:

**Comment by shamanDevel** [comment]
Can we mark this issue as closed?
