### ISSUE TITLE
Renderer.copyFrameBufferWithFormat only allow to read from the first RenderBuffer of the FrameBuffer.

### ISSUE THREAD

**Issue by Nehon** [jMonkeyEngine/jmonkeyengine#503]
Which is obviously an issue when you use MRT and want to copy one of the multiple target to the CPU.

This line : 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java#L1761
is somehow the issue as it gets the first renderBuffer from the frame buffer whatever happens.

there are 2 options to solve this issue IMO : 
1. Allow to pass the required index in the copyFrameBufferBla method, and use frameBuffer.getColorBuffer(index).
2. make getColorBuffer return the renderBuffer in the colorBufIndex index od the buffer list (this variable is set by using FrameBuffer.setTargetIndex, and would make it actually useful).

I'd rather go for option 2.

**Comment by shamanDevel** [comment]
@Nehon do you mean this fix: #561

**Comment by Nehon** [comment]
Hey thanks. I'd like @shadowislord comment on this, because I still don't get what's the intended way to use this in the first place.

**Comment by shadowislord** [comment]
Fixed in  2e58f27
