### ISSUE TITLE
Suggestion: TTF font loading

### ISSUE THREAD

**Issue by ModernBroccoli** [jMonkeyEngine/jmonkeyengine#523]
Hey! I just got started with your engine and I have to say It is really good! :).
However a small thing I noticed is the fact that there is no way of loading .ttf fonts, which is kind of weird because I *especially* use .ttf fonts. Is there a way to Implement it.

**Comment by pspeed42** [comment]
You should ask questions on the forum.

**Comment by MeFisto94** [comment]
Plus you should google/search the forums first, since there is a TTF Library (3rd Party though)
https://hub.jmonkeyengine.org/t/jme-truetypefont-rendering-library/35395
