### ISSUE TITLE
ShadowFilters with Mesh.Mode.Patch meshes make the drivers crash

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#524]
Driver: AMD Crimson 15.20
Card: r9 270x 
Crash log:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0f3ec5d25d, pid=30501, tid=139704433215232
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [fglrx_dri.so+0x161a25d]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /xyz/hs_err_pid30501.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
[hs_err_pid30501.log](https://gist.github.com/riccardobl/7fafafa7150320115b4f87552443582b)

**Comment by Nehon** [comment]
Did you try to update the drivers?
In any case if you want me to do something about it, a test case would help.

**Comment by riccardobl** [comment]
15.20 are the latest drivers available for my card in linux.
This is the test case: https://gist.github.com/riccardobl/38de2113eb379f04d7880be85165a4f4

**Comment by Nehon** [comment]
rhoo dude, ATI + Linux, you like to hurt yourself... ;)
Will look into it, thanks for the test case.

**Comment by empirephoenix** [comment]
Nah AMD on linux is pretty good by now (actually far better integrated than nvidia) , (if you use the opensource driver that is)

**Comment by riccardobl** [comment]
It turned out being caused by the Post/PreShadow techniques lacking of tessellation shader.
I close the issue myself, since it's not related to jme.
