### ISSUE TITLE
OpenCL/LWJGL3 implementation uses deprecated objects like CLDevice

### ISSUE THREAD

**Issue by phr00t** [jMonkeyEngine/jmonkeyengine#534]
The current jME3 OpenCL implementation likely works, but if you try & use the latest LWJGL 3 release, it won't compile. CLDevice wrappers were removed in the latest release:

https://github.com/LWJGL/lwjgl3/releases

... due to this issue:

https://github.com/LWJGL/lwjgl3/issues/152

See current usage of CLDevice here:

https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglDevice.java

They likely want a simple "long" define of the device, instead of CLDevice, which is the address.

**Comment by shamanDevel** [comment]
Thank you that you noticed that change in the API.
To the core members: Am I allowed to update the dependency of lwjgl3 from 3.0.0b to 3.0.0? Then I can implement the changes.

**Comment by shadowislord** [comment]
Yeah, it's okay to update LWJGL3

**Comment by shamanDevel** [comment]
Can we mark this issue as closed?
