### ISSUE TITLE
JMonkeyEngine Simple Application changes screen resolution on exit

### ISSUE THREAD

**Issue by nsatragno** [jMonkeyEngine/jmonkeyengine#536]
- OS: Ubuntu 16.04.1 LTS (64 bits).
- Graphics card: NVIDIA Corporation GK104M [GeForce GTX 870M] (rev a1).
- Driver version: 361.42 (proprietary).
- Using OpenJDK version "1.8.0_91".
- Running vanilla jMonkeyEngineSDK 3.0.
- Laptop running with dual cards (but only the powerful nVidia one should be running).

Steps to reproduce:
1) Create new basic application project.
2) Run it.
3) Close it pressing 'esc'.

What happens: regardless of the application resolution / fullscreen or windowed mode, the desktop resolution is changed to something like 640 \* 480 (I can't say for sure because the 'monitors' dialog still shows 1920 \* 1080). Everything comes back to normal by changing the resolution back manually.

**Comment by Dokthar** [comment]
This issue is very strange.
Can you reproduce this issue with the last version of the SDK ? xor with your other card ? ..ect

Do some kind of "cross-checking" so we can have a better idea on where the issue come from.

**Comment by empirephoenix** [comment]
does that also happen with oracle jvm? what happens with jme 3.1 or with git head version?

**Comment by nicolassatragno** [comment]
Thanks for the replies everyone.
> Can you reproduce this issue with the last version of the SDK ?
> what happens with jme 3.1

I cannot repro with the latest beta [v3.1.0-beta](https://github.com/jMonkeyEngine/jmonkeyengine/releases/tag/v3.1.0-beta1) :smile: 

> xor with your other card

Cannot repro with the integrated intel card either.

> does that also happen with oracle jvm?

Yes (tried with the provided Oracle JVM 7).

So I assume this means we can close the issue?
