### ISSUE TITLE
Typo in assert

### ISSUE THREAD

**Issue by AppChecker** [jMonkeyEngine/jmonkeyengine#538]
Hi.

In file [jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, line 230](https://github.com/jMonkeyEngine/jmonkeyengine/blob/46891b32c69e8696947a12b4069d8c7383f87d3f/jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java#L230)

bp.clientObject is checked twice:

```
assert (
bp.clientObject instanceof com.bulletphysics.collision.dispatch.CollisionObject && 
bp.clientObject instanceof com.bulletphysics.collision.dispatch.CollisionObject
);
```

Probably, it should be:

```
assert (
bp.clientObject instanceof com.bulletphysics.collision.dispatch.CollisionObject && 
bp1.clientObject instanceof com.bulletphysics.collision.dispatch.CollisionObject
);
```

This possible defect found by [statis analyzer AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by empirephoenix** [comment]
Quite likely

**Comment by demoth** [comment]
so i'm taking it

**Comment by demoth** [comment]
well, in master branch this code is commented out

**Comment by DomenicDev** [comment]
I will create a pull request for this issue.

**Comment by Nehon** [comment]
Thanks ;)
Seems I can't assign you for some reason so I'll just assign myself so that other people know that it's taken care of
