### ISSUE TITLE
Support for Vulkan API

### ISSUE THREAD

**Issue by spacekookie** [jMonkeyEngine/jmonkeyengine#542]
With lwjgl 3 making its way into jME 3.1, can we expect Vulkan rendering soon? Are there any plans?

**Comment by pspeed42** [comment]
The issue tracker is not a forum.

**Comment by Ali-RS** [comment]
short answer : https://hub.jmonkeyengine.org/t/jmonkeyengine-3-1-alpha-2-released/35197/11?u=ali_rs

if you search the forum you can find more answers https://hub.jmonkeyengine.org/
