### ISSUE TITLE
Broken Links in Documentation

### ISSUE THREAD

**Issue by vinf100** [jMonkeyEngine/jmonkeyengine#562]
This is not a problem with the engine itself, but with the wiki. Many of the links written on the wiki are broken and result in 404 pages. One of these links even loads a page of what appears to be a Chinese Jockey club (the faulty link is the one at the bottom of the 3D rotations doc page which is supposed to link to Transform Matrices). Also, many of the links in the actual content are broken. Even the page on reporting bugs is not updated; it links to the Google code archive instead of Github. This is not a severe issue; I can access what I wanted to see by typing in Google, but it is frustrating and sometimes confusing when the link works, but it points to the wrong page (like in the report bugs link).

**Comment by Nehon** [comment]
Hello I made a pass this morning and fixed a couple of issues.
Could you please check? Also it could help that you report the exact links

**Comment by vinf100** [comment]
I cannot report the _exact_ links as there are so many of them. However, from having a look, the broken links are the links which point to internal resources (other help pages in the documentation) in all the pages except the introduction, and the links in the table of the "Create" section of the introduction. However, the documentation seems to be fractured between "github.io" docs, and "docs.jmonkeyengine.org". The links in "github.io" work fine, but almost all of the information is in the other one. It is as if the entire page had been copy-pasted from the old wiki the current documentation, but the links inside had not been updated.

**Comment by vinf100** [comment]
Just to be clear, the problem is in the "docs.jmonkeyengine.org", _not_ "github.io".

**Comment by Nehon** [comment]
alright I'll make another pass in the source to find the faulty URL ;)

**Comment by mitm001** [comment]
As I go through the tutorials I will post broken links here. If you rather I open another issue just let me know.

**jMonkeyEngine 3 Tutorial (1) - Hello SimpleApplication**
downloaded the jMonkeyEngine SDK -http://jmonkeyengine.org/wiki/doku.php/
Install the jMonkeyEngine - http://jmonkeyengine.org/wiki/doku.php/

**jMonkeyEngine 3 Tutorial (3) - Hello Assets**
1.Download the town.zip - http://jmonkeyengine.googlecode.com/files/town.zip
This file has been uploaded to a git hub fork by ali.
https://github.com/Ali-RS/jmonkeyengine/blob/master/jme3testdata/src/main/resources/Scenes/town.zip

**jMonkeyEngine 3 Tutorial (4) - Hello Update Loop**
Link to user-proposed solutions: http://jmonkeyengine.org/wiki/doku.php/jm3:solutions

**jMonkeyEngine 3 Tutorial (5) - Hello Input System**
Link to user-proposed solutions: http://jmonkeyengine.org/wiki/doku.php/jm3:solutions

**jMonkeyEngine 3 Tutorial (6) - Hello Materials**
Materials forum thread - http://jmonkeyengine.org/forum/index.php?topic=14179.0
jME3 Materials documentation (PDF) - http://jmonkeyengine.googlecode.com/files/jME3_materials.pdf
Creating textures in Blender - https://www.blender.org/education-help/tutorials/materials/
Various Material screenshots - http://www.shaders.org/ifw2_textures/whatsin10.htm

**Comment by Ali-RS** [comment]
Yes , please post them here. I will go through them and push fix  when i have free times.

**Comment by Ali-RS** [comment]
> jMonkeyEngine 3 Tutorial (1) - Hello SimpleApplication
> downloaded the jMonkeyEngine SDK -http://jmonkeyengine.org/wiki/doku.php/
> Install the jMonkeyEngine - http://jmonkeyengine.org/wiki/doku.php/

fixed 
https://github.com/jMonkeyEngine/wiki/pull/19

**Comment by Ali-RS** [comment]
It may be better create issue in JME github wiki page https://github.com/jMonkeyEngine/wiki/issues

**Comment by Ali-RS** [comment]
@mitm001 , @vinf100 
You are welcome to put broken links [here](https://github.com/jMonkeyEngine/wiki/issues/20). I will try to fix them.

**Comment by mitm001** [comment]
Thank you. I will post others there if I find them. I will do it in batches to make it easier. I will have read every web page and visited every link on the wiki over the next several weeks.

**Comment by Nehon** [comment]
@mitm001 can this issue be closed?

**Comment by mitm001** [comment]
We took care of the wiki stuff.  docs.jmonkeyengine.org is nowhere to be found in wiki.
