### ISSUE TITLE
Constructors of SpotLight does not set invSpotRange 

### ISSUE THREAD

**Issue by theMinka** [jMonkeyEngine/jmonkeyengine#563]
If the method _SpotLight.setSpotRange(float)_ is called, also the inner value _invSpotRange_ is set. But if one of the constructors of the _SpotLight_ class is used that also provide the _spotRange_ parameter, the inverse range value is not set to the correct value. This leads to some lighting effects in the scene, where the default range of _100f_ is used instead of the value set by the constructor.

To fix this, the internal variable _invSpotRange_ of the _SpotLight_ class has to be set every time, the variable _spotRange_ is set. I whould recommand to simply call _setSpotRange(float)_ from within the constructor.

**Comment by empirephoenix** [comment]
Yes, thanks seems like you found an issue :)
Could you try to create a pull request for it?

**Comment by Nehon** [comment]
You are definitely right
fixed https://github.com/jMonkeyEngine/jmonkeyengine/commit/9cf67b902e46dbc2e01f88cb3e8b28729730c5f4
and also on 3.1 branch
https://github.com/jMonkeyEngine/jmonkeyengine/commit/dd8271e8b3a5b63fec0388aae5e75be58b0b0c9e
