### ISSUE TITLE
Animation NullPointerException

### ISSUE THREAD

**Issue by dinokino** [jMonkeyEngine/jmonkeyengine#564]
Hello, when I copy code from this tutorial (https://jmonkeyengine.github.io/wiki/jme3/beginner/hello_animation.html), everythink works correctly. But when I change the model from example to my, which I made in Blender, it writes error java.lang.NullPointerException. It is because of:
`control.addListener(this);`
And it is because "control" is null. And it is because prevouris instruction: `control = player.getControl(AnimControl.class);` gives null to variable "control". 
So what is the solution? When I try example code from tutorial, it works correctly, but when I replace the model name(path), it doesn't works. (Path of model is correct, because when I only display my model, it load the model correctly).

**Comment by pspeed42** [comment]
Please ask trouble shooting questions on the forum and/or wait for an answer there.  This is not a JME bug.  This is a "your understanding" bug.
