### ISSUE TITLE
Unclear documentation with Better Character Control

### ISSUE THREAD

**Issue by vinf100** [jMonkeyEngine/jmonkeyengine#568]
Hello,

I was using Better Character Control on a test/practice project, when I ran into a problem.
With Better Character Control, the player is allowed to scale any slope regardless of steepness.

The Walking Character page mentions a method to set the steepness that the character can climb (setMaxSlope()), but that method is for the now deprecated Character Control (not Better Character Control); the method does not exist in Better Character Control, nor is its functionality implemented. 

Is there supposed to be something else which replaces setMaxSlope(), or should Character Control be used?

**Comment by empirephoenix** [comment]
It is expected (for both) to only use them as a starting Point. Better uses real physics, while the other uses simplified ray based physics and is suspect to quite a few issues. Something like a character Needs to be adjusted for your game anyway. So you could add the slope checks yourself in your Version of it.
