### ISSUE TITLE
Blender importer does not handle transformations correctly

### ISSUE THREAD

**Issue by mrwatts** [jMonkeyEngine/jmonkeyengine#583]
The Blender importer does not apply transformations, at least not rotations, to spatials and geometries consistently. 

E.g. a model of a vehicle with a 180 degree z-rotation transformation in Blender. After import, selecting the front left wheel spatial will highlight the rear right wheel. However, selecting the front left wheel geometry does highlight the correct meshes.

See: [example](https://dl.dropboxusercontent.com/u/21307972/jmonkey_rotation_problem.blend)

There is a workaround: applying all the transformations in Blender (ctrl-A).

**Comment by NemesisMate** [comment]
Is this still being an issue?, the example link is broken. I'm not sure if the problem you mention (the selection issue) is a jme3 problem or just a an sdk one.

However, the workaround you mention isn't really a workaround but the way to proceed if you want the rotations to be "applied" (as the name suggests) when imported.

**Comment by stephengold** [comment]
Since jme3-blender was removed from the Engine on 19 April 2020, this issue is now moot.
