### ISSUE TITLE
Bullet VehicleControl behaves differently in jME 3.1

### ISSUE THREAD

**Issue by mrwatts** [jMonkeyEngine/jmonkeyengine#593]
A Bullet vehicle that worked perfectly in jME 3.0, no longer works in jME 3.1. At least not in the most current beta of jME 3.1.

Versions used: 

JME sdk 3.0.10 (Windows x64)
jME 3.1-beta2-b001-SNAPSHOT (Windows x64)

Steps to reproduce:

1. Create a new project from the BasicGame template
2. Copy the files in the attached zip file to your project folder
3. Hit F6

Results:

- jME 3.0 - a controllable car
- jME 3.1 - an uncontrollable car

Test files: 
[testfiles.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/691376/testfiles.zip)

**Comment by jayfella** [comment]
related: https://hub.jmonkeyengine.org/t/solved-problem-with-switching-to-jbullet-in-jme-3-1-alpha-5-sdk/35698

**Comment by Troxid** [comment]
vehicle doesn't work only in bullet (native) or for jbullet too?

**Comment by Ali-RS** [comment]
> vehicle doesn't work only in bullet (native) or for jbullet too?

Only in native bullet, 
which I think someone was able to solve it. 
see https://hub.jmonkeyengine.org/t/bullet-vehicle-problems/37578/19?u=ali_rs

**Comment by stephengold** [comment]
I tested the original testfiles.zip from 7 January 2017 with JME 3.2.0, and it worked perfectly with both Native Bullet and JBullet. Not sure when or how it was fixed.
