### ISSUE TITLE
jME 3.1 beta 2 installer does not observe destination folder correctly

### ISSUE THREAD

**Issue by mrwatts** [jMonkeyEngine/jmonkeyengine#594]
Attempting to install jME 3.1 in the directory D:\3d\jmonkeyplatform_3_1 fails. The installer will install jME in D:\3d\jmonkeyplatform. The _3_1 suffix is ignored. Observed with the 3.1-beta2-b001-SNAPSHOT Windows x64 installer. The JME sdk 3.0.10 Windows x64 installer works correctly.

**Comment by grizeldi** [comment]
Someone move this issue to the sdk repo please.

**Comment by MeFisto94** [comment]
Moved to jMonkeyEngine/sdk#111
