### ISSUE TITLE
Animation system support for pose and morph animations

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#6]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=131

**Comment by stephengold** [comment]
Note that the original issue was for the Ogre XML importer. JME 3.3 supports morph animations in the glTF loader but not the Ogre one.

**Comment by Ali-RS** [comment]
I believe we can close this issue. As mentioned Gltf loader supports this and is the preferred way for importing assets to JME.
