### ISSUE TITLE
The stable release should not be marked as "Pre-release"

### ISSUE THREAD

**Issue by muellermartin** [jMonkeyEngine/jmonkeyengine#619]
Currently the release tag `v3.1.0-stable` is marked as "Pre-release" (see attached screenshot) although the name states it is stable. Isn't this somewhat contradictory?

![jmonkeyengine-pre-release](https://cloud.githubusercontent.com/assets/343302/22929768/9009843a-f2bd-11e6-8089-13dc9c481d2c.png)

**Comment by Nehon** [comment]
It's marked as pre release because we didn't yet publish a suitable change log. It will be done in the coming days.

**Comment by muellermartin** [comment]
k, thanks for the stable release though!

**Comment by pspeed42** [comment]
Also, in the future you might actually look at the release page that might explain why such a situation exists.  Since in this case it said right at the very top of the release description.
