### ISSUE TITLE
BinaryImporter creates buffer as large as J3O file it is loading

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#62]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=477

**Comment by stephengold** [comment]
I believe that the `DesktopAssetManager` uses streams. Perhaps this is an Android-only issue?

**Comment by MeFisto94** [comment]
Android actually uses the DesktopAssetManager. 
But the resulting file is cached/stored in memory, maybe they were seeing that?

**Comment by stephengold** [comment]
You're right about Android using DesktopAssetManager. Currently, it's the sole implementation of AssetManager.

I don't think there's any useful info in this issue. Shall we close it?

**Comment by MeFisto94** [comment]
Well in theory we could check the RAM Usage when loading an Asset, but I think that is normal behavior with just limited space. I mean it literarly says "needs RAM in the Dimension of the File Size", well, we load the file, so yeah. Streams aren't going to solve that.

When/if we get the GSoC to do Android, I'll keep a look at the heap when profiling, so I am closing it for now.
