### ISSUE TITLE
Make TempVars Closeable

### ISSUE THREAD

**Issue by manuel-hegner** [jMonkeyEngine/jmonkeyengine#621]
TempVars should be a Closeable or AutoCloseable class. The close method would simply return the object to the stack. This would allow methods that burrow a TempVars object to use a try-with-resource construct to return the object even in case of an exception or any other kind of return. 

On that occasion temp vars could also throw a more meaningful exception if too many objects are borrowed.

**Comment by pspeed42** [comment]
Do note: generally user code should not be using TempVars.  It's a sign of big problems.  JME has no choice in some cases but user code almost always does.

**Comment by manuel-hegner** [comment]
It should not? I was under the impression that this is the way to reduce
object allocation/garbage collection in performance critical steps.
But I guess if it is not supposed to be used externally this issue is not
as important.

Paul Speed <notifications@github.com> schrieb am Do., 16. Feb. 2017, 23:00:

**Comment by pspeed42** [comment]
In user-level code, there is almost always a better way to reduce your allocations.  You have access to your own fields, your own lifecycle, and so on.  JME often uses similar tactics when possible to avoid using tempvars.  Tempvars is a last resort in code that is executed often and has no other way to keep context.

**Comment by shamanDevel** [comment]
Hi,
Is this issue still active?
I side with manuel-heger, I've used TempVars from time to time in math heavy, but short living classes.
The proposed changes to make TempVars​ AutoCloseable does not influence the functionality, it only improves the usability. Furthermore, it reduces the chance of errors if the instance is not released by allowing the try-with-resource construct.
Lastly, this only adds maybe 5 lines.

**Comment by empirephoenix** [comment]
Wont try with ressources break older java api compability? this would be kinda fatal to android and other more exotic platforms

**Comment by manuel-hegner** [comment]
It would not. To enable try-with-resource statements the class only 
needs to implement Closeable, which is part of Java since 1.5 and part 
of Android since the beginning.

**Comment by empirephoenix** [comment]
hm right, it only needs to implement that interface, not use the construct anywhere, my bad

**Comment by pspeed42** [comment]
But see... there's no patch I guess so we're only arguing over hypothetical code.

**Comment by stephengold** [comment]
It's odd that PR #662 was closed but this issue was left open. If the consensus is not to make TempVars closeable, then this issue should be closed.

**Comment by pspeed42** [comment]
It's fine to close this because "neat idea" without a patch is destined to languish.  The issue we had was that making TempVars Closeable is meaningless without also changing the rest of the engine to use it.  Since if users are using TempVars then they are already doing the wrong thing.  So making it Closeable on its own has 0 effect on anything important.
