### ISSUE TITLE
3DS Max 2017 Support?

### ISSUE THREAD

**Issue by JustDaile** [jMonkeyEngine/jmonkeyengine#628]
There seems to be very little support of 3DSMax OgreMax Exporter is not working and most links on their site are broken. It seems impossible to import any animations into JM3 from 3DSMax. Is there a chance you're adding this support? Blender is not an option and even when I try exporting from blender I get a lot of issues.

**Comment by pspeed42** [comment]
Please ask questions on the forum not as bug reports.

**Comment by JustDaile** [comment]
Some of your links in tutorials are broken these are issues, it all seems outdated. Ogre seems unsupported in 3DS max 2017... How can I import animations using max? I have search everywhere an no luck..

**Comment by pspeed42** [comment]
You should ask questions on the forum.  This is not a forum.  This is a bug tracking page.  That's what the forum is for... asking questions.

In other words, don't ask questions here... ask them on the forum since the forum is the place to ask questions.
