### ISSUE TITLE
Link in WaterFilter documentation is 404

### ISSUE THREAD

**Issue by fscheffer** [jMonkeyEngine/jmonkeyengine#636]
The documentation for **com.jme3.water.WaterFilter** refers to a blog post

> http://jmonkeyengine.org/2011/01/15/new-advanced-water-effect-for-jmonkeyengine-3

which returns "404 - File not found".

**Comment by jayfella** [comment]
Where did you find the link?

**Comment by mitm001** [comment]
Its in the java doc comment for the class. Can search for new advanced water effect for jmonkeyengine 3 on forum for correct link.

**Comment by mitm001** [comment]
I fixed it, submitted the pull request. The blog post was turned into a wiki page so I pointed the url there instead.

**Comment by iamcreasy** [comment]
Solved with PR #655
