### ISSUE TITLE
Command line setup not working

### ISSUE THREAD

**Issue by squishybanana04** [jMonkeyEngine/jmonkeyengine#643]
https://jmonkeyengine.github.io/wiki/jme3/simpleapplication_from_the_commandline.html
This link: http://updates.jmonkeyengine.org/stable/3.0/engine is dead, and this link: https://jmonkeyengine.googlecode.com/svn/branches/3.0final/engine is dead.

**Comment by normen** [comment]
Yep, all documentation and the web links are pretty much fucked up because of constant useless website changes plus our documentation contributor doesn't have much time anymore (nor do I). So if you want to see this fixed its best to do it yourself. Just sent a pull request for the wiki.

**Comment by squishybanana04** [comment]
Are there any active links or should I self host?

**Comment by normen** [comment]
Idk if theres any nightly zip distros anymore, I doubt so. Everything else should be on github.

**Comment by Nehon** [comment]
There is no nightly anymore.
The part in this doc explaining how to build from source is outdated.
Now you have to pull the repo from got and do a "gradlew install".
@mitm001 could you look into this?

**Comment by mitm001** [comment]
Just saw this, Ill look into it.

**Comment by mitm001** [comment]
Ill address this in two comments.

The only place I found this link http://updates.jmonkeyengine.org/stable/3.0/engine was on the https://jmonkeyengine.github.io/wiki/jme3/eclipse_jme3_android_jnindk.html page. 

Its fixed but the content of that page needs significant work. Android Developer Tools (ADT) in Eclipse is no longer supported and I don't do eclipse so I will troll for someone on the forum to go through it. Doubtful we will get a volunteer though.

Should probably remove this page if no volunteers.

Still working on command line page.

**Comment by Nehon** [comment]
Yeah obsolete content should go away if there is no one to update it.
Thank you for your work on the wiki @mitm001 ;)

**Comment by mitm001** [comment]
Np, I updated the command line page.

https://jmonkeyengine.github.io/wiki/jme3/simpleapplication_from_the_commandline.html

If you see errors or have suggestions let me know, otherwise this issue is done.

**Comment by Nehon** [comment]
seems that travis gh-pages push fails, gonna look into it.

**Comment by mitm001** [comment]
Its acting up on other repos I contribute to also, I will try again.

**Comment by mitm001** [comment]
Weird thing is, the page is now updated but the build shows as failed. I will post a link on forum to see if there are any changes that need to be made.

If you think its good, can close this.
