### ISSUE TITLE
Ogre importer ignores receive_shadows

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#647]
It looks like com.jme3.scene.plugins.ogre.MaterialLoader#readMaterialStatement() parses the receive_shadows statement in the .material file and then forgets about it. As a result, models imported from Ogre always have ShadowMode=Inherit (which may have the effect of Off) even when the original model had "receive_shadows on".

I discovered this bug  in JME 3.1.0-stable using a model exported from MakeHuman.

**Comment by thoced** [comment]
I will try, I will try to solve this problem. but I do not promise anything
Thoced

**Comment by DomenicDev** [comment]
Seems like this issue can be closed since the commit has now been successfully merged into master.
