### ISSUE TITLE
Website broken gateway nginx

### ISSUE THREAD

**Issue by mitm001** [jMonkeyEngine/jmonkeyengine#653]
There was a post on the forum about broken links today and whoever wrote it gave directions for fixing them editing the nginx file.

It didn't work. Now the forum is serving up 502 Bad Gateway, nginx.

No other way to let you know so hopefully this gets through.

**Comment by mitm001** [comment]
Am I the only one experiencing this problem with the forum?

**Comment by jayfella** [comment]
No. We are aware. Sorry for the inconvenience. It will be fixed asap.

**Comment by mitm001** [comment]
np, ill close issue.

**Comment by Sailsman63** [comment]
Well, it was back for a while yesterday, and is now gone again. Pinging, just in case site admins thought that  this was corrected.

**Comment by grizeldi** [comment]
Still there for me

**Comment by mitm001** [comment]
Its still down for me, now Saturday. It showed back up for 10 min and been down since.

**Comment by Nehon** [comment]
we are experiencing some difficulties with the forum to say the less... the 3 persons that have the keys of the house are out of town... and there is not much we can do about it except wait.

**Comment by AquariusPower** [comment]
do you have a read-only copy of the community forum? 
if not, could this  be a good time to create one?
some things we can still read thru google's cache, but many are hard to find even there...
well, some ppl will just earn more points on stackexchange I guess :)

**Comment by kwando** [comment]
Issue should be temporarily fixed now.

**Comment by mitm001** [comment]
Closing.

**Comment by JESTERRRRRR** [comment]
nooooooooooooooooooooooooooooooooooooooooo it's back

**Comment by AquariusPower** [comment]
@JESTERRRRRR 
https://hub.jmonkeyengine.org/t/why-it-was-down/38569/44
