### ISSUE TITLE
Lost positional attributes when saving WaterFilter.

### ISSUE THREAD

**Issue by jmecn** [jMonkeyEngine/jmonkeyengine#654]
[com.jme3.water.WaterFilter](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-effects/src/main/java/com/jme3/water/WaterFilter.java)

these 3 attributes are not saved in `public void write(JmeExporter ex)`

     //positional attributes
    private Vector3f center;
    private float radius;
    private AreaShape shapeType = AreaShape.Circular;

**Comment by empirephoenix** [comment]
Hm, can you make a patch and do a pullrequest? I would be happy to merge this then.

**Comment by jmecn** [comment]
ok, I'll do it tonight.

**Comment by jmecn** [comment]
@empirephoenix I made a pr again to fix this problem.
