### ISSUE TITLE
jmonkeyplatform 3.1 sdk Windows 10 64-bit fails to install

### ISSUE THREAD

**Issue by midikiman** [jMonkeyEngine/jmonkeyengine#659]
I downloaded jmonkeyplatform-windows-x64.exe from the 3.1 (stable) section. It started, displayed the first window with the progress bar, went to 100%, then quit. No jmonkeyengine process remained active in the system, no jmonkeyengine installation was apparent anywhere. The log file in .jmonkeyplatform-installer/log ended with the line:
[2017-05-15 14:57:47.552]:         ... creating JFileChooser object to check possible issues with UI
No file chooser was displayed, so I assume there's some other problem here causing the process to fail.

It's not clear how to use jmonkeyengine without the SDK. Should I just download and unpack the zip file and use it in my currently installed versions of Netbeans and the JDK? Will that work?

**Comment by midikiman** [comment]
Oh, there are some jre dump logs in the directory where I ran the installer, one for each attempt. First one attached, access violation in "Swing-Shell" thread.
[hs_err_pid12144.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/1002312/hs_err_pid12144.zip)

**Comment by iamcreasy** [comment]
What windows version you are using? You can try temporarily disabling User Account Control(UAC) feature on Windows. [Source](https://www.java.com/en/download/help/exception_access.xml)

**Comment by midikiman** [comment]
Windows 10 home, 64-bit. Turning off UAC made no difference, unfortunately. Guess I'll have to try using jME without the SDK, or go with a different engine.

**Comment by iamcreasy** [comment]
Try a couple more. On my computer java -version yields the following,
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

But on your error log is says you are using an older versions or JRE and JVM,
```
JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode windows-amd64 compressed oops)
```

Try updating to latest JRE and JVM.

**Comment by midikiman** [comment]
I updated to 131 and uninstalled earlier versions, "java -version" reports 1.8.0_131, but the error message in the hs_err file didn't change. It still crashes with a memory access exception (0xc0000005 reading address 0), and reports version 8.0_111-b14. I don't have 111 installed on my machine, so I'm guessing it's using code baked into the installer exe..

**Comment by iamcreasy** [comment]
Can you post the hs_err_pidXXX again. Also, please post the output of your 'java -version'.

**Comment by midikiman** [comment]
OK. hs_err, installer log, and screenshot of "java -version".
[installer-crash-logs.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/1003217/installer-crash-logs.zip)

**Comment by iamcreasy** [comment]
It's a NetBeans issue, not a jMP issue. I tried to find the solution and here is what I've found so far, [1](https://netbeans.org/bugzilla/show_bug.cgi?id=122101), [2](https://forums.netbeans.org/post-34228.html) and [3](http://w.planetnetbeans.org/topic7912.html).

**Comment by midikiman** [comment]
Thank you for looking into the problem. It seems from those bug threads that the installer expects to be installing the only version of Netbeans on the system, a flaw that it inherited from the base platform. I'm not sure I want to scrap the version I have yet.

I unpacked the platform zip file and can run the SDK from there, so I think the issue is resolved. It only finds one of the graphics drivers (this machine has both Intel and nVidia cards installed, it's only listing Intel), and the connection to grab the 'welcome' screen times out, but those are minor quibbles. I think you can close this issue.

**Comment by grizeldi** [comment]
@midikiman connection for the welcome screen times out because the server for it went bananas a while ago

**Comment by MeFisto94** [comment]
> that the installer expects to be installing the only version of Netbeans on the system, a flaw that it inherited from the base platform. I'm not sure I want to scrap the version I have yet.

Without looking into logs or the issues, this seems only partially true. The installer has this flaw, yes, however it should only apply to previous SDK Installations, since we use `jmonkeyplatform` instead of `netbeans` or something as our product name. So what you could try is deleting `.jmonkeyplatform` and `.jmonkeyplatform-installer` and similar in your user directory (it might be hidden by default, though) and restart the installer. Did you previously have an SDK installed once? 

Updating the JDK/JRE is unrelated, by the way, since the SDK comes with it's own JDK bundled (except when you use the zip file, so maybe the jdk which is currently bundled is for some reason incompatible with your setup)

>  It only finds one of the graphics drivers (this machine has both Intel and nVidia cards installed, it's only listing Intel),
This is as far as I know a flaw of JME's design, It simply picks the first (compatible?) GPU lwjgl returns, since at the time JME was created there were no integrated GPUs.

Or am I wrong? If not, we might want to change that in "some clever way", @Nehon @shadowislord ?
