### ISSUE TITLE
SkeletonDebugger doesn't clone properly

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#660]
SkeletonDebugger extends Node. Node implements JmeCloneable and overrides the cloneFields() method. SkeletonDebugger doesn't override cloneFields(), so when the cloner encounters a SkeletonDebugger instance, it applies Node.cloneFields(). The result: two SkeletonDebugger instances sharing the same points and wires.

I discovered this in 3.1-stable

**Comment by stephengold** [comment]
Thanks for the fix.

**Comment by Bekreth** [comment]
Can this ticket be marked as close?

**Comment by Nehon** [comment]
it can ;) thanks
