### ISSUE TITLE
Spatial.getUserData sometimes returns NaN

### ISSUE THREAD

**Issue by dragon0** [jMonkeyEngine/jmonkeyengine#676]
When using float Custom Properties in Blender, `getUserData` will sometimes return NaN. It seems to work for fractions divisible by a power of 2 (eg 1.5, 0.5, 0.0625), but returns NaN for others (eg 1.1, 0.1, 0.05). Someone else encountered this issue a few months ago: https://hub.jmonkeyengine.org/t/blender-exporter-exporting-custom-property-float-is-nan/38135

This is most likely due to some rounding errors somewhere in the import/loading pipeline.

To test, I created a BasicGame, created a model using `New > Blender > Box prepared for UV texturing`, added a Custom Property to the Cube object, converted to J3O Binary, and added the following code to `simpleInitApp`:

```java
        Spatial customproperty = assetManager.loadModel("Models/customproperty.j3o");
        Spatial cube = ((Node)customproperty).getChild("Cube");
        float prop = cube.getUserData("prop");
        System.out.println(prop);
```

Tested with releases https://github.com/jMonkeyEngine/sdk/commit/80f2257763de37f45a12e988e37959178aa27030 and https://github.com/jMonkeyEngine/sdk/commit/1523305e30186605b19506b32241e8499c3e9ac6

**Comment by quazi-irfan** [comment]
I can reproduce this error with 3.1.0-stable and blender 2.78c(Win 64). But I am loading the blend file instead of converting it to j3o.

**Comment by OvermindDL1** [comment]
> I'll look more into it tomorrow.

@quazi-irfan How's it going?

**Comment by quazi-irfan** [comment]
@OvermindDL1 I haven't had the chance to look into it. But thanks for the reminder.

**Comment by stephengold** [comment]
Since jme3-blender was removed from the Engine on 19 April 2020, this issue is now moot.
