### ISSUE TITLE
Camera Spinning with Gamepad

### ISSUE THREAD

**Issue by SpaceboyRoss01** [jMonkeyEngine/jmonkeyengine#685]
I'm adding in gamepad and joystick support for my game, but the camera is just spinning. I can still kind of move the camera, however, it's difficult. The player is also constantly making minute movements on the map. Does anyone know how to fix this?

**Comment by thoced** [comment]
Hello, have you disabled the flycam?

By leaving the flycam on enable, generally without intercepting the entries of the gamepad, the camera can be directly controlled

How do you retrieve gamepad entries?

Try using the addRawInputListener method in InputManager.

For the future, I think the forum https://hub.jmonkeyengine.org/ is more appropriate to ask your question

**Comment by SpaceboyRoss01** [comment]
I am using the addRawInputListener method in InputManager.

**Comment by thoced** [comment]
You must retrieve the value using the getValue method of the JoyAxisEvent object.

The value will be between -1f and + 1f, for example, multiply this value by a factor and apply it to your transformations that will move your character or something else.

**Comment by SpaceboyRoss01** [comment]
That part works for moving the player, but not yet the camera

**Comment by pspeed42** [comment]
Step 1: ask trouble shooting questions on the forum.
Step 2: ask trouble shooting questions on the forum.
Step 3: ask trouble shooting questions on the forum.

**Comment by grizeldi** [comment]
@SpaceboyRoss01 is your gamepad by any chance xbox based?

**Comment by SpaceboyRoss01** [comment]
Yes
