### ISSUE TITLE
GLSL Error

### ISSUE THREAD

**Issue by JavaSaBr** [jMonkeyEngine/jmonkeyengine#690]
I have the error with core shader on macOS:
https://gist.github.com/anonymous/163d94fa217837d23832d264584aeafb
@Nehon do you have any idea how to fix it?

**Comment by Nehon** [comment]
Seems that the glslcompat.glsllib was not included in the shader

**Comment by JavaSaBr** [comment]
@Nehon Are you going to fix it? or I can make a PR with it

**Comment by Nehon** [comment]
I'm in vacations in a zoo right now so I'd appreciate à PR 😉

**Comment by JavaSaBr** [comment]
@Nehon https://github.com/jMonkeyEngine/jmonkeyengine/pull/691
