### ISSUE TITLE
OpenCLObjectManager calls gc every 10 frames.

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#695]
OpenCLObjectManager calls gc every 10 frames if you have at least one native object. Not really a good idea since you may have long lived objects and this code will still call gc every few ms.

Imo GC should be called by the developer when (if) needed and not by the engine.

**Comment by riccardobl** [comment]
Oh, yes, i forgot: https://github.com/jMonkeyEngine/jmonkeyengine/blob/445f7ed010199d30c484fe75bacef4b87f2eb38e/jme3-core/src/main/java/com/jme3/opencl/OpenCLObjectManager.java#L98

I'm not sure that an hybrid approach would be good either.

My understanding is that there are two ways to deallocate a native object in this implementation:

1. By manually deallocating the object like you would normally do in opencl

2. By letting java's gc handle the deallocation

the gc hack in OpenCLObjectManager is used to force the gc to deallocate the java pointers (and thus their cl counterpart) ,for developers that use the second method, that otherwise wouldn't be deallocated because the actual java object seen by the gc is too small to trigger the deallocation.

The issue i see in this is that you have no benefit in using method 2.

Imo native objects should be deallocated only manually and the deallocation on gc should be considered as last resort for developer who forget to properly deallocate the memory. Trigger the gc constantly to make up for who forgets to deallocate large objects is imo not a good idea.

Also this is not something like aparapi that is supposed to work transparently, you have to know opencl and if you do know opencl chances are that you also have an idea about memory deallocation.

**Comment by empirephoenix** [comment]
O.o Runtime.getRuntime().gc(); of I see what you mean, no go. I thought it uses some only opencl related cleanup. Invoking the main gc stutters for up to a second. Can you create a Pull request that removes that part?

**Comment by riccardobl** [comment]
Yes, but i don't know if the rest of the code relies on this, we could end up with objects that are never deallocated... Let's see what @shamanDevel has to say before.

**Comment by gouessej** [comment]
I advise you to read my explanation, it's about OpenGL but it's still valid for OpenCL:
https://stackoverflow.com/questions/3496508/deallocating-direct-buffer-native-memory-in-java-for-jogl#26777380

The native counterpart is the native memory allocated for the direct byte buffer, isn't it?

**Comment by riccardobl** [comment]
Well this is another problem that I assume is handle correctly in the code. But here we are talking about native memory on the gpu, the direct buffer is used to send the data from java to the cl api, then the cl api uploads it to the gpu vram (at this point you can free the native buffer), then when you have finished using it you should tell cl to deallocate it, the cheat here is to add the deallocation code to the finalize method of the java object that hold its pointer, so that the deallocation is triggered by the java gc when there are no more references to it and when the gc is called... and that's the problem, the gc is not called immediately if you don't trigger System.gc manually.

**Comment by shamanDevel** [comment]
Hi everyone,
@riccardobl  summarized it very well. There are two ways to deallocate the native objects: manually and with the gc. As long as you only use the manual deallocation, the gc is not called every 10 seconds. That's the preferred way.
The second way is more tricky. The OpenCL-objects are very tiny. For example, an OpenCL-Buffer only stores the pointer to the native memory and a link to a releaser. Including any JVM overhead, this comes probably down to less than a dozen bytes. While on the GPU, this object can hold maybe a GB of memory and the JVM does not see this memory at all. Same holds for driver-objects like events. Hence the JVM will not release the Java-Objects for a long time, resulting in the out-of-memory errors on the native side. This is why I explicitly call the gc.
At least in my experiments, this was the only way that I found.
Any suggestions are welcome.

**Comment by riccardobl** [comment]
If I allocate an object at the beginning of the application and deallocate it manually at the end of it, wouldn't this cause the gc to be called every 10 frames in the meantime? 
I didn't read the full code, but that's my understanding, only if you deallocate in the same frame the gc is not called.

**Comment by shamanDevel** [comment]
No, the OpenCLObjectManager comes only in play when you call OpenCLObject.register(). This tells the ObjectManager that there is an object that you want to be handled by the gc. Only then is Runtime.getRuntime().gc() called every 10 seconds.
So as long as you don't call register() and handle it only manually, the gc won't be called.

Note: OpenCLObject.register() is only a hint: objects are still deallocated by the gc using finalize() as a last resort, if you forget to call register() or release().

**Comment by gouessej** [comment]
It's similar to the situation in OpenGL with vertex buffer objects, they use some memory on the GPU too and you need a direct NIO buffer for the transfer from Java to C. If you call the garbage collector on objects that aren't finalized yet, it might be completely useless. You could run the finalization and then "call" the garbage collector (System.gc() doesn't always call the garbage collector, it's just an hint) but it's counter-intuitive because there is no pressure on the Java heap as the Java part of an OpenCL object is tiny.

If I were you, I would use phantom references and allow manual deallocation. When Java tells you that an object has become reclaimable by the garbage collector, you can run your own pre-mortem cleanup actions, for example deallocating the memory on the native heap (used by the direct NIO buffer) and telling OpenCL to release the resources used on the GPU. When there isn't enough pressure on the Java heap, manual deallocation might be the only solution.

**Comment by riccardobl** [comment]
Ok, i thought all objects were registered automatically. Then it's a non issue i guess, you just don't use the object manager and you are fine.

**Comment by gouessej** [comment]
Oops, you already use PhantomReference...

**Comment by gouessej** [comment]
@shamanDevel Is there still anything wrong? As long as com.jogamp.opencl.CLBuffer.release() or any equivalent method is called to release the OpenCL resource, it should work. Is it what you mean by "we are running out of host memory on the OpenCL side quickly"? host memory on the OpenCL side = OpenCL resource?

**Comment by gouessej** [comment]
Maybe calling Runtime.runFinalization() would be enough. Now I understand your code. You call Runtime.getRuntime().gc() so that the OpenCL object is seen as reclaimable by the garbage collector earlier.

**Comment by gouessej** [comment]
Is there a reason why OpenCLObjectRef.clear() is never called? You should declare refQueue as a ReferenceQueue<OpenCLObjectRef> as only OpenCLObjectRef instances are enqueued and it would eliminate a useless cast.

**Comment by shamanDevel** [comment]
Oh, yes, the cast is completely useless. I'll change that.
What do you mean with OpenCLObjectRef.clear()? When should Reference.clear() be called? When the user deletes an object that was registered in the queue?
Honestly, I'm not very experienced with all the references and gc internals. I copied most of the cody of OpenCLObjectManager from com.jm3.util.NativeObjectManager.

**Comment by shamanDevel** [comment]
And to your comment above: no, the code should not be wrong in the sense that no memory leak should be produced.
But because the gc potentially delays the deletion of e.g. Event extremely, the driver will crash sometimes because it runs out of handles for event objects. At least I experienced that in my code.

**Comment by gouessej** [comment]
Reference.clear() should be called when you're done with the referent.

In my humble opinion, bothering the garbage collector so often can have some side effects, it doesn't help Java to behave consistently, I had this kind of problem when I did this kind of thing in my own first person shooter about ten years ago. If Java can't know whether an object is used without using dirty tricks impacting the performance, it should be up to the developer to tell the manager when such an object has become useless. The objects whose memory is allocated on the Java heap are managed by the garbage collector, the objects whose memory is allocated on the native heap aren't managed by the same mechanism in Java, the native memory of the direct NIO buffers is released by some "cleaners", the "objects" whose memory is allocated neither on the Java heap nor on the native heap shouldn't rely on the garbage collection. I understand your problem, you can't create an OpenCL buffer when you run out of memory on the GPU but I disagree with your solution. OpenJFX/JavaFX has the same kind of concern and it doesn't call the garbage collector potentially several times per second.

The native object manager doesn't call the garbage collector whereas it has to solve a similar problem. I could create a huge VBO whose data reside only on the GPU... A native object can be enqueued and freed later.

**Comment by shamanDevel** [comment]
So your opinion is to remove this repeating gc() call completely?

**Comment by gouessej** [comment]
Yes. My main concern was that some variable changes done just before calling System.gc() were lost or at least postponed which caused some bugs and driving those variables volatile didn't fix it. As long as there is a mechanism to indicate that an object has to be "freed" in a timely manner, it's ok for me, there is no need of using the garbage collection for this purpose. Your code is already smart and kind enough without System.gc() and Runtime.getRuntime().gc().

**Comment by shamanDevel** [comment]
So, the pull request is here.
@gouessej I can't drop the casts related to the ReferenceQueue. The PhantomReference has the following constructur: `PhantomReference(T referent, ReferenceQueue<? super T> q)`. But here, the referent is an `OpenCLObject` but the queue contains the `OpenCLObjectRef` instances. So I need to use the more general Object type. 
Remark: This is also how the `NativeObjectManager` handles the stuff.
