### ISSUE TITLE
copy pasted comment needs to be updated in FlyByCamera.java

### ISSUE THREAD

**Issue by ericchase** [jMonkeyEngine/jmonkeyengine#697]
[FlyByCamera.java](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/input/FlyByCamera.java#L133)

![image](https://user-images.githubusercontent.com/30473157/28991592-9252dab6-794f-11e7-9a70-b133c1e3890a.png)

**Comment by stephengold** [comment]
Fixed in master by PR #748 at commit 082fea9 .
