### ISSUE TITLE
J3MLoader warnings while loading glTF sample models

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#741]
Using recent 'master' builds of JME3 to load various models from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0 (including "2CylinderEngine/glTF/2CylinderEngine.gltf") I get warnings similar to this:

Sep 07, 2017 11:28:19 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'Glow':
Define 'HAS_GLOWMAP' mapped to non-existent material parameter 'GlowMap', ignoring.
Sep 07, 2017 11:28:19 PM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'Glow':
Define 'HAS_GLOWCOLOR' mapped to non-existent material parameter 'GlowColor', ignoring.

**Comment by Nehon** [comment]
@stephengold hasn't it been fixed by this commit? https://github.com/jMonkeyEngine/jmonkeyengine/commit/37e4d4d564f7bc21fdc6a3ff122fc221bc6e959f

**Comment by stephengold** [comment]
I'll verify. Thanks!

**Comment by stephengold** [comment]
Yup. The warnings are gone as of jMonkeyEngine 3.2-6361 (hash c17c3e9). Thanks again!
