### ISSUE TITLE
attachment nodes are not compatible with ignoreTransform geometries

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#742]
When the animated Geometry has ignoreTransform=true, attachment nodes fail to take this into account, causing the attached object to appear in the wrong location.

To see this issue in action, add the following line of code to TestAttachmentsNode:

((Geometry)((Node)model).getChild(0)).setIgnoreTransform(true);

Discovered in 'master' branch at Git hash 66137d5.

**Comment by Nehon** [comment]
Not sure this can be fixed easily and to me it's a very  rare corner case.
Doesn't completely worth the effort of fixing it IMO.
What do you think @stephengold ?

**Comment by stephengold** [comment]
Yes, it's a corner case. Also, I expect that attach nodes will be deprecated when SkinningControl supplants SkeletonControl.

**Comment by Nehon** [comment]
Not really, this system will stay in place in SkinningControl

**Comment by stephengold** [comment]
I'm willing to work on a fix, then. Taken!

**Comment by stephengold** [comment]
I tested the fix. Looks good.

**Comment by pspeed42** [comment]
The weird thing about including this in 3.2.2 is the new functionality "Spatial.setWorldTransform()" (which I'm not 100% happy with the name but neither can I think of one better... just a shame to imply a bean-style setter that isn't really.)

Also, while it may be unlikely, could it be the case where some user has a malformed model that has ignore transform set on an attachment and doesn't realize it?  Now this change will break their game.  So I'm inclined to not include this in 3.2.2.

**Comment by stephengold** [comment]
Nehon also though the name was weird, so he did a follow-up commit to eliminate the new Spatial method. See hash 824e99c in `master`.
