### ISSUE TITLE
SkeletonDebugger is not compatible with ignoreTransform geometries

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#743]
When the animated Geometry has ignoreTransform=true, the SkeletonDebugger fails to take this into account, causing the skeleton visualization to appear in the wrong location.

To see this issue in action, add the following code to TestAnimBlendBug:

import com.jme3.scene.Geometry;
...
((Geometry)model1.getChild(0)).setIgnoreTransform(true);

Discovered in 'master' branch at Git hash 66137d5.

**Comment by Nehon** [comment]
In 3.3 SkeletonDebugger will be deprecated and there will be an ArmatureDebugger that works completely differently and should address this issue.
