### ISSUE TITLE
CollideIgnoreTransformTest.testPhantomTriangles: NPE

### ISSUE THREAD

**Issue by kruchinin-pavel** [jMonkeyEngine/jmonkeyengine#749]
Fix is attached. I wished i would fix it directly, but too amateur for this repo to work.
[CollideIgnoreTransformTest.NPE.fix.patch.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/1346117/CollideIgnoreTransformTest.NPE.fix.patch.zip)

**Comment by stephengold** [comment]
I'm OK with this change, and am available to integrate it, once wiser heads have reviewed it.

**Comment by Nehon** [comment]
looks fine

**Comment by stephengold** [comment]
Fixed in 'master' branch by pull request #750 (commit hash 94e828f).

@kruchinin-pavel please indicate whether or not the issue is resolved to your satisfaction.

**Comment by stephengold** [comment]
Since the user who opened the issue has been unresponsive, mark this as closed.
