### ISSUE TITLE
WireSphere generates parallels with wrong radii

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#762]
Meshes generated by com.jme3.scene.debug.WireSphere are inaccurate because the parallel circles have the wrong radii -- they do not lie on the surface of the sphere being visualized.

The errant code is in the updatePositions() method:

`float scale = FastMath.sin(b * FastMath.PI);`

where b varies from roughly 0 to 1. The correct formula would be something like:

`float scale = FastMath.sqrt(4f * (b - b * b));`

**Comment by pspeed42** [comment]
I admit the old code is wrong... by looking at it I see that it's treating b as an angle when it's clearly a vertical slice.

...but where does this formula come from:
float scale = 2f * FastMath.sqrt(b - b * b);

I might have calculated the scale differently.  But I'd have also calculated b differently, I guess.  If it ran 1 to -1 then I guess scale would be more straight forward maybe?  sqrt(1 - b * b) if my envelope math is right.  I guess that's not too different but it's closer to an inversion of Pythagoras: a*a + b*b = c*c... where c = 1

**Comment by stephengold** [comment]
If b ranged from -1 to 1, the formula would be sqrt(1 - b*b).

But since b ranges from 0 to 1, you have substitute B = 2*b - 1 into sqrt(1 - B*B).

Then algebra happens:
1 - B*B = 1 - (2*b - 1)*(2*b - 1) = 1 - (4*b*b - 4*b + 1) = 1 - 4*b*b + 4*b - 1 = -4*b*b + 4*b
            = 4*(-b*b + b) = 4*(b - b*b)

And of course the 4 gets pulled out of the radical as a 2...

**Comment by stephengold** [comment]
Fixed in 'master' branch at hash=47a46a8.
