### ISSUE TITLE
Problems with double Packages with JDK9/Jingsaw

### ISSUE THREAD

**Issue by ASDFGamer** [jMonkeyEngine/jmonkeyengine#768]
There is currently a problem with same Package names in different modules wich leads to an build error in JDK9 with Jingsaw-modules. 
For example the package come.jme3.app is in both jme3.core and jme3.desktop.

**Comment by pspeed42** [comment]
You will have to make a really strong case as to why this is a problem... because that's a pretty typical development practice and we are unlikely to stop doing it.  It could just be that we are never going to be compatible with "jingsaw" (sic).

**Comment by ASDFGamer** [comment]
Ok, thanks for the quick answer, i was just curious.
