### ISSUE TITLE
GammaCorrectionFilter is deprecated in 3.2

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#781]
I'm unhappy that GammaCorrectionFilter is deprecated in JME 3.2.0-alpha1 . SkyControl uses it for an off-screen render, where AppSettings isn't a viable solution. I could write my own filter, but that seems like a waste, given that the Engine already provides that functionality.

**Comment by empirephoenix** [comment]
What is the reason that it was deprecated? Eg. what does the commit say?

**Comment by stephengold** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/commit/f7181c38dc1720d3df491b7ccac048ffc59817d6#diff-6d6b25ca99b0a3b73d214a0a675b890f

```
Removed all xxx15.frag shaders and used GLSLCompat to have the same shader whatever version it's used for
```

**Comment by Nehon** [comment]
The reason is that it's just wrong to handle gamma correction like this. There is a lot more to it than just correcting the last image of the filter stack.
Also it should not be needed anymore, you can set gamma correction on in the app settings, and it will handle it properly even with post process.
Steve has a corner case where he has a custom offscreen render, we need to discuss this as there are a couple of things to know to do it properly.

**Comment by stephengold** [comment]
@pspeed42  pointed out that what I want is actually a contrast filter. From digital photography, I'm accustomed to adjusting contrast using a gamma function. For reference:

https://en.wikipedia.org/wiki/Image_editing#Gamma_correction

**Comment by stephengold** [comment]
In addition to the deprecation warning at compile time, I get an AssetNotFoundException at runtime (in JME 3.2.0-alpha1):
```
Dec 03, 2017 5:30:55 PM jme3utilities.sky.test.TestGlobeRenderer simpleInitApp
INFO: jme3-core version is "jMonkeyEngine 3.2-alpha1"
Dec 03, 2017 5:30:55 PM jme3utilities.sky.test.TestGlobeRenderer simpleInitApp
INFO: SkyControl version is "master 0.9.6+1"
Dec 03, 2017 5:30:55 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.asset.AssetNotFoundException: Common/MatDefs/Post/GammaCorrection.j3md
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.material.Material.<init>(Material.java:108)
	at com.jme3.post.filters.GammaCorrectionFilter.initFilter(GammaCorrectionFilter.java:68)
	at com.jme3.post.Filter.init(Filter.java:251)
	at com.jme3.post.FilterPostProcessor.initFilter(FilterPostProcessor.java:189)
	at com.jme3.post.FilterPostProcessor.reshape(FilterPostProcessor.java:500)
	at com.jme3.post.FilterPostProcessor.initialize(FilterPostProcessor.java:166)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1074)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1150)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stephengold** [comment]
Does JME 3.2 provide a contrast filter, or must I write my own?

**Comment by Nehon** [comment]
I'll try to add a contrast and color balance filter in a future release

**Comment by stephengold** [comment]
Why not simply un-deprecate the existing filter and rename it to ContrastAdjustmentFilter or something similar?

**Comment by Nehon** [comment]
well...because it does gamma correction for real, and some people might use it.. :p

**Comment by stephengold** [comment]
There's a contrast-adjustment filter in the 3rd-party Heart library that might provide a good starting point:
[https://github.com/stephengold/Heart/blob/master/HeartLibrary/src/main/java/jme3utilities/ContrastAdjustmentFilter.java](https://github.com/stephengold/Heart/blob/master/HeartLibrary/src/main/java/jme3utilities/ContrastAdjustmentFilter.java)

`ContrastAdjustmentFilter` is simply a power-law function on the red, green, and blue components. A more complete solution would also provide options to clip the input values and output values to specified ranges.

**Comment by Scrappers-glitch** [comment]
> There's a contrast-adjustment filter in the 3rd-party Heart library that might provide a good starting point: https://github.com/stephengold/Heart/blob/master/HeartLibrary/src/main/java/jme3utilities/ContrastAdjustmentFilter.java
> 
> Heart's `ContrastAdjustmentFilter` is simply a power-law function on the red, green, and blue components. A more complete solution would also provide options to clip the input values and output values to specified ranges.

Thanks for sharing, i just may need this to forcefully solve another issue #809 , i am not so sure of your intentions concerning this issue, would you un-deprecate this in v3.5 ?

**Comment by stephengold** [comment]
> would you un-deprecate this in v3.5 ?

It's not decided yet. Un-deprecating would be the easiest solution for this issue, if nobody objects. And with Nehon gone, I can't imagine who would object.

Creating a replacement filter would be extra work, but might bring additional benefit.

I'll open a discussion about this at the Hub/Forum.

**Comment by stephengold** [comment]
https://hub.jmonkeyengine.org/t/gammacorrectionfilter/45076

**Comment by Scrappers-glitch** [comment]
Check the PR :-) https://github.com/jMonkeyEngine/jmonkeyengine/pull/1665
