### ISSUE TITLE
FlyByCamera doesn't work with JOGL

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#796]
If the JOGL_OPENGL_BACKWARD_COMPATIBLE renderer is selected, FlyByCamera with default settings (dragToRotate=false, invertY=false, canRotate=false) seems only able to turn downward and to the right. 

Also, each time the mouse cursor leaves and re-enters the display (in windowed mode) it jumps to the upper-left corner of the display.

Same result with both jMonkeyEngine 3.1.0-stable and 3.2.0-stable.
Same result with JOGL_OPENGL_FORWARD_COMPATIBLE. 

FlyByCamera works as expected when the LWJGL_OPENGL2 renderer is selected, in both 3.1 and 3.2.

Here is my test app:
```
package mygame;

import com.jme3.app.SimpleApplication;
import com.jme3.font.BitmapText;
import com.jme3.material.Material;
import com.jme3.math.ColorRGBA;
import com.jme3.scene.Geometry;
import com.jme3.scene.shape.Box;
import com.jme3.system.AppSettings;

public class Main extends SimpleApplication {

    BitmapText bitmapText;

    public static void main(String[] args) {
        Main app = new Main();
        app.setShowSettings(false);
        AppSettings settings = new AppSettings(true);
        settings.setRenderer(AppSettings.JOGL_OPENGL_BACKWARD_COMPATIBLE);
        app.setSettings(settings);
        app.start();
    }

    @Override
    public void simpleInitApp() {
        Box b = new Box(1, 1, 1);
        Geometry geom = new Geometry("Box", b);

        Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        mat.setColor("Color", ColorRGBA.Blue);
        geom.setMaterial(mat);

        rootNode.attachChild(geom);
    }
}
```

**Comment by stephengold** [comment]
@gouessej Any insight into this issue?

**Comment by gouessej** [comment]
There is probably a problem in the way the cursor is managed. I lack of time to investigate this bug right now.

**Comment by stephengold** [comment]
Since jme3-jogl was removed from the Engine on 15 April 2020, this issue is no longer our responsibility.
