### ISSUE TITLE
AbstractShadowRenderer.setEdgesThickness() is a no-op?

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#810]
I wasn't seeing any visible effect from varying the edge thickness of my shadow renderer, so I analyzed the source code.

 + setEdgesThickness() sets the "PCFEdge" parameter in the post-shadow material.
 + In "Common/MatDefs/Shadow/PostShadow.j3md",  PCFEdge defines PCFEDGE.
 + But there is no use of the PCFEDGE define, neither in PostShadow.frag nor PostShadow.vert

If the feature is no longer supported, perhaps we should deprecate the setEdgesThickness() method.

**Comment by Nehon** [comment]
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/resources/Common/ShaderLib/Shadows.glsllib#L163-L166
It's used in Shadows.glsllib which is where the actual shadow code is.

The result should be visible though, but especially on low resolution shadowmaps.

**Comment by stephengold** [comment]
Thanks. I'll recheck for visible effect.

**Comment by stephengold** [comment]
After gafiating for several months, I finally ran that check. I don't see any difference between setEdgesThickness(1) and setEdgesThickness(10), even in a closeup with a low-resolution shadowmap.

Here are images:
![dlsr thickness 1](https://user-images.githubusercontent.com/2287609/44540267-2da9d480-a6bb-11e8-8754-e2d45d58b844.png)
![dlsr thickness 10](https://user-images.githubusercontent.com/2287609/44540272-34d0e280-a6bb-11e8-9c58-7eebca7ced87.png)

And here is the source code:
```
package mygame;

import com.jme3.app.SimpleApplication;
import com.jme3.font.BitmapText;
import com.jme3.light.DirectionalLight;
import com.jme3.material.Material;
import com.jme3.math.ColorRGBA;
import com.jme3.math.Quaternion;
import com.jme3.math.Vector3f;
import com.jme3.renderer.queue.RenderQueue.ShadowMode;
import com.jme3.scene.Geometry;
import com.jme3.scene.Spatial;
import com.jme3.scene.shape.Box;
import com.jme3.shadow.DirectionalLightShadowRenderer;

public class Main extends SimpleApplication {

    DirectionalLight dl = new DirectionalLight();

    public static void main(String[] args) {
        Main app = new Main();
        app.start();
    }

    @Override
    public void simpleInitApp() {
        setDisplayFps(false);
        setDisplayStatView(false);
        flyCam.setEnabled(false);
        cam.setLocation(new Vector3f(-0.69f, 2.08f, -0.77f));
        cam.setRotation(new Quaternion(0.256207f, -0.653331f, 0.2510693f, 0.666693f));

        loadScene();

        DirectionalLightShadowRenderer dlsr;
        dlsr = new DirectionalLightShadowRenderer(assetManager, 256, 3);
        dlsr.setLight(dl);
        dlsr.setShadowIntensity(1f);
        //dlsr.setEdgesThickness(1); // minimum value
        dlsr.setEdgesThickness(10); // maximum value
        viewPort.addProcessor(dlsr);
        
        BitmapText text = new BitmapText(guiFont, false);
        text.setColor(ColorRGBA.Red);
        text.setSize(40f);
        
        int thickness = dlsr.getEdgesThickness();
        String message = String.format("thickness = %d", thickness);
        text.setText(message);
        float centerX = (cam.getWidth() - text.getLineWidth()) / 2;
        text.setLocalTranslation(centerX, cam.getHeight(), 0f);
        guiNode.attachChild(text);
    }

    void loadScene() {
        dl.setDirection(new Vector3f(-2f, -1f, -1f));
        rootNode.addLight(dl);

        Material white = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        white.setColor("Color", ColorRGBA.White);

        Box cube = new Box(1f, 1f, 1f);
        Spatial box = new Geometry("box", cube);
        box.setLocalTranslation(2f, 4f, 2f);
        box.setMaterial(white);
        box.setShadowMode(ShadowMode.Cast);
        rootNode.attachChild(box);

        Box slab = new Box(10f, 0.1f, 10f);
        Spatial ground = new Geometry("ground", slab);
        ground.setMaterial(white);
        ground.setShadowMode(ShadowMode.Receive);
        rootNode.attachChild(ground);
    }
}
```

**Comment by JESTERRRRRR** [comment]
Add this:

`dlsr.setEdgeFilteringMode(EdgeFilteringMode.PCFPOISSON);`

or some of the others from here:

https://javadoc.jmonkeyengine.org/com/jme3/shadow/EdgeFilteringMode.html


#if (FILTER_MODE == 2)
    #define GETSHADOW Shadow_DoDither_2x2
    #define KERNEL 1.0
#elif FILTER_MODE == 3
    #define GETSHADOW Shadow_DoPCF
    #define KERNEL 4.0
#elif FILTER_MODE == 4
    #define GETSHADOW Shadow_DoPCFPoisson
    #define KERNEL 4.0
#elif FILTER_MODE == 5
    #define GETSHADOW Shadow_DoPCF
    #define KERNEL 8.0
#endif

KERNEL must be >1.0 for it to have an effect

**Comment by stephengold** [comment]
Now I'm convinced that the feature works. Thank you!
