### ISSUE TITLE
BoneTrack.setKeyframes() throws NPE with assertions enabled

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#816]
If any of the translations/rotations/scales arguments to BoneTrack.setKeyframes() is null, an NPE is thrown, but only if assertions are enabled.  Null values are legal for these arguments.

Here are the problematic assertions:

```
        assert times.length == translations.length && times.length == rotations.length;
```
and
```
        assert times.length == scales.length;
```

I discovered this issue in 'master' branch, but it looks like it was introduced in JME v3.2.0 .

**Comment by Nehon** [comment]
well for this one 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/animation/BoneTrack.java#L145
null values are not valid.
for this one 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/animation/BoneTrack.java#L168
the assertion should be after the if(scale!=null) indeed

**Comment by stephengold** [comment]
I thought 3.2 allowed tracks without translations, for instance when importing from glTF.

**Comment by pspeed42** [comment]
And I don't really care if nulls are valid or not but assertions should not throw NPEs regardless.

**Comment by stephengold** [comment]
I've seen glTF import generates *spatial* tracks without translations. Are bone tracks different in this regard?
