### ISSUE TITLE
SpatialTrack.clone() sets the trackSpatial to null

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#825]
The clone() method for SpatialTrack invokes jmeClone() which invokes the SpatialTrack constructor. Unfortunately, the constructor does not set the trackSpatial field, and neither does jmeClone() nor clone(). As a result, the cloned track's trackSpatial is always null.

**Comment by pspeed42** [comment]
So we are not going to fix the cloning here or will that be a separate PR
or something?

**Comment by stephengold** [comment]
I'll make a separate PR.
