### ISSUE TITLE
BoneTrack.clone() adds scales

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#829]
When a BoneTrack with scales == null is cloned, the result is a track with scales != null. While this behavior doesn't change the appearance of the animation, it is unexpected and unnecessary.

**Comment by pspeed42** [comment]
Is BoneTrack also using a strange patter for clone()?  Or is this a
different issue?

**Comment by stephengold** [comment]
BoneTrack isn't even JmeCloneable, so it's setting a bad example for others.

**Comment by stephengold** [comment]
PR#830 should've fixed this.
