### ISSUE TITLE
MaterialDebugAppState is not reloading the changed shader instead reloads the old one

### ISSUE THREAD

**Issue by b00nation** [jMonkeyEngine/jmonkeyengine#843]
If a shader-file has changed the application recognizes correctly the change, but the reload of the material actually reloads the old shader code instead of loading the new code. This is caused by the TechniqueDefault deep in the MaterialDefiniton.

**Comment by Nehon** [comment]
Could you provide a test case please

**Comment by b00nation** [comment]
Sure here you go:

[Issue840.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/1800826/Issue840.zip)

**Comment by Nehon** [comment]
fixed in https://github.com/jMonkeyEngine/jmonkeyengine/pull/840
Thanks a lot
