### ISSUE TITLE
BlendEquations and BlendFactors gets not updated correctly

### ISSUE THREAD

**Issue by theMinka** [jMonkeyEngine/jmonkeyengine#848]
## Problem description
I have two objects my scene with different materials. Each material uses the same `RenderState.BlendMode` (in my case its `RenderState.BlendMode.Custom`), but they use different `RenderState.BlendEquation`'s and _BlendFactors_.
Everything works fine, as long as only one of the two objects is visible. If both objects gets rendered at the same time, one of the materials always reuses the _BlendEquations_ and _BlendFactors_ of the other one. This behavior occurs always on the second rendered object (depending on the rendering order). Therefore this effect can switch to the other object, if the camera gets repositioned.

## Simple example for reproducing this bug
```java
package myexample;

import com.jme3.app.SimpleApplication;
import com.jme3.light.DirectionalLight;
import com.jme3.material.Material;
import com.jme3.material.RenderState;
import com.jme3.math.ColorRGBA;
import com.jme3.math.Vector3f;
import com.jme3.renderer.queue.RenderQueue;
import com.jme3.scene.Geometry;
import com.jme3.scene.Spatial;
import com.jme3.scene.shape.Quad;

public class BlendModeBugTest extends SimpleApplication {

    public static void main(String[] args) {
        BlendModeBugTest app = new BlendModeBugTest();
        app.start();
    }

    @Override
    public void simpleInitApp() {
        DirectionalLight directionalLight = new DirectionalLight();
        directionalLight.setColor(ColorRGBA.White);
        directionalLight.setDirection(Vector3f.UNIT_XYZ.negate());
        rootNode.addLight(directionalLight);

        cam.setLocation(new Vector3f(0f, 0.5f, 3f));

        Spatial teapotModel = assetManager.loadModel("Models/Teapot/Teapot.obj");
        teapotModel.move(0f, 0f, 0f);
        rootNode.attachChild(teapotModel);

        // Everything works fine, if only one of the two squads gets drawn.
        // If both of them gets drawn, always one of them uses the same blend equations
        // and factors of the other one.
        // (Have fun and move the camera left and right. ;) )
        createLeftSquad();
        createRightSquad();
    }

    private void createLeftSquad() {
        // This material reduces the red value of the underlying scene to 20%
        Material leftMaterial = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        leftMaterial.setColor("Color", new ColorRGBA(0.2f, 1f, 1f, 1f));

        // 0 * Source + Source * Destination   =   Source * Destination
        leftMaterial.getAdditionalRenderState().setBlendMode(RenderState.BlendMode.Custom);
        leftMaterial.getAdditionalRenderState().setBlendEquation(RenderState.BlendEquation.Add);
        leftMaterial.getAdditionalRenderState().setBlendEquationAlpha(RenderState.BlendEquationAlpha.Add);
        leftMaterial.getAdditionalRenderState().setCustomBlendFactors(
                RenderState.BlendFunc.Zero, RenderState.BlendFunc.Src_Color,
                RenderState.BlendFunc.Zero, RenderState.BlendFunc.Src_Alpha);

        Geometry leftQuad = new Geometry("LeftQuad", new Quad(1f, 1f));
        leftQuad.setMaterial(leftMaterial);
        leftQuad.setQueueBucket(RenderQueue.Bucket.Transparent);
        leftQuad.setLocalTranslation(-1f, 0f, 1f);
        rootNode.attachChild(leftQuad);
    }

    private void createRightSquad() {
        // This material reduces the green value of the underlying scene by 80%
        Material rightMaterial = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        rightMaterial.setColor("Color", new ColorRGBA(0f, 0.8f, 0f, 0f));

        // 1 * Destination - Destination * Source   =   (1 - Source) * Destination
        rightMaterial.getAdditionalRenderState().setBlendMode(RenderState.BlendMode.Custom);
        rightMaterial.getAdditionalRenderState().setBlendEquation(RenderState.BlendEquation.ReverseSubtract);
        rightMaterial.getAdditionalRenderState().setBlendEquationAlpha(RenderState.BlendEquationAlpha.ReverseSubtract);
        rightMaterial.getAdditionalRenderState().setCustomBlendFactors(
                RenderState.BlendFunc.Dst_Color, RenderState.BlendFunc.One,
                RenderState.BlendFunc.Dst_Alpha, RenderState.BlendFunc.One);

        Geometry rightQuad = new Geometry("RightQuad", new Quad(1f, 1f));
        rightQuad.setMaterial(rightMaterial);
        rightQuad.setQueueBucket(RenderQueue.Bucket.Transparent);
        rightQuad.setLocalTranslation(0f, 0f, 1f);
        rootNode.attachChild(rightQuad);
    }
}
```

## Problem analysis and possible solution
The _BlendEquations_ and _BlendFactors_ of a material has to be set to the renderer before rendering an object with the material. This is done in line 746~808 of the `GLRenderer`. Unfortunately the first if-statement checks, if the _BlendMode_ of the material differs from the _BlendMode_ already used by the renderer. Therefor if two different materials with the same _BlendMode_, but different _BlendEquations_ or _BlendFactors_ gets handled directly one after another by the renderer, no further update of the renderer occurs. The renderer will reuse the _BlendEquations_ and _BlendFactors_ of the first material when rendering the second one.

After tracking back the change history of the `GLRenderer`, I understood that the concept of the _BlendMode_ is much older than the possibility to customize the _BlendEquations_ and _BlendFactors_ directly on a material. As I understand it, a _BlendMode_ is just a predefined (common) combination of _BlendEquations_ and _BlendFactors_. Therefore setting the _BlendEquations_ and _BlendFactors_ should have nothing to do with one of the predefined _BlendModes_ at all. Unfortunately there has to be always a _BlendMode_ set. As a simple workaround `RenderState.BlendMode.Custom` was added, but there are multiple problems with the current implementation:
1. Setting different _BlendEquations_ has an effect on all _BlendModes_.
 This pervertes the original concept of the predefined _BlendModes_. Setting _BlendEquations_ or _BlendFactors_ should only affect `RenderState.BlendMode.Custom`.
2. The "common" _BlendModes_ currently only predefine the _BlendFactors_, but leaving the _BlendEquations_ open.
 Setting only one of the two aspects is much pointless. All "common" _BlendModes_ should also predefine the _BlendEquations_ to use, which is a simple _ADD_ for all of them by now.
3. The special mode `RenderState.BlendMode.Custom` is handled (and checked) as all the other "common" _BlendModes_.
 This is most of the reason for this reported bug. `RenderState.BlendMode.Custom` should be handled separately, because it can always provide different _BlendEquations_ and _BlendFactors_.

_

I think I can rework this part of the renderer without to much changes. I would be glad to provide a Pull-Request, if you guys are ok with that.

**Comment by Nehon** [comment]
Man, I wish every one post issues like that.
If you're up for a PR, please do!
I'll review it.
Thanks

**Comment by theMinka** [comment]
#849

**Comment by Nehon** [comment]
fixed in  https://github.com/jMonkeyEngine/jmonkeyengine/pull/849

**Comment by pspeed42** [comment]
Seems like in addition to the fix, some of the defaults changed.  I recommend leaving this one until 3.3.
