### ISSUE TITLE
PBR bloom not working

### ISSUE THREAD

**Issue by grizeldi** [jMonkeyEngine/jmonkeyengine#854]
PBR material definition's glowmap currently doesn't work with bloom filter. The Glow technique is using the Glow.frag shader which requires GlowMap or GlowColor material parameters. Those are not present in the PBR material definition. As the result, there's no bloom.

**Comment by Nehon** [comment]
This is intended, the GlowMode.Object will not work with the PBR material.
The intended way is to use an emissive color and/or an emissive map on the material and use regular bloom in GlowMode.Scene.
