### ISSUE TITLE
wiki 404

### ISSUE THREAD

**Issue by naserkhosravi** [jMonkeyEngine/jmonkeyengine#857]
hey;
We're trying to switch to jMonkeyEngine but today we got 404 error on wiki page of it!
where we can find any document like its wiki page? or is it possible to have its pdf or something?
myPreThanks

**Comment by grizeldi** [comment]
See here https://hub.jmonkeyengine.org/t/is-anyone-else-seeing-broken-link-to-wiki/

**Comment by shadowislord** [comment]
Thanks, the issue has been fixed in this commit:
https://github.com/jMonkeyEngine/wiki/commit/438a6d93c2cb70b82369e19ddb123b5ff865288e
