### ISSUE TITLE
Unable to use "import" in a shader node if it is used multiple times in a material

### ISSUE THREAD

**Issue by aegroto** [jMonkeyEngine/jmonkeyengine#858]
Importing an external file in a shader node results in a multiple definition compile error as its code gets included different times in the shader's code.

Using "define" in the shader node doesn't help. What i mean is that:
`#import "Common/ShaderLib/BlinnPhongLighting.glsllib"`

And: 
```
#ifndef IMPORT_BPL
    #define BPL
    #import "Common/ShaderLib/BlinnPhongLighting.glsllib"
#endif
```

Lead to the same result.
The final shader is this:

#ifndef IMPORT_BPL
    #define BPL
#endif

And after that the source code into /BlinnPhongLighting.glsllib, leaving the define totally ignored.

Possible solutions:
- A list of already included files in the shader node assembler (I'm not sure where is it located in jME's source code). Whenever an import is parsed it is first checked if its name is contained in the list.
- A simple application of define refactoring in all .glsllib files. I've already tested this method but didn't get it to work, don't know why, maybe I'm making some stupid mistakes.
- Having a specific and unique shader node for each stage of the pipeline to import files could be a solution, but it's a bit of a workaround and may complicate the workflow in my honest opinion.

**Comment by pspeed42** [comment]
Just some notes from my experience that may color what you say above:
-imports are done by JME because shaders don't support includes
-ifdefs are handled by the shader compiler after JME has already done its own import processing.

So, yeah, probably a set (not a list) of imported names to only do it once might be a solution.

**Comment by Nehon** [comment]
I'll check that, imports are supposed to be "deduplicated". There must be an issue.

**Comment by aegroto** [comment]
As far as i remember I tried to compile snapshots releases

**Comment by aegroto** [comment]
The fact that imports are injected once is still creating me issues.
The way those imports are added is uncontrollable to the programmer (I think that an alphabetical order is used), being impossible or unreliable to use imports in an already 'importable' file, like on glsllibs used in jME's core. This sort of nestability could be really useful.

I think that imports should just be copied in source code every time they get involved, then the programmer should be responsible to handle multiple importing with preprocessing annotations. This could lead to some incompatibility with older materials, but will make the import system more versatile.

**Comment by Nehon** [comment]
"(I think that an alphabetical order is used)" Nope... there is no sort . They are inserted in the backward order they have been found in the nodes declaration. That may be what troubles you and what can cause an issue in the case of imports of imports. The reason for the backward order is moot though they could be inserted in the correct order. So the user would have more control. I'm gonna change that.

"then the programmer should be responsible to handle multiple importing with preprocessing annotations." Well I don't see it that way. This is typically something that I don't want the user to care about. It should just work.

**Comment by aegroto** [comment]
Changing the order could be useful, but what about multiple imports in different shader nodes?

**Comment by Nehon** [comment]
What about them?

**Comment by aegroto** [comment]
Does changing older solve this issue too? I can't recognize how.

**Comment by Nehon** [comment]
Well I can't tell for sure right now but it's should include it once the first time the import is found. Imports of imports are quite the corner case to me. We don't have a complex dependency system, just the possibility to import libs in shaders.

**Comment by aegroto** [comment]
Well this is exactly the situation where I found this issue. I have the need to import a glsllib with common helpers functions in other glsllibs which perform specific tasks. Redefining those functions is pretty redundant.

**Comment by Nehon** [comment]
ok this is an issue I can look into.
the glsl lib loading is not done by the shader generator and I guess the imports are imported in place.
There must be the same issue with classic shaders btw.

**Comment by pspeed42** [comment]
Pasting in the code the first time the import is encountered seems right to me.  It should handle all cases as long as you aren't wrapping imports in #ifdef.

**Comment by Nehon** [comment]
Yep I guess it should be ok.

**Comment by aegroto** [comment]
I'll close this issue as the original problem is solved in latest snapshots.
