### ISSUE TITLE
Add an "aimAtTarget" Method to Ray

### ISSUE THREAD

**Issue by Bekreth** [jMonkeyEngine/jmonkeyengine#859]
The ray class should contain a method to take in a Vector3f as a target to aim at and calculate the vector to use for the `setDirection` method.

**Comment by MeFisto94** [comment]
Hey, thanks for your Contribution.
Actually what you want would be easily achieveable with standard methods already:
```java
Quaternion q = new Quaternion();
q = q.lookAt(target); // I am not sure whether this is a static method or not, if it returns something or not

// Transform the "Forward" Vector to look into the direction:
Vector3f v = q.mult(Vector3f.UNIT_Z); // Now you have your direction
Ray r = new Ray(Vector3f.ZERO, v);
```

It's a bit more verbose, but technically it's already there
