### ISSUE TITLE
please add *-javadoc.jar files to JCentral deployment

### ISSUE THREAD

**Issue by jjYBdx4IL** [jMonkeyEngine/jmonkeyengine#861]
I'm missing the javadoc files in the current (jme 3.2.1) maven deployment to JCentral. Eclipse and other maven-compatible IDEs expect the documentation in these files.

**Comment by stephengold** [comment]
Yes, this would be helpful.

**Comment by stephengold** [comment]
Deployments of JavaDoc JARs should happen automatically, now that we have "buildJavaDoc = true" in our gradle.properties file. Among other things, this adds "archives javadocJar" to the artifacts in the common.gradle file, and that should cause bintray.gradle to deploy those JARs.

If so, give @shadowislord credit for the fix.

The fix still needs to be propagated to the v3.2 branch in case there's a JME 3.2.2 release, so I'll leave the issue open for now.

**Comment by stephengold** [comment]
JavaDoc JARs for v3.2.2-beta1 were successfully deployed to JCenter, so I think this issue can be closed.
