### ISSUE TITLE
Bullet skipping enqueued tasks - found possible issue

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#867]
In my code, bullet was skipping some enqueued tasks, i found out that pQueue.poll() is called twice at the beginning of this code

https://github.com/jMonkeyEngine/jmonkeyengine/blob/cd1d14500571da1d771b9748d6eda912edeb40bd/jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java#L194-L206

This looks like the issue to me and without the double poll the issue is gone. I need some confirmations that i'm not breaking something i don't know.

**Comment by empirephoenix** [comment]
Yes that surely looks like a bug to me, good find, can you make a pull request for it?

**Comment by riccardobl** [comment]
Done. I've rewritten the code to make it cleaner and to prevent line 201 from logging npe if the task was cancelled and the queue over.

https://github.com/riccardobl/jmonkeyengine/blob/3e8152c3ec64eceef49b3b41dc9daf915b9f6f8d/jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java#L196-L204

**Comment by stephengold** [comment]
While I agree this is a good catch, it looks to me like preTick_native() is never invoked, so rewriting it will have no effect. The same goes for PhysicsSpace.postTick_native(), addCollision_native(), needCollision_native(), addCollisionEvent_native(), and notifyCollisionGroupListeners_native().

I recommend removing all this dead code.

**Comment by stephengold** [comment]
Correction: those methods are invoked from native code, so they can't be removed.

**Comment by riccardobl** [comment]
PR has been merged, so i think it's time to close this.

**Comment by stephengold** [comment]
Thanks. I forgot to do so.
