### ISSUE TITLE
SettingsDialog

### ISSUE THREAD

**Issue by ghost** [jMonkeyEngine/jmonkeyengine#87]
Reference on googlecode: https://code.google.com/p/jmonkeyengine/issues/detail?id=573

**Comment by shadowislord** [comment]
Some more windowed resolutions were added in 2fb87f9682e22255ba1402d8a3404efb95e5afda.
It is questionable under which circumstances users would actually want to modify the set of windowed resolution (and based on what criteria?) as well as how to expose such functionality.
