### ISSUE TITLE
Update LWJGL to 3.1.6

### ISSUE THREAD

**Issue by tonihele** [jMonkeyEngine/jmonkeyengine#871]
Update LWJGL to 3.1.6.

Also there is a bug in the context creation. The if the context is re-created at any point, it will crash. This is due to adding the error listener to GLWF that has already been freed but the pointer still exists in GLWF. This is reproducible always when running the examples with the example chooser and choosing i.e. BrickWall. First time ok, second time crash.

**Comment by tonihele** [comment]
I'll create a PR in just a minute, I can't add myself as a assignee. GIT n00b still. Lets see :)

**Comment by tonihele** [comment]
Hmm, I did it twice with both branches having the same issue, I don't know what is causing all the white space changes :(  I didn't have any auto-formattings on, at least I shouldn't have had.

**Comment by tonihele** [comment]
Ok, now it should be ok. I redid it, and I don't know why this time it worked. But it did, so, great :)

**Comment by stephengold** [comment]
I'm unsure whether to include this in v3.2.2 . How risky is the fix?

**Comment by tonihele** [comment]
Hmm, not super risky I'd say. It was 3.1.5 -> 3.1.6, https://github.com/LWJGL/lwjgl3/releases. I did try the demos and they worked. And actually there was a fix included in this to how JME uses LWJGL 3 context, as I mentioned. So I'd say... yay, go for it :)
