### ISSUE TITLE
Cloner fails on enums and wrapped primitives

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#879]
It would be convenient if com.jme3.util.clone.Cloner worked on enums and wrapped primitives (such as Float and Boolean).

Currently, the test code (below) fails with an IllegalArgumentException because f is a Float, which is not an array, nor Cloneable, nor JmeCloneable.

```
package mygame;

import com.jme3.app.SimpleApplication;
import com.jme3.font.LineWrapMode;
import com.jme3.util.clone.Cloner;

public class Main extends SimpleApplication {

    public static void main(String[] args) {
        Main app = new Main();
        app.start();
    }

    @Override
    public void simpleInitApp() {
        Boolean bo = false;
        Byte by = 0;
        Double d = 0.0;
        LineWrapMode e = LineWrapMode.Clip;
        Float f = 0f;
        Integer i = 0;
        Long l = 0L;

        Object clone;
        clone = Cloner.deepClone(f);
        clone = Cloner.deepClone(bo);
        clone = Cloner.deepClone(by);
        clone = Cloner.deepClone(d);
        clone = Cloner.deepClone(e);
        clone = Cloner.deepClone(i);
        clone = Cloner.deepClone(l);
    }
}
```

**Comment by pspeed42** [comment]
There is no reason to deep clone Float or enums... in fact, if cloning an enum does anything but just copying the reference then the enum would be broken.

So, here is how you "clone" an enum above:
clone = e;

**Comment by stephengold** [comment]
For situations where the type of Object is unknown at compile time, I work around this issue like so:
```
        if (object instanceof Boolean
                || object instanceof Byte
                || object instanceof Character
                || object instanceof Enum) {
            // a unique instance for every possible value, so alias
            clone = object;

        } else if (object instanceof String) {
            // instances are immutable, so alias
            clone = object;

        } else if (object instanceof Double) {
            clone = (double) object;
        } else if (object instanceof Float) {
            clone = (float) object;
        } else if (object instanceof Integer) {
            clone = (int) object;
        } else if (object instanceof Long) {
            clone = (long) object;
        } else if (object instanceof Short) {
            clone = (short) object;

        } else {
            clone = Cloner.deepClone(object);
        }
```

**Comment by pspeed42** [comment]
In what cases does this come up?

...by the way, all of those casts are unnecessary and make more work.  At best, it's a lot of compiler work to just return the same instance, at worst it causes boxing and unboxing (which may also end up returning the same instance in the end).

**Comment by stephengold** [comment]
While cloning material parameter values, I encountered one that was a Float.

**Comment by pspeed42** [comment]
In that case the material parameter does know what type it is for that
special case.  If it's float then it can just copy directly, ie: do nothing.

**Comment by stephengold** [comment]
I would also need cases for Integer and Boolean, since material parameters can also have such values. So I thought, "Why not use a Cloner? It can clone anything."

**Comment by pspeed42** [comment]
Cloner can clone Cloneable things.

Probably just switch( VarType ) in the cloneFields() method.

If it truly concerns you then the solution is to register IdentityCloneFunction with the various types on the cloner constructor but I think the code and documentation to explain that is more trouble than it's worth.
