### ISSUE TITLE
J3MLoader silently treats "true" as false when parsing booleans

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#880]
If a J3M or J3MD asset contains "Transparent true", the parser will setTransparent(false) since J3MLoader.parseBoolean() treats any word other than "On" as false.

Similarly for "Wireframe true" or "DepthWrite on" or "DepthTest yes".

It would be nice if parseBoolean() generated a diagnostic for words other than "On" or "Off".

**Comment by stephengold** [comment]
Fixed in 'master' branch.

**Comment by pspeed42** [comment]
This could break applications that are accidentally relying on the old behavior.  Recommend for 3.3 and not 3.2.2.
