### ISSUE TITLE
No native implementation for PhysicsJoint.finalizeNative

### ISSUE THREAD

**Issue by James-Richardson** [jMonkeyEngine/jmonkeyengine#913]
Although PhysicsJoint declares a native finalizeNative method, com_jme3_bullet_joints_PhysicsJoint.cpp doesn't contain an implementation of that method. This can result in UnsatisfiedLinkErrors at runtime. See the [forum topic](https://hub.jmonkeyengine.org/t/exception-access-violation-after-64-kinematicragdollcontrols/40952) where I originally raised this issue for more details.

**Comment by stephengold** [comment]
Good catch! My C++ skills are a bit rusty, but I think I can handle this one.

**Comment by James-Richardson** [comment]
Thanks, Stephen. I look forward to giving it a test once it's in the master repo.

**Comment by stephengold** [comment]
@James-Richardson: ready for testing!

If you're on Linux, you'll need to build your own jme3-bullet-native, due to issue #915.

If convenient, please provide a Short, Self Contained, Correct Example for future testing.

**Comment by stephengold** [comment]
In the absence of a self-contained test, I applied a temporary hack to PhysicsJoint so I could invoke finalizeNative() on demand. No exception was thrown.

Fixed in the `master` branch.
