### ISSUE TITLE
CI build process doesn't update libbulletjme.so

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#915]
Up until about a year ago, the Linux shared objects (SOs) were automatically committed to the Git repository by Travis after any change that affected them.  This is no longer happening.

For instance, the commit dc4189afc3bb625f8be8044b53667ebedb4fd46e triggered automatic commits of `libbulletjme.dylib` and `bulletjme.dll` (both 32-bit and 64-bit) but failed to update `libbulletjme.so` (either version). `libbulletjme.so` hasn't been updated since e12261eaa5673ef6aa698b078a697d5fc10e1a7d back in August 2017.

Travis job 2286.1 completely successfully. It executed `private/upload_native.sh`, and the outcome was `nothing to commit, working directory clean`.

I'm unsure where to go from here.

**Comment by stephengold** [comment]
Here's a clue from job 2286.1:
```
> Task :jme3-bullet-native:downloadBullet
> Task :jme3-bullet-native:unzipBullet
> Task :jme3-bullet-native:unzipBulletIfNeeded
> Task :jme3-bullet-native:compileBulletjmeLinux32SharedLibraryBulletjmeCpp FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Failed to capture fingerprint of input files for task ':jme3-bullet-native:compileBulletjmeLinux32SharedLibraryBulletjmeCpp' property 'headerDependencies' during up-to-date check.
> Could not list contents of '/usr/include/driver.h'. Couldn't follow symbolic link.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 52s
```

For reasons I don't understand, the job continued through the failure.

**Comment by stephengold** [comment]
By googling the error message, I learned that Ubuntu sometimes relocates header files between releases.
I notice our `.travis.xml` changed the build environment (from default to "precise") on 19 August 2017. Circumstantial evidence, but perhaps sufficient to justify experimentally reverting that change.

**Comment by stephengold** [comment]
With that change, the `compileBulletjmeLinux32SharedLibraryBulletjmeCpp` task completes silently during the `oraclejdk8` build.  However, now upload_native.sh reports `No native changes.` and the openjdk7 build fails with a `javax.net.ssl.SSLException`.

Btw, according to the Travis blog, support for the "precise" environment ended back in April.

**Comment by stephengold** [comment]
That commit helped: all builds succeeded.

The `upload_native.sh` script still reports `No native changes.` however. Perhaps a future commit will produce some native changes for it to commit.

**Comment by shadowislord** [comment]
cool, I guess this works

**Comment by stephengold** [comment]
I'm not convinced the issue is resolved. Wait-and-see for now.

**Comment by stephengold** [comment]
Now I'm convinced.
