### ISSUE TITLE
HingeJoint.read() fails to set native object's angular-only flag

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#917]
In current native Bullet (jme3-bullet), `HingeJoint.read()` reads an `angularOnly` value from the capsule, but it never invokes `setAngularOnly()` to initialize the `m_angularOnly` field in the `btHingeConstraint`.

**Comment by stephengold** [comment]
Found the same issue with JBullet.

**Comment by pspeed42** [comment]
Seems like this could break existing applications that are accidentally relying on the bug.  Recommend for 3.3 only and not 3.2.2.
