### ISSUE TITLE
Point2PointJoint.getImpulseClamp() returns the damping value instead

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#918]
Another probable copy-and-paste error:
```
    JNIEXPORT jfloat JNICALL
    Java_com_jme3_bullet_joints_Point2PointJoint_getImpulseClamp(
        JNIEnv * env,
        jobject object,
        jlong jointId) {
```
...
```
        return joint->m_setting.m_damping;
```

**Comment by stephengold** [comment]
Also, Point2PointJoint.getTau() has the exact same issue. Might as well fix both methods at once.

**Comment by stephengold** [comment]
Fixed in the `master` branch.

**Comment by pspeed42** [comment]
Ok... but only because the machinations necessary for some app to rely on this incorrect values seems to overwhelm even my imagination.
