### ISSUE TITLE
RagdollUtils can miss model meshes or use wrong ones

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#931]
The `buildPointMap()` and `makeShapeFromVerticeWeights()` methods in `com.jme3.bullet.control.ragdoll.RagdollUtils` search for meshes of the specified model. However, they look only at the model's root spatial and its immediate children. Any meshes deeper in the tree are missed. This may cause a crash later, if there are insufficient vertices to form a shape.

Furthermore, these methods should ignore non-animated meshes.

**Comment by stephengold** [comment]
Fixed in `master` branch.

**Comment by pspeed42** [comment]
Seems like this could break existing applications that are relying on the older behavior.  Recommend for 3.3 and not 3.2.2.
