### ISSUE TITLE
Keyboard Mapping inconsistency between lwjgl2 and 3

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine/jmonkeyengine#942]
This issue might need further testing because I _think_ this was different on Windows than on the linux I am currently seeing this bug. It probably also only affects non-english people but certainly those with a german (QWERTZ) layout. The problem is that lwjgl3 doesn't seem to care about to local keyboard layout and treat it as if it was an us-layout causing confusion.

```java
package mygame;

import com.jme3.app.SimpleApplication;
import com.jme3.input.KeyInput;
import com.jme3.input.controls.ActionListener;
import com.jme3.input.controls.KeyTrigger;

/**
 * Small Testcase for (at least) german keyboards: Behavior on "y" is different from lwjgl2 to lwjgl3 (3 doesn't seem
 * to respect the local keyboard mapping)
 * @author normenhansen
 */
public class Main extends SimpleApplication implements ActionListener {

    public static void main(String[] args) {
        Main app = new Main();
        app.start();
    }

    @Override
    public void simpleInitApp() {
        inputManager.addMapping("y", new KeyTrigger(KeyInput.KEY_Y));
        inputManager.addMapping("z", new KeyTrigger(KeyInput.KEY_Z));
        inputManager.addListener(this, "y", "z");
    }

    @Override
    public void onAction(String name, boolean isPressed, float tpf) {
        System.out.println(name + ": " + isPressed);
    }
}
```
Run this once with lwjgl2 and once with lwjgl3 and in 3 when you press y you actually see "z" printed and vice-versa.

For convenience I've added a slightly modified version of Stephens "BasicGame-on-Gradle" so that it works with the commandline, you just need to comment out lwjgl3 and execute ./gradlew run:
(Gradle doesn't automatically add run otherwise and the mainclass is also a different property)
```gradle
apply plugin: 'java'
apply plugin: 'application'

// select one source-code option
//sourceCompatibility = '1.6'
//sourceCompatibility = '1.7'
sourceCompatibility = '1.8'

gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.compilerArgs << '-Xdiags:verbose'
        options.compilerArgs << '-Xlint:unchecked'
        options.deprecation = true
        options.encoding = 'UTF-8'
    }
    tasks.withType(JavaExec) {
        args = []
        classpath sourceSets.main.runtimeClasspath
        //debug true
        enableAssertions true
        jvmArgs '-XX:+UseConcMarkSweepGC'
        //jvmArgs '-XX:+UseG1GC', '-XX:MaxGCPauseMillis=10'
    }
}

// select one version of the Engine
//ext.jmonkeyengineVersion = '3.1.0-stable' // from jcenter
//ext.jmonkeyengineVersion = '3.2.0-stable' // from jcenter
ext.jmonkeyengineVersion = '3.2.1-stable' // from jcenter
//ext.jmonkeyengineVersion = '3.2.1-SNAPSHOT' // from mavenLocal

// NetBeans will automatically add "run" and "debug" tasks relying on the
// "mainClass" property. You may however define the property prior executing
// tasks by passing a "-PmainClass=<QUALIFIED_CLASS_NAME>" argument.
//
// Note however, that you may define your own "run" and "debug" task if you
// prefer. In this case NetBeans will not add these tasks but you may rely on
// your own implementation.
if (!hasProperty('mainClass')) {
    mainClassName = 'mygame.Main'
}

repositories {
    //mavenLocal()
    jcenter()
    //maven { url 'http://nifty-gui.sourceforge.net/nifty-maven-repo' }
    //maven { url 'https://dl.bintray.com/stephengold/org.jmonkeyengine' }
    //google()
    //mavenCentral()
    // Read more about repositories here:
    //   https://docs.gradle.org/current/userguide/dependency_management.html#sec:repositories
}

dependencies {
    // You can read more about how to add dependencies here:
    //   https://docs.gradle.org/current/userguide/dependency_management.html#sec:how_to_declare_your_dependencies

    // from jcenter (or mavenLocal) repositories:
    compile "org.jmonkeyengine:jme3-core:$jmonkeyengineVersion"
    runtime "org.jmonkeyengine:jme3-blender:$jmonkeyengineVersion"
    //compile "org.jmonkeyengine:jme3-bullet:$jmonkeyengineVersion"
    //runtime "org.jmonkeyengine:jme3-bullet-native:$jmonkeyengineVersion"
    runtime "org.jmonkeyengine:jme3-desktop:$jmonkeyengineVersion"
    //compile "org.jmonkeyengine:jme3-effects:$jmonkeyengineVersion"
    //runtime "org.jmonkeyengine:jme3-jogg:$jmonkeyengineVersion"
    //compile "org.jmonkeyengine:jme3-jogl:$jmonkeyengineVersion"
    //compile "org.jmonkeyengine:jme3-networking:$jmonkeyengineVersion"
    //compile "org.jmonkeyengine:jme3-niftygui:$jmonkeyengineVersion"
    runtime "org.jmonkeyengine:jme3-plugins:$jmonkeyengineVersion"
    //compile "org.jmonkeyengine:jme3-terrain:$jmonkeyengineVersion"

    // select one version of LWJGL (from jcenter or mavenLocal)
    //runtime "org.jmonkeyengine:jme3-lwjgl:$jmonkeyengineVersion"
    runtime "org.jmonkeyengine:jme3-lwjgl3:$jmonkeyengineVersion"

    // from stephengold's bintray repositories:
    //runtime 'org.jmonkeyengine:jme3-testdata:3.1.0-stable'
}

// cleanup tasks
clean { dependsOn 'cleanDLLs', 'cleanSOs' }
task cleanDLLs(type: Delete) {
    delete fileTree(dir: '.', include: '*.dll')
}
task cleanSOs(type: Delete) {
    delete fileTree(dir: '.', include: '*.so')
}
```

I am not sure if this issue isn't within lwjgl3 itself though or rather our "configuration". Maybe it's also already fixed upstream and we just need a newer version

**Comment by grizeldi** [comment]
Can confirm, happens with Slovenian QWERTZ keyboard too.

**Comment by empirephoenix** [comment]
Lwjgl is build by lwjgl itself, we only consume the release jars, while we compile bullet ourselves (as we maintain the wrapper). So it should not be a version issue between operating systems. 

I just tested with lwjgl3, my application surprisingly seem to correctly work. On Arch with Xfce

**Comment by pspeed42** [comment]
Reading that thread... is your issue that the character code comes in a different event now or something?

**Comment by MeFisto94** [comment]
>I'm not sure what the issue is. If you bind your game directly to WASD then that's not going to work on french keyboards no matter what... because their keys are in different places.
The real issue is that lwjgl3.2.1 started to always use the US-Layout for key chars to support that use case, where to me the real solution would've been the legacy behavior (if I want to have the key which is on the same position as the US-W, I'd use the key code, otherwise the key char). And I think we should restore that behavior for exact that reason. Otherwise on a non-us-layout you're screwed. Can't display "Press W", can't have a textinput.

>Reading that thread... is your issue that the character code comes in a different event now or something?
No, but jme's input events are now related to the US-Layout, no matter what keyboard I have.

Re-reading the issue it might be that I got that wrong. Their issue was that the scancode wasn't propagated to the keycode in earlier versions, which means  the keycode reflected the key character. Either way jme's input events don't correlate to the active user layout, probably 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/989fc0a9f0dc7a5c46b6c5d1f479064cffda8023/jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java#L119 at least the char is only there for KeyInputEvents with KEY_UNKNOWN

**Comment by MeFisto94** [comment]
Note that investigation can also happen on US Keyboards, the only crucial thing here is to change the Keyboard Layout.

From a russian QWERTY Keyboard, which has been toggled to russian mode after typing qwe:

lwjgl2:
```
RES = q   / 16 / q / 113  ----> Key(CODE=16, CHAR=q, PRESSED)
RES = q   / 16 /   / 0  ----> Key(CODE=16, RELEASED)
RES = w   / 17 / w / 119  ----> Key(CODE=17, CHAR=w, PRESSED)
RES = w   / 17 /   / 0  ----> Key(CODE=17, RELEASED)
RES = e   / 18 / e / 101  ----> Key(CODE=18, CHAR=e, PRESSED)
RES = e   / 18 /   / 0  ----> Key(CODE=18, RELEASED)
RES = й   / 16 / й / 1081  ----> Key(CODE=16, CHAR=й, PRESSED)
RES = й   / 16 /   / 0  ----> Key(CODE=16, RELEASED)
RES = ц   / 17 / ц / 1094  ----> Key(CODE=17, CHAR=ц, PRESSED)
RES = ц   / 17 /   / 0  ----> Key(CODE=17, RELEASED)
RES = у   / 18 / у / 1091  ----> Key(CODE=18, CHAR=у, PRESSED)
RES = у   / 18 /   / 0  ----> Key(CODE=18, RELEASED)
RES =    / 1 /  / 27  ----> Key(CODE=1, CHAR=, PRESSED)
```

lwjgl3
```
RES =    / 16 /   / 0  ----> Key(CODE=16, PRESSED)
RES = q   / 0 / q / 113  ----> Key(CODE=0, CHAR=q, PRESSED)
RES = q   / 0 / q / 113  ----> Key(CODE=0, CHAR=q, RELEASED)
RES = null   / 16 /   / 0  ----> Key(CODE=16, RELEASED)
RES =    / 17 /   / 0  ----> Key(CODE=17, PRESSED)
RES = w   / 0 / w / 119  ----> Key(CODE=0, CHAR=w, PRESSED)
RES = w   / 0 / w / 119  ----> Key(CODE=0, CHAR=w, RELEASED)
RES = null   / 17 /   / 0  ----> Key(CODE=17, RELEASED)
RES =    / 18 /   / 0  ----> Key(CODE=18, PRESSED)
RES = e   / 0 / e / 101  ----> Key(CODE=0, CHAR=e, PRESSED)
RES = e   / 0 / e / 101  ----> Key(CODE=0, CHAR=e, RELEASED)
RES = null   / 18 /   / 0  ----> Key(CODE=18, RELEASED)
RES =    / 16 /   / 0  ----> Key(CODE=16, PRESSED)
RES = й   / 0 / й / 1081  ----> Key(CODE=0, CHAR=й, PRESSED)
RES = й   / 0 / й / 1081  ----> Key(CODE=0, CHAR=й, RELEASED)
RES = null   / 16 /   / 0  ----> Key(CODE=16, RELEASED)
RES =    / 17 /   / 0  ----> Key(CODE=17, PRESSED)
RES = ц   / 0 / ц / 1094  ----> Key(CODE=0, CHAR=ц, PRESSED)
RES = ц   / 0 / ц / 1094  ----> Key(CODE=0, CHAR=ц, RELEASED)
RES = null   / 17 /   / 0  ----> Key(CODE=17, RELEASED)
RES =    / 18 /   / 0  ----> Key(CODE=18, PRESSED)
RES = у   / 0 / у / 1091  ----> Key(CODE=0, CHAR=у, PRESSED)
RES = у   / 0 / у / 1091  ----> Key(CODE=0, CHAR=у, RELEASED)
RES = null   / 18 /   / 0  ----> Key(CODE=18, RELEASED)
RES =    / 1 /   / 0  ----> Key(CODE=1, PRESSED)
```

What happens is that KeyCode and KeyChar don't come in combined but as seperate events.
Furthermore I don't know what is happening with ActionListener's name field, which should always return the keycode (or the name associated with the keycode) and not the keychar.

Time to checkout the code and see what happens, I guess.

**Comment by MeFisto94** [comment]
@pspeed42, I think I fully figured this out, bu I need your advice.

Three important things:
- https://github.com/jMonkeyEngine/jmonkeyengine/commit/b5b6ebd97cfb72f13a18db92ae0282a5f4a8910d
- `int jmeKey = GlfwKeyMap.toJmeKeyCode(key);` by kirill
- https://javadoc.lwjgl.org/org/lwjgl/glfw/GLFW.html#glfwSetKeyCallback(long,org.lwjgl.glfw.GLFWKeyCallbackI) and https://javadoc.lwjgl.org/org/lwjgl/glfw/GLFW.html#glfwSetCharCallback(long,org.lwjgl.glfw.GLFWCharCallbackI)

-> I reverted the changes from the first point, but then I get chars for things like the shift-key as well as always-capital-letters. This means the KeyCallback _must not_ be used for chars.
-> I don't know why kirill did what he did (maybe there is an issue explaining), but during my testing, the scancode was almost always equal to the translated jmeKey (I debugged this with an exception and hammered my keyboard, something indeed is different).
-> The third one is the actual culprit: There are multiple Callbacks and thus multiple events are fired. That also explains why CHAR and CODE are mutably(?) exclusive.

I am a bit confused by 
> Characters do not map 1:1 to physical keys, as a key may produce zero, one or more characters. If you want to know whether a specific physical key was pressed or released, see the key callback instead.

As written on the javadoc from SetCharCallback. This means we cannot get the Scancode from the CodePoint.
Thus my only solution would be to consolidate events by iterating over the event list, but the callbacks arent guaranteed to happen in that order (Pressed -> Code then Char, Released -> Char then Code), because I can press Shift + E and release Shift before E:
```
Key(CODE=42, PRESSED)
Key(CODE=18, PRESSED)
Key(CODE=0, CHAR=E, PRESSED)
Key(CODE=0, CHAR=E, RELEASED)
Key(CODE=42, RELEASED)
Key(CODE=18, RELEASED)
```
Here 42 (shift) has been released before 18 (e), but the Char has been removed before.

I don't know if we can really solve this easily, especially as has been pointed out a Char can be a combination of Keys and thus is different.

Now we probably cannot make breaking changes to lwjgl2 by splitting keycode and keychar, but I think some code is confused by this multiple events and keycodes without chars.

**Comment by pspeed42** [comment]
lwjgl2 is doing this right and so we should not break it just to be the same.

re: " (I debugged this with an exception and hammered my keyboard, something indeed is different)."  

That means that the mapping is necessary?  I think there were some keys that didn't map correctly and so we had to translate them.  I'm surprised we don't pass both the key code and scan code in so that if there is no mapping we can just defer to the scan code (that is usually the same according to your testing).  But I don't know what cases you found that were different in your testing.

Regarding the actual issue of two events being sent, I'm curious what is getting confused by this.  While we'd rather it didn't do that, I'm wondering if JME is part of the issue with why things aren't responding properly (for example, filtering keycode = 0 somewhere).

To me, most code is either interested in pressed/released and so will watch scan code... or is interested in typing and will watch charCode (and ignore scan code).  For example, if text boxes are not working in Lemur then I feel like it must be something that JME is doing... because if the event is delivered to Lemur's listener then it will forward the character if there is one.  It doesn't look at the scan code at all in that case.

(One thing I really wonder is why we aren't just using Java's standard way of intercepting application-wide keys... I don't know what issue that causes... would have also maybe let us work with JavaFX style integration 'for free' at least at the key handling level.)  

For anyone ever interested in exploring that route and seeing if there are issues: https://docs.oracle.com/javase/7/docs/api/java/awt/KeyboardFocusManager.html#addKeyEventDispatcher(java.awt.KeyEventDispatcher)

Only works when AWT is there but I thought lwjgl3 was also already on desktop... ie: AWT is available.

**Comment by MeFisto94** [comment]
> Only works when AWT is there but I thought lwjgl3 was also already on desktop... ie: AWT is available.
Probably that is one of the reasons. Lwjgl3 has issues with the AWTContext [not sure if they are fixed].
I could imagine the display modes fullscreen, borderless window or smth also leading to problems there, but that is blind guessing.

> That means that the mapping is necessary? I think there were some keys that didn't map correctly and so we had to translate them. I'm surprised we don't pass both the key code and scan code in so that if there is no mapping we can just defer to the scan code (that is usually the same according to your testing). But I don't know what cases you found that were different in your testing.

I don't know them either, I could try it (this time with proper logging), but that most certainly isn't the root cause, unless the `jmeKey` is interpreted as KeyChar laterOn. But I don't know about the higher level use cases anymore, so for now I just saw the multiple events.

I've given merging events a second thought and technically, merging them should just work.
This is because `Key(CODE=42, CHAR=E, RELEASED)` doesn't have a matching code to a char, but that's what one gets when using merged events, Shift has been released, not e.
```
Key(CODE=42, PRESSED)
Key(CODE=18, PRESSED)
Key(CODE=0, CHAR=E, PRESSED)
Key(CODE=0, CHAR=E, RELEASED)
Key(CODE=42, RELEASED)
Key(CODE=18, RELEASED)
```
Will become:
```
Key(CODE=42, PRESSED)
Key(CODE=18, CHAR=E, PRESSED)
Key(CODE=42, CHAR=E, RELEASED)
Key(CODE=18, RELEASED)
```

Do not the first and last event, though. They don't make up a char (at least not the shift key alone), and thus I wonder what exactly lwjgl2 did in that case. There is no char that would make sense and the old "Shift + E" is already broken due to Shift being released.

**Comment by MeFisto94** [comment]
So LWJGL2 does it like this:
```
Key(CODE=42, PRESSED)
Key(CODE=18, CHAR=E, PRESSED)
Key(CODE=42, RELEASED)
Key(CODE=18, RELEASED)
```
This means, LWJGL2 only merges keycodes and chars on PRESSED.
Also pressing e and then Shift does yield (lwjgl2):
```
Key(CODE=18, CHAR=e, PRESSED)
Key(CODE=42, PRESSED)
Key(CODE=42, RELEASED)
```

LWJGL3:
```
Key(CODE=18, PRESSED)
Key(CODE=0, CHAR=e, PRESSED)
Key(CODE=0, CHAR=e, RELEASED)
Key(CODE=42, PRESSED)
Key(CODE=42, RELEASED)
Key(CODE=18, RELEASED)
```
So here the char was "released" as I started to press shift even though key code 18 wasn't released at all.

**Comment by pspeed42** [comment]
I'm 99% sure lwjgl2 won't give you releases for key chars... because it's a bit silly.

re: AWT, you don't need an AWT context.  Java desktop always has AWT... you should be able to grab the keyboard focus manager and register for key dispatch with no AWT managed windows at all.  In theory.  I'm like 80% sure I've used it from console apps before but it's going on 15 years ago.

**Comment by riccardobl** [comment]
The lwjgl3 handling seems correct to me. You map the keys to positions of the US layout, it's the position of the keys that matter in a game, not the actual values.
If you need to map those keys to chars for text input, then it's up to you to do the proper remapping.

**Comment by stephengold** [comment]
1. Documenting keyboard controls based on scan codes would be inconvenient. It's simpler and clearer to say "press the Y key" than to say "press the key that generates scan code 21 decimal".
2. A lot of games need the actual chars. Where's the API for doing the proper remapping?

**Comment by riccardobl** [comment]
> Documenting keyboard controls based on scan codes would be inconvenient. It's simpler and clearer to say "press the Y key" than to say "press the key that generates scan code 21 decimal".

You are going to need to remap all of them anyway, since they will be in wrong positions.
Imagine telling a french player to use WASD to move.
![KA-French-20823](https://user-images.githubusercontent.com/4943530/95673082-eb4af680-0ba5-11eb-906e-7063f8f58acd.jpg)
When you remap the keys you can save their charcode.



> A lot of games need the actual chars. Where's the API for doing the proper remapping?

The test case here is wrong. The code to read input characters should be:

```java
package com.mygame;

import com.jme3.app.SimpleApplication;
import com.jme3.input.RawInputListener;
import com.jme3.input.event.JoyAxisEvent;
import com.jme3.input.event.JoyButtonEvent;
import com.jme3.input.event.KeyInputEvent;
import com.jme3.input.event.MouseButtonEvent;
import com.jme3.input.event.MouseMotionEvent;
import com.jme3.input.event.TouchEvent;

/**
 * Small Testcase for (at least) german keyboards: Behavior on "y" is different from lwjgl2 to lwjgl3 (3 doesn't seem
 * to respect the local keyboard mapping)
 * @author normenhansen
 */
public class Test extends SimpleApplication implements RawInputListener{

    public static void main(String[] args) {
        Test app=new Test();
        app.start();
    }

    @Override
    public void simpleInitApp() {
        inputManager.addRawInputListener(this);
    }

    @Override
    public void beginInput() {
    }

    @Override
    public void endInput() {
    }

    @Override
    public void onJoyAxisEvent(JoyAxisEvent evt) {
    }

    @Override
    public void onJoyButtonEvent(JoyButtonEvent evt) {
    }

    @Override
    public void onMouseMotionEvent(MouseMotionEvent evt) {
    }

    @Override
    public void onMouseButtonEvent(MouseButtonEvent evt) {
    }

    @Override
    public void onKeyEvent(KeyInputEvent evt) {
        if(evt.getKeyChar()!=0){
            System.out.println("Input char: "+evt.getKeyChar());
        }else{
            System.out.println("Input code: "+evt.getKeyCode());
        }
    }

    @Override
    public void onTouchEvent(TouchEvent evt) {
    }
}
```

I tried it and it seems to read the proper characters

**Comment by stephengold** [comment]
Sometimes games assign keys based on position (such as movement using WASD in the US and ZQSD in France). Sometimes they assign them based on mnemonics (such as L for launch/lancer/lanciare). 

The sample code you provided is useful for implementing both kinds of assignment. Thank you.

For a user interface to be friendly, it must be documented somewhere. Given all the different layouts, perhaps the best way to document positional keys is to use a diagram. However, I was hoping there is an API to determine which type of keyboard is present, so my apps could accurately describe their key assignments to user without a drawing diagram.

**Comment by pspeed42** [comment]
For any of a half-dozen reasons, games should provide a way to remap the keys.  This can smooth over the QWERTY vs. AZERTY differences... I'm sure users of french keyboards are really familiar with that dance.

The newer lwjgl approach of mapping key "positions" instead of the key codes is really swimming up stream and super unfortunate.  It's the least intuitive way to map game keys because most of them tend to be mnemonic and keyboard scan code layouts may not even be consistent within even the same language's keyboard.  It's a hardware function and more or less totally arbitrary.  Relying on the fact that most of them layout key positions consistently is no different than relying on that most keyboards are QWERTY.

**Comment by riccardobl** [comment]
Well i guess it depends on the game genre
I can implement the glfwGetKeyName api in the input manager, and expose a method ( `inputManager.getKeyName(int)` )to get the layout specific name for jme keycodes. 
This solves the documentation issue and can partially solve the mnemonic issue too, since it is possible to just cycle through all the jme keycodes and find the one that matches the mnemonic key name as a form of auto remapping.
Eg. I want to map L to launch
```java
int launchKey=KeyInput.KEY_L; // L position in US layout
forEach(int key in jmeKeys){
  if(inputManager.getKeyName(key).equals("L")){
     //remap
     launchKey=key; // layout specific position of L
     break;
  }
}
System.out.println("Use "+inputManager.getKeyName(launchKey)+" to launch");
```
if the key name is not found (eg. on russian keyboards) it won't remap and the positional key will be used. 
With this code it is also possible to use mnemonic keys for languages that don't use latin letters.

**Comment by riccardobl** [comment]
This is how it looks like: (don't try to run stuff from this PR draft branch, it's wip / often broken )
https://github.com/jMonkeyEngine/jmonkeyengine/pull/1406/commits/b024cf635d569ebe417e8c8e97e702bd87227388

And example:
https://github.com/jMonkeyEngine/jmonkeyengine/pull/1406/commits/ddb69309659a6b341bee1af794448b329ba638bf

**Comment by stephengold** [comment]
That looks promising.

**Comment by riccardobl** [comment]
I can go ahead and commit https://github.com/jMonkeyEngine/jmonkeyengine/commit/b024cf635d569ebe417e8c8e97e702bd87227388 to the master if everybody is satisfied with this solution.
Is it a problem to have default methods in interfaces? I'm thinking about android and iOS deployments.

**Comment by stephengold** [comment]
I don't see any problem.

**Comment by MeFisto94** [comment]
On that matter, Lemur ( @pspeed42 ) may need to look into this for the input boxes, iirc they used the "keycode", so not my locale part. But I am not so sure on that, atm, so hopefully it's obvious in the code.

**Comment by pspeed42** [comment]
Not sure how to interpret that comment.  You mean for inserting text characters?

https://github.com/jMonkeyEngine-Contributions/Lemur/blob/master/src/main/java/com/simsilica/lemur/component/TextEntryComponent.java#L763

It uses event.getKeyChar() because it's essentially impossible for application code to turn a keycode into the appropriate character otherwise.  That's the OS's job.
