### ISSUE TITLE
Matrix4f: why are the values not stored in a float array?

### ISSUE THREAD

**Issue by neo-expert** [jMonkeyEngine/jmonkeyengine#953]
I would like to pass a Matrix4f to the Shader with
`GLES20.glUniformMatrix4fv(mMVPMatrixHandle, 1, false, myMatrix, 0)
`
currentrly I do it like:
```
Matrix4f m4f=new Matrix4f();
float[] myMatrix=new float[16];
m4f.get(myMatrix);
GLES20.glUniformMatrix4fv(mMVPMatrixHandle, 1, false, myMatrix, 0);
```
the problem is, that the "get" function does a lot of work to copy all the values to the array, because they all are stored as float values: 

`float m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33;
`
so for testing, I wrote my own Matrix4f class where all the values are stored in an array
`float[] m=new float[16];
`
but, why does jmonkeyengine use this Matrix4f class? Are there some advandates to do so?

**Comment by stephengold** [comment]
Your question should be directed to the authors of `Matrix4f.java`: Mark Powell and Joshua Slack. I suspect they no longer read jMonkeyEngine issues on GitHub, if they ever did.
