### ISSUE TITLE
Node returns null bounding volume.

### ISSUE THREAD

**Issue by mitm001** [jMonkeyEngine/jmonkeyengine#954]
I can not do pull requests anymore on github, along with many other issues with gitflub, so will just post the issue and fix here. Someone will have to test it out. 

Node returns null bounding volume when it has no children. 

See this forum post:
https://hub.jmonkeyengine.org/t/lemur-simtools-patch-stravaganza/41094/61

Suggested fix by pspeed is change this line:
this.worldBound = resultBound;
to
this.worldBound = resultBound != null ? resultBound : new BoundingBox(getWorldTranslation(), 0, 0, 0):

https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/scene/Node.java#L173
or something like it.

**Comment by stephengold** [comment]
Fixed now in `master` branch. (That was quick!)

By the way, given the lack of documentation for bounding volumes, I'm not convinced this was a bug.

The old way seemed to work fine in practice. The new way is more intuitive, but uses more heap memory.

**Comment by pspeed42** [comment]
Other places in JME call getWorldBound() without checking for null.  You can find other places in Camera (I think) where we had to add the check.  So I guess another alternative would have been to track down everywhere in JME where getWorldBound() is called and add a null check.  This seems like the cleaner option to me.

"uses more heap memory"... yes, one additional BoundingBox per node without any children that continues to have no children with its world bound is next calculated.  It would be interesting to see how often that happens in practice.

**Comment by pspeed42** [comment]
Yeah, here's one of the places we had to fix so that an empty GUI node wouldn't crash JME:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-core/src/main/java/com/jme3/renderer/Camera.java#L1070
There are others... and probably still others yet unfixed.

Besides, the world bound of an empty node is knowable.  It may even make sense to ask the question.  It seems reasonable to return it.  But I guess the argument could be made the other way, too.

**Comment by stephengold** [comment]
Good to know. Thanks!

**Comment by pspeed42** [comment]
There could be existing applications relying on null world bound to indicate no children.  Recommend this for 3.3 and not 3.2.2.
