### ISSUE TITLE
setFriction for CharacterControl?

### ISSUE THREAD

**Issue by neo-expert** [jMonkeyEngine/jmonkeyengine#956]
My player-object slides on the terrain, but CharacterControl does not have a setFriction-method. How to solve that?

**Comment by empirephoenix** [comment]
The normal CharacterControl is very basic, and only works good for classical levels, eg Quake or similar. There is a BetterCharacterControl, that actually uses a physical object. However due to this it also behaves differently in some cases, to check if it better fits your requirements.
