### ISSUE TITLE
Triangle setters should null out the cached center and normal

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#957]
`com.jme3.math.Triangle` generates a center vector and a normal vector and caches them. However, altering the triangle's vertices (using `set(int,Vector3f)`, `set(int, float, float, float)`, `set1(Vector3f)`, `set2(Vector3f)`, `set3(Vector3f)` or `set(Vector3f, Vector3f, Vector3f)`) does not update or invalidate the cached vectors. As a consequence, `getCenter()` and `getNormal()` may return incorrect values.

**Comment by stephengold** [comment]
Fixed in `master` branch.

**Comment by pspeed42** [comment]
Existing apps may be relying on this bug accidentally.  Recommend for 3.3 and not 3.2.2.
