### ISSUE TITLE
Add a way to set CF_NO_CONTACT_RESPONSE for rigid bodies

### ISSUE THREAD

**Issue by riccardobl** [jMonkeyEngine/jmonkeyengine#964]
Long story short, i have a physic projectile that needs to explode when hitting everything except one rb.
Of course i could do that by messing around with collision groups, but it turned out that bullet provides a more convenient way for my use case.

Enabling CF_NO_CONTACT_RESPONSE will make the rb behave pretty much like a ghost control that is subjected to forces, the collision events will still be triggered, but it will pass through everything.

For my personal use i've just made a patch that exposes the setCollisionFlags method https://github.com/riccardobl/jmonkeyengine/commit/f1840b2ba2dfdbfc29094423366d7de66491bb94

Seeing over the years others issues that would have been easily fixed by this, I think the engine would benefit from having a setContactResponse(boolean) method in PhysicsCollisionObject.

Thoughts?

**Comment by stephengold** [comment]
Sounds useful.

Adding this would create yet another incompatibility between `jme3-bullet` and `jme3-jbullet`, but I don't think that's a major concern at this point.

Why in `PhysicsCollisionObject` instead of `PhysicsRigidBody`?

If you create a pull request, remember that the flag will have to be handled whenever a physics object is loaded, saved, or cloned.

**Comment by riccardobl** [comment]
> Why in PhysicsCollisionObject instead of PhysicsRigidBody?

It is a property of btCollisionObject in bullet.

**Comment by stephengold** [comment]
Are there circumstances where one might wish to setContactResponse() on a ghost or character object?

**Comment by riccardobl** [comment]
It is already set by jme for the ghost controls, i think it should work for characters and soft  bodies.

**Comment by stephengold** [comment]
I'll implement this for `jme3-bullet`.

**Comment by stephengold** [comment]
I'm satisfied that the new feature works in `jme3-bullet`. In `jme3-jbullet`, it throws an appropriate exception on any attempt to set it to false.

**Comment by stephengold** [comment]
I'm reopening this. Now that we've rediscovered the source code for `jbullet.jar`, it should be possible to implement this feature for JBullet as well.

**Comment by stephengold** [comment]
Implemented (for `PhysicsRigidBody`) at 234bd476f3af6ada000eb1ede76c7f48995df304 .
