### ISSUE TITLE
RigidBodyMotionState performance

### ISSUE THREAD

**Issue by neo-expert** [jMonkeyEngine/jmonkeyengine#967]
There is a method called
`applyTransform(Spatial)`
which is called for each(?) physics step.
Can we just set a class variable representing the translation and rotation directly from jni code?

**Comment by pspeed42** [comment]
Set it on what?

**Comment by neo-expert** [comment]
For example we could have a modelmatrix in the Spatial class:
float[] modelmatrix=new float[16];
can we change the values of this matrix directly from jni?
It would be much performanter, because you don't need to call the methods to update the tranformation.

**Comment by pspeed42** [comment]
So we would put a whole 16 float matrix on EVERY spatial everywhere... bitmap text, cubes, whatever... just so that the physics engine (which is totally and completely separate from the visualization because the physics engine is 'game objects') might want to set it sometimes.  When would it set it?  Every time it changes?  Or only when it needs to change?  How would it know it needs to change?

It's bad idea for about 400 reasons.

**Comment by pspeed42** [comment]
We're not going to add something to Spatial just to support the add-on physics engine.  It's silly.

**Comment by pspeed42** [comment]
Also, you'd still have to call something once a VISUALIZATION frame to get the latest value... something like apply....

**Comment by neo-expert** [comment]
When we change the values directly, we don't need to call anything.
I will try it maybe... The question is just, if it is possible to access the class variables from jni, and the synchronization thing. The access to such matrix should be synchronized...

**Comment by pspeed42** [comment]
But WHEN would you call it directly?  JNI calls back to Java are not free.  It's generally cheaper to call the other way... which is why JME does that.  And having the physics library update these values "whenever they change" is going to slow the physics engine down for no reason.... since those values might never get displayed in time.

You should post this kind of discussion on the forum so that everyone can pile on instead of just me.

**Comment by pspeed42** [comment]
Oh, and keep in mind that you can use JME's bullet wrapper without any spatials at all (which is really the proper way if you want to have real game objects).

**Comment by pspeed42** [comment]
So keep in mind, what you are suggesting is pretty much exactly the same as suggesting:
"Hey, why don't we have the database update our JText string directly every time the field updates..."  It's 100% backwards.

**Comment by neo-expert** [comment]
jme3 bullet package uses Spatial class, I think it has jme3-core as dependency.

I mean when such Matrix is somewhere in the memory, and we can change its float values directly, we don't need to do anything else, they get just changed.
But it is just a consideration.
The applyTransform method does a lot of work:

```
public boolean applyTransform(Spatial spatial) {
        if (!physicsLocationDirty) {
            return false;
        }
        if (!applyPhysicsLocal && spatial.getParent() != null) {
            localLocation.set(worldLocation).subtractLocal(spatial.getParent().getWorldTranslation());
            localLocation.divideLocal(spatial.getParent().getWorldScale());
            tmp_inverseWorldRotation.set(spatial.getParent().getWorldRotation()).inverseLocal().multLocal(localLocation);

            localRotationQuat.set(worldRotationQuat);
            tmp_inverseWorldRotation.set(spatial.getParent().getWorldRotation()).inverseLocal().mult(localRotationQuat, localRotationQuat);

            spatial.setLocalTranslation(localLocation);
            spatial.setLocalRotation(localRotationQuat);
        } else {
            spatial.setLocalTranslation(worldLocation);
            spatial.setLocalRotation(worldRotationQuat);
        }
        physicsLocationDirty = false;
        return true;
    }
```

**Comment by neo-expert** [comment]
And on the other hand, I think bullet stores these values also somewhere. So we have these values twice in the memory.

**Comment by pspeed42** [comment]
Ah, I thought you understood how JNI worked.  You should probably learn how impossible what you say is... then post to the forum about it if you still think it's even possible and we can discuss the other 399 reasons that it's a bad idea.
