### ISSUE TITLE
Physically based rendering texture support?

### ISSUE THREAD

**Issue by brylie** [jMonkeyEngine/jmonkeyengine#975]
There seems to be a significant movement towards PBR textures, from game engines like Godot, Unity, and Unreal, as well as Blender Cycles/Eevee. Does jMonkeyEngine currently, or plan to, support physically based rendering?

**Comment by Ali-RS** [comment]
JME already supports PBR since 3.2.0 

You can take a look at release page for added features: https://github.com/jMonkeyEngine/jmonkeyengine/releases

**Comment by pspeed42** [comment]
Ask questions on the forum not in the bug tracker.
