### ISSUE TITLE
add getSpeed()/setSpeed() methods to SimpleApplication

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine#978]
`LegacyAppliction` provides accessors for most of its protected fields, but not for `speed`. So each app that uses `speed` must provide its own.

**Comment by pspeed42** [comment]
Apps should not use speed.  It's a broken concept because it equates animation time and visualization time with game time.  It automatically presumes and FORCES spatials to be game objects.  The whole concept will be removed eventually... so I'm against expanding the API since we should already add deprecated tags to these methods.

**Comment by stephengold** [comment]
I thought `speed` was a multiplier used to convert real time to game time. Equating those metrics would imply `speed=1`, which is effectively what we'd have if the concept were removed. So your 2nd sentence makes no sense to me.

I also don't see `speed` forcing spatials to be game objects; to me, that looks like an orthogonal issue. Care to elaborate?

**Comment by stephengold** [comment]
I don't agree that `speed=0` is the only interesting value. Aside from `speed=1` there's also the range from about 0.1 to 0.6, which provides a slow-motion effect (extra drama for victory/defeat situations). And in my demos I use `speed=1e-12` to produce a pause effect while still updating controls and appstates.

**Comment by pspeed42** [comment]
To LegacyApplication speed=0 is the same as paused=true.  Speed = anything else does nothing in LEGACY APPLICATION.

Speed should be moved to SimpleApplication where it can live in the same someday-deprecated state the SimpleApplication does... where it pretends that game time is the same as animation time is the same as screen update speed.  None of which is true.  Else you are saying if a GUI button is emitting sparkly particles as part of the general UI then those should ALSO slow down or hang when the game itself is running at half speed.

There is a more complicated question of "which time" that JME completely ignores and will have to be built into future concepts of "pause"... or just left up to the game.

**Comment by stephengold** [comment]
Okay, so `speed` belongs in `SimpleApplication` not `LegacyApplication`. In that case, `setSpeed()` and `getSpeed()` also belong in `SimpleApplication`.

Right?

**Comment by pspeed42** [comment]
Yes, I guess SimpleApplication is fine since it actually uses it... and then we can deprecate it with all of the rest of SimpleApplication when we get there.

**Comment by stephengold** [comment]
Enhancement added to `master` branch at hash c6158bba68c92f70182009968f56b06bb32a178b (pull request #986)
